// Auto-generated by scripts/smart_logo_fetcher.py

export const BRAND_LOGO_MAP: Record<string, string> = {
};

const NORMALIZED_BRAND_LOGO_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(BRAND_LOGO_MAP).map(([key, value]) => [key.toLowerCase(), value])
);

export const getBrandLogo = (brandName: string): string => {
  if (!brandName) return '/logos/placeholder.svg';
  const normalizedName = brandName.trim().toLowerCase();
  return BRAND_LOGO_MAP[brandName] || NORMALIZED_BRAND_LOGO_MAP[normalizedName] || '/logos/placeholder.svg';
};
