// src/lib/brands.ts

export interface Brand {
  name: string;
  description?: string; // Optional description
  logoUrl?: string; // Optional path to logo
}

export const brandsUsa: Brand[] = [
  { name: '1221 wheels' },
  { name: '1016 Industries' },
  { name: '5150 Autosport' },
  { name: 'AE Design' },
  { name: 'ADV.1 wheels' },
  { name: 'Agency Power' },
  { name: 'Airlift Performance' },
  { name: 'AL13 wheels' },
  { name: 'AMS / Alpha Performance' },
  { name: 'American Racing Headers' },
  { name: 'ANRKY wheels' },
  { name: 'APR' },
  { name: 'Avantgarde Wheels' },
  { name: 'BE bearings' },
  { name: 'BBi Autosport' },
  { name: 'Big Boost' },
  { name: 'BimmerWorld' },
  { name: 'BootMod3' },
  { name: 'Borla' },
  { name: 'Brixton wheels' },
  { name: 'Burger Motorsport' },
  { name: 'Circle D' },
  { name: 'Cobb tuning' },
  { name: 'CMST' },
  { name: 'CSF' },
  { name: 'DarwinPro' },
  { name: 'Deatschwerks' },
  { name: 'Dorch Engineering' },
  { name: 'Driveshaftshop' },
  { name: 'Duke Dynamics' },
  { name: 'Eterna Motorworks' },
  { name: 'Fabspeed' },
  { name: 'Fall-Line Motorsports' },
  { name: 'Fore Innovations' },
  { name: 'Fragola Performance Systems' },
  { name: 'Full-Race' },
  { name: 'Future Design' },
  { name: 'Girodisc' },
  { name: 'HRE wheels' },
  { name: 'Injector Dynamics' },
  { name: 'JXB Performance' },
  { name: 'Karbel' },
  { name: 'Killer B Motorsport' },
  { name: 'KLM Race' },
  { name: 'Kooks Headers' },
  { name: 'Lingenfelter' },
  { name: 'Mega3 Performance' },
  { name: 'Mickey Thompson' },
  { name: 'Motiv Motorsport' },
  { name: 'Moser Engineering' },
  { name: 'Mountune' },
  { name: 'MV Forged' },
  { name: 'Paragon brakes' },
  { name: 'Paramount transmissions' },
  { name: 'Premier Tuning Group' },
  { name: 'Project 6GR' },
  { name: 'Pure Drivetrain Solutions' },
  { name: 'Pure Turbos' },
  { name: 'Renntech' },
  { name: 'RK Autowerks' },
  { name: 'RPM Transmissions' },
  { name: 'RKP' },
  { name: 'RYFT' },
  { name: 'Seibon' },
  { name: 'ShepTrans' },
  { name: 'Southern Hotrod' },
  { name: 'Spool Performance' },
  { name: 'SPL Parts' },
  { name: 'Strasse wheels' },
  { name: 'Stoptech' },
  { name: 'Stillen' },
  { name: 'Titan Motorsport' },
  { name: 'TireRack' },
  { name: 'Turner Motorsport' },
  { name: 'Vargas Turbo' },
  { name: 'Velos Wheels' },
  { name: 'VF Engineering' },
  { name: 'VP Racing Fuel' },
  { name: 'VR Aero' },
  { name: 'VR Bespoke' },
  { name: 'VR Forged' },
  { name: 'VR Performance' },
  { name: 'VR Tuned' },
  { name: 'Vorsteiner' },
  { name: 'Wavetrac' },
  { name: 'Weistec Engineering' },
  { name: 'Whipple Superchargers' },
  { name: 'XDI fuel systems' },
];

export const brandsEurope: Brand[] = [
  { name: '3D Design' },
  { name: 'ABT' },
  { name: 'AC Schnitzer' },
  { name: 'ADRO' },
  { name: 'Akrapovic' },
  { name: 'Alpha-N' },
  { name: 'ARMA Speed' },
  { name: 'Armytrix' },
  { name: 'Black Boost' },
  { name: 'BMC filters' },
  { name: 'Brabus' },
  { name: 'Brembo' },
  { name: 'BC Racing' },
  { name: 'Capristo' },
  { name: 'CT Carbon' },
  { name: 'Custom Cages' },
  { name: 'Dahler' },
  { name: 'Deikin' },
  { name: 'DMC' },
  { name: 'do88' },
  { name: 'DTE Systems' },
  { name: 'ESS Tuning' },
  { name: 'Eventuri' },
  { name: 'FI Exhaust' },
  { name: 'GTHaus' },
  { name: 'Gruppe-M' },
  { name: 'Hamann' },
  { name: 'Hardrace' },
  { name: 'Harrop' },
  { name: 'IPe exhaust' },
  { name: 'ItalianRP' },
  { name: 'KAHN design' },
  { name: 'Karbonius' },
  { name: 'Keyvany' },
  { name: 'Kline Innovation' },
  { name: 'KW Suspension' },
  { name: 'Lamspeed' },
  { name: 'Larte Design' },
  { name: 'Liberty Walk' },
  { name: 'LOBA Motorsport' },
  { name: 'Lorinser' },
  { name: 'Lumma' },
  { name: 'Manhart' },
  { name: 'Mansory' },
  { name: 'Mamba turbo' },
  { name: "Matt's carbon" },
  { name: 'Milltek' },
  { name: 'MST Performance' },
  { name: 'Novitec' },
  { name: 'Nitron Suspension' },
  { name: 'Onyx Concept' },
  { name: 'Power Division' },
  { name: 'ProTrack Wheels' },
  { name: 'R44 Performance' },
  { name: 'Raliw Forged' },
  { name: 'Red Star Exhaust' },
  { name: 'Remus' },
  { name: 'Renegade Design' },
  { name: 'Ronin Design' },
  { name: 'RES Exhaust' },
  { name: 'RS-R' },
  { name: 'RW Carbon' },
  { name: 'Sachs Performance' },
  { name: 'Schrick' },
  { name: 'SooQoo' },
  { name: 'Sterckenn' },
  { name: 'STOPART ceramic' },
  { name: 'Supersprint' },
  { name: 'TopCar Design' },
  { name: 'Tubi Style' },
  { name: 'TTE Turbos' },
  { name: 'TTH turbos' },
  { name: 'Urban Automotive' },
  { name: 'Wagner Tuning' },
  { name: 'WALD' },
  { name: 'WheelForce' },
  { name: 'xHP' },
  { name: 'YPG' },
  { name: 'Zacoe' },
];

export const brandsOem: Brand[] = [
  { name: 'Aston Martin' },
  { name: 'Ferrari' },
  { name: 'Lamborghini' },
  { name: 'Maserati' },
  { name: 'McLaren' },
  { name: 'Rolls Royce' },
];

export const brandsRacing: Brand[] = [
  { name: 'AIM Sportline' },
  { name: 'ARE dry sump' },
  { name: 'Bell Intercoolers' },
  { name: 'DMS Shocks' },
  { name: 'Drenth Gearboxes' },
  { name: 'Driftworks' },
  { name: 'Extreme tyres' },
  { name: 'ISA Racing' },
  { name: 'Link ECU' },
  { name: 'Lithiumax batteries' },
  { name: 'MCA Suspension' },
  { name: 'Modena Engineering' },
  { name: 'Samsonas Motorsport' },
  { name: 'Sandtler' },
  { name: 'Summit Racing' },
  { name: 'Team Oreca' },
];

export const brandsMoto: Brand[] = [
  { name: 'Accossato' },
  { name: 'AEM Factory' },
  { name: 'AIM Sportline' },
  { name: 'Akrapovic' },
  { name: 'Alpha Racing' },
  { name: 'Aprilia original parts and accessories' },
  { name: 'Arrow' },
  { name: 'Austin Racing' },
  { name: 'Bikesplast' },
  { name: 'Bitubo Suspension' },
  { name: 'Black-T' },
  { name: 'BMC' },
  { name: 'Bonamici' },
  { name: 'Brembo' },
  { name: 'CNC Racing' },
  { name: 'Cordona' },
  { name: 'CRC Fairings' },
  { name: 'DBHolders' },
  { name: 'Domino' },
  { name: 'ECUStudio' },
  { name: 'EVR' },
  { name: 'Evotech' },
  { name: 'Evolution Bike' },
  { name: 'Febur' },
  { name: 'FlashTune' },
  { name: 'GBracing' },
  { name: 'Gilles Tooling' },
  { name: 'GPR Stabilizer' },
  { name: 'Healtech' },
  { name: 'HM Quickshifter' },
  { name: 'HyperPro' },
  { name: 'Ilmberger Carbon' },
  { name: 'ISA Racing' },
  { name: 'Jetprime' },
  { name: 'New Rage Cycles' },
  { name: 'Racefoxx' },
  { name: 'Rotobox' },
  { name: 'SC-Project' },
  { name: 'Samco Sport' },
  { name: 'Starlane' },
  { name: 'STM Italy' },
  { name: 'Stompgrip' },
  { name: 'Termignoni' },
  { name: 'Translogic' },
  { name: 'TWM' },
  { name: 'ValterMoto' },
  { name: 'Vandemon' },
  { name: 'WRS' },
];

export const allAutomotiveBrands: Brand[] = [
  ...brandsUsa,
  ...brandsEurope,
  ...brandsOem,
  ...brandsRacing,
].sort((a, b) => a.name.localeCompare(b.name));

export const allMotoBrands: Brand[] = [...brandsMoto].sort((a, b) => a.name.localeCompare(b.name));

export function getBrandsByCategory(category: string): Brand[] {
  switch (category) {
    case 'usa':
      return brandsUsa;
    case 'europe':
      return brandsEurope;
    case 'oem':
      return brandsOem;
    case 'racing':
      return brandsRacing;
    case 'moto':
      return brandsMoto;
    case 'auto':
      return allAutomotiveBrands;
    default:
      return [];
  }
}