import type { Metadata } from 'next';
import type { CategorySlug, Localized } from './categoryMeta';

export interface CategoryData {
  slug: CategorySlug;
  segment: 'auto' | 'moto';
  title: Localized;
  description: Localized;
  spotlight: Localized;
  brands: string[];
}

export const categoryData: CategoryData[] = [
  {
    slug: 'exhaust',
    segment: 'auto',
    title: { en: 'Exhaust Systems', ua: 'Системи випуску' },
    description: {
      en: 'TIG-welded manifolds, valvetronic cat-backs and lightweight titanium sections tuned on dynos to release power and a signature soundtrack.',
      ua: 'Колектори TIG, клапанні катбеки та титанові тракти, налаштовані на стендах для приросту потужності та фірмового тембру.',
    },
    spotlight: {
      en: 'Perfect for turbo efficiency, heat management and emotional tone.',
      ua: 'Для кращої ефективності турбіни, відведення тепла та емоційного тембру.',
    },
    brands: [
      'American Racing Headers',
      'Armytrix',
      'Borla',
      'Capristo',
      'FI Exhaust',
      'GTHaus',
      'Kline Innovation',
      'Kooks Headers',
      'Milltek',
      'Remus',
      'Supersprint',
      'Tubi Style',
      'iPE exhaust',
    ],
  },
  {
    slug: 'suspension',
    segment: 'auto',
    title: { en: 'Suspension', ua: 'Підвіска' },
    description: {
      en: 'Adaptive coilovers, motorsport dampers and full-arm kits for geometry control on street and track builds.',
      ua: 'Адаптивні койловери, мотоспорт демпфери та комплекти важелів для контролю геометрії на дорозі й треку.',
    },
    spotlight: {
      en: 'Dial in ride height, rebound and compression with OEM-safe hardware.',
      ua: 'Регулюйте кліренс, відбій і стиснення на OEM-безпечній фурнітурі.',
    },
    brands: [
      'Airlift Performance',
      'BC Racing',
      'Hardrace',
      'KW Suspension',
      'MCA Suspension',
      'Nitron Suspension',
      'SPL Parts',
    ],
  },
  {
    slug: 'wheels',
    segment: 'auto',
    title: { en: 'Wheels & Tires', ua: 'Диски та шини' },
    description: {
      en: 'Fully forged monoblock, 2-piece and 3-piece sets engineered for unsprung weight reduction and custom fitments.',
      ua: 'Ковані моноблоки, дво- та трьохсекційні диски для зменшення непідресореної маси та індивідуальних параметрів.',
    },
    spotlight: {
      en: 'Tailored offsets, finishes and load ratings for supercars and SUVs.',
      ua: 'Індивідуальні вильоти, фініші та навантаження для суперкарів та SUV.',
    },
    brands: [
      '1221 wheels',
      'ADV.1 wheels',
      'AL13 wheels',
      'ANRKY wheels',
      'Avantgarde Wheels',
      'Brixton wheels',
      'Extreme tyres',
      'HRE wheels',
      'MV Forged',
      'Mickey Thompson',
      'ONE COMPANY forged',
      'ProTrack Wheels',
      'Project 6GR',
      'Raliw Forged',
      'Strasse wheels',
      'TireRack',
      'Velos Wheels',
      'WheelForce',
    ],
  },
  {
    slug: 'brakes',
    segment: 'auto',
    title: { en: 'Brake Systems', ua: 'Гальмівні системи' },
    description: {
      en: 'Monoblock calipers, floating rotors and racing pads that deliver repeatable deceleration and pedal precision.',
      ua: 'Моноблочні супорти, плаваючі диски та спортивні колодки для стабільного гальмування та точності педалі.',
    },
    spotlight: {
      en: 'Option BBK conversions or track-only ceramic kits with telemetry support.',
      ua: 'Вибір BBK-комплектів або трекових керамічних систем із телеметрією.',
    },
    brands: [
      'Girodisc',
      'Paragon brakes',
      'STOPART ceramic',
      'STOPFLEX',
      'Stoptech',
    ],
  },
  {
    slug: 'intake',
    segment: 'auto',
    title: { en: 'Air Intake', ua: 'Впускна система' },
    description: {
      en: 'Carbon velocity stacks, sealed intakes and charge pipes that stabilise IAT and airflow on tuned platforms.',
      ua: 'Карбонові тракти, герметичні впуски та пайпінг для стабільних температур і потоку на тюнінгованих авто.',
    },
    spotlight: {
      en: 'Ideal for turbo upgrades and track cars chasing consistency.',
      ua: 'Ідеально для апгрейду турбо та трекових авто для стабільності.',
    },
    brands: [
      'ARMA Speed',
      'Alpha-N',
      'BMC filters',
      'Burger Motorsport',
      'Cobb tuning',
      'Eventuri',
      'Gruppe-M',
      'Integrated Engineering',
      'Karbonius',
      'MST Performance',
      'do88',
    ],
  },
  {
    slug: 'exterior',
    segment: 'auto',
    title: { en: 'Exterior & Aero', ua: 'Екстер’єр та аеро' },
    description: {
      en: 'Widebody kits, carbon splitters, diffusers and spoilers engineered for downforce and aggressive stance.',
      ua: 'Widebody-обвіси, карбонові сплітери, дифузори та спойлери для притискної сили та агресивного вигляду.',
    },
    spotlight: {
      en: 'From subtle OEM+ carbon accents to full widebody transformations.',
      ua: 'Від карбонових акцентів OEM+ до повних widebody трансформацій.',
    },
    brands: [
      '1016 Industries',
      '3D Design',
      'ADRO',
      'APR',
      'Alpha-N',
      'Aston Martin',
      'CT Carbon',
      'DMC',
      'DarwinPro',
      'Duke Dynamics',
      'Eterna Motorworks',
      'Ferrari',
      'Lamborghini',
      'Larte Design',
      'Liberty Walk',
      'Maserati',
      'Matt\'s carbon',
      'McLaren',
      'RKP',
      'RW Carbon',
      'Rolls Royce',
      'Seibon Carbon',
      'Urban Automotive',
      'Verus Engineering',
      'Vorsteiner',
      'WALD',
      'Zacoe',
    ],
  },
  {
    slug: 'interior',
    segment: 'auto',
    title: { en: 'Interior', ua: 'Інтер’єр' },
    description: {
      en: 'Bucket seats, steering wheels and cabin trims crafted from Alcantara, forged carbon and titanium hardware.',
      ua: 'Спортивні крісла, керма та елементи інтер’єру з алькантари, кованого карбону та титанової фурнітури.',
    },
    spotlight: {
      en: 'Ergonomics for track focus without sacrificing luxury touchpoints.',
      ua: 'Ергономіка треку без втрати преміальних матеріалів.',
    },
    brands: [
      'Bride',
      'Corbeau',
      'OMP',
      'Recaro',
      'Sabelt',
      'Schroth',
      'Sparco',
      'Takata',
    ],
  },
  {
    slug: 'performance',
    segment: 'auto',
    title: { en: 'Performance', ua: 'Продуктивність' },
    description: {
      en: 'Turbo solutions, fuel systems and ECU tuning engineered for reliable power stages up to full drag programs.',
      ua: 'Турбіни, паливні системи та налаштування ECU, розроблені для надійних ступенів потужності аж до драг-проєктів.',
    },
    spotlight: {
      en: 'From billet turbos to complete fuel system upgrades.',
      ua: 'Від білетних турбін до повних апгрейдів паливної системи.',
    },
    brands: [
      '034 Motorsport',
      '5150 Autosport',
      'ABT',
      'AC Schnitzer',
      'AIM Sportline',
      'AMS / Alpha Performance',
      'ARE dry sump',
      'ARMA Speed',
      'BBi Autosport',
      'BE bearings',
      'BMC filters',
      'Bell Intercoolers',
      'Big Boost',
      'BimmerWorld',
      'Black Boost',
      'BootMod3',
      'Brabus',
      'Burger Motorsport',
      'CSF',
      'Circle D',
      'Cobb tuning',
      'DTE Systems',
      'Dahler',
      'Deatschwerks',
      'Dinan',
      'Dorch Engineering',
      'Drenth Gearboxes',
      'Driveshaftshop',
      'ESS Tuning',
      'Eventuri',
      'Fabspeed',
      'Fall-Line Motorsports',
      'Fore Innovations',
      'Fragola Performance Systems',
      'Full-Race',
      'Gruppe-M',
      'Hamann',
      'Harrop',
      'Heico',
      'Injector Dynamics',
      'Integrated Engineering',
      'ItalianRP',
      'JXB Performance',
      'KAHN design',
      'KLM Race',
      'Karbonius',
      'Keyvany',
      'Killer B Motorsport',
      'Kotouc',
      'LOBA Motorsport',
      'Lamspeed',
      'Lingenfelter',
      'Link ECU',
      'Lithiumax batteries',
      'Lorinser',
      'Lumma',
      'MST Performance',
      'Mamba turbo',
      'Manhart',
      'Mansory',
      'Modena Engineering',
      'Moser Engineering',
      'Motiv Motorsport',
      'Mountune',
      'Novitec',
      'Onyx Concept',
      'Paramount transmissions',
      'Power Division',
      'Premier Tuning Group',
      'Pulsar turbo',
      'Pure Drivetrain Solutions',
      'Pure Turbos',
      'R44 Performance',
      'RK Autowerks',
      'RPM Transmissions',
      'RYFT',
      'Renntech',
      'Sachs Performance',
      'Samsonas Motorsport',
      'Schrick',
      'ShepTrans',
      'Silly Rabbit Motorsport',
      'Southern Hotrod',
      'Spool Performance',
      'Stillen',
      'Titan Motorsport',
      'Turner Motorsport',
      'VF Engineering',
      'VP Racing Fuel',
      'Vargas Turbo',
      'Wagner Tuning',
      'Wavetrac',
      'Weistec Engineering',
      'Whipple Superchargers',
      'XDI fuel systems',
      'Xshift',
      'YPG',
      'do88',
    ],
  },
  {
    slug: 'cooling',
    segment: 'auto',
    title: { en: 'Cooling', ua: 'Охолодження' },
    description: {
      en: 'High-performance intercoolers, radiators and oil coolers to manage heat soak on track and street.',
      ua: 'Високопродуктивні інтеркулери, радіатори та маслокулери для контролю температур на треку та вулиці.',
    },
    spotlight: {
      en: 'Essential for maintaining power during repeated hard driving.',
      ua: 'Необхідно для збереження потужності при тривалих навантаженнях.',
    },
    brands: [
      'Bell Intercoolers',
      'CSF',
      'Wagner Tuning',
      'do88',
    ],
  },
  {
    slug: 'moto-exhaust',
    segment: 'moto',
    title: { en: 'Exhaust & Sound', ua: 'Вихлоп та звук' },
    description: {
      en: 'Full titanium systems, slip-ons and race-only exhausts with FIM homologation and dyno-verified power gains.',
      ua: 'Повні титанові системи, slip-on та трекові вихлопи з FIM гомологацією та підтвердженим приростом потужності.',
    },
    spotlight: {
      en: 'Designed for WorldSBK, MotoGP and track day domination.',
      ua: 'Розроблені для WorldSBK, MotoGP та трекових днів.',
    },
    brands: [
      'Akrapovic',
      'Arrow',
      'Austin Racing',
      'Cobra Sport',
      'Dominator Exhaust',
      'IXIL',
      'SC-Project',
      'SparkExhaust',
      'TOCE Exhaust',
      'Termignoni',
      'Vandemon',
      'ZARD Exhaust',
    ],
  },
  {
    slug: 'moto-suspension',
    segment: 'moto',
    title: { en: 'Suspension & Chassis', ua: 'Підвіска та шасі' },
    description: {
      en: 'Cartridge kits, fully adjustable forks and rear shocks with dyno-driven shim stacks and linkage geometry.',
      ua: 'Картриджі, повністю регульовані вилки та задні амортизатори з діно-підбором шайб та геометрії лінків.',
    },
    spotlight: {
      en: 'From street comfort to race-spec compression and rebound control.',
      ua: 'Від комфорту на дорозі до трекового контролю стиснення та відбою.',
    },
    brands: [
      'Bitubo',
      'GPR Stabilizer',
      'HyperPro',
      'Ohlins',
    ],
  },
  {
    slug: 'moto-wheels',
    segment: 'moto',
    title: { en: 'Wheels & Brakes', ua: 'Диски та гальма' },
    description: {
      en: 'Carbon and forged aluminum wheels paired with radial master cylinders, racing pads and floating rotors.',
      ua: 'Карбонові та ковані алюмінієві диски з радіальними циліндрами, спортивними колодками та плаваючими дисками.',
    },
    spotlight: {
      en: 'Unsprung weight reduction and repeatable braking for litre bikes.',
      ua: 'Зменшення непідресореної маси та стабільне гальмування для літрових байків.',
    },
    brands: [
      'Accossato',
      'Brembo',
      'Marchesini',
      'OZ Racing',
      'Rotobox',
      'X-GRIP',
    ],
  },
  {
    slug: 'moto-carbon',
    segment: 'moto',
    title: { en: 'Carbon & Aero', ua: 'Карбон та аеро' },
    description: {
      en: 'Pre-preg carbon fairings, tank covers, fenders and crash protection engineered for weight savings and track legality.',
      ua: 'Препрег-карбон обтічники, баки, крила та краш-захист для зниження ваги та трекової легальності.',
    },
    spotlight: {
      en: 'FIM-approved kits with paint-to-sample finishing options.',
      ua: 'FIM-сертифіковані комплекти з індивідуальним фарбуванням.',
    },
    brands: [
      'AXP',
      'Bikesplast',
      'DB-Race',
      'Fullsix Carbon',
      'Ilmberger Carbon',
      'New Rage Cycles',
      'P3 Carbon',
      'S2 Concept',
      'Sebimoto',
      'Stompgrip',
    ],
  },
  {
    slug: 'moto-controls',
    segment: 'moto',
    title: { en: 'Controls & Ergonomics', ua: 'Керування та ергономіка' },
    description: {
      en: 'Adjustable rearsets, clip-ons and billet levers for precise rider interface and lap time gains.',
      ua: 'Регульовані підніжки, кліпони та білетні важелі для точного керування та кращих часів кіл.',
    },
    spotlight: {
      en: 'CNC-machined with multiple position options for track ergonomics.',
      ua: 'CNC-оброблені з кількома позиціями для трекової ергономіки.',
    },
    brands: [
      'AEM Factory',
      'ARP Racingparts',
      'Alpha Racing',
      'Bonamici',
      'CNC Racing',
      'Capit',
      'Domino',
      'Evolution Bike',
      'Evotech',
      'Gilles Tooling',
      'Melotti Racing',
      'R&G Racing',
      'Racefoxx',
      'Rizoma',
      'TWM',
      'Thermal Technology',
      'ValterMoto',
    ],
  },
  {
    slug: 'moto-electronics',
    segment: 'moto',
    title: { en: 'Electronics & Data', ua: 'Електроніка та дані' },
    description: {
      en: 'ECU flashing, quickshifter modules, traction control and GPS telemetry systems for data-driven setup optimization.',
      ua: 'Прошивка ECU, модулі квікшифтера, трекшн-контроль та GPS-телеметрія для оптимізації налаштувань на основі даних.',
    },
    spotlight: {
      en: 'From street power unlocks to full race data acquisition.',
      ua: 'Від розблокування потужності на дорозі до повної трекової телеметрії.',
    },
    brands: [
      'AIM Tech',
      'BT Moto',
      'Cordona',
      'ECUStudio',
      'FlashTune',
      'HM Quickshifter',
      'Healtech',
      'Jetprime',
      'Starlane',
      'Translogic',
    ],
  },
];

export function getCategoryMetadata(slug: string, locale: string): Metadata {
  const category = categoryData.find(c => c.slug === slug);
  if (!category) return {};

  const lang = locale === 'ua' ? 'ua' : 'en';
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://onecompany.global';
  const url = `${baseUrl}/${locale}/${category.segment}/categories/${slug}`;
  
  return {
    title: category.title[lang],
    description: category.description[lang],
    alternates: {
      canonical: url,
      languages: {
        'en': `${baseUrl}/en/${category.segment}/categories/${slug}`,
        'uk-UA': `${baseUrl}/ua/${category.segment}/categories/${slug}`,
      }
    },
    openGraph: {
      title: category.title[lang],
      description: category.description[lang],
      url: url,
    }
  };
}
