import type { Metadata } from 'next';
import type { CategorySlug, Localized } from './categoryMeta';

export interface CategoryData {
  slug: CategorySlug;
  segment: 'auto' | 'moto';
  title: Localized;
  description: Localized;
  spotlight: Localized;
  brands: string[];
}

export const categoryData: CategoryData[] = [
  // -----------------------
  // AUTO CATEGORIES
  // -----------------------
  {
    slug: 'wheels',
    segment: 'auto',
    title: { en: 'Wheels', ua: 'Диски' },
    description: {
      en: 'Premium forged monoblock, 2-piece and 3-piece wheels for performance and style.',
      ua: 'Преміальні ковані моноблоки, дво- та трьохсекційні диски для продуктивності та стилю.',
    },
    spotlight: {
      en: 'Custom fitments and lightweight engineering.',
      ua: 'Індивідуальні параметри та легка конструкція.',
    },
    brands: [
      // USA
      '1221 wheels',
      'ADV.1 wheels',
      'AL13 wheels',
      'ANRKY wheels',
      'Avantgarde Wheels',
      'Brixton wheels',
      'HRE wheels',
      'MV Forged',
      'Project 6GR',
      'Strasse wheels',
      'Velos Wheels',
      'Vorsteiner', // also makes wheels
      // Europe + World
      'ProTrack Wheels',
      'Raliw Forged',
      'WheelForce',
      'ONE COMPANY forged',
    ],
  },
  {
    slug: 'exterior',
    segment: 'auto',
    title: { en: 'Body Kit, Carbon & Aero', ua: 'Обвіс, Карбон та Аеро' },
    description: {
      en: 'Complete widebody kits, carbon fiber aerodynamics, and exterior styling upgrades.',
      ua: 'Повні комплекти розширення, карбонова аеродинаміка та стайлінг екстер\'єру.',
    },
    spotlight: {
      en: 'Aggressive stance and functional downforce.',
      ua: 'Агресивний вигляд та функціональна притискна сила.',
    },
    brands: [
      // USA
      '1016 Industries',
      'APR',
      'DarwinPro',
      'Duke Dynamics',
      'Eterna Motorworks',
      'Renntech', // also makes body kits
      'RKP',
      'RW Carbon',
      'Seibon Carbon',
      'Stillen', // also makes body kits
      'Vorsteiner',
      // Europe + World
      '3D Design',
      'ABT',
      'AC Schnitzer',
      'ADRO',
      'Alpha-N',
      'Brabus',
      'CT Carbon',
      'DMC',
      'Hamann',
      'KAHN design',
      'Keyvany',
      'Larte Design',
      'Liberty Walk',
      'Lorinser',
      'Lumma',
      'Manhart',
      'Mansory',
      "Matt's carbon",
      'Novitec',
      'Onyx Concept',
      'Renegade Design',
      'Ronin Design',
      'SCL Concept',
      'SooQoo',
      'Sterckenn',
      'TopCar Design',
      'Urban Automotive',
      'WALD',
      'Zacoe',
    ],
  },
  {
    slug: 'exhaust',
    segment: 'auto',
    title: { en: 'Exhaust Systems', ua: 'Вихлопні системи' },
    description: {
      en: 'High-performance headers, downpipes, and valvetronic exhaust systems.',
      ua: 'Високопродуктивні колектори, даунпайпи та вальветронік системи вихлопу.',
    },
    spotlight: {
      en: 'Unlock power and signature sound.',
      ua: 'Розкрийте потужність та фірмовий звук.',
    },
    brands: [
      // USA
      'American Racing Headers',
      'Borla',
      'Fabspeed',
      'GTHaus',
      'Kooks Headers',
      // Europe + World
      'Akrapovic',
      'Armytrix',
      'Brabus', // also makes exhaust
      'Capristo',
      'Deikin',
      'FI Exhaust',
      'iPE exhaust',
      'Kline Innovation',
      'Mansory', // also makes exhaust
      'Milltek',
      'Novitec', // also makes exhaust
      'Red Star Exhaust',
      'Remus',
      'RES Exhaust',
      'Supersprint',
      'Tubi Style',
    ],
  },
  {
    slug: 'performance',
    segment: 'auto',
    title: { en: 'Engine, Turbo & Fuel', ua: 'Двигун, Турбо та Паливо' },
    description: {
      en: 'Turbo upgrades, fuel system components, superchargers, and engine internals.',
      ua: 'Модернізація турбін, компоненти паливної системи, компресори та внутрішні частини двигуна.',
    },
    spotlight: {
      en: 'Reliable power for street and track.',
      ua: 'Надійна потужність для вулиці та треку.',
    },
    brands: [
      // USA
      '5150 Autosport',
      'AMS / Alpha Performance',
      'ARE dry sump',
      'BE bearings',
      'Big Boost',
      'Burger Motorsport',
      'Deatschwerks',
      'Dorch Engineering',
      'Fore Innovations',
      'Fragola Performance Systems',
      'Full-Race',
      'Injector Dynamics',
      'Killer B Motorsport',
      'KLM Race',
      'Lingenfelter',
      'Motiv Motorsport',
      'Pure Turbos',
      'RK Autowerks',
      'Silly Rabbit Motorsport',
      'Spool Performance',
      'Vargas Turbo',
      'VF Engineering',
      'VP Racing Fuel',
      'Weistec Engineering',
      'Whipple Superchargers',
      'XDI fuel systems',
      // Europe + World
      'ARMA Speed',
      'Black Boost',
      'BMC filters',
      'ESS Tuning',
      'Eventuri',
      'Gruppe-M',
      'Harrop',
      'ItalianRP',
      'Karbonius',
      'LOBA Motorsport',
      'Mamba turbo',
      'MST Performance',
      'Power Division',
      'Pulsar turbo',
      'Schrick',
      'TTE Turbos',
      'TTH turbos',
    ],
  },
  {
    slug: 'suspension',
    segment: 'auto',
    title: { en: 'Suspension & Brakes', ua: 'Підвіска та Гальма' },
    description: {
      en: 'Coilovers, air suspension, big brake kits, and chassis reinforcement.',
      ua: 'Койловери, пневмопідвіска, гальмівні кіти та підсилення шасі.',
    },
    spotlight: {
      en: 'Handling, stance, and stopping power.',
      ua: 'Керованість, стенс та гальмівна потужність.',
    },
    brands: [
      // USA
      'Airlift Performance',
      'Girodisc',
      'MCA Suspension',
      'Paragon brakes',
      'SPL Parts',
      'Stoptech',
      // Europe + World
      'BC Racing',
      'Brembo',
      'Hardrace',
      'KW Suspension',
      'Nitron Suspension',
      'RS-R',
      'STOPART ceramic',
      'STOPFLEX',
    ],
  },
  {
    slug: 'drivetrain',
    segment: 'auto',
    title: { en: 'Drivetrain', ua: 'Трансмісія' },
    description: {
      en: 'Performance gearboxes, clutches, driveshafts, and differentials.',
      ua: 'Спортивні коробки передач, зчеплення, карданні вали та диференціали.',
    },
    spotlight: {
      en: 'Put the power to the ground.',
      ua: 'Реалізуйте потужність на дорозі.',
    },
    brands: [
      // USA
      'Circle D',
      'Driveshaftshop',
      'JXB Performance',
      'Moser Engineering',
      'Paramount transmissions',
      'Pure Drivetrain Solutions',
      'RPM Transmissions',
      'ShepTrans',
      'Southern Hotrod',
      'Wavetrac',
      // Europe + World
      'Drenth Gearboxes',
      'Kotouc',
      'Modena Engineering',
      'Sachs Performance',
      'Samsonas Motorsport',
      'Xshift',
    ],
  },
  {
    slug: 'electronics',
    segment: 'auto',
    title: { en: 'Tuning & Electronics', ua: 'Тюнінг та Електроніка' },
    description: {
      en: 'ECU tuning, chip tuning, and comprehensive performance tuning specialists.',
      ua: 'ECU тюнінг, чіп-тюнінг та комплексні спеціалісти з продуктивності.',
    },
    spotlight: {
      en: 'Software and hardware integration.',
      ua: 'Інтеграція програмного та апаратного забезпечення.',
    },
    brands: [
      // USA
      'AMS / Alpha Performance',
      'BBi Autosport',
      'BimmerWorld',
      'BootMod3',
      'Burger Motorsport',
      'Cobb tuning',
      'Fabspeed',
      'Fall-Line Motorsports',
      'Lingenfelter',
      'Mountune',
      'Premier Tuning Group',
      'Renntech',
      'RYFT',
      'Silly Rabbit Motorsport',
      'Stillen',
      'Titan Motorsport',
      'Turner Motorsport',
      'Vargas Turbo',
      'Weistec Engineering',
      // Europe + World
      'ABT',
      'AC Schnitzer',
      'AIM Sportline',
      'Black Boost',
      'Brabus',
      'Dahler',
      'DTE Systems',
      'ESS Tuning',
      'Hamann',
      'Heico',
      'KAHN design',
      'Keyvany',
      'Lamspeed',
      'Link ECU',
      'Lorinser',
      'Lumma',
      'Manhart',
      'Mansory',
      'Novitec',
      'Onyx Concept',
      'R44 Performance',
      'YPG',
    ],
  },
  {
    slug: 'cooling',
    segment: 'auto',
    title: { en: 'Cooling & Tires', ua: 'Охолодження та Шини' },
    description: {
      en: 'Intercoolers, radiators, hoses, and high-performance tires.',
      ua: 'Інтеркулери, радіатори, патрубки та високопродуктивні шини.',
    },
    spotlight: {
      en: 'Temperature control and grip.',
      ua: 'Контроль температури та зчеплення.',
    },
    brands: [
      // USA
      'Bell Intercoolers',
      'CSF',
      'Lithiumax batteries',
      'Mickey Thompson',
      'TireRack',
      // Europe + World
      'do88',
      'Extreme tyres',
      'Wagner Tuning',
    ],
  },
  {
    slug: 'oem',
    segment: 'auto',
    title: { en: 'OEM Parts', ua: 'OEM Частини' },
    description: {
      en: 'Genuine original equipment manufacturer parts for luxury vehicles.',
      ua: 'Оригінальні запчастини для автомобілів люкс-класу.',
    },
    spotlight: {
      en: 'Authentic quality and fitment.',
      ua: 'Автентична якість та сумісність.',
    },
    brands: [
      'Aston Martin',
      'Ferrari',
      'Lamborghini',
      'Maserati',
      'McLaren',
      'Rolls Royce',
    ],
  },
  {
    slug: 'racing',
    segment: 'auto',
    title: { en: 'Racing & Motorsport', ua: 'Гонки та Автоспорт' },
    description: {
      en: 'Professional racing equipment: sequential gearboxes, data acquisition, dry sump systems, and race-spec components.',
      ua: 'Професійне гоночне обладнання: секвентальні КПП, системи телеметрії, сухі картери та гоночні компоненти.',
    },
    spotlight: {
      en: 'Track-proven performance for serious competitors.',
      ua: 'Перевірена на треку продуктивність для серйозних учасників.',
    },
    brands: [
      'AIM Sportline',
      'ARE dry sump',
      'Bell Intercoolers',
      'Drenth Gearboxes',
      'Extreme tyres',
      'Kotouc',
      'Link ECU',
      'Lithiumax batteries',
      'MCA Suspension',
      'Modena Engineering',
      'Samsonas Motorsport',
      'Xshift',
    ],
  },

  // -----------------------
  // MOTO CATEGORIES
  // -----------------------
  {
    slug: 'moto-exhaust',
    segment: 'moto',
    title: { en: 'Exhaust & Sound', ua: 'Вихлоп та звук' },
    description: {
      en: 'Full titanium systems, slip-ons and race-only exhausts with FIM homologation and dyno-verified power gains.',
      ua: 'Повні титанові системи, slip-on та трекові вихлопи з FIM гомологацією та підтвердженим приростом потужності.',
    },
    spotlight: {
      en: 'Designed for WorldSBK, MotoGP and track day domination.',
      ua: 'Розроблені для WorldSBK, MotoGP та трекових днів.',
    },
    brands: [
      'Akrapovic',
      'Arrow',
      'Austin Racing',
      'Dominator Exhaust',
      'IXIL',
      'LeoVince',
      'Mivv',
      'Remus',
      'SC-Project',
      'SparkExhaust',
      'TOCE Exhaust',
      'Termignoni',
      'Two Brothers Racing',
      'Vandemon',
      'Yoshimura',
      'ZARD Exhaust',
    ],
  },
  {
    slug: 'moto-suspension',
    segment: 'moto',
    title: { en: 'Suspension & Chassis', ua: 'Підвіска та шасі' },
    description: {
      en: 'Cartridge kits, fully adjustable forks and rear shocks with dyno-driven shim stacks and linkage geometry.',
      ua: 'Картриджі, повністю регульовані вилки та задні амортизатори з діно-підбором шайб та геометрії лінків.',
    },
    spotlight: {
      en: 'From street comfort to race-spec compression and rebound control.',
      ua: 'Від комфорту на дорозі до трекового контролю стиснення та відбою.',
    },
    brands: [
      'Andreani',
      'Bitubo',
      'EMC',
      'GPR Stabilizer',
      'HyperPro',
      'K-Tech',
      'Matris',
      'Mupo',
      'Nitron',
      'Ohlins',
      'Penske',
      'Sachs',
      'Showa',
      'WP Suspension',
      'YSS',
    ],
  },
  {
    slug: 'moto-wheels',
    segment: 'moto',
    title: { en: 'Wheels & Brakes', ua: 'Диски та гальма' },
    description: {
      en: 'Carbon and forged aluminum wheels paired with radial master cylinders, racing pads and floating rotors.',
      ua: 'Карбонові та ковані алюмінієві диски з радіальними циліндрами, спортивними колодками та плаваючими дисками.',
    },
    spotlight: {
      en: 'Unsprung weight reduction and repeatable braking for litre bikes.',
      ua: 'Зменшення непідресореної маси та стабільне гальмування для літрових байків.',
    },
    brands: [
      'Accossato',
      'Beringer',
      'Braking',
      'Brembo',
      'BST',
      'Dymag',
      'EBC Brakes',
      'Ferodo',
      'Galfer',
      'Marchesini',
      'Moto-Master',
      'OZ Racing',
      'Rotobox',
      'SBS',
      'Sunstar',
      'Thyssenkrupp',
    ],
  },
  {
    slug: 'moto-carbon',
    segment: 'moto',
    title: { en: 'Carbon & Aero', ua: 'Карбон та аеро' },
    description: {
      en: 'Pre-preg carbon fairings, tank covers, fenders and crash protection engineered for weight savings and track legality.',
      ua: 'Препрег-карбон обтічники, баки, крила та краш-захист для зниження ваги та трекової легальності.',
    },
    spotlight: {
      en: 'FIM-approved kits with paint-to-sample finishing options.',
      ua: 'FIM-сертифіковані комплекти з індивідуальним фарбуванням.',
    },
    brands: [
      'Akrapovic',
      'AXP',
      'Bikesplast',
      'BST',
      'Carbon2Race',
      'Carbonin',
      'CDT',
      'CMT Compositi',
      'DB Holders',
      'Evotech',
      'Extreme Components',
      'Fullsix Carbon',
      'GBracing',
      'Ilmberger Carbon',
      'MotoComposites',
      'P3 Carbon',
      'R&G Racing',
      'S2 Concept',
      'SC-Project',
      'Sebimoto',
      'Shift-Tech',
      'Strauss Carbon',
      'Termignoni',
    ],
  },
  {
    slug: 'moto-controls',
    segment: 'moto',
    title: { en: 'Controls & Ergonomics', ua: 'Керування та ергономіка' },
    description: {
      en: 'Adjustable rearsets, clip-ons and billet levers for precise rider interface and lap time gains.',
      ua: 'Регульовані підніжки, кліпони та білетні важелі для точного керування та кращих часів кіл.',
    },
    spotlight: {
      en: 'CNC-machined with multiple position options for track ergonomics.',
      ua: 'CNC-оброблені з кількома позиціями для трекової ергономіки.',
    },
    brands: [
      'Accossato',
      'AEM Factory',
      'Bonamici',
      'Brembo',
      'CNC Racing',
      'Domino',
      'Driven Racing',
      'Evotech',
      'Gilles Tooling',
      'GPR Stabilizer',
      'Lightech',
      'LSL',
      'Ohlins',
      'PP Tuning',
      'Puig',
      'R&G Racing',
      'Renthal',
      'Rizoma',
      'Sato Racing',
      'Spider',
      'Spiegler',
      'TWM',
      'Toby',
      'ValterMoto',
      'Woodcraft',
    ],
  },
  {
    slug: 'moto-electronics',
    segment: 'moto',
    title: { en: 'Electronics & Chip Tuning', ua: 'Електроніка, прилади та чіп-тюнінг' },
    description: {
      en: 'ECU flashing, quickshifter modules, traction control and GPS telemetry systems for data-driven setup optimization.',
      ua: 'Прошивка ECU, модулі квікшифтера, трекшн-контроль та GPS-телеметрія для оптимізації налаштувань на основі даних.',
    },
    spotlight: {
      en: 'From street power unlocks to full race data acquisition.',
      ua: 'Від розблокування потужності на дорозі до повної трекової телеметрії.',
    },
    brands: [
      '2D Data Recording',
      'AIM Sportline',
      'Alpha Racing',
      'Bazzaz',
      'Cordona',
      'Dynojet',
      'ECUMaster',
      'FlashTune',
      'GET',
      'Healtech',
      'HM Quickshifter',
      'iRace',
      'Jetprime',
      'MoTeC',
      'Ohlins',
      'Rapid Bike',
      'Starlane',
      'Translogic',
      'Woolich Racing',
    ],
  },
];

export function getCategoryMetadata(slug: string, locale: string): Metadata {
  const category = categoryData.find(c => c.slug === slug);
  if (!category) return {};

  const lang = locale === 'ua' ? 'ua' : 'en';
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://onecompany.global';
  const url = `${baseUrl}/${locale}/${category.segment}/categories/${slug}`;
  
  return {
    title: category.title[lang],
    description: category.description[lang],
    alternates: {
      canonical: url,
      languages: {
        'en': `${baseUrl}/en/${category.segment}/categories/${slug}`,
        'uk-UA': `${baseUrl}/ua/${category.segment}/categories/${slug}`,
      }
    },
    openGraph: {
      title: category.title[lang],
      description: category.description[lang],
      url: url,
    }
  };
}
