import type { Metadata } from 'next';
import type { CategorySlug, Localized } from './categoryMeta';

export interface CategoryData {
  slug: CategorySlug;
  segment: 'auto' | 'moto';
  title: Localized;
  description: Localized;
  spotlight: Localized;
  brands: string[];
}

export const categoryData: CategoryData[] = [
  // -----------------------
  // AUTO CATEGORIES
  // -----------------------
  {
    slug: 'wheels',
    segment: 'auto',
    title: { en: 'Wheels', ua: 'Диски' },
    description: {
      en: 'Premium forged monoblock, 2-piece and 3-piece wheels for performance and style.',
      ua: 'Преміальні ковані моноблоки, дво- та трьохсекційні диски для продуктивності та стилю.',
    },
    spotlight: {
      en: 'Custom fitments and lightweight engineering.',
      ua: 'Індивідуальні параметри та легка конструкція.',
    },
    brands: [
      'Avantgarde Wheels',
      'ANRKY wheels',
      'ADV.1 wheels',
      'AL13 wheels',
      '1221 wheels',
      'Strasse wheels',
      'Brixton wheels',
      'Project 6GR',
      'HRE wheels',
      'MV Forged',
      'ONE COMPANY forged',
      'ProTrack Wheels',
      'Velos Wheels',
      'Raliw Forged',
      'WheelForce',
    ],
  },
  {
    slug: 'exterior',
    segment: 'auto',
    title: { en: 'Body Kit, Carbon & Aero', ua: 'Обвіс, Карбон та Аеро' },
    description: {
      en: 'Complete widebody kits, carbon fiber aerodynamics, and exterior styling upgrades.',
      ua: 'Повні комплекти розширення, карбонова аеродинаміка та стайлінг екстер’єру.',
    },
    spotlight: {
      en: 'Aggressive stance and functional downforce.',
      ua: 'Агресивний вигляд та функціональна притискна сила.',
    },
    brands: [
      'Eterna Motorworks',
      'Duke Dynamics',
      'Seibon Carbon',
      '1016 Industries',
      'DarwinPro',
      '3D Design',
      'Vorsteiner',
      'WALD',
      'RKP',
      'Renegade Design',
      "Matt's carbon",
      'Larte Design',
      'Liberty Walk',
      'CT Carbon',
      'Alpha-N',
      'ADRO',
      'DMC',
      'Urban Automotive',
      'Verus Engineering',
      'TopCar Design',
      'Ronin Design',
      'SCL Concept',
      'Sterckenn',
      'SooQoo',
      'Zacoe',
      'APR',
    ],
  },
  {
    slug: 'exhaust',
    segment: 'auto',
    title: { en: 'Exhaust Systems', ua: 'Вихлопні системи' },
    description: {
      en: 'High-performance headers, downpipes, and valvetronic exhaust systems.',
      ua: 'Високопродуктивні колектори, даунпайпи та вальветронік системи вихлопу.',
    },
    spotlight: {
      en: 'Unlock power and signature sound.',
      ua: 'Розкрийте потужність та фірмовий звук.',
    },
    brands: [
      'American Racing Headers',
      'Kooks Headers',
      'Akrapovic',
      'Fabspeed',
      'Armytrix',
      'Borla',
      'Kline Innovation',
      'iPE exhaust',
      'FI Exhaust',
      'Capristo',
      'GTHaus',
      'Deikin',
      'Red Star Exhaust',
      'RES Exhaust',
      'Supersprint',
      'Tubi Style',
      'Milltek',
      'Remus',
    ],
  },
  { 
    slug: 'performance',
    segment: 'auto',
    title: { en: 'Engine, Turbo & Fuel', ua: 'Двигун, Турбо та Паливо' },
    description: {
      en: 'Turbo upgrades, fuel system components, and engine tuning solutions.',
      ua: 'Модернізація турбін, компоненти паливної системи та рішення для тюнінгу двигуна.',
    },
    spotlight: {
      en: 'Reliable power for street and track.',
      ua: 'Надійна потужність для вулиці та треку.',
    },
    brands: [
      'Fragola Performance Systems',
      'AMS / Alpha Performance',
      'Dorch Engineering',
      'Killer B Motorsport',
      'Burger Motorsport',
      'Injector Dynamics',
      'Fore Innovations',
      '5150 Autosport',
      'Deatschwerks',
      'BE bearings',
      'Big Boost',
      'Full-Race',
      'MST Performance',
      'LOBA Motorsport',
      'Power Division',
      'Mamba turbo',
      'Pulsar turbo',
      'TTE Turbos',
      'TTH turbos',
      'Gruppe-M',
      'Karbonius',
      'ItalianRP',
      'Eventuri',
      'Schrick',
      'Harrop',
      'Silly Rabbit Motorsport',
      'Spool Performance',
      'Motiv Motorsport',
      'XDI fuel systems',
      'RK Autowerks',
      'ARE dry sump',
      'Lingenfelter',
      'Pure Turbos',
      'Black Boost',
      'ESS Tuning',
      'BMC filters',
      'KLM Race',
    ],
  },
  {
    slug: 'suspension',
    segment: 'auto',
    title: { en: 'Suspension & Brakes', ua: 'Підвіска та Гальма' },
    description: {
      en: 'Coilovers, air suspension, big brake kits, and chassis reinforcement.',
      ua: 'Койловери, пневмопідвіска, гальмівні кіти та підсилення шасі.',
    },
    spotlight: {
      en: 'Handling, stance, and stopping power.',
      ua: 'Керованість, стенс та гальмівна потужність.',
    },
    brands: [
      'Airlift Performance',
      'Paragon brakes',
      'SPL Parts',
      'Girodisc',
      'Nitron Suspension',
      'KW Suspension',
      'BC Racing',
      'Stoptech',
      'Brembo',
      'STOPART ceramic',
      'STOPFLEX',
      'Hardrace',
      'RS-R',
    ],
  },
  {
    slug: 'drivetrain',
    segment: 'auto',
    title: { en: 'Drivetrain', ua: 'Трансмісія' },
    description: {
      en: 'Performance gearboxes, clutches, driveshafts, and differentials.',
      ua: 'Спортивні коробки передач, зчеплення, карданні вали та диференціали.',
    },
    spotlight: {
      en: 'Put the power to the ground.',
      ua: 'Реалізуйте потужність на дорозі.',
    },
    brands: [
      'Moser Engineering',
      'Drenth Gearboxes',
      'JXB Performance',
      'Driveshaftshop',
      'Circle D',
      'Paramount transmissions',
      'Pure Drivetrain Solutions',
      'Modena Engineering',
      'RPM Transmissions',
      'Kotouc',
      'Xshift',
      'Samsonas Motorsport',
      'Sachs Performance',
      'Southern Hotrod',
      'ShepTrans',
      'Wavetrac',
    ],
  },
  {
    slug: 'electronics',
    segment: 'auto',
    title: { en: 'Tuning & Electronics', ua: 'Тюнінг та Електроніка' },
    description: {
      en: 'Comprehensive tuning, ECU remapping, and electronic upgrades.',
      ua: 'Комплексний тюнінг, перепрошивка ECU та електронні апгрейди.',
    },
    spotlight: {
      en: 'Software and hardware integration.',
      ua: 'Інтеграція програмного та апаратного забезпечення.',
    },
    brands: [
      'Premier Tuning Group',
      'Fall-Line Motorsports',
      'Titan Motorsport',
      'BimmerWorld',
      'BBi Autosport',
      'Cobb tuning',
      'BootMod3',
      'Mountune',
      'Renntech',
      'Stillen',
      'RYFT',
      'R44 Performance',
      'Onyx Concept',
      'KAHN design',
      'Lamspeed',
      'Manhart',
      'Mansory',
      'Keyvany',
      'Lorinser',
      'Novitec',
      'Lumma',
      'YPG',
      'ABT',
      'Turner Motorsport',
      'VF Engineering',
      'AIM Sportline',
      'Vargas Turbo',
      'DTE Systems',
      'AC Schnitzer',
      'Hamann',
      'Link ECU',
      'Brabus',
      'Dahler',
      'Heico',
    ],
  },
  {
    slug: 'cooling',
    segment: 'auto',
    title: { en: 'Cooling & Tires', ua: 'Охолодження та Шини' },
    description: {
      en: 'Intercoolers, radiators, hoses, and high-performance tires.',
      ua: 'Інтеркулери, радіатори, патрубки та високопродуктивні шини.',
    },
    spotlight: {
      en: 'Temperature control and grip.',
      ua: 'Контроль температури та зчеплення.',
    },
    brands: [
      'Bell Intercoolers',
      'Wagner Tuning',
      'Extreme tyres',
      'BMC',
      'CSF',
      'do88',
      'TireRack',
      'Samco Sport',
      'Mickey Thompson',
      'Lithiumax batteries',
    ],
  },
  {
    slug: 'oem',
    segment: 'auto',
    title: { en: 'OEM Parts', ua: 'OEM Частини' },
    description: {
      en: 'Genuine original equipment manufacturer parts for luxury vehicles.',
      ua: 'Оригінальні запчастини для автомобілів люкс-класу.',
    },
    spotlight: {
      en: 'Authentic quality and fitment.',
      ua: 'Автентична якість та сумісність.',
    },
    brands: [
      'Aston Martin',
      'Ferrari',
      'Lamborghini',
      'Maserati',
      'Rolls Royce',
      'McLaren',
    ],
  },

  // -----------------------
  // MOTO CATEGORIES (Keep existing)
  // -----------------------
  {
    slug: 'moto-exhaust',
    segment: 'moto',
    title: { en: 'Exhaust & Sound', ua: 'Вихлоп та звук' },
    description: {
      en: 'Full titanium systems, slip-ons and race-only exhausts with FIM homologation and dyno-verified power gains.',
      ua: 'Повні титанові системи, slip-on та трекові вихлопи з FIM гомологацією та підтвердженим приростом потужності.',
    },
    spotlight: {
      en: 'Designed for WorldSBK, MotoGP and track day domination.',
      ua: 'Розроблені для WorldSBK, MotoGP та трекових днів.',
    },
    brands: [
      'Accossato',
      'Akrapovic',
      'Arrow',
      'Austin Racing',
      'Cobra Sport',
      'Dominator Exhaust',
      'Febur',
      'IXIL',
      'P3 Carbon',
      'SC-Project',
      'SparkExhaust',
      'Starlane',
      'TOCE Exhaust',
      'Termignoni',
      'Translogic',
      'Vandemon',
      'ZARD Exhaust',
    ],
  },
  {
    slug: 'moto-suspension',
    segment: 'moto',
    title: { en: 'Suspension & Chassis', ua: 'Підвіска та шасі' },
    description: {
      en: 'Cartridge kits, fully adjustable forks and rear shocks with dyno-driven shim stacks and linkage geometry.',
      ua: 'Картриджі, повністю регульовані вилки та задні амортизатори з діно-підбором шайб та геометрії лінків.',
    },
    spotlight: {
      en: 'From street comfort to race-spec compression and rebound control.',
      ua: 'Від комфорту на дорозі до трекового контролю стиснення та відбою.',
    },
    brands: [
      'Bitubo',
      'Febur',
      'GPR Stabilizer',
      'HyperPro',
      'Ohlins',
      'Samco Sport',
    ],
  },
  {
    slug: 'moto-wheels',
    segment: 'moto',
    title: { en: 'Wheels & Brakes', ua: 'Диски та гальма' },
    description: {
      en: 'Carbon and forged aluminum wheels paired with radial master cylinders, racing pads and floating rotors.',
      ua: 'Карбонові та ковані алюмінієві диски з радіальними циліндрами, спортивними колодками та плаваючими дисками.',
    },
    spotlight: {
      en: 'Unsprung weight reduction and repeatable braking for litre bikes.',
      ua: 'Зменшення непідресореної маси та стабільне гальмування для літрових байків.',
    },
    brands: [
      'Accossato',
      'Brembo',
      'Jetprime',
      'Marchesini',
      'OZ Racing',
      'Racefoxx',
      'Rotobox',
      'Thermal Technology',
      'X-GRIP',
    ],
  },
  {
    slug: 'moto-carbon',
    segment: 'moto',
    title: { en: 'Carbon & Aero', ua: 'Карбон та аеро' },
    description: {
      en: 'Pre-preg carbon fairings, tank covers, fenders and crash protection engineered for weight savings and track legality.',
      ua: 'Препрег-карбон обтічники, баки, крила та краш-захист для зниження ваги та трекової легальності.',
    },
    spotlight: {
      en: 'FIM-approved kits with paint-to-sample finishing options.',
      ua: 'FIM-сертифіковані комплекти з індивідуальним фарбуванням.',
    },
    brands: [
      'AXP',
      'Akrapovic',
      'Bikesplast',
      'Ceracarbon',
      'DB-Race',
      'EVR',
      'Evotech',
      'Fullsix Carbon',
      'GBracing',
      'Ilmberger Carbon',
      'Melotti Racing',
      'New Rage Cycles',
      'P3 Carbon',
      'R&G Racing',
      'Racefoxx',
      'Rotobox',
      'S2 Concept',
      'SC-Project',
      'Sebimoto',
      'Stompgrip',
    ],
  },
  {
    slug: 'moto-controls',
    segment: 'moto',
    title: { en: 'Controls & Ergonomics', ua: 'Керування та ергономіка' },
    description: {
      en: 'Adjustable rearsets, clip-ons and billet levers for precise rider interface and lap time gains.',
      ua: 'Регульовані підніжки, кліпони та білетні важелі для точного керування та кращих часів кіл.',
    },
    spotlight: {
      en: 'CNC-machined with multiple position options for track ergonomics.',
      ua: 'CNC-оброблені з кількома позиціями для трекової ергономіки.',
    },
    brands: [
      'AEM Factory',
      'ARP Racingparts',
      'Accossato',
      'Alpha Racing',
      'Bonamici',
      'Brembo',
      'CNC Racing',
      'Capit',
      'Domino',
      'ECUStudio',
      'Evolution Bike',
      'Evotech',
      'GPR Stabilizer',
      'Gilles Tooling',
      'Jetprime',
      'Melotti Racing',
      'R&G Racing',
      'Racefoxx',
      'Rizoma',
      'Stompgrip',
      'TWM',
      'Thermal Technology',
      'ValterMoto',
      'X-GRIP',
    ],
  },
  {
    slug: 'moto-electronics',
    segment: 'moto',
    title: { en: 'Electronics & Data', ua: 'Електроніка та дані' },
    description: {
      en: 'ECU flashing, quickshifter modules, traction control and GPS telemetry systems for data-driven setup optimization.',
      ua: 'Прошивка ECU, модулі квікшифтера, трекшн-контроль та GPS-телеметрія для оптимізації налаштувань на основі даних.',
    },
    spotlight: {
      en: 'From street power unlocks to full race data acquisition.',
      ua: 'Від розблокування потужності на дорозі до повної трекової телеметрії.',
    },
    brands: [
      'AIM Tech',
      'BT Moto',
      'Cordona',
      'ECUStudio',
      'Evolution Bike',
      'FlashTune',
      'HM Quickshifter',
      'Healtech',
      'Jetprime',
      'Ohlins',
      'Starlane',
      'Stompgrip',
      'Translogic',
      'X-GRIP',
    ],
  },
];

export function getCategoryMetadata(slug: string, locale: string): Metadata {
  const category = categoryData.find(c => c.slug === slug);
  if (!category) return {};

  const lang = locale === 'ua' ? 'ua' : 'en';
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://onecompany.global';
  const url = `${baseUrl}/${locale}/${category.segment}/categories/${slug}`;
  
  return {
    title: category.title[lang],
    description: category.description[lang],
    alternates: {
      canonical: url,
      languages: {
        'en': `${baseUrl}/en/${category.segment}/categories/${slug}`,
        'uk-UA': `${baseUrl}/ua/${category.segment}/categories/${slug}`,
      }
    },
    openGraph: {
      title: category.title[lang],
      description: category.description[lang],
      url: url,
    }
  };
}
