/** Reviewed supplier aliases from the public auto and moto fitment selectors.
 * Keep body styles and performance models separate. An empty result quarantines
 * an ambiguous fragment or a model assigned to the wrong make; it never invents fitment.
 */
type ModelCorrections = Readonly<Record<string, Readonly<Record<string, readonly string[]>>>>;

const REVIEWED_MODEL_CORRECTIONS: ModelCorrections = {
  "aston martin": { "VANTAGE Vantage": ["Vantage"] },
  audi: { ATECA: [], "ENYAQ iV Coupe": [], "Q4 E-TRON Sportback": ["Q4 Sportback e-tron"] },
  bmw: {
    "M S 1000 Rr": ["M 1000 RR", "S 1000 RR"],
    M1000R: ["M 1000 R"],
    M1000RR: ["M 1000 RR"],
    "M1000rr Bmw": ["M 1000 RR"],
    "M1000rr Bmw M": ["M 1000 RR"],
    M1000XR: ["M 1000 XR"],
    R1300gs: ["R 1300 GS"],
    R1300r: ["R 1300 R"],
    "S 1000 Rr Street": ["S 1000 RR"],
    S1000R: ["S 1000 R"],
    S1000RR: ["S 1000 RR"],
    S1000XR: ["S 1000 XR"],
  },
  citroen: { "c-elysee": ["C-Elysee"] },
  ds: {
    ds3: ["DS 3"],
    ds5: ["DS 5"],
    "ds-3-crossback": ["DS 3 Crossback"],
    "ds7-crossback": ["DS 7 Crossback"],
    "DS 4 / DS 4 CROSSBACK": ["DS 4", "DS 4 Crossback"],
  },
  ducati: {
    "Diavel 1260 Ducati Diavel": ["Diavel 1260"],
    "Panigale V4 Carbon": ["Panigale V4"],
    "Panigale V4 V4": ["Panigale V4"],
    "Panigale V4 V4s": ["Panigale V4", "Panigale V4 S"],
    "Streetfighter V4 Ducati": ["Streetfighter V4"],
    "V4 Panigale Streetfighter Ducati Ducati": ["Panigale V4", "Streetfighter V4"],
    "Xdiavel 16 Diavel 1260": ["XDiavel", "Diavel 1260"],
  },
  ferrari: {
    "488 GTB / Spider": ["488 GTB", "488 Spider"],
    "599 GTB/GTO": ["599 GTB", "599 GTO"],
    Stradale: ["SF90 Stradale"],
    Tributo: ["F8 Tributo"],
    "F8 Tributo Coupe": ["F8 Tributo"],
  },
  ford: {
    "edge-2nd-gen": ["Edge"],
    "escape-3rd-gen": ["Escape"],
    "kuga-i": ["Kuga"],
    "tourneo-connect-grand-tourneo": ["Tourneo Connect", "Grand Tourneo Connect"],
  },
  honda: { fr: [], hr: [] },
  hyundai: { h: [], "i20-pb-pbt": ["i20"], "h-1-starex": ["H-1 Starex"] },
  infiniti: { "ex-qx50": ["EX", "QX50"], "fx-qx70": ["FX", "QX70"] },
  maserati: { "GRAN TURISMO": ["GranTurismo"], GRANCABRIO: ["GranCabrio"] },
  mazda: { bt: [], cx: [] },
  "mercedes benz": {
    A35: ["AMG A 35"],
    A45S: ["AMG A 45 S"],
    A250: ["A 250"],
    "C63 AMG": ["AMG C 63"],
    C63S: ["AMG C 63 S"],
    C200: ["C 200"],
    C250: ["C 250"],
    C300: ["C 300"],
    C400: ["C 400"],
    CLA35: ["AMG CLA 35"],
    CLA250: ["CLA 250"],
    E43: ["AMG E 43"],
    "E43 Coupe": ["AMG E 43 Coupe"],
    "E53 Coupe": ["AMG E 53 Coupe"],
    E200: ["E 200"],
    E400: ["E 400"],
    "G63 AMG": ["AMG G 63"],
    GLB35: ["AMG GLB 35"],
    GLC43: ["AMG GLC 43"],
    GLC63: ["AMG GLC 63"],
    "GLC63 AMG": ["AMG GLC 63"],
    GLE53: ["AMG GLE 53"],
    GLE63: ["AMG GLE 63"],
    GLE63S: ["AMG GLE 63 S"],
    GLE450: ["GLE 450"],
    GT: ["AMG GT"],
    GT43: ["AMG GT 43"],
    "AMG GT43": ["AMG GT 43"],
    GT53: ["AMG GT 53"],
    GT63: ["AMG GT 63"],
    GTR: ["AMG GT R"],
    GTS: ["AMG GT S"],
    SL43: ["AMG SL 43"],
  },
  mini: {
    "MINI CLUBMAN": ["Clubman"],
    "MINI COUNTRYMAN": ["Countryman"],
    "MINI COOPER": ["Cooper"],
    "MINI Convertible": ["Cabrio"],
    "Cooper S LCI": ["Cooper S"],
  },
  mitsubishi: { "l-200-kaot-kbot": ["L200"] },
  nissan: { R35: ["GT-R"], "nv250-kasten": ["NV250 Van"] },
  opel: { "antara-l": ["Antara"] },
  peugeot: { "partner-kasten-tepee": ["Partner Van", "Partner Tepee"] },
  polestar: { "POLESTAR 2": ["2"] },
  porsche: {
    Carrera: ["911 Carrera"],
    "Carrera S": ["911 Carrera S"],
    "Carrera GTS": ["911 Carrera GTS"],
    "Carrera Turbo": ["911 Turbo"],
    "911 Turbo / Turbo S": ["911 Turbo", "911 Turbo S"],
    "Cayenne 9Y0": ["Cayenne"],
    "Cayenne 9Y0 (Titanium)": ["Cayenne"],
    "Macan 2.0T / S / GTS / Turbo": ["Macan", "Macan S", "Macan GTS", "Macan Turbo"],
    "Macan S 2.9T": ["Macan S"],
  },
  saab: { "9": [] },
  scion: { BRZ: [] },
  seat: { "GOLF VII Estate": [] },
  subaru: { GR86: [] },
  toyota: {
    BRZ: [],
    rav: [],
    "ALPHARD / VELLFIRE": ["Alphard", "Vellfire"],
    "YARIS/VITZ": ["Yaris", "Vitz"],
    "GR 86 Coupe": ["GR86"],
    "Supra 2.0T": ["Supra"],
  },
  vauxhall: { "antara-l": ["Antara"], "zafira-mk": ["Zafira"] },
  volkswagen: { Born: [], "t7-stm-stn": ["Multivan T7"] },
};

/**
 * Audit of the public auto selector on 2026-10-07 (135 makes, 2,664 labels):
 * chassis lists, product titles, market qualifiers (`[american Market]`), make
 * prefixes and body variants that were offered as separate models. Every raw
 * value stays queryable through the label it maps to.
 */
const SELECTOR_AUDIT_MODEL_CORRECTIONS: ModelCorrections = {
  aro: { "Aro 10": ["10"] },
  "aston martin": { "DBS Superleggera 770 Ultimate": ["DBS Superleggera"] },
  audi: {
    "A4 + Cabriolet": ["A4"],
    "A5 + A5 Cabriolet + Sportback": ["A5"],
    "A5 + Cabriolet": ["A5"],
    "A7 Sportback": ["A7"],
    "A8 [american Market]": ["A8"],
    "Allroad Quattro": ["Allroad"],
    "Audi / A5 / B9.5": ["A5"],
    "Audi / A6 / C8,audi / A6 / C9": ["A6"],
    "Audi / A7 / C8": ["A7"],
    "Audi / Q3 / F3": ["Q3"],
    "Audi / Q5 / Fy": ["Q5"],
    "Audi / Q7 / 4M": ["Q7"],
    "Audi / Q8 / 4M": ["Q8"],
    "Audi / RS6 / C7,audi / RS6 / C8,audi / RS6 / C6,audi / RS6 / C5": ["RS6"],
    Golf: [],
    "Golf GTI": [],
    "Golf R": [],
    "RS3 8Y Limousine": ["RS3"],
    "RS3 8Y Limousine Sportback": ["RS3"],
    "RS3 8Y Sportback": ["RS3"],
    "RS4 B9.5 Avant": ["RS4"],
    "RS5 B9.5 Coupé": ["RS5 Coupé"],
    "RS5 B9.5 Sportback": ["RS5 Sportback"],
    "RS6 C8": ["RS6"],
    "RS7 C8": ["RS7"],
    "RS6 RS7 C8": ["RS6", "RS7"],
    "TT / Tts / Ttrs II": ["TT", "TTS", "TTRS"],
    "TT / Tts / Ttrs III": ["TT", "TTS", "TTRS"],
    Tts: ["TTS"],
  },
  bmw: {
    "1": ["1 Series"],
    "1 [american Market]": ["1 Series"],
    "2": ["2 Series"],
    "2 Convertible": ["2 Series"],
    "2 Coupe": ["2 Series"],
    "3": ["3 Series"],
    "3 [american Market]": ["3 Series"],
    "3 Compact": ["3 Series"],
    "3 Gran Turismo": ["3 Series"],
    "3 GT": ["3 Series"],
    "3 Touring": ["3 Series"],
    "4": ["4 Series"],
    "4 Convertible": ["4 Series"],
    "4 Coupe": ["4 Series"],
    "4 Gran Coupe": ["4 Series"],
    "5": ["5 Series"],
    "5 GT": ["5 Series"],
    "5 Touring": ["5 Series"],
    "6": ["6 Series"],
    "6 Convertible": ["6 Series"],
    "6 Gc": ["6 Series"],
    "6 Gran Coupe": ["6 Series"],
    "7": ["7 Series"],
    "7 [american Market]": ["7 Series"],
    M760LI: ["7 Series"],
    "8": ["8 Series"],
    "8 Convertible": ["8 Series"],
    "8 Coupe": ["8 Series"],
    "8 Gran Coupe": ["8 Series"],
    // ALPINA B3/B4 share the 3/4 Series platform and parts.
    B3: ["3 Series"],
    B4: ["4 Series"],
    "2025 BMW G99 M5 wagon revozport dry carbon spoiler": ["M5"],
    "M5 G90 Sedan": ["M5"],
    "M5 G90SEDAN G99TOURING": ["M5"],
    G80: ["M3"],
    G81: ["M3"],
    "G80 M3": ["M3"],
    "G81 M3": ["M3"],
    "G80 G81 M3": ["M3"],
    "G80 G81 M3 G82 G83 M4": ["M3", "M4"],
    G82: ["M4"],
    G83: ["M4"],
    "G82 M4": ["M4"],
    "G83 M4": ["M4"],
    "G82 G83 M4": ["M4"],
    "G82 M4 G22": ["M4", "4 Series"],
    G87: ["M2"],
    "G87 M2": ["M2"],
    "F91 F92 F93 M8": ["M8"],
    "F91 F92 M8 G14 G15": ["M8", "8 Series"],
    "F91 F92 M8 G15": ["M8", "8 Series"],
    "X3M F97 LCI": ["X3 M"],
    "X3M F97 X4M F98 LCI": ["X3 M", "X4 M"],
    "X4M F98 LCI": ["X4 M"],
    "X5M F95": ["X5 M"],
    "X5M F95 LCI": ["X5 M"],
    "X5M F95 X6M F96": ["X5 M", "X6 M"],
    "X5M X6M F95 F96 LCI": ["X5 M", "X6 M"],
    "X5M X6M F95 LCI": ["X5 M", "X6 M"],
    "X6M F96": ["X6 M"],
    "X6M F96 LCI": ["X6 M"],
    "X6 G06 M Sport": ["X6"],
    "X7 M60I": ["X7"],
    "Z 1": ["Z1"],
    "Z 3": ["Z3"],
    "Z 8": ["Z8"],
  },
  cadillac: { Elr: ["ELR"], Xlr: ["XLR"], "Xlr-V": ["XLR-V"], Xts: ["XTS"] },
  chevrolet: {
    "Avalanche [mexican Market]": ["Avalanche"],
    "Silverado [mexican Market]": ["Silverado"],
    "Suburban [mexican Market]": ["Suburban"],
    "Corvette C6 Base/ZR1": ["Corvette"],
    "Corvette C6 ZR1": ["Corvette"],
    "Corvette C7": ["Corvette"],
    "Dry Carbon Front Inner Fender Liners Set (2 Pcs) For 2014–2019 Chevrolet Corvette C7": [
      "Corvette",
    ],
  },
  daihatsu: { "Terios II [american Market]": ["Terios II"] },
  ds: { "DS3 Crossback": ["DS 3 Crossback"], "DS4 II": ["DS 4"], DS9: ["DS 9"] },
  fiat: {
    "500 / Nuova 500 [american Market]": ["500 / Nuova 500"],
    "500 Abarth [american Market]": ["500 Abarth"],
    "500L [american Market]": ["500L"],
    "500X [american Market]": ["500X"],
  },
  ford: { "C-Max Ii,grand C-Max": ["C-Max"], "Ranger [american Market]": ["Ranger"] },
  honda: {
    "Civic X [china]": ["Civic X"],
    "Civic X [usa]": ["Civic X"],
    "Civic XI [china]": ["Civic XI"],
    "Civic XI [usa]": ["Civic XI"],
    "CR-V V [china, Usa]": ["CR-V V"],
    "Fit [china]": ["Fit"],
    "Prelude IV [europe]": ["Prelude IV"],
    "Prelude IV [japan]": ["Prelude IV"],
    "Prelude IV [usa, Aus]": ["Prelude IV"],
    "Prelude V [japan]": ["Prelude V"],
    "Prelude VI [europe]": ["Prelude VI"],
    "Prelude VI [japan]": ["Prelude VI"],
  },
  infiniti: { "Q70 / M [russia]": ["Q70"] },
  jaguar: { "Xf,xf Sportbrake": ["XF"], "XJ / Xjr": ["XJ", "XJR"], "Xk / XKR": ["XK", "XKR"] },
  jeep: { "Renegade [american Market]": ["Renegade"] },
  lada: { "Niva / 4X4 /Taiga": ["Niva"], "Vesta Cross,vesta Sw,vesta SW Cross": ["Vesta"] },
  lexus: {
    GX470: ["GX"],
    GX550: ["GX"],
    LX460: ["LX"],
    LX470: ["LX"],
    LX570: ["LX"],
    RX450H: ["RX"],
    "SC 300": ["SC"],
    "SC 400": ["SC"],
    "IS + IS Sportcross": ["IS"],
  },
  lotus: { "Elise [american Market]": ["Elise"] },
  "maruti suzuki": { "Jimny [indian Market, 5 Doors]": ["Jimny"] },
  maserati: { "Quattroporte [chinese Market]": ["Quattroporte"] },
  "mercedes benz": {
    "Class A": ["A-Class"],
    "Class B": ["B-Class"],
    "Class C": ["C-Class"],
    "Class E": ["E-Class"],
    "Class G": ["G-Class"],
    "Class G [american Market]": ["G-Class"],
    "G-Wagon": ["G-Class"],
    "Class M": ["M-Class"],
    "Class R": ["R-Class"],
    "Class S": ["S-Class"],
    "Class S [american Market]": ["S-Class"],
    "Class SL": ["SL-Class"],
    "Class T": ["T-Class"],
    "Class V": ["V-Class"],
    "Class V III": ["V-Class"],
    "Class X": ["X-Class"],
    Clc: ["CLC-Class"],
    Cle: ["CLE-Class"],
    Clk: ["CLK-Class"],
    CLS: ["CLS-Class"],
    "CLS / CLS Shooting Brake": ["CLS-Class"],
    GL: ["GL-Class"],
    "GL / GLS": ["GL-Class", "GLS-Class"],
    GLC: ["GLC-Class"],
    "GLC / GLC Coupe": ["GLC-Class"],
    GLE: ["GLE-Class"],
    "GLE Coupe": ["GLE-Class"],
    "GLE / GLS / GLE Coupe": ["GLE-Class", "GLS-Class"],
    Glk: ["GLK-Class"],
    "Slr Mclaren": ["SLR McLaren"],
    SLS: ["SLS AMG"],
    "SLS AMG Roadster": ["SLS AMG"],
    "G63 W465": ["AMG G 63"],
    GLC63S: ["AMG GLC 63 S"],
    CLA45: ["AMG CLA 45"],
    "Maybach II": ["Maybach"],
    "Maybach III": ["Maybach"],
    "Vito Box": ["Vito"],
    "Vito Dualiner": ["Vito"],
    "Vito Tourer": ["Vito"],
    "/8": ["W114 / W115"],
    "W120,121,w128,w180": ["W120 / W121 / W128 / W180"],
    "W108/W109 Sel/Seb": ["W108 / W109"],
    "W110 - 112 Limousine": ["W110 / W111 / W112"],
    "W100 - Pullmann": ["W100 Pullman"],
  },
  mg: { Mgf: ["MGF"], Mgtf: ["TF"], Zr: ["ZR"], Zs: ["ZS"] },
  mini: {
    "MINI Cooper I": ["Cooper", "Cooper S"],
    "MINI I": ["Cooper", "Cooper S"],
    "MINI II": ["Cooper", "Cooper S"],
    "MINI II [american And Korea Market]": ["Cooper", "Cooper S"],
    "MINI III": ["Cooper", "Cooper S"],
    "MINI IV": ["Cooper", "Cooper S"],
    "Countryman JCW ALL4": ["Countryman"],
    "JCW Countryman": ["Countryman"],
    "Clubman JCW ALL4": ["Clubman"],
  },
  nissan: {
    "200 SX [american Market]": ["200 SX"],
    "200 Sx, Zx": ["200 SX"],
    "Bluebird/Stanza [american Market]": ["Bluebird/Stanza"],
    "Blubird Sylphy": ["Bluebird Sylphy"],
    "370Z Coupe": ["370 Z"],
    "370Z Roadster": ["370 Z"],
  },
  porsche: { "986": ["Boxster"], "987": ["Boxster", "Cayman"] },
  "rolls royce": {
    "Ghost I/II": ["Ghost"],
    "Cullinan I": ["Cullinan"],
    "Phantom VIII": ["Phantom"],
  },
  rover: {
    "Rover 25": ["25"],
    "Rover 45": ["45"],
    "Rover 75": ["75"],
    "Rover 100": ["100"],
    "Rover 200": ["200"],
    "Rover 400": ["400"],
    "Rover 600": ["600"],
    "Rover 800": ["800"],
    "Mg Zr": ["MG ZR"],
    "Mg Zs": ["MG ZS"],
    Mgf: ["MGF"],
  },
  opel: { "Mokka, Mokka X": ["Mokka"] },
  renault: { "Kangoo/ Kangoo Express,rapid": ["Kangoo"] },
  suzuki: { "Jimny [japan Market, Jb64w]": ["Jimny"], "Swift II [chinese Market]": ["Swift II"] },
  toyota: {
    "Camry [made In Usa]": ["Camry"],
    "Corolla Altis [malaysan Market]": ["Corolla Altis"],
    "Corolla Ix [american Market]": ["Corolla IX"],
    "Yaris III [chinese Market]": ["Yaris III"],
  },
  uaz: { "Uaz 3151/31512": ["3151"] },
  vauxhall: { "Mokka, Mokka X": ["Mokka"] },
  "vdl bus coach": { "Vdl Midcity / Mideuro": ["Midcity / Mideuro"] },
  volkswagen: {
    A3: [],
    S3: [],
    Altas: ["Atlas"],
    "Crafter 30,35,50": ["Crafter"],
    "Crafter II 30, 35": ["Crafter II"],
    "Golf R Variant": ["Golf R"],
    "Golf VII [brazilian Market]": ["Golf"],
    "Lupo [mexican Market]": ["Lupo"],
    "Passat Nms [american Market]": ["Passat"],
    "Tiguan I [chinese Market]": ["Tiguan"],
    "Up / Load Up [brazilian Market]": ["Up / Load Up"],
  },
  volvo: {
    "C 70 I": ["C70"],
    "C 70 II": ["C70"],
    "S 40 I": ["S40"],
    "S 40 II": ["S40"],
    "S 80 II": ["S80"],
    "V 40 II": ["V40"],
    "V 40 II / Cross Country": ["V40"],
    "V 70 II": ["V70"],
    "V 70 III": ["V70"],
    "XC 40": ["XC40"],
    "XC 60 II": ["XC60"],
    "XC 70 II": ["XC70"],
    "XC 90 II": ["XC90"],
    "XC 90 Sport": ["XC90"],
    "XC 90 / XC 90 Sport": ["XC90"],
    "S 60 II / V 60 / Cross Country": ["S60", "V60"],
    "S 60 III / V 60 II / V 60 II Cross Country": ["S60", "V60"],
    "S 90 II / V 90 II / V90 II Cross Country": ["S90", "V90"],
  },
};

function mergeModelCorrections(...sources: readonly ModelCorrections[]): ModelCorrections {
  const merged: Record<string, Record<string, readonly string[]>> = {};
  for (const source of sources) {
    for (const [make, corrections] of Object.entries(source)) {
      merged[make] = { ...merged[make], ...corrections };
    }
  }
  return merged;
}

export const SHOP_VEHICLE_MODEL_CORRECTIONS = mergeModelCorrections(
  REVIEWED_MODEL_CORRECTIONS,
  SELECTOR_AUDIT_MODEL_CORRECTIONS
);

const UPPER_TOKENS = new Set(
  "amg asx ats ax bls br brz bt bx cc cla cls cr crv ct cts cx dbs dbx ds es ex ev ev6 fj fr fx gl glc gle gls gp gr gs gt gtb gtc gti gto gtr gts gx hr hs ii iii ilx is iv ix jcw ka lbx lc lci lfa lm lp ls ltd luv lx m mf mini mpv mu mx n np nsx nx nv oem pb pbt qx rc rcz rf rr rs rsx rx s sc sl sls ss st sti suv svj svx sw sx t tdi tsi tt tx ux v v8 vi vii viii vr wr wrx x xc xe xf xj xkr xi xii xl xr xv zr zx".split(
    " "
  )
);
const WORD_CASE: Readonly<Record<string, string>> = {
  mito: "MiTo",
  ecosport: "EcoSport",
  spacetourer: "SpaceTourer",
  xceed: "XCeed",
  iq: "iQ",
  xd: "xD",
  "500e": "500e",
  stepwgn: "STEPWGN",
  xdiavel: "XDiavel",
  vrs: "vRS",
  pt: "PT",
  mcv: "MCV",
};
const SPACED_SLUG =
  /^(?:grand-|range-rover|discovery-sport|santa-fe|grande-punto|124-spider|c[345]-(?:aircross|picasso|spacetourer)|xsara-picasso|pajero-sport|space-star|almera-tino|tigra-twintop|zafira-life|panamera-sport-turismo|vel-satis|corolla-verso|land-cruiser|urban-cruiser|yaris-verso|golf-(?:plus|sportsvan)|gl[ce]-coupe)/i;

/** Cosmetic formatting only: punctuation and case never broaden model identity. */
export function formatVehicleModelLabel(value: string) {
  const cleaned = SPACED_SLUG.test(value) ? value.replace(/-/g, " ") : value;
  return cleaned
    .trim()
    .replace(/\s+/g, " ")
    .split(/([\s/-]+)/)
    .map((token) => {
      if (!/[a-z]/i.test(token)) return token;
      const lower = token.toLowerCase();
      if (WORD_CASE[lower]) return WORD_CASE[lower];
      if (/^id\./.test(lower)) return token.toUpperCase();
      if (/^(?:i\d+|ix\d+)$/.test(lower)) return lower;
      if (lower === "iv" && value.toLowerCase().includes("enyaq")) return "iV";
      if (UPPER_TOKENS.has(lower) || /^(?:[a-z]{1,3}\d+[a-z]*|\d+[a-z]{1,3}\d*)$/i.test(token))
        return token.toUpperCase();
      return lower[0]!.toUpperCase() + lower.slice(1);
    })
    .join("");
}
