import { createHash } from "node:crypto"; import { flattenShopCatalogRawPayload } from "./shopCatalogSourceCoverage";
export type RemusSnapshotProduct = { id: string; slug: string; sku: string; scope: string; brand: string; title: { ua: string; en: string }; tags: string[]; variants: unknown[]; [key: string]: unknown };
export type RemusApplication = { make: string; model: string; generation: null; yearFrom: number | null; yearTo: number | null; opfGpf: string | null };
export type RemusNormalization = { productId: string; variantId: null; variantSku: string; recordKey: string; mode: "UNIVERSAL" | "VEHICLE_SPECIFIC" | "NEEDS_REVIEW"; applications: RemusApplication[]; engineRelevant: boolean; opfGpfRelevant: boolean; verification: "VERIFIED" | "NEEDS_REVIEW"; issues: string[] };
const makeNames: Record<string, string> = { vw: "Volkswagen", bmw: "BMW", mini: "MINI", audi: "Audi", cupra: "Cupra", ford: "Ford", seat: "SEAT", honda: "Honda", toyota: "Toyota", hyundai: "Hyundai", "alfa-romeo": "Alfa Romeo", maserati: "Maserati", porsche: "Porsche", suzuki: "Suzuki", fiat: "Fiat", abarth: "Abarth", skoda: "Skoda", "mercedes-benz": "Mercedes-Benz", mazda: "Mazda", subaru: "Subaru", chevrolet: "Chevrolet", peugeot: "Peugeot", renault: "Renault", kia: "Kia", opel: "Opel" };
function values(product: RemusSnapshotProduct, prefix: string) { return [...new Set(product.tags.filter((tag) => tag.startsWith(prefix)).map((tag) => tag.slice(prefix.length)).filter(Boolean))]; }
function humanize(slug: string) { return slug.split("-").map((part) => /^\d+$/.test(part) || (/\d/.test(part) && /[a-z]/i.test(part)) || /^(?:m|rs|s|x)\d/i.test(part) ? part.toUpperCase() : `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`).join(" "); }
function orderedGroups(product: RemusSnapshotProduct) { const groups: Array<{ rawMake: string; model: string; years: number[] }> = []; let currentMake = "", current: (typeof groups)[number] | null = null; for (const tag of product.tags) { if (tag.startsWith("fits-make:")) { currentMake = tag.slice(10); current = null; } else if (tag.startsWith("fits-model:")) { const [make, ...model] = tag.slice(11).split(":"); if (make && model.length && (!currentMake || make === currentMake)) { currentMake = make; current = { rawMake: make, model: humanize(model.join(":")), years: [] }; groups.push(current); } } else if (tag.startsWith("fits-year:") && current) { const year = Number(tag.slice(10)); if (Number.isSafeInteger(year) && !current.years.includes(year)) current.years.push(year); } } return groups; }
export function normalizeRemusSnapshotProduct(product: RemusSnapshotProduct): RemusNormalization { const issues: string[] = [], rawMakes = values(product, "fits-make:"), groups = orderedGroups(product), applications: RemusApplication[] = [], opfGpf = /\b(?:OPF|GPF)\b/i.test(product.title.en) ? "OPF/GPF" : null;
  if (rawMakes.length === 1 && rawMakes[0] === "universal") { /* audited universal supplier row */ } else if (!rawMakes.length || rawMakes.some((rawMake) => !makeNames[rawMake]) || !groups.length) issues.push("vehicle_application_unresolved"); else { for (const group of groups) { const years = group.years.length ? group.years : [null]; for (const year of years) applications.push({ make: makeNames[group.rawMake]!, model: group.model, generation: null, yearFrom: year, yearTo: year, opfGpf }); } }
  if (product.variants.length) issues.push("unexpected_variant_payload"); const uniqueIssues = [...new Set(issues)].sort(), universal = rawMakes[0] === "universal"; return { productId: product.id, variantId: null, variantSku: product.sku, recordKey: `${product.id}:${product.sku}`, mode: uniqueIssues.length ? "NEEDS_REVIEW" : universal ? "UNIVERSAL" : "VEHICLE_SPECIFIC", applications, engineRelevant: !universal, opfGpfRelevant: !universal && Boolean(opfGpf), verification: uniqueIssues.length ? "NEEDS_REVIEW" : "VERIFIED", issues: uniqueIssues }; }
export function buildRemusSourceRecordDraft(input: { product: RemusSnapshotProduct; sourceRevision: string }) { const normalization = normalizeRemusSnapshotProduct(input.product), provenance = flattenShopCatalogRawPayload(input.product).map((leaf) => ({ fieldPath: leaf.fieldPath, ordinal: leaf.ordinal, rawValue: leaf.value, canonicalEntityType: "PRODUCT" as const, canonicalEntityId: input.product.id, canonicalField: leaf.fieldPath, normalizedValue: leaf.value, mappingStatus: "MAPPED" as const, mapperVersion: "remus-generic-subset-v1" as const, confidence: 1 as const, reason: null, productId: input.product.id, variantId: null })); return { sourceRecord: { recordKey: normalization.recordKey, sourceRevision: input.sourceRevision, rawPayload: input.product, payloadHash: createHash("sha256").update(JSON.stringify(input.product)).digest("hex"), productId: input.product.id }, provenance, normalization, issues: normalization.issues.map((issue) => ({ issueKey: `remus:${issue}`, code: issue.toUpperCase(), rawPath: "$", details: { productId: input.product.id, supplierSku: input.product.sku } })) }; }
