import { createHash } from "node:crypto";
import { flattenShopCatalogRawPayload } from "./shopCatalogSourceCoverage";
export type IlmbergerSnapshotProduct = { id: string; slug: string; sku: string; scope: string; title: { ua: string; en: string }; category: { ua: string; en: string }; tags: string[]; variants: Array<{ id: string; sku: string | null; isDefault: boolean }>; [key: string]: unknown };
export type IlmbergerApplication = { make: string; model: string; generation: null; yearFrom: number | null; yearTo: number | null };
export type IlmbergerNormalization = { productId: string; variantId: null; variantSku: string; recordKey: string; mode: "VEHICLE_SPECIFIC" | "NEEDS_REVIEW"; applications: IlmbergerApplication[]; engineRelevant: false; verification: "VERIFIED" | "NEEDS_REVIEW"; issues: string[] };
const nonModels = new Set(["ilmberger", "ilmberger carbon", "bmw", "bmw motorrad", "ducati", "fairings", "frame-protection", "cockpit", "seats", "tank-covers", "fenders", "air-intake", "engine", "exhaust", "lighting"]);
function escape(value: string) { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function modelTags(product: IlmbergerSnapshotProduct, make: string) { const haystack = `${product.title.en} ${product.category.en}`.toLowerCase(); return [...new Set(product.tags.filter((tag) => !tag.startsWith("fits") && !nonModels.has(tag.toLowerCase()) && haystack.includes(tag.toLowerCase()) && (make === "BMW" ? /\b(?:M|S|R)\s*\d{3,4}/i.test(tag) : tag.length > 2)))]; }
function yearFor(product: IlmbergerSnapshotProduct, model: string) { const title = product.title.en, match = new RegExp(`${escape(model)}[\\s\\S]{0,45}?(?:MY\\s*)?(?:from\\s*)?((?:19|20)\\d{2})`, "i").exec(title); if (match) return Number(match[1]); const category = product.category.en.match(/(?:MY\s*)?((?:19|20)\d{2})/i), tagged = [...new Set(product.tags.filter((tag) => tag.startsWith("fits-year:")).map((tag) => Number(tag.slice(10))).filter(Number.isSafeInteger))]; return category ? Number(category[1]) : tagged.length === 1 ? tagged[0]! : null; }
export function normalizeIlmbergerSnapshotProduct(product: IlmbergerSnapshotProduct): IlmbergerNormalization { const makes = [product.tags.includes("BMW") ? "BMW" : null, product.tags.includes("Ducati") ? "Ducati" : null].filter((value): value is string => Boolean(value)), issues: string[] = [], applications: IlmbergerApplication[] = [];
  if (makes.length !== 1) issues.push("motorcycle_make_unresolved"); else { const models = modelTags(product, makes[0]!); if (!models.length) issues.push("motorcycle_model_unresolved"); else for (const model of models) { const year = yearFor(product, model); applications.push({ make: makes[0]!, model, generation: null, yearFrom: year, yearTo: year }); } }
  if (product.variants.length) issues.push("unexpected_variant_payload"); const uniqueIssues = [...new Set(issues)].sort(); return { productId: product.id, variantId: null, variantSku: product.sku, recordKey: `${product.id}:${product.sku}`, mode: uniqueIssues.length ? "NEEDS_REVIEW" : "VEHICLE_SPECIFIC", applications, engineRelevant: false, verification: uniqueIssues.length ? "NEEDS_REVIEW" : "VERIFIED", issues: uniqueIssues }; }
export function buildIlmbergerSourceRecordDraft(input: { product: IlmbergerSnapshotProduct; sourceRevision: string }) { const normalization = normalizeIlmbergerSnapshotProduct(input.product), provenance = flattenShopCatalogRawPayload(input.product).map((leaf) => { const variantField = leaf.fieldPath.startsWith("variants."), variant = variantField ? input.product.variants.length === 1 ? input.product.variants[0] : input.product.variants[leaf.ordinal] : null; if (variantField && !variant) throw new Error(`Ilmberger variant provenance cannot resolve ${leaf.fieldPath}`); const legacyScope = leaf.fieldPath === "scope" && leaf.value === "SHOP"; return { fieldPath: leaf.fieldPath, ordinal: leaf.ordinal, rawValue: leaf.value, canonicalEntityType: variantField ? ("VARIANT" as const) : ("PRODUCT" as const), canonicalEntityId: variant?.id ?? input.product.id, canonicalField: legacyScope ? "scope" : variantField ? leaf.fieldPath.slice(9) : leaf.fieldPath, normalizedValue: legacyScope ? "moto" : leaf.value, mappingStatus: "MAPPED" as const, mapperVersion: "ilmberger-snapshot-v1" as const, confidence: 1 as const, reason: legacyScope ? "audited Ilmberger SHOP scope maps to moto" : null, productId: input.product.id, variantId: variant?.id ?? null }; });
  return { sourceRecord: { recordKey: normalization.recordKey, sourceRevision: input.sourceRevision, rawPayload: input.product, payloadHash: createHash("sha256").update(JSON.stringify(input.product)).digest("hex"), productId: input.product.id }, provenance, normalization, issues: normalization.issues.map((issue) => ({ issueKey: `ilmberger:${issue}`, code: issue.toUpperCase(), rawPath: "$", details: { productId: input.product.id, supplierSku: input.product.sku } })) }; }
