import { createHash } from "node:crypto";
import { flattenShopCatalogRawPayload } from "./shopCatalogSourceCoverage";
export type BurgerSnapshotProduct = { id: string; slug: string; sku: string; scope: string; title: { ua: string; en: string }; tags: string[]; variants: Array<{ id: string; sku: string | null; isDefault: boolean }>; [key: string]: unknown };
export type BurgerApplication = { make: string; model: string; generation: string | null; yearFrom: number | null; yearTo: number | null; engineCode: string | null };
export type BurgerNormalization = { productId: string; variantId: string; variantSku: string; recordKey: string; mode: "UNIVERSAL" | "VEHICLE_SPECIFIC" | "NEEDS_REVIEW"; applications: BurgerApplication[]; engineRelevant: boolean; verification: "VERIFIED" | "NEEDS_REVIEW"; issues: string[] };
const makes: Record<string, string> = { bmw: "BMW", audi: "Audi", volkswagen: "Volkswagen", vw: "Volkswagen", porsche: "Porsche", mercedes: "Mercedes-Benz", "mercedes-benz": "Mercedes-Benz", toyota: "Toyota", ford: "Ford", infiniti: "Infiniti", kia: "Kia", hyundai: "Hyundai", "alfa romeo": "Alfa Romeo", mini: "MINI", dodge: "Dodge", jeep: "Jeep", ram: "RAM", chevrolet: "Chevrolet", cadillac: "Cadillac", nissan: "Nissan", genesis: "Genesis", maserati: "Maserati", landrover: "Land Rover", "land rover": "Land Rover", polaris: "Polaris", canam: "Can-Am", "can-am": "Can-Am", honda: "Honda", mazda: "Mazda", subaru: "Subaru", lexus: "Lexus" };
function values(product: BurgerSnapshotProduct, prefix: string) { return [...new Set(product.tags.filter((tag) => tag.startsWith(prefix)).map((tag) => tag.slice(prefix.length).trim()).filter(Boolean))]; }
function years(title: string) { const match = title.match(/\b((?:19|20)\d{2})(?:\s*[-–]\s*((?:19|20)\d{2}))?(\+)?/); return { yearFrom: match ? Number(match[1]) : null, yearTo: match?.[2] ? Number(match[2]) : match?.[3] ? null : match ? Number(match[1]) : null }; }
function titleBrands(product: BurgerSnapshotProduct) { const title = product.title.en.toLowerCase(); return values(product, "brand:").map((raw) => makes[raw.toLowerCase()]).filter((make): make is string => Boolean(make)).filter((make) => title.includes(make.toLowerCase().replace("-benz", "")) || (make === "BMW" && /\bbmw\b/i.test(title))); }
function normalize(product: BurgerSnapshotProduct) { const issues: string[] = [], models = values(product, "model:"), engines = values(product, "engine:"), chassis = values(product, "chassis:").map((value) => value.toUpperCase()), titleMakes = [...new Set(titleBrands(product))];
  const hasVehicleEvidence = Boolean(models.length || engines.length || chassis.length || titleMakes.length), applications: BurgerApplication[] = []; if (!hasVehicleEvidence) return { applications, issues, engineRelevant: false };
  if (titleMakes.length !== 1 || !models.length) issues.push(titleMakes.length > 1 ? "multi_make_correlation_unresolved" : "vehicle_make_or_model_unresolved");
  if (!issues.length) { const make = titleMakes[0]!, range = years(product.title.en); if (make === "BMW") { const fitModels = values(product, "fits-model:bmw:"); for (const model of models) { const slug = model.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); if (fitModels.length && !fitModels.includes(slug)) continue; const generations = values(product, `fits-trim:bmw:${slug}:`).map((value) => value.toUpperCase()); for (const generation of generations.length ? generations : [null]) for (const engineCode of engines.length ? engines : [null]) applications.push({ make, model, generation, ...range, engineCode }); } }
    else for (const model of models) for (const engineCode of engines.length ? engines : [null]) applications.push({ make, model, generation: null, ...range, engineCode }); }
  if (!applications.length && !issues.length) issues.push("vehicle_application_unresolved"); return { applications, issues, engineRelevant: true }; }
export function normalizeBurgerSnapshotProduct(product: BurgerSnapshotProduct): BurgerNormalization { const parsed = normalize(product), variants = product.variants.filter((variant) => variant.isDefault && variant.sku?.trim()), issues = [...parsed.issues]; if (variants.length !== 1) issues.push("default_variant_missing_or_ambiguous"); const variant = variants[0], uniqueIssues = [...new Set(issues)].sort(), hasVehicleEvidence = parsed.engineRelevant;
  return { productId: product.id, variantId: variant?.id ?? "", variantSku: variant?.sku?.trim() ?? "", recordKey: `${product.id}:${product.slug}`, mode: uniqueIssues.length ? "NEEDS_REVIEW" : hasVehicleEvidence ? "VEHICLE_SPECIFIC" : "UNIVERSAL", applications: parsed.applications, engineRelevant: parsed.engineRelevant, verification: uniqueIssues.length ? "NEEDS_REVIEW" : "VERIFIED", issues: uniqueIssues }; }
export function buildBurgerSourceRecordDraft(input: { product: BurgerSnapshotProduct; sourceRevision: string }) { const normalization = normalizeBurgerSnapshotProduct(input.product), provenance = flattenShopCatalogRawPayload(input.product).map((leaf) => { const variantField = leaf.fieldPath.startsWith("variants."), variant = variantField ? input.product.variants.length === 1 ? input.product.variants[0] : input.product.variants[leaf.ordinal] : null; if (variantField && !variant) throw new Error(`Burger variant provenance cannot resolve ${leaf.fieldPath}`); const legacyScope = leaf.fieldPath === "scope" && leaf.value === "SHOP"; return { fieldPath: leaf.fieldPath, ordinal: leaf.ordinal, rawValue: leaf.value, canonicalEntityType: variantField ? ("VARIANT" as const) : ("PRODUCT" as const), canonicalEntityId: variant?.id ?? input.product.id, canonicalField: legacyScope ? "scope" : variantField ? leaf.fieldPath.slice(9) : leaf.fieldPath, normalizedValue: legacyScope ? "auto" : leaf.value, mappingStatus: "MAPPED" as const, mapperVersion: "burger-snapshot-v1" as const, confidence: 1 as const, reason: legacyScope ? "audited LEGACY SHOP scope maps to auto" : null, productId: input.product.id, variantId: variant?.id ?? null }; });
  return { sourceRecord: { recordKey: normalization.recordKey, sourceRevision: input.sourceRevision, rawPayload: input.product, payloadHash: createHash("sha256").update(JSON.stringify(input.product)).digest("hex"), productId: input.product.id }, provenance, normalization, issues: normalization.issues.map((issue) => ({ issueKey: `burger:${issue}`, code: issue.toUpperCase(), rawPath: "$", details: { productId: input.product.id, supplierSku: input.product.sku, slug: input.product.slug } })) }; }
