/**
 * Model families: a base model and the labels suppliers use for its trims,
 * body styles and generations. Selecting the base includes every member.
 * Generated from the public selector (2026-10-07) and reviewed by hand: separate
 * models (Range Rover Sport/Evoque/Velar, 2 Series Tourers, X5 M, Cross/Sport
 * derivatives) are intentionally not members of their namesake.
 */
export const SHOP_VEHICLE_MODEL_FAMILIES: Readonly<
  Record<string, Readonly<Record<string, readonly string[]>>>
> = {
  "Alfa Romeo": {
    "4C": ["4C Spider"],
    "8C": ["8C Spider"],
  },
  Alpina: {
    Roadster: ["Roadster S"],
  },
  "Aston Martin": {
    DBS: ["DBS Superleggera"],
    DBX: ["DBX S"],
  },
  Audi: {
    "90": ["90 / Coupe"],
    A3: ["A3 Saloon", "A3 Sportback", "A3 Convertible"],
    A4: ["A4 Avant"],
    A5: ["A5 Sportback"],
    A6: ["A6 Avant"],
    Allroad: ["Allroad II"],
    Q3: ["Q3 Sportback"],
    Q5: ["Q5 III"],
    RS5: ["RS5 Coupé", "RS5 Sportback"],
    TT: ["TT I", "TT Roadster"],
  },
  Bentley: {
    Continental: ["Continental GT", "Continental GTC"],
  },
  Cadillac: {
    ATS: ["ATS-V"],
    XLR: ["XLR-V"],
  },
  Chevrolet: {
    Aveo: ["Aveo II"],
    Camaro: ["Camaro V", "Camaro VI"],
    Malibu: ["Malibu V"],
    P30: ["P30 Van"],
  },
  Dodge: {
    Challenger: ["Challenger Coupe"],
    D100: ["D100 Pickup"],
    D200: ["D200 Pickup"],
    D300: ["D300 Pickup"],
    "Ram 1500": ["Ram 1500 Van"],
    "Ram 2500": ["Ram 2500 Van"],
    "Ram 3500": ["Ram 3500 Van"],
    W100: ["W100 Pickup", "W100 Series"],
    W200: ["W200 Series", "W200 Pickup"],
    W300: ["W300 Pickup", "W300 Series"],
  },
  Ferrari: {
    F12: ["F12 Berlinetta"],
    F8: ["F8 Tributo"],
    SF90: ["SF90 Stradale"],
  },
  Ford: {
    Bronco: ["Bronco Raptor", "Bronco II"],
    Courier: ["Courier II"],
    Custom: ["Custom 500"],
    Escape: ["Escape IV"],
    Falcon: ["Falcon II", "Falcon Fg", "Falcon III", "Falcon V", "Falcon VI"],
    Fiesta: [
      "Fiesta IV",
      "Fiesta IV / Fiesta Mk IV + V",
      "Fiesta VII / Fiesta Mk VIII",
      "Fiesta VI / Fiesta Mk VII",
      "Fiesta V / Fiesta Mk VI",
    ],
    "Fiesta IV": ["Fiesta IV / Fiesta Mk IV + V"],
    Focus: ["Focus I", "Focus Cabriolet", "Focus II"],
    Fusion: ["Fusion / Fusion Plus"],
    Galaxy: ["Galaxy I", "Galaxy III", "Galaxy II"],
    "Grand Tourneo Connect": ["Grand Tourneo Connect III"],
    Kuga: ["Kuga III"],
    Mondeo: ["Mondeo I", "Mondeo III", "Mondeo IV", "Mondeo V"],
    Motorhome: ["Motorhome - Class C"],
    Mustang: [
      "Mustang Coupe",
      "Mustang GT",
      "Mustang Convertible",
      "Mustang I",
      "Mustang V",
      "Mustang III",
    ],
    Probe: ["Probe I"],
    Puma: ["Puma II"],
    "S-Max": ["S-Max II"],
    Taurus: ["Taurus Sho", "Taurus X"],
    Tourneo: [
      "Tourneo Connect III",
      "Tourneo Connect II / Grand Tourneo Connect",
      "Tourneo Custom 2012",
      "Tourneo Connect III / Grand Tourneo Connect",
      "Tourneo Connect",
    ],
    "Tourneo Connect": [
      "Tourneo Connect III",
      "Tourneo Connect II / Grand Tourneo Connect",
      "Tourneo Connect III / Grand Tourneo Connect",
    ],
    "Tourneo Connect III": ["Tourneo Connect III / Grand Tourneo Connect"],
    // Connect, Custom and Courier are separate vans, not Transit generations.
    Transit: ["Transit 2014", "Transit 77", "Transit 92"],
    "Transit / Tourneo Courier": ["Transit / Tourneo Courier II"],
    "Transit Connect": ["Transit Connect II", "Transit Connect III"],
  },
  Honda: {
    Civic: [
      "Civic IX",
      "Civic VII",
      "Civic V",
      "Civic VIII",
      "Civic Type R",
      "Civic VI",
      "Civic X",
      "Civic XI",
    ],
    "HR-V": ["HR-V II", "HR-V III"],
    Integra: ["Integra V"],
    Jazz: ["Jazz II / Fit II", "Jazz III / Fit III", "Jazz IV / Fit IV"],
  },
  Hyundai: {
    Tucson: ["Tucson IV", "Tucson II"],
    Veloster: ["Veloster II"],
    i10: ["i10 II"],
    i20: ["i20 II"],
    i30: ["i30 + i30 Cw", "i30 Fastback"],
  },
  Jeep: {
    Cherokee: ["Cherokee / Liberty", "Cherokee I", "Cherokee V"],
    "Grand Cherokee": ["Grand Cherokee I", "Grand Cherokee II", "Grand Cherokee III"],
  },
  Kia: {
    Optima: ["Optima / Optima III", "Optima IV", "Optima V"],
    Sorento: ["Sorento II", "Sorento IV"],
  },
  Lamborghini: {
    Aventador: ["Aventador Coupe", "Aventador Targa"],
    Gallardo: ["Gallardo Spyder"],
    Urus: ["Urus Performante", "Urus S", "Urus SE"],
  },
  "Land Rover": {
    Defender: ["Defender 90", "Defender 90/110/130", "Defender 110", "Defender 130"],
    "Defender 90": ["Defender 90/110/130"],
    "Range Rover": [
      "Range Rover III",
      "Range Rover I",
      "Range Rover II",
      "Range Rover IV",
      "Range Rover V",
    ],
    "Range Rover Sport": ["Range Rover Sport II", "Range Rover Sport III", "Range Rover Sport I"],
  },
  Lexus: {
    NX: ["NX II"],
  },
  MINI: {
    Cooper: ["Cooper S"],
  },
  Maserati: {
    Levante: ["Levante S"],
  },
  Mazda: {
    "626": ["626 IV", "626 V"],
  },
  McLaren: {
    "570S": ["570S Spider"],
    "600LT": ["600LT Spider"],
    "625C": ["625C Spider"],
    "650S": ["650S Can-Am Spider", "650S Spider"],
    "675LT": ["675LT Spider"],
    "720S": ["720S Spider"],
    "750S": ["750S Spider"],
    "765LT": ["765LT Spider"],
    Artura: ["Artura Spider"],
    "MP4 12C": ["MP4 12C Spider"],
  },
  "Mercedes-Benz": {
    "A-Class": ["A 250", "AMG A 35", "AMG A 45", "AMG A 45 S"],
    "AMG A 45": ["AMG A 45 S"],
    "AMG C 63": ["AMG C 63 S"],
    "AMG E 43": ["AMG E 43 Coupe"],
    "AMG E 53": ["AMG E 53 Coupe"],
    "AMG GLC 63": ["AMG GLC 63 S"],
    "AMG GLE 63": ["AMG GLE 63 S"],
    "AMG GT": ["AMG GT S", "AMG GT Roadster", "AMG GT R"],
    "C-Class": [
      "C-Class Convertible",
      "C-Class T-Model",
      "C-Class Coupe",
      "AMG C 43",
      "AMG C 63",
      "AMG C 63 S",
      "C 200",
      "C 250",
      "C 300",
      "C 400",
      "C 450 AMG",
    ],
    "CLA-Class": ["CLA 250", "AMG CLA 35", "AMG CLA 45"],
    "CLS-Class": ["AMG CLS 53"],
    "E-Class": [
      "AMG E 43",
      "AMG E 43 Coupe",
      "AMG E 53",
      "AMG E 53 Coupe",
      "AMG E 63",
      "E 200",
      "E 400",
    ],
    "G-Class": ["G-Class Convertible", "AMG G 63", "G 500"],
    "GLA-Class": ["AMG GLA 35", "AMG GLA 45"],
    "GLB-Class": ["AMG GLB 35"],
    "GLC-Class": ["AMG GLC 43", "AMG GLC 63", "AMG GLC 63 S"],
    "GLE-Class": ["AMG GLE 53", "AMG GLE 63", "AMG GLE 63 S", "GLE 450"],
    "S-Class": ["AMG S 63"],
    "SL-Class": ["AMG SL 43"],
    Sprinter: ["Sprinter Classic", "Sprinter II", "Sprinter I", "Sprinter III"],
    Vito: ["Vito I", "Vito III"],
  },
  Nissan: {
    Almera: ["Almera II", "Almera Tino", "Almera I"],
    Avenir: ["Avenir/Expert"],
    Bluebird: ["Bluebird Sylphy", "Bluebird/Stanza"],
    Navara: ["Navara II", "Navara NP 300", "Navara/Frontier"],
    Pathfinder: ["Pathfinder III"],
    Pulsar: ["Pulsar III", "Pulsar V", "Pulsar IV"],
    Qashqai: ["Qashqai II"],
    Terrano: ["Terrano I", "Terrano III", "Terrano II"],
    Tiida: ["Tiida III", "Tiida Qida", "Tiida Yida"],
    Wingroad: ["Wingroad / Ad Van"],
    "X-Trail": ["X-Trail III", "X-Trail II"],
  },
  Porsche: {
    "718": ["718 Boxster", "718 Spyder RS", "718 Cayman", "718 Cayman GT4 RS"],
    "718 Cayman": ["718 Cayman GT4 RS"],
    "911": [
      "911 Carrera GTS",
      "911 Carrera",
      "911 Carrera S",
      "911 Convertible",
      "911 GT2 RS",
      "911 GT3",
      "911 GT3 RS",
      "911 GTS",
      "911 Targa",
      "911 Turbo",
      "911 Turbo S",
    ],
    "911 Carrera": ["911 Carrera GTS", "911 Carrera S"],
    "911 GT3": ["911 GT3 RS"],
    "911 Turbo": ["911 Turbo S"],
    Cayenne: [
      "Cayenne GTS",
      "Cayenne I",
      "Cayenne S",
      "Cayenne Turbo",
      "Cayenne II",
      "Cayenne III",
    ],
    Macan: ["Macan I", "Macan GTS", "Macan S", "Macan Turbo"],
    Panamera: ["Panamera GTS", "Panamera II", "Panamera I", "Panamera III", "Panamera Turbo"],
  },
  SEAT: {
    Altea: ["Altea XL", "Altea / Altea XL / Freetrack"],
    Ateca: ["Ateca Cupra"],
    Ibiza: ["Ibiza III", "Ibiza II", "Ibiza IV", "Ibiza V", "Ibiza VI"],
    Leon: ["Leon I", "Leon II", "Leon IV", "Leon III", "Leon SC", "Leon Sportstourer", "Leon ST"],
    Toledo: ["Toledo I", "Toledo II", "Toledo III"],
  },
  Subaru: {
    Impreza: ["Impreza I", "Impreza II", "Impreza III", "Impreza IV", "Impreza Saloon GR"],
    Legacy: ["Legacy I", "Legacy II", "Legacy IV", "Legacy VI", "Legacy VII"],
    Outback: ["Outback I", "Outback II", "Outback VI"],
  },
  Toyota: {
    Alphard: ["Alphard IV", "Alphard I"],
    Avanza: ["Avanza II"],
    Aygo: ["Aygo II", "Aygo X III", "Aygo Van"],
    "C-HR": ["C-HR II"],
    Camry: ["Camry II", "Camry I", "Camry / Vista", "Camry IX", "Camry VI", "Camry VIII"],
    Carina: ["Carina II", "Carina I", "Carina III", "Carina IV"],
    Corolla: [
      "Corolla GR",
      "Corolla Altis",
      "Corolla IX",
      "Corolla V",
      "Corolla VIII",
      "Corolla XI",
      "Corolla VI",
      "Corolla VII",
      "Corolla X",
    ],
    Etios: ["Etios Liva"],
    Fortuner: ["Fortuner I", "Fortuner II"],
    Hilux: ["Hilux Rangga", "Hilux Champ", "Hilux Stout"],
    Innova: ["Innova III"],
    "Land Cruiser": ["Land Cruiser 150", "Land Cruiser 300", "Land Cruiser FJ"],
    "Land Cruiser Prado": ["Land Cruiser Prado 250"],
    Matrix: ["Matrix II"],
    "Premio/Allion": ["Premio/Allion II"],
    Proace: ["Proace II / Proace City"],
    Vans: ["Vans Dyna"],
    Verso: ["Verso-S"],
    Vista: ["Vista / Camry"],
    Vitz: ["Vitz II"],
    Yaris: ["Yaris III", "Yaris I / Yaris Verso", "Yaris II"],
  },
  Volkswagen: {
    Arteon: ["Arteon R", "Arteon Shooting Brake"],
    Beetle: ["Beetle Convertible", "Beetle / Beetle Cabrio"],
    Caddy: ["Caddy IV", "Caddy III", "Caddy I", "Caddy II", "Caddy V"],
    Caravelle: ["Caravelle T4", "Caravelle T5", "Caravelle T6", "Caravelle T7"],
    Crafter: ["Crafter II"],
    Golf: [
      "Golf Cabriolet I",
      "Golf GTI",
      "Golf Estate",
      "Golf I",
      "Golf II",
      "Golf R",
      "Golf III",
      "Golf Plus",
      "Golf IV",
      "Golf Sportsvan",
      "Golf VI",
      "Golf V / Golf Plus",
      "Golf V",
      "Golf VI / Cabrio VI / Golf Plus",
    ],
    "Golf V": ["Golf V / Golf Plus"],
    "Golf VI": ["Golf VI / Cabrio VI / Golf Plus"],
    Jetta: ["Jetta I", "Jetta II", "Jetta III", "Jetta V", "Jetta VI"],
    Passat: [
      "Passat B1",
      "Passat B2",
      "Passat B5",
      "Passat B3 / B4",
      "Passat B3",
      "Passat B6",
      "Passat B7",
      "Passat B8",
      "Passat B9 Variant",
      "Passat B9",
      "Passat Estate 3G5",
    ],
    "Passat B3": ["Passat B3 / B4"],
    "Passat B9": ["Passat B9 Variant"],
    Polo: ["Polo II", "Polo III", "Polo I", "Polo IV", "Polo Saloon", "Polo V Sedan"],
    Rabbit: ["Rabbit I", "Rabbit V"],
    Santana: ["Santana 1"],
    Scirocco: ["Scirocco II"],
    "T-Roc": ["T-Roc / T-Roc Cabrio", "T-Roc R", "T-Roc Cabrio", "T-Roc II"],
    Teramont: ["Teramont Pro", "Teramont X"],
    Tiguan: ["Tiguan R", "Tiguan III", "Tiguan Allspace"],
    Touran: ["Touran I", "Touran II"],
    Transporter: [
      "Transporter Caravelle Bus",
      "Transporter Box",
      "Transporter/Bus T4",
      "Transporter/Bus T5",
      "Transporter/Bus T1",
      "Transporter/Bus T2",
      "Transporter/Bus T3",
      "Transporter/Bus T6",
      "Transporter/Bus T7",
    ],
    Vento: ["Vento India"],
  },
  Škoda: {
    Fabia: ["Fabia I", "Fabia II"],
    Kodiaq: ["Kodiaq II"],
    Octavia: ["Octavia Combi", "Octavia II", "Octavia I", "Octavia vRS"],
    Roomster: ["Roomster Praktik"],
    Superb: ["Superb I", "Superb IV", "Superb II"],
  },
};
