import { NextRequest, NextResponse } from 'next/server';
import { getCurrentShopCustomerSession } from '@/lib/shopCustomerSession';
import { addItemToShopCart, SHOP_CART_COOKIE, serializeResolvedShopCart } from '@/lib/shopCart';
import { getOrCreateShopSettings, getShopSettingsRuntime } from '@/lib/shopAdminSettings';
import { buildShopViewerPricingContext } from '@/lib/shopPricingAudience';
import { prisma } from '@/lib/prisma';

import { importTurn14ItemToDb } from '@/lib/turn14Sync';

const COOKIE_MAX_AGE = 60 * 60 * 24 * 30;

function setCartCookie(response: NextResponse, token: string) {
  response.cookies.set(SHOP_CART_COOKIE, token, {
    path: '/',
    maxAge: COOKIE_MAX_AGE,
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
  });
}

export async function POST(request: NextRequest) {
  let body: { slug?: string; turn14Id?: string; quantity?: number; variantId?: string | null; currency?: string; locale?: string };
  try {
    body = (await request.json()) as any;
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  let finalSlug = String(body.slug ?? '').trim();

  try {
    // === LAZY HYDRATION for Turn14 Live Catalog Items ===
    if (finalSlug.startsWith('turn14-')) {
      const parts = finalSlug.split('-');
      if (parts.length >= 2) {
        // ID is whatever comes after "turn14-" since IDs might be numeric like 12345
        const turn14Id = finalSlug.substring(7); // remove "turn14-"
        
        // 1. Check if we already created it (by looking for existing slug match)
        // Wait, importTurn14ItemToDb builds slugs like `t14-brand-sku`. 
        // We might not know the exact final slug yet without the API attrs.
        // Let's call the API if it's not a known deterministic slug.
        
        // Let's just immediately rely on the Live API! 
        const { fetchTurn14ItemDetail } = require('@/lib/turn14');
        const { importTurn14ItemToDb } = require('@/lib/turn14Sync');
        
        try {
          const liveData = await fetchTurn14ItemDetail(turn14Id);
          if (liveData?.data) {
            const syncRes = await importTurn14ItemToDb(prisma, liveData.data, {
              fetchPricing: true // Real-time secure refresh
            });
            // 2. Overwrite the finalSlug with the REAL deterministic slug generated by importTurn14ItemToDb!
            finalSlug = syncRes.slug;
          } else {
            return NextResponse.json({ error: 'Item not found in Turn14 database' }, { status: 404 });
          }
        } catch (e: any) {
          console.error('[Cart Live Hydration Error]', e);
          return NextResponse.json({ error: 'Turn14 API Proxy Error: ' + e.message }, { status: 502 });
        }
      }
    }

    if (!finalSlug) {
      return NextResponse.json({ error: 'slug or turn14Id is required to add an item to the cart' }, { status: 400 });
    }

    const [session, settingsRecord] = await Promise.all([
      getCurrentShopCustomerSession(),
      getOrCreateShopSettings(prisma),
    ]);
    const settings = getShopSettingsRuntime(settingsRecord);
    const context = buildShopViewerPricingContext(
      settings,
      session?.group ?? null,
      Boolean(session),
      session?.b2bDiscountPercent ?? null
    );
    const { cart, token } = await addItemToShopCart(prisma, {
      cartToken: request.cookies.get(SHOP_CART_COOKIE)?.value,
      customerId: session?.customerId ?? null,
      currency: body.currency ?? settings.defaultCurrency,
      locale: body.locale ?? session?.preferredLocale ?? 'en',
      item: {
        slug: finalSlug,  // Use the newly hydrated or explicit slug
        quantity: Number(body.quantity ?? 1),
        variantId: body.variantId ? String(body.variantId) : null,
      },
    });

    const payload = await serializeResolvedShopCart(cart, context);
    const response = NextResponse.json(payload);
    setCartCookie(response, token);
    return response;
  } catch (error) {
    console.error('Shop cart item add', error);
    return NextResponse.json({ error: 'Failed to add cart item' }, { status: 500 });
  }
}

export const runtime = 'nodejs';
