import "server-only";

import type { OpsDemoData, OpsTask } from "@/components/admin/operations/types";
import { isOpsLocalDemoMode } from "@/app/admin/operations/demoMode";

const now = new Date("2026-07-19T10:35:00+03:00");
const iso = (days: number, hour = 18) => {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

const person = (id: string, name: string) => ({
  id,
  name,
  email: `${id}@onecompany.global`,
});

const tasks: OpsTask[] = [
  {
    id: "demo-task-maxton",
    externalId: "ONE-1042",
    title: "Проверить совместимость Maxton для BMW G20",
    description:
      "Проверить совместимость комплекта Maxton с BMW G20 до рестайлинга и подготовить ответ менеджеру.",
    status: "IN_PROGRESS",
    priority: "HIGH",
    executorType: "HUMAN",
    dueAt: iso(0),
    nextAction: "Сверить артикулы переднего сплиттера с каталогом Maxton",
    definitionOfDone: "Подтверждены подходящие артикулы и добавлен короткий ответ для клиента.",
    version: 3,
    assignee: person("alexey", "Алексей К."),
    createdBy: person("owner", "Алексей К."),
    project: { id: "project-sales", externalId: "PRJ-1003", title: "Текущие продажи" },
    createdAt: iso(0, 10),
    updatedAt: iso(0, 10),
    comments: [],
    events: [
      {
        id: "event-2",
        type: "ATTACHMENT_ADDED",
        createdAt: iso(0, 10),
        actor: person("owner", "Алексей К."),
      },
      {
        id: "event-1",
        type: "CREATED",
        createdAt: iso(0, 10),
        actor: person("owner", "Алексей К."),
      },
    ],
    attachments: [
      {
        id: "task-attachment-1",
        attachment: {
          id: "voice-1",
          fileName: "telegram-voice.ogg",
          mimeType: "audio/ogg",
          sizeBytes: 328_430,
          state: "AVAILABLE",
          createdAt: iso(0, 10),
          transcription:
            "Нужно проверить совместимость комплекта Maxton с BMW G20 до рестайлинга и подготовить ответ менеджеру.",
        },
      },
    ],
    knowledgeLinks: [
      {
        article: {
          id: "article-maxton",
          slug: "maxton-compatibility",
          title: "Maxton: как проверить совместимость",
          category: "prices-and-brands",
          brandKey: "maxton",
          tags: ["brand-guide", "formula-available"],
          status: "PUBLISHED",
          updatedAt: iso(-7),
        },
      },
    ],
    _count: { children: 0, comments: 0, attachments: 1 },
  },
  {
    id: "demo-task-delivery",
    externalId: "ONE-1038",
    title: "Рассчитать доставку в Киев",
    status: "BLOCKED",
    priority: "URGENT",
    dueAt: iso(-3),
    nextAction: null,
    blockerType: "INFORMATION",
    blockerDescription: "Ожидаем габариты упаковки от склада.",
    version: 2,
    assignee: person("mikhail", "Михаил К."),
    project: { id: "project-sales", externalId: "PRJ-1003", title: "Текущие продажи" },
    updatedAt: iso(-2),
  },
  {
    id: "demo-task-akrapovic",
    externalId: "ONE-1039",
    title: "Подготовить предложение по Akrapovič",
    status: "PLANNED",
    priority: "HIGH",
    dueAt: iso(-2),
    nextAction: "Проверить актуальную цену поставщика",
    version: 1,
    assignee: person("daria", "Дарья С."),
    project: { id: "project-sales", externalId: "PRJ-1003", title: "Текущие продажи" },
    updatedAt: iso(-2),
  },
  {
    id: "demo-task-brabus",
    externalId: "ONE-1043",
    title: "Обновить правила цены Brabus",
    status: "IN_PROGRESS",
    priority: "NORMAL",
    dueAt: iso(0),
    nextAction: "Сравнить коэффициенты B2B и B2C",
    version: 4,
    assignee: person("yulia", "Юлия П."),
    project: { id: "project-pricing", externalId: "PRJ-1002", title: "Правила цен" },
    updatedAt: iso(0),
  },
  {
    id: "demo-task-spoiler",
    externalId: "ONE-1044",
    title: "Уточнить наличие спойлера",
    status: "WAITING_EXTERNAL",
    priority: "NORMAL",
    dueAt: iso(0),
    nextAction: null,
    blockerType: "EXTERNAL",
    blockerDescription: "Ждём подтверждение наличия поставщиком.",
    version: 1,
    assignee: person("svetlana", "Светлана В."),
    updatedAt: iso(0),
  },
  {
    id: "demo-task-content",
    externalId: "ONE-1045",
    title: "Согласовать контент для сайта",
    status: "NEEDS_APPROVAL",
    priority: "LOW",
    dueAt: iso(2),
    nextAction: null,
    blockerType: "APPROVAL",
    blockerDescription: "Нужно решение владельца по финальной версии.",
    version: 1,
    assignee: person("ivan", "Иван В."),
    updatedAt: iso(0),
  },
  {
    id: "demo-task-recaro",
    externalId: "ONE-1046",
    title: "Проверить отзывы по Recaro",
    status: "REVIEW",
    priority: "LOW",
    dueAt: iso(3),
    nextAction: "Проверить собранные источники",
    version: 2,
    assignee: person("dmitry", "Дмитрий В."),
    updatedAt: iso(0),
  },
  {
    id: "demo-task-report",
    externalId: "ONE-1047",
    title: "Сформировать вечерний отчёт",
    status: "AGENT_RUNNING",
    priority: "NORMAL",
    dueAt: iso(0, 19),
    nextAction: "Собрать изменения активных задач",
    executorType: "AUTOMATION",
    version: 2,
    assignee: null,
    updatedAt: iso(0),
  },
];

export function getOpsDemoData(): OpsDemoData | null {
  if (!isOpsLocalDemoMode()) {
    return null;
  }

  return {
    tasks,
    projects: [
      {
        id: "project-sales",
        externalId: "PRJ-1003",
        title: "Текущие продажи",
        description: "Операционные задачи по активным запросам и заказам.",
        status: "ACTIVE",
        priority: "HIGH",
        nextAction: "Разобрать задачи на сегодня",
        dueDate: iso(14),
        version: 2,
        owner: person("owner", "Алексей К."),
        updatedAt: iso(0),
        _count: { tasks: 4, knowledgeArticles: 2 },
      },
      {
        id: "project-pricing",
        externalId: "PRJ-1002",
        title: "Правила цен",
        description: "Проверка и актуализация правил для брендов.",
        status: "ACTIVE",
        priority: "NORMAL",
        nextAction: "Опубликовать обновление Brabus",
        version: 3,
        owner: person("yulia", "Юлия П."),
        updatedAt: iso(-1),
        _count: { tasks: 2, knowledgeArticles: 6 },
      },
      {
        id: "project-onboarding",
        externalId: "PRJ-1001",
        title: "Онбординг менеджеров",
        description: "Собрать понятную БАЗУ для новых сотрудников.",
        status: "ACTIVE",
        priority: "NORMAL",
        nextAction: "Дополнить инструкцию по доставке",
        version: 1,
        owner: person("daria", "Дарья С."),
        updatedAt: iso(-2),
        _count: { tasks: 3, knowledgeArticles: 8 },
      },
    ],
    articles: [
      {
        id: "article-maxton",
        slug: "maxton-compatibility",
        title: "Maxton: как проверить совместимость",
        excerpt: "Порядок проверки поколения, кузова и артикула перед расчётом.",
        contentMarkdown:
          "## Перед началом\n\nУточните модель, поколение, год и тип кузова.\n\n## Проверка\n\n1. Найдите артикул в каталоге Maxton.\n2. Сверьте фото штатного бампера.\n3. Зафиксируйте результат в задаче.\n\n> Если есть несколько вариантов, не выбирайте случайно — запросите фото автомобиля.",
        locale: "ru",
        category: "prices-and-brands",
        brandKey: "maxton",
        tags: ["maxton", "совместимость", "бренды"],
        status: "PUBLISHED",
        version: 4,
        publishedRevision: 4,
        updatedAt: iso(-7),
        author: person("owner", "Алексей К."),
        _count: { taskLinks: 3, revisions: 4 },
      },
      {
        id: "article-delivery",
        slug: "delivery-ukraine",
        title: "Как оформить доставку по Украине",
        excerpt: "Чек-лист для Новой почты и крупногабаритных отправлений.",
        contentMarkdown:
          "## Что проверить\n\n- Контакт получателя\n- Габариты и вес\n- Страховую стоимость\n- Тип отделения\n\nПолный адрес не копируйте в комментарии задачи.",
        locale: "ru",
        category: "delivery",
        tags: ["доставка", "новая почта"],
        status: "PUBLISHED",
        version: 3,
        publishedRevision: 3,
        updatedAt: iso(-2),
        author: person("daria", "Дарья С."),
        _count: { taskLinks: 5, revisions: 3 },
      },
      {
        id: "article-pricing",
        slug: "pricing-basics",
        title: "Базовая логика расчёта цены",
        excerpt: "Какие данные нужны перед запуском существующего pricing engine.",
        contentMarkdown:
          "## Важно\n\nРасчёт выполняет только действующий pricing engine. Не считайте итог вручную и не просите AI менять цену.",
        locale: "ru",
        category: "prices-and-brands",
        tags: ["цены", "процесс"],
        status: "DRAFT",
        version: 2,
        updatedAt: iso(0),
        author: person("yulia", "Юлия П."),
        _count: { taskLinks: 0, revisions: 2 },
      },
      {
        id: "article-orders",
        slug: "order-intake",
        title: "Приём нового заказа",
        excerpt: "Какие данные проверить до подтверждения заказа в существующей системе.",
        contentMarkdown:
          "## Чек-лист\n\n1. Проверить товар и совместимость.\n2. Убедиться, что цена рассчитана текущими правилами.\n3. Уточнить безопасный destination reference.",
        locale: "ru",
        category: "order-processing",
        tags: ["заказы", "чек-лист"],
        status: "PUBLISHED",
        version: 1,
        publishedRevision: 1,
        updatedAt: iso(-4),
        author: person("owner", "Алексей К."),
        _count: { taskLinks: 2, revisions: 1 },
      },
    ],
    inbox: [
      {
        id: "inbox-1",
        originalMessage: "Алексей, проверь пожалуйста Maxton на G20 и подготовь ответ сегодня.",
        transcription: null,
        extractionStatus: "SUCCEEDED",
        reviewStatus: "PENDING",
        confidence: 0.91,
        summary: "Проверить совместимость Maxton и подготовить ответ",
        createdAt: iso(0, 11),
        telegramUpdate: {
          telegramUserId: "demo-manager",
          updateType: "MESSAGE",
          isUntrustedForward: false,
          receivedAt: iso(0, 11),
        },
        proposals: [
          {
            id: "proposal-1",
            kind: "TASK",
            confidence: 0.91,
            status: "PENDING",
            payload: {
              title: "Проверить совместимость Maxton для BMW G20",
              priority: "HIGH",
              dueAt: iso(0),
            },
          },
        ],
        attachments: [],
      },
      {
        id: "inbox-2",
        originalMessage: "Голосовое сообщение",
        transcription: "Нужно уточнить, кто завтра сможет оформить отправку Akrapovič в Одессу.",
        extractionStatus: "SUCCEEDED",
        reviewStatus: "PENDING",
        confidence: 0.72,
        summary: "Назначить ответственного за отправку Akrapovič",
        createdAt: iso(0, 9),
        telegramUpdate: {
          telegramUserId: "demo-owner",
          updateType: "VOICE",
          isUntrustedForward: false,
          receivedAt: iso(0, 9),
        },
        proposals: [
          {
            id: "proposal-2",
            kind: "TASK",
            confidence: 0.72,
            status: "PENDING",
            payload: {
              title: "Оформить отправку Akrapovič в Одессу",
              priority: "NORMAL",
            },
          },
        ],
        attachments: [
          {
            id: "voice-inbox",
            fileName: "voice-9.ogg",
            mimeType: "audio/ogg",
            sizeBytes: 214_200,
            state: "AVAILABLE",
            transcription: "Нужно уточнить, кто завтра сможет оформить отправку.",
          },
        ],
      },
    ],
  };
}
