// Generated by scripts/do88/generate-specs.mjs
// Do not edit by hand — run the generator after re-scraping do88.se.
// Last generated: 2026-04-25T19:25:58.081Z

import type { Do88ProductSpec } from '@/lib/do88ProductSpecs';

export const DO88_GENERATED_SPECS: Record<string, Do88ProductSpec> = {
  'A3L60-76': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'A3L60-89': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'A3L76-100': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-100BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Saab 9-5.",
    en: "Big Pack — complete do88 upgrade for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-110-BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Saab 9-3.",
    en: "Big Pack — complete do88 upgrade for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-120-BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Saab 9-3.",
    en: "Big Pack — complete do88 upgrade for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-130SIR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Porsche 911 Turbo (997.2).",
    en: "Big Pack — complete do88 upgrade for Porsche 911 Turbo (997.2).",
  },
  fitment: { ua: "Porsche 911 Turbo (997.2)", en: "Porsche 911 Turbo (997.2)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-140SIR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Porsche 911 Turbo (997.1).",
    en: "Big Pack — complete do88 upgrade for Porsche 911 Turbo (997.1).",
  },
  fitment: { ua: "Porsche 911 Turbo (997.1)", en: "Porsche 911 Turbo (997.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-200SV-GEN1-R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Porsche 911 Turbo (991.1).",
    en: "Big Pack — complete do88 upgrade for Porsche 911 Turbo (991.1).",
  },
  fitment: { ua: "Porsche 911 Turbo (991.1)", en: "Porsche 911 Turbo (991.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-250-R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для BMW F8X (M2/M3/M4).",
    en: "Big Pack — complete do88 upgrade for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-260-D-BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo S60.",
    en: "Big Pack — complete do88 upgrade for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-310-CR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Porsche 911 Carrera (992.1).",
    en: "Big Pack — complete do88 upgrade for Porsche 911 Carrera (992.1).",
  },
  fitment: { ua: "Porsche 911 Carrera (992.1)", en: "Porsche 911 Carrera (992.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Bar & Plate осердя Garrett Motorsport",
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
          "Карбонові повітроводи з prepreg-карбону",
        ],
        en: [
          "Garrett Motorsport Bar & Plate core",
          "CAD-designed cast aluminium tanks for optimised flow",
          "Pre-preg carbon-fibre airflow guides",
        ],
      },
    },
  ],
  replacesOe: ["992145805F","992145928C","992145928B","992145927C","992145927B"],
},
  'BIG-350-S': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Toyota GR Yaris.",
    en: "Big Pack — complete do88 upgrade for Toyota GR Yaris.",
  },
  fitment: { ua: "Toyota GR Yaris", en: "Toyota GR Yaris" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-740-B-63R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo.",
    en: "Big Pack — complete do88 upgrade for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-850-B-63R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo 850.",
    en: "Big Pack — complete do88 upgrade for Volvo 850.",
  },
  fitment: { ua: "Volvo 850", en: "Volvo 850" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-940-B-63R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo.",
    en: "Big Pack — complete do88 upgrade for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-95-B-03R': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Saab 9-5.",
    en: "Big Pack — complete do88 upgrade for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-M3-DCT': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88.",
    en: "Big Pack — complete do88 upgrade.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-M3-MAN': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88.",
    en: "Big Pack — complete do88 upgrade.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-V50-BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo.",
    en: "Big Pack — complete do88 upgrade for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-V70-BR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo S70.",
    en: "Big Pack — complete do88 upgrade for Volvo S70.",
  },
  fitment: { ua: "Volvo S70", en: "Volvo S70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'BIG-X70-B-MGR': {
  headline: {
    ua: "Big Pack — комплектний апгрейд do88 для Volvo S60.",
    en: "Big Pack — complete do88 upgrade for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT101BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-3.",
    en: "do88 silicone hose kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT102-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT102-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT103BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo 740.",
    en: "do88 silicone hose kit for Volvo 740.",
  },
  fitment: { ua: "Volvo 740", en: "Volvo 740" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT11-R': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo 240.",
    en: "do88 silicone hose kit for Volvo 240.",
  },
  fitment: { ua: "Volvo 240", en: "Volvo 240" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT115-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT115-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT115-4S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT116-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo.",
    en: "do88 intercooler kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT116-4S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo.",
    en: "do88 intercooler kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT117-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT117-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT118-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT119-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT119-4S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT130BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT172BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo.",
    en: "do88 silicone hose kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT178S': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT188BR': {
  headline: {
    ua: "Радіатор do88 підвищеної продуктивності.",
    en: "do88 high-performance radiator.",
  },
  sections: [],
  replacesOe: ["5Q0122101DS","5Q0121051E","5Q0121051L","5Q0122051AT","5Q0121101J","5Q0121101P"],
},
  'DO88-KIT189BR': {
  headline: {
    ua: "Радіатор do88 підвищеної продуктивності.",
    en: "do88 high-performance radiator.",
  },
  sections: [],
  replacesOe: ["5Q0122051BC","5Q0121101M","5Q0121101N","5Q0121101H","5Q0121051K","5Q0121051D"],
},
  'DO88-KIT198BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo S60.",
    en: "do88 silicone hose kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT206S': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo 740.",
    en: "do88 silicone hose kit for Volvo 740.",
  },
  fitment: { ua: "Volvo 740", en: "Volvo 740" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT216BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-5.",
    en: "do88 silicone hose kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT217BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-5.",
    en: "do88 silicone hose kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT45-R': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
  replacesOe: ["1K0122101HQ","1K0122101HC","1K0122051FD","1K0122157HH","1K0122073FS","1K0122101HQ","06J121492C","1K0122063J"],
},
  'DO88-KIT46-R': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo.",
    en: "do88 silicone hose kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT49-R': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo V70.",
    en: "do88 silicone hose kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT58BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-5.",
    en: "do88 silicone hose kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT59BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-5.",
    en: "do88 silicone hose kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT64B-R': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Volvo 240.",
    en: "do88 silicone hose kit for Volvo 240.",
  },
  fitment: { ua: "Volvo 240", en: "Volvo 240" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT67S': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
  replacesOe: ["857121101B","857121101C","857121055A","893121109E","857121081C"],
},
  'DO88-KIT68S': {
  headline: {
    ua: "Впускна система do88. Чистіший потік повітря, ізоляція від тепла моторного відсіку.",
    en: "do88 intake system. Cleaner airflow, engine-bay heat isolation.",
  },
  sections: [],
  replacesOe: ["034133357Q","034145742B","034145745A"],
},
  'DO88-KIT71BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT78BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
  replacesOe: ["8N0121051B","8L9121101A","8L9121053A","8L9121073D","8L9121157D","8N0121088","8L9121096C","8L9121086D"],
},
  'DO88-KIT82BR': {
  headline: {
    ua: "Впускна система do88. Чистіший потік повітря, ізоляція від тепла моторного відсіку.",
    en: "do88 intake system. Cleaner airflow, engine-bay heat isolation.",
  },
  sections: [],
  replacesOe: ["06A133354B"],
},
  'DO88-KIT83-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT83-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT83-4S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT83-5S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT84-1S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT84-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT85-1S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT85-2S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT85-3S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT85-4S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'DO88-KIT94BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'DO88-KIT97BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88.",
    en: "do88 silicone hose kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
  replacesOe: ["4A0121101B","4A0121055D","4A0121055C","4A0819371C","4A0819371B","4A0819373C","4A0121082","4A0121081"],
},
  'DO88-KIT98BR': {
  headline: {
    ua: "Силіконовий патрубковий комплект do88 для Saab 9-3.",
    en: "do88 silicone hose kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Армований 4-шаровий силікон, витримує підвищений тиск і температуру",
        ],
        en: [
          "4-ply reinforced silicone, withstands elevated pressure and temperature",
        ],
      },
    },
  ],
},
  'IC-110': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-120': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-130': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-140': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-150': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-160': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-170': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-190': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-200': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-230': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'IC-250': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-100': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 900.",
    en: "do88 intercooler kit for Saab 900.",
  },
  fitment: { ua: "Saab 900", en: "Saab 900" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-110-I4-M-BR': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-110-TTID': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-110-V6': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-3.",
    en: "do88 intercooler kit for Saab 9-3.",
  },
  fitment: { ua: "Saab 9-3", en: "Saab 9-3" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-110-VEI4-BR': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-110-VEV6': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-120': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-130-DO88R': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo 850.",
    en: "do88 intercooler kit for Volvo 850.",
  },
  fitment: { ua: "Volvo 850", en: "Volvo 850" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-140': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo.",
    en: "do88 intercooler kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-150': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo.",
    en: "do88 intercooler kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-160': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo S60.",
    en: "do88 intercooler kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-170': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo. знижує температуру наддуву на 31 °C.",
    en: "do88 intercooler kit for Volvo. drops intake temperature by 31 °C.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Продуктивність", en: "Performance" },
      bullets: {
        ua: [
          "Температура наддуву: 38 °C проти 69 °C OE — на 31 °C нижче",
        ],
        en: [
          "Intake temperature: 38 °C vs 69 °C OE — 31 °C lower",
        ],
      },
    },
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-180': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-190': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo 240.",
    en: "do88 intercooler kit for Volvo 240.",
  },
  fitment: { ua: "Volvo 240", en: "Volvo 240" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-200': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (997.1).",
    en: "do88 intercooler kit for Porsche 911 Turbo (997.1).",
  },
  fitment: { ua: "Porsche 911 Turbo (997.1)", en: "Porsche 911 Turbo (997.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-200-996': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (996).",
    en: "do88 intercooler kit for Porsche 911 Turbo (996).",
  },
  fitment: { ua: "Porsche 911 Turbo (996)", en: "Porsche 911 Turbo (996)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-220-S60': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo S60.",
    en: "do88 intercooler kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-220-V70': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo V70.",
    en: "do88 intercooler kit for Volvo V70.",
  },
  fitment: { ua: "Volvo V70", en: "Volvo V70" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-230-1-DO88R': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (997.1).",
    en: "do88 intercooler kit for Porsche 911 Turbo (997.1).",
  },
  fitment: { ua: "Porsche 911 Turbo (997.1)", en: "Porsche 911 Turbo (997.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-230-DO88R': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (997.2).",
    en: "do88 intercooler kit for Porsche 911 Turbo (997.2).",
  },
  fitment: { ua: "Porsche 911 Turbo (997.2)", en: "Porsche 911 Turbo (997.2)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-250-S-1R': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo.",
    en: "do88 intercooler kit for Volvo.",
  },
  fitment: { ua: "Volvo", en: "Volvo" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-270-DO88R': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (991).",
    en: "do88 intercooler kit for Porsche 911 Turbo (991).",
  },
  fitment: { ua: "Porsche 911 Turbo (991)", en: "Porsche 911 Turbo (991)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-280': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-290': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo S60.",
    en: "do88 intercooler kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-300-BR': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-320': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-330-S-OEMR': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo S60.",
    en: "do88 intercooler kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-350-S': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-360-CR': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Carrera (992.1).",
    en: "do88 intercooler kit for Porsche 911 Carrera (992.1).",
  },
  fitment: { ua: "Porsche 911 Carrera (992.1)", en: "Porsche 911 Carrera (992.1)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Bar & Plate осердя Garrett Motorsport",
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
          "Карбонові повітроводи з prepreg-карбону",
        ],
        en: [
          "Garrett Motorsport Bar & Plate core",
          "CAD-designed cast aluminium tanks for optimised flow",
          "Pre-preg carbon-fibre airflow guides",
        ],
      },
    },
  ],
  replacesOe: ["992145805F","992145928C","992145928B","992145927C","992145927B"],
},
  'ICM-370': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Saab 9-5.",
    en: "do88 intercooler kit for Saab 9-5.",
  },
  fitment: { ua: "Saab 9-5", en: "Saab 9-5" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-370-INSIGNIA': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'ICM-380-S': {
  headline: {
    ua: "Інтеркулерний комплект do88.",
    en: "do88 intercooler kit.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
  replacesOe: ["5Q0145803AE","5Q0145803AB","5Q0145803AC"],
},
  'ICM-390-S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Toyota GR Yaris.",
    en: "do88 intercooler kit for Toyota GR Yaris.",
  },
  fitment: { ua: "Toyota GR Yaris", en: "Toyota GR Yaris" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'LF-120-B-OEMR': {
  headline: {
    ua: "Впускна система do88. Чистіший потік повітря, ізоляція від тепла моторного відсіку.",
    en: "do88 intake system. Cleaner airflow, engine-bay heat isolation.",
  },
  sections: [],
  replacesOe: ["5Q0129607AC","5Q0129620B","5Q0129654P","5Q0129654AE","5Q0129654L","5Q0129635L","5Q0129635P","5Q0129635Q"],
},
  'LF-160-ST-66R': {
  headline: {
    ua: "Впускна система do88 для Porsche 911 Carrera (992). Чистіший потік повітря, ізоляція від тепла моторного відсіку.",
    en: "do88 intake system for Porsche 911 Carrera (992). Cleaner airflow, engine-bay heat isolation.",
  },
  fitment: { ua: "Porsche 911 Carrera (992)", en: "Porsche 911 Carrera (992)" },
  sections: [],
  replacesOe: ["992129620A"],
},
  'OC-120-E46': {
  headline: {
    ua: "Масляний радіатор do88. Збільшена поверхня теплообміну.",
    en: "do88 oil cooler. Increased heat-exchange surface.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Товщина осердя 2 мм",
        ],
        en: [
          "2 mm core thickness",
        ],
      },
    },
  ],
},
  'TR-210-997': {
  headline: {
    ua: "Пленум впуску do88 для Porsche 911 Turbo (997.2). Збільшений обʼєм для рівномірного розподілу повітря.",
    en: "do88 intake plenum for Porsche 911 Turbo (997.2). Increased volume for even air distribution.",
  },
  fitment: { ua: "Porsche 911 Turbo (997.2)", en: "Porsche 911 Turbo (997.2)" },
  sections: [],
  replacesOe: ["9A111003770","9A211003702","9A211013702"],
},
  'TR-240-SS': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'TR-250-S': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'TR-270S': {
  headline: {
    ua: "Алюмінієвий пайп наддуву do88. Заміна пластикового OE-елемента.",
    en: "do88 aluminium charge pipe. Replaces failure-prone plastic OE part.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Порти для методанолового впорскування",
        ],
        en: [
          "Methanol injection ports",
        ],
      },
    },
  ],
},
  'TR-290S': {
  headline: {
    ua: "Алюмінієвий пайп наддуву do88. Заміна пластикового OE-елемента.",
    en: "do88 aluminium charge pipe. Replaces failure-prone plastic OE part.",
  },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Порти для методанолового впорскування",
        ],
        en: [
          "Methanol injection ports",
        ],
      },
    },
  ],
},
  'TR-310-SST-OER': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Porsche 911 Turbo (992).",
    en: "do88 intercooler kit for Porsche 911 Turbo (992).",
  },
  fitment: { ua: "Porsche 911 Turbo (992)", en: "Porsche 911 Turbo (992)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'TR-350-S-DO88': {
  headline: {
    ua: "Алюмінієвий пайп наддуву do88 для Toyota GR Yaris. Заміна пластикового OE-елемента.",
    en: "do88 aluminium charge pipe for Toyota GR Yaris. Replaces failure-prone plastic OE part.",
  },
  fitment: { ua: "Toyota GR Yaris", en: "Toyota GR Yaris" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Порти для методанолового впорскування",
        ],
        en: [
          "Methanol injection ports",
        ],
      },
    },
  ],
},
  'TR-X70R-UD-BR': {
  headline: {
    ua: "Інтеркулерний комплект do88 для Volvo S60.",
    en: "do88 intercooler kit for Volvo S60.",
  },
  fitment: { ua: "Volvo S60", en: "Volvo S60" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'WC-350': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
  'WC-360': {
  headline: {
    ua: "Інтеркулерний комплект do88 для BMW F8X (M2/M3/M4).",
    en: "do88 intercooler kit for BMW F8X (M2/M3/M4).",
  },
  fitment: { ua: "BMW F8X (M2/M3/M4)", en: "BMW F8X (M2/M3/M4)" },
  sections: [
    {
      kicker: { ua: "Конструкція", en: "Construction" },
      bullets: {
        ua: [
          "Литі алюмінієві бачки CAD-розробки для оптимальних потоків",
        ],
        en: [
          "CAD-designed cast aluminium tanks for optimised flow",
        ],
      },
    },
  ],
},
};
