import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { buildBurgerSourceRecordDraft, normalizeBurgerSnapshotProduct, type BurgerSnapshotProduct } from "../src/lib/shopCatalogBurgerNormalization";
import { buildShopCatalogSourceRecordCoverage } from "../src/lib/shopCatalogSourceCoverage";
async function main() { const manifestPath = resolve("public", "catalog-fallback", "manifest.json"), manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { stores?: Record<string, { file?: string; count?: number }> }, descriptor = manifest.stores?.burger;
  if (!descriptor?.file || !descriptor.count) throw new Error("Burger fallback shard is missing"); const raw = await readFile(resolve(dirname(manifestPath), descriptor.file), "utf8"), hash = createHash("sha256").update(raw).digest("hex").slice(0, 12); if (!descriptor.file.includes(`.${hash}.json`)) throw new Error("Burger shard hash mismatch"); const products = JSON.parse(raw) as BurgerSnapshotProduct[]; if (products.length !== descriptor.count) throw new Error("Burger shard count mismatch");
  const normalized = products.map(normalizeBurgerSnapshotProduct), issues = new Map<string, number>(), skuCounts = new Map<string, number>(); let rawLeaves = 0, provenanceEntries = 0, coverageRecords = 0; for (const product of products) { skuCounts.set(product.sku, (skuCounts.get(product.sku) ?? 0) + 1); const draft = buildBurgerSourceRecordDraft({ product, sourceRevision: hash }), coverage = buildShopCatalogSourceRecordCoverage({ recordKey: draft.sourceRecord.recordKey, rawPayload: product, provenance: draft.provenance }); rawLeaves += coverage.leafCount; provenanceEntries += draft.provenance.length; if (coverage.coveragePercent === 100 && coverage.activationReady) coverageRecords += 1; for (const issue of draft.normalization.issues) issues.set(issue, (issues.get(issue) ?? 0) + 1); }
  console.log(JSON.stringify({ version: 1, immutableInput: { manifest: manifestPath, shard: descriptor.file, count: products.length, hash }, duplicateSkuValues: [...skuCounts.values()].filter((count) => count > 1).length, verified: normalized.filter((entry) => entry.verification === "VERIFIED").length, needsReview: normalized.filter((entry) => entry.verification === "NEEDS_REVIEW").length, universal: normalized.filter((entry) => entry.mode === "UNIVERSAL").length, vehicleSpecific: normalized.filter((entry) => entry.mode === "VEHICLE_SPECIFIC").length, applications: normalized.reduce((sum, entry) => sum + entry.applications.length, 0), exactChassisApplications: normalized.reduce((sum, entry) => sum + entry.applications.filter((app) => app.generation).length, 0), exactEngineApplications: normalized.reduce((sum, entry) => sum + entry.applications.filter((app) => app.engineCode).length, 0), losslessCoverage: { records: coverageRecords, rawLeaves, provenanceEntries }, issues: Object.fromEntries([...issues].sort()), fingerprint: createHash("sha256").update(normalized.map((entry) => `${entry.recordKey}:${JSON.stringify(entry.applications)}:${entry.verification}`).sort().join("\n")).digest("hex") }, null, 2)); }
main().catch((error) => { console.error(error); process.exitCode = 1; });
