
import fs from 'fs/promises';
import path from 'path';
import axios from 'axios';
import pLimit from 'p-limit';
import { allAutomotiveBrands, allMotoBrands } from '../src/lib/brands';

const LOGO_DIR = path.join(process.cwd(), 'public', 'logos');
const BRAND_LOGOS_PATH = path.join(process.cwd(), 'src', 'lib', 'brandLogos.ts');
const CONCURRENCY = 20; // Increased concurrency for direct hits

// Slugify function
const slugify = (text: string): string => {
  return text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
};

const downloadFile = async (url: string, filepath: string): Promise<boolean> => {
  try {
    const response = await axios.get(url, {
      responseType: 'arraybuffer',
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      },
      timeout: 3000,
    });
    
    const contentType = response.headers['content-type'];
    // Accept svg or octet-stream (sometimes CDNs send wrong type)
    if (response.status === 200 && response.data.length > 0) {
        await fs.writeFile(filepath, response.data);
        return true;
    }
    return false;
  } catch (error) {
    return false;
  }
};

const searchAndDownloadLogo = async (brandName: string): Promise<string | null> => {
  const slug = slugify(brandName);
  const filename = `${slug}.svg`;
  const filepath = path.join(LOGO_DIR, filename);

  // Check if exists
  try {
    await fs.access(filepath);
    return filename;
  } catch {
    // Continue
  }

  // Direct URL candidates
  const candidates = [
    `https://cdn.worldvectorlogo.com/logos/${slug}.svg`,
    `https://cdn.worldvectorlogo.com/logos/${slug}-1.svg`,
    `https://cdn.worldvectorlogo.com/logos/${slug}-logo.svg`,
    `https://www.vectorlogo.zone/logos/${slug}/${slug}-icon.svg`,
    `https://www.vectorlogo.zone/logos/${slug}/${slug}-ar21.svg`,
    `https://www.vectorlogo.zone/logos/${slug}/${slug}-official.svg`,
    // Try without hyphens for some
    `https://cdn.worldvectorlogo.com/logos/${slug.replace(/-/g, '')}.svg`,
  ];

  for (const url of candidates) {
      if (await downloadFile(url, filepath)) {
          console.log(`  ✅ ${brandName}: Downloaded from ${new URL(url).hostname}`);
          return filename;
      }
  }

  console.log(`  ⚠️ ${brandName}: No SVG found`);
  return null;
};

const main = async () => {
  const allBrands = [...allAutomotiveBrands, ...allMotoBrands];
  const uniqueBrands = Array.from(new Set(allBrands.map(b => b.name))).sort();

  console.log(`🚀 Processing ${uniqueBrands.length} brands with concurrency ${CONCURRENCY}...`);
  
  await fs.mkdir(LOGO_DIR, { recursive: true });

  const limit = pLimit(CONCURRENCY);
  const logoMap: Record<string, string> = {};

  const tasks = uniqueBrands.map(brandName => {
    return limit(async () => {
      const filename = await searchAndDownloadLogo(brandName);
      if (filename) {
        logoMap[brandName] = `/logos/${filename}`;
      }
    });
  });

  await Promise.all(tasks);

  // Generate brandLogos.ts
  console.log('\n📝 Generating brandLogos.ts file...');
  let fileContent = `// This file is auto-generated by scripts/download-logos-google.ts\n\n`;
  fileContent += `export const BRAND_LOGO_MAP: Record<string, string> = {\n`;

  for (const [brandName, logoPath] of Object.entries(logoMap).sort((a, b) => a[0].localeCompare(b[0]))) {
    fileContent += `  '${brandName.replace(/'/g, "\\'")}': '${logoPath}',\n`;
  }

  fileContent += `};\n\n`;
  fileContent += `const NORMALIZED_BRAND_LOGO_MAP: Record<string, string> = Object.fromEntries(\n`;
  fileContent += `  Object.entries(BRAND_LOGO_MAP).map(([key, value]) => [key.toLowerCase(), value])\n`;
  fileContent += `);\n\n`;
  fileContent += `export const getBrandLogo = (brandName: string): string => {\n`;
  fileContent += `  if (!brandName) {\n`;
  fileContent += `    return '/logos/placeholder.svg';\n`;
  fileContent += `  }\n`;
  fileContent += `\n`;
  fileContent += `  const normalizedName = brandName.trim().toLowerCase();\n`;
  fileContent += `  return (\n`;
  fileContent += `    BRAND_LOGO_MAP[brandName] ||\n`;
  fileContent += `    NORMALIZED_BRAND_LOGO_MAP[normalizedName] ||\n`;
  fileContent += `    '/logos/placeholder.svg'\n`;
  fileContent += `  );\n`;
  fileContent += `};\n`;

  await fs.writeFile(BRAND_LOGOS_PATH, fileContent, 'utf-8');
  console.log('Done!');
};

main();
