import fs from 'fs/promises';
import path from 'path';
import axios from 'axios';

const LOGO_DIR = path.join(process.cwd(), 'public', 'logos');
const BRAND_LOGOS_PATH = path.join(process.cwd(), 'src', 'lib', 'brandLogos.ts');

const FIXES = [
  { name: 'GBracing', domain: 'gbracing.eu' },
  { name: 'Ilmberger Carbon', domain: 'ilmberger-carbon.com' },
  { name: 'Brembo', domain: 'brembo.com' },
  { name: 'Rotobox', domain: 'rotobox-wheels.com' }, 
  { name: 'DB-Race', domain: 'db-race.com' }, 
  { name: 'Melotti Racing', domain: 'melottiracing.com' }, 
  { name: 'Gilles Tooling', domain: 'gillestooling.com' },
  { name: 'X-GRIP', domain: 'x-grip.at' },
  { name: 'Samco Sport', domain: 'samcosport.com' },
];

// Headers to mimic a real browser
const HEADERS = {
  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
};

const slugify = (text: string): string => {
  return text
    .toString()
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^\w\-]+/g, '')
    .replace(/\-\-+/g, '-')
    .replace(/^-+/, '')
    .replace(/-+$/, '');
};

const downloadFile = async (url: string, filepath: string): Promise<boolean> => {
  try {
    const response = await axios.get(url, {
      responseType: 'arraybuffer',
      headers: HEADERS,
      timeout: 15000,
    });
    await fs.writeFile(filepath, response.data);
    return true;
  } catch (error) {
    console.log(`Failed to download ${url}: ${(error as Error).message}`);
    return false;
  }
};

const main = async () => {
  console.log('🔧 Fixing specific bad logos (Round 4 - Google High Res)...');
  
  for (const fix of FIXES) {
    const slug = slugify(fix.name);
    // Google High Res Favicon API
    const url = `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://${fix.domain}&size=256`;
    const filepath = path.join(LOGO_DIR, `${slug}.png`);
    
    console.log(`  Fixing ${fix.name}...`);
    if (await downloadFile(url, filepath)) {
      console.log(`  ✅ Fixed ${fix.name}`);
    } else {
      console.log(`  ❌ Failed to fix ${fix.name}`);
    }
  }
  
  console.log('\n📝 Updating brandLogos.ts...');
  
  const files = await fs.readdir(LOGO_DIR);
  let fileContent = `// This file is auto-generated by scripts/download-moto-logos.ts (and fixes)\n\n`;
  fileContent += `export const BRAND_LOGO_MAP: Record<string, string> = {\n`;
  
  const brandsData = await fs.readFile(path.join(process.cwd(), 'scripts', 'moto-brands.json'), 'utf-8');
  const brands = JSON.parse(brandsData);
  
  let allBrands: {name: string}[] = [...brands];
  try {
      const bigListPath = path.join(process.cwd(), 'scripts', 'brands-list.json');
      const bigListRaw = await fs.readFile(bigListPath, 'utf-8');
      const bigListJson = JSON.parse(bigListRaw);
      Object.values(bigListJson.categories).forEach((arr: any) => {
          arr.forEach((b: string) => allBrands.push({name: b}));
      });
  } catch (e) {}

  const sortedFiles = files.filter(f => ['.svg', '.png', '.webp', '.jpg', '.jpeg'].includes(path.extname(f))).sort();

  for (const file of sortedFiles) {
      const slug = path.basename(file, path.extname(file));
      const match = allBrands.find(b => slugify(b.name) === slug);
      const displayName = match ? match.name : slug;
      fileContent += `  '${displayName.replace(/'/g, "\\'")}': '/logos/${file}',\n`;
  }

  fileContent += `};\n\n`;
  fileContent += `const NORMALIZED_BRAND_LOGO_MAP: Record<string, string> = Object.fromEntries(\n`;
  fileContent += `  Object.entries(BRAND_LOGO_MAP).map(([key, value]) => [key.toLowerCase(), value])\n`;
  fileContent += `);\n\n`;
  fileContent += `export const getBrandLogo = (brandName: string): string => {\n`;
  fileContent += `  if (!brandName) {\n`;
  fileContent += `    return '/logos/placeholder.svg';\n`;
  fileContent += `  }\n`;
  fileContent += `\n`;
  fileContent += `  const normalizedName = brandName.trim().toLowerCase();\n`;
  fileContent += `  return (\n`;
  fileContent += `    BRAND_LOGO_MAP[brandName] ||\n`;
  fileContent += `    NORMALIZED_BRAND_LOGO_MAP[normalizedName] ||\n`;
  fileContent += `    '/logos/placeholder.svg'\n`;
  fileContent += `  );\n`;
  fileContent += `};\n`;

  await fs.writeFile(BRAND_LOGOS_PATH, fileContent, 'utf-8');
  console.log('✨ Map updated.');
};

main();
