// scripts/generate-brand-logo-map.ts
// Script to generate BRAND_LOGO_MAP from existing logo files

import * as fs from 'fs';
import * as path from 'path';

const LOGOS_DIR = path.join(__dirname, '..', 'public', 'logos');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'lib', 'brandLogos.ts');

// Priority: SVG > PNG > WEBP > JPG
const EXTENSION_PRIORITY = ['.svg', '.png', '.webp', '.jpg', '.jpeg'];

function slugToBrandName(slug: string): string {
  // Remove extension
  const name = slug.replace(/\.(svg|png|webp|jpg|jpeg)$/i, '');
  
  // Convert slug to brand name
  // E.g., "ac-schnitzer" -> "AC Schnitzer"
  return name
    .split('-')
    .map(word => {
      // Special cases for all-caps abbreviations
      const upperCaseWords = ['abt', 'bmw', 'amc', 'vw', 'hks', 'apr', 'jdm', 'bbs', 'mst', 'kw', 'gtr', 'ecu', 'bc', 'ams', 'adv', 'csf', 'rkp', 'evr', 'ess', 'bmc', 'dmc', 'vf', 'ac', 'ae', 'ai', 'al', 'ap', 'ct', 'do', 'fi', 'mv', 'rk', 'sc', 'vr', 'xhp'];
      if (upperCaseWords.includes(word.toLowerCase())) {
        return word.toUpperCase();
      }
      // Capitalize first letter
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

function generateBrandLogoMap(): void {
  // Get all files in logos directory
  const files = fs.readdirSync(LOGOS_DIR);
  
  // Group files by base name (without extension)
  const filesByBase: Record<string, string[]> = {};
  
  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    if (!EXTENSION_PRIORITY.includes(ext)) continue;
    
    const baseName = file.replace(/\.(svg|png|webp|jpg|jpeg)$/i, '').toLowerCase();
    if (!filesByBase[baseName]) {
      filesByBase[baseName] = [];
    }
    filesByBase[baseName].push(file);
  }
  
  // Build the map, selecting best file for each brand
  const brandLogoMap: Record<string, string> = {};
  
  for (const [baseName, fileList] of Object.entries(filesByBase)) {
    // Sort by extension priority
    fileList.sort((a, b) => {
      const extA = path.extname(a).toLowerCase();
      const extB = path.extname(b).toLowerCase();
      return EXTENSION_PRIORITY.indexOf(extA) - EXTENSION_PRIORITY.indexOf(extB);
    });
    
    // Use the best file (first after sorting)
    const bestFile = fileList[0];
    const brandName = slugToBrandName(baseName);
    
    brandLogoMap[brandName] = `/logos/${bestFile}`;
  }
  
  // Generate TypeScript file content
  const entries = Object.entries(brandLogoMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([brand, path]) => `  "${brand}": "${path}"`)
    .join(',\n');
  
  const content = `// Auto-generated by scripts/generate-brand-logo-map.ts
// Run: npx ts-node --project tsconfig.script.json scripts/generate-brand-logo-map.ts

export const BRAND_LOGO_MAP: Record<string, string> = {
${entries}
};

const NORMALIZED_BRAND_LOGO_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(BRAND_LOGO_MAP).map(([key, value]) => [key.toLowerCase(), value])
);

// Normalized slug map for URL-friendly lookups
const SLUG_TO_LOGO_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(BRAND_LOGO_MAP).map(([key, value]) => [
    key.toLowerCase().replace(/\\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
    value
  ])
);

export const getBrandLogo = (brandName: string): string => {
  if (!brandName) return '/logos/placeholder.svg';
  
  const normalizedName = brandName.trim().toLowerCase();
  const slugName = normalizedName.replace(/\\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  
  // Try exact match first
  if (BRAND_LOGO_MAP[brandName]) {
    return BRAND_LOGO_MAP[brandName];
  }
  
  // Try normalized (lowercase) match
  if (NORMALIZED_BRAND_LOGO_MAP[normalizedName]) {
    return NORMALIZED_BRAND_LOGO_MAP[normalizedName];
  }
  
  // Try slug match
  if (SLUG_TO_LOGO_MAP[slugName]) {
    return SLUG_TO_LOGO_MAP[slugName];
  }
  
  // Try partial match (for brands with extra words)
  for (const [key, value] of Object.entries(NORMALIZED_BRAND_LOGO_MAP)) {
    if (key.includes(normalizedName) || normalizedName.includes(key)) {
      return value;
    }
  }
  
  return '/logos/placeholder.svg';
};
`;

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(brandLogoMap).length} brand logos`);
  
  // Log some examples
  console.log('\nExample mappings:');
  const examples = Object.entries(brandLogoMap).slice(0, 10);
  for (const [brand, logoPath] of examples) {
    console.log(`  "${brand}" -> "${logoPath}"`);
  }
}

generateBrandLogoMap();
