import 'dotenv/config';
import fs from 'fs';
import { PrismaClient } from '../node_modules/.prisma/client/index.js';

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: "postgres://bf7d0275e2bb3ccb33f5725fe2b25fea7069faebb9e79230445f5853b74ecaae:sk_wleM8vpJZfUAYDaJbCknI@db.prisma.io:5432/postgres?sslmode=require&pgbouncer=true"
    }
  }
});
const JSON_PATH = 'd:/OneCompany/do88-products-v4.json';

// Better dictionary that translates individual fragments reliably
const DICT = {
  'Kolfiberkåpa': { en: 'Carbon Fiber Cover', ua: 'Карбонова кришка' },
  'insugskåpa': { en: 'Intake Cover', ua: 'Впускна кришка' },
  'Insugskåpa': { en: 'Intake Cover', ua: 'Впускна кришка' },
  'Insugssystem': { en: 'Intake System', ua: 'Впускна система' },
  'kolfiber': { en: 'Carbon Fiber', ua: 'Карбон' },
  'Kolfiber': { en: 'Carbon Fiber', ua: 'Карбоновий' },
  'Modellanpassat': { en: 'Vehicle Specific', ua: 'Оригінальний' },
  'Для авто ': { ua: '' }, // remove the bad placement generated by scrape-do88-v4
  'För': { en: 'For', ua: 'Для' },
  'för': { en: 'for', ua: 'для' },
  'Med': { en: 'With', ua: 'З' },
  'med': { en: 'with', ua: 'з' },
  'Och': { en: 'And', ua: 'Та' },
  'och': { en: 'and', ua: 'та' },
  'Tryckrör': { en: 'Charge Pipe', ua: 'Нагнітальна труба' },
  'tryckrör': { en: 'charge pipe', ua: 'нагнітальна труба' },
  'Tryckslang': { en: 'Boost Hose', ua: 'Патрубок наддуву' },
  'tryckslang': { en: 'boost hose', ua: 'патрубок наддуву' },
  'Kåpa': { en: 'Cover', ua: 'Кришка' },
  'kåpa': { en: 'cover', ua: 'кришка' },
  'Pysventil': { en: 'Bleed Valve', ua: 'Кран' },
};

function fixTitle(text, lang) {
  if (!text) return '';
  let result = text;
  Object.keys(DICT).forEach(sv => {
    const replacement = DICT[sv]?.[lang];
    if (replacement !== undefined) {
      if (sv === 'Для авто ') {
        result = result.replace(sv, replacement);
      } else {
         const regex = new RegExp(`\\b${sv}\\b`, 'g');
         result = result.replace(regex, replacement);
      }
    }
  });
  return result.replace(/\s+/g, ' ').trim();
}

async function restore() {
  console.log('🩹 Restoring and Fixing DO88 Titles...');
  const data = JSON.parse(fs.readFileSync(JSON_PATH, 'utf-8'));
  
  let updated = 0;
  for (const p of data) {
    const fixedEn = fixTitle(p.titleEn, 'en');
    const fixedUa = fixTitle(p.titleUa, 'ua');
    
    // Check if it's different from the JSON, or if we need to restore it because Gemma broke it
    // Wait, let's just forcefully overwrite ALL DO88 titles with fixed ones from JSON to ensure 100% cleanliness
    
    await prisma.shopProduct.updateMany({
      where: { sku: p.sku, vendor: 'DO88' },
      data: {
        titleEn: fixedEn,
        titleUa: fixedUa,
      }
    });
    
    updated++;
    if (updated % 100 === 0) {
      console.log(`  ...restored ${updated}/${data.length}`);
    }
  }
  
  console.log(`✅ Fixed ${updated} DO88 products successfully!`);
  await prisma.$disconnect();
}

restore().catch(console.error);
