import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { PrismaClient } from "@prisma/client";
import { buildAdroSourceRecordDraft } from "../src/lib/shopCatalogAdroNormalization";
import { persistAdroSourceRecordPageWithClient } from "../src/lib/shopCatalogAdroBackfill.server";
import { buildAkrapovicSourceRecordDraft } from "../src/lib/shopCatalogAkrapovicNormalization";
import { persistAkrapovicSourceRecordPageWithClient } from "../src/lib/shopCatalogAkrapovicBackfill.server";
import { buildBrabusSourceRecordDraft } from "../src/lib/shopCatalogBrabusNormalization";
import { persistBrabusSourceRecordPageWithClient } from "../src/lib/shopCatalogBrabusBackfill.server";
import { buildBurgerSourceRecordDraft } from "../src/lib/shopCatalogBurgerNormalization";
import { persistBurgerSourceRecordPageWithClient } from "../src/lib/shopCatalogBurgerBackfill.server";
import { buildCsfSourceRecordDraft } from "../src/lib/shopCatalogCsfNormalization";
import { persistCsfSourceRecordPageWithClient } from "../src/lib/shopCatalogCsfBackfill.server";
import { buildDo88SourceRecordDraft } from "../src/lib/shopCatalogDo88Normalization";
import { persistDo88SourceRecordPageWithClient } from "../src/lib/shopCatalogDo88Backfill.server";
import { buildEventuriSourceRecordDraft } from "../src/lib/shopCatalogEventuriNormalization";
import { persistEventuriSourceRecordPageWithClient } from "../src/lib/shopCatalogEventuriBackfill.server";
import { buildGirodiscSourceRecordDraft } from "../src/lib/shopCatalogGirodiscNormalization";
import { persistGirodiscSourceRecordPageWithClient } from "../src/lib/shopCatalogGirodiscBackfill.server";
import { buildIlmbergerSourceRecordDraft } from "../src/lib/shopCatalogIlmbergerNormalization";
import { persistIlmbergerSourceRecordPageWithClient } from "../src/lib/shopCatalogIlmbergerBackfill.server";
import { buildIpeSourceRecordDraft } from "../src/lib/shopCatalogIpeNormalization";
import { persistIpeSourceRecordPageWithClient } from "../src/lib/shopCatalogIpeBackfill.server";
import { buildOhlinsSourceRecordDraft } from "../src/lib/shopCatalogOhlinsNormalization";
import { persistOhlinsSourceRecordPageWithClient } from "../src/lib/shopCatalogOhlinsBackfill.server";
import { buildRaceChipSourceRecordDraft } from "../src/lib/shopCatalogRaceChipNormalization";
import { persistRaceChipSourceRecordPageWithClient } from "../src/lib/shopCatalogRaceChipBackfill.server";
import { buildRemusSourceRecordDraft } from "../src/lib/shopCatalogRemusNormalization";
import { persistRemusSourceRecordPageWithClient } from "../src/lib/shopCatalogRemusBackfill.server";
import { buildUrbanSourceRecordDraft } from "../src/lib/shopCatalogUrbanNormalization";
import { persistUrbanSourceRecordPageWithClient } from "../src/lib/shopCatalogUrbanBackfill.server";

type Snapshot = { id: string; slug: string; sku?: string | null; title?: { ua?: string; en?: string }; variants?: Array<{ id: string; sku?: string | null; title?: string; isDefault?: boolean }>; brand?: string; [key: string]: unknown };
type Draft = { provenance: unknown[]; issues: unknown[]; normalization: { productId: string; variantId: string | null; verification: string }; sourceRecord: { recordKey: string } };
type Persist = (client: PrismaClient, input: { drafts: readonly never[]; sourceKey?: string; sourceDisplayName?: string }) => Promise<{ inserted: number; idempotent: number; provenanceInserted: number; issuesInserted: number }>;
const builders = { adro: buildAdroSourceRecordDraft, akrapovic: buildAkrapovicSourceRecordDraft, brabus: buildBrabusSourceRecordDraft, burger: buildBurgerSourceRecordDraft, csf: buildCsfSourceRecordDraft, do88: buildDo88SourceRecordDraft, eventuri: buildEventuriSourceRecordDraft, girodisc: buildGirodiscSourceRecordDraft, ilmberger: buildIlmbergerSourceRecordDraft, ipe: buildIpeSourceRecordDraft, ohlins: buildOhlinsSourceRecordDraft, racechip: buildRaceChipSourceRecordDraft, remus: buildRemusSourceRecordDraft, urban: buildUrbanSourceRecordDraft } as const;
const persisters = { adro: persistAdroSourceRecordPageWithClient, akrapovic: persistAkrapovicSourceRecordPageWithClient, brabus: persistBrabusSourceRecordPageWithClient, burger: persistBurgerSourceRecordPageWithClient, csf: persistCsfSourceRecordPageWithClient, do88: persistDo88SourceRecordPageWithClient, eventuri: persistEventuriSourceRecordPageWithClient, girodisc: persistGirodiscSourceRecordPageWithClient, ilmberger: persistIlmbergerSourceRecordPageWithClient, ipe: persistIpeSourceRecordPageWithClient, ohlins: persistOhlinsSourceRecordPageWithClient, racechip: persistRaceChipSourceRecordPageWithClient, remus: persistRemusSourceRecordPageWithClient, urban: persistUrbanSourceRecordPageWithClient } as unknown as Record<string, Persist>;
function assertDatabaseUrl() { const value = process.env.CATALOG_ALL_SOURCE_GATE_DATABASE_URL?.trim(); if (!value) throw new Error("CATALOG_ALL_SOURCE_GATE_DATABASE_URL is required"); const url = new URL(value); if (!new Set(["localhost", "127.0.0.1", "::1"]).has(url.hostname) || url.searchParams.get("application_name") !== "catalog-all-source-gate") throw new Error("All-source gate requires a localhost disposable database with application_name=catalog-all-source-gate"); return value; }
function pages<T>(values: T[], size: number) { const output: T[][] = []; for (let index = 0; index < values.length; index += size) output.push(values.slice(index, index + size)); return output; }
async function load() { const manifestPath = resolve("public", "catalog-fallback", "manifest.json"), manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { stores: Record<string, { file: string; count: number }> }, sources: Array<{ name: keyof typeof builders; products: Snapshot[]; revision: string }> = [];
  for (const [name, descriptor] of Object.entries(manifest.stores)) { const raw = await readFile(resolve(dirname(manifestPath), descriptor.file), "utf8"), revision = createHash("sha256").update(raw).digest("hex").slice(0, 12), products = JSON.parse(raw) as Snapshot[]; if (products.length !== descriptor.count || !descriptor.file.includes(`.${revision}.json`)) throw new Error(`${name} immutable shard mismatch`); if (name === "generic") { const eventuri = products.filter((product) => product.brand?.toLowerCase() === "eventuri"), remus = products.filter((product) => product.brand?.toLowerCase() === "remus"); if (eventuri.length + remus.length !== products.length) throw new Error("Generic partition is incomplete"); sources.push({ name: "eventuri", products: eventuri, revision }, { name: "remus", products: remus, revision }); } else sources.push({ name: name as keyof typeof builders, products, revision }); }
  return sources.sort((left, right) => left.name.localeCompare(right.name)); }
async function main() { const startedAt = Date.now(), client = new PrismaClient({ datasources: { db: { url: assertDatabaseUrl() } } }), sources = await load(), products = sources.flatMap((source) => source.products), draftsBySource = new Map<string, Draft[]>();
  try { for (const page of pages(products, 500)) await client.shopProduct.createMany({ data: page.map((product) => ({ id: product.id, slug: product.slug, titleUa: product.title?.ua || product.slug, titleEn: product.title?.en || product.slug, brand: product.brand ?? null })), skipDuplicates: true }); const variants = products.flatMap((product) => (product.variants ?? []).map((variant) => ({ id: variant.id, productId: product.id, title: variant.title || "Default", sku: variant.sku ?? null, isDefault: Boolean(variant.isDefault) }))); for (const page of pages(variants, 500)) await client.shopProductVariant.createMany({ data: page, skipDuplicates: true });
    for (const source of sources) { const builder = builders[source.name] as unknown as (input: { product: Snapshot; sourceRevision: string }) => Draft, drafts = source.products.map((product) => builder({ product, sourceRevision: source.revision })).sort((left, right) => left.sourceRecord.recordKey.localeCompare(right.sourceRecord.recordKey)); draftsBySource.set(source.name, drafts); let completed = 0; for (const page of pages(drafts, 50)) { await persisters[source.name]!(client, { drafts: page as never[], sourceKey: `gate-${source.name}`, sourceDisplayName: `Gate ${source.name}` }); completed += page.length; if (completed % 500 === 0 || completed === drafts.length) process.stdout.write(`[all-source-gate] ${source.name} ${completed}/${drafts.length}\n`); } }
    const expectedRecords = [...draftsBySource.values()].reduce((sum, drafts) => sum + drafts.length, 0), expectedProvenance = [...draftsBySource.values()].flat().reduce((sum, draft) => sum + draft.provenance.length, 0), expectedIssues = [...draftsBySource.values()].flat().reduce((sum, draft) => sum + draft.issues.length, 0), expectedReview = [...draftsBySource.values()].flat().filter((draft) => draft.normalization.verification === "NEEDS_REVIEW").length;
    const counts = { sources: await client.shopCatalogSource.count({ where: { key: { startsWith: "gate-" } } }), records: await client.shopCatalogSourceRecord.count(), provenance: await client.shopCatalogFieldProvenance.count(), issues: await client.shopCatalogNormalizationIssue.count(), activePolicies: await client.shopCatalogCompatibilityPolicy.count({ where: { isActive: true } }), reviewPolicies: await client.shopCatalogCompatibilityPolicy.count({ where: { isActive: true, mode: "NEEDS_REVIEW" } }) };
    if (counts.sources !== sources.length || counts.records !== expectedRecords || counts.provenance !== expectedProvenance || counts.issues !== expectedIssues || counts.activePolicies !== expectedRecords || counts.reviewPolicies !== expectedReview) throw new Error(`All-source persistence parity failed: ${JSON.stringify({ counts, expectedRecords, expectedProvenance, expectedIssues, expectedReview })}`);
    let replayed = 0; for (const source of sources) for (const page of pages(draftsBySource.get(source.name)!, 50)) { const result = await persisters[source.name]!(client, { drafts: page as never[], sourceKey: `gate-${source.name}`, sourceDisplayName: `Gate ${source.name}` }); if (result.inserted !== 0 || result.idempotent !== page.length || result.provenanceInserted !== 0 || result.issuesInserted !== 0) throw new Error(`${source.name} replay was not idempotent`); replayed += page.length; }
    const report = { version: 1, sources: sources.length, records: expectedRecords, variants: variants.length, provenance: expectedProvenance, issues: expectedIssues, reviewPolicies: expectedReview, activePolicies: counts.activePolicies, replayed, elapsedMs: Date.now() - startedAt, fingerprint: createHash("sha256").update([...draftsBySource.entries()].flatMap(([source, drafts]) => drafts.map((draft) => `${source}:${draft.sourceRecord.recordKey}`)).sort().join("\n")).digest("hex") }; process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
  } finally { await client.$disconnect(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
