// Source-checked billet accessories, caps, service tools, and lifting adapters; local draft only.
const rows = {
  'bms-performance-s58-bmw-m-engine-cap-cover-set': {
    titleUa: 'BMS Billet Cap Cover Set для BMW S58 / S68 — 3 деталі', titleEn: 'BMS Billet Cap Cover Set for BMW S58 / S68 — 3 Pieces',
    shortUa: 'Три anodized billet cover накладаються на OEM oil, coolant і heat-exchanger caps; колір або raw finish.', shortEn: 'Three anodized billet covers fit OEM oil, coolant, and heat-exchanger caps; choose color or raw finish.',
    benefitUa: 'Комплект BMS змінює вигляд моторного відсіку BMW S58/S68, зберігаючи штатні кришки та їхню функцію. CNC billet-алюмінієві накладки встановлюються поверх OEM деталей і додають анодований або custom-paint фініш.', benefitEn: 'The BMS set updates the S58/S68 engine bay while retaining the factory caps and their function. CNC billet-aluminum covers fit over OEM parts and add an anodized or custom-paint finish.',
    detailsUa: 'У наборі три cover: oil filler cap, coolant reservoir cap та heat-exchanger cap cover. Оберіть Blue Anodized, Red Anodized або RAW для власного фарбування. Очищення спиртом і комплектна 3M automotive tape потрібні для монтажу; це накладки, не три нові герметичні кришки.', detailsEn: 'The set contains three covers: oil-filler cap, coolant-reservoir cap, and heat-exchanger cap cover. Choose Blue Anodized, Red Anodized, or RAW for custom paint. Clean with alcohol and apply the included 3M automotive tape; these are covers, not three replacement sealing caps.',
    fitUa: 'BMW S58 G87 M2, G80 M3, G82/G83 M4, F97/F98 X3M/X4M та перелічені S68 G70/G90/G05/G06/G07/G09 моделі. Звірте форму штатних кришок перед монтажем.', fitEn: 'For listed BMW S58 G87 M2, G80 M3, G82/G83 M4, F97/F98 X3M/X4M, and S68 G70/G90/G05/G06/G07/G09 applications. Match factory cap shapes before installation.'
  },
  'vw-audi-tow-hook-camera-mount-for-gopro-cameras': {
    titleUa: 'VW / Audi Tow-Hook Camera Mount для GoPro — вибір різьби', titleEn: 'VW / Audi Tow-Hook Camera Mount for GoPro — Select Thread',
    shortUa: 'CNC billet-алюмінієве кріплення GoPro у tow-hook точку; оберіть Type 1 E або Type 2 VW thread.', shortEn: 'CNC billet GoPro mount uses the tow-hook point; select Type 1 E or Type 2 VW thread.',
    benefitUa: 'Кріплення встановлює GoPro у передню або задню tow-hook точку й утримує камеру на авто без suction cup чи клейкої стрічки. Суцільний CNC billet корпус розрахований на стабільну зйомку та не потребує свердління бампера.', benefitEn: 'The mount secures a GoPro in the front or rear tow-hook point without a suction cup or adhesive tape. Its solid CNC billet body supports stable filming without drilling the bumper.',
    detailsUa: 'Оберіть різьбу Type 1 (E) або Type 2 (VW); назви типу у джерелі суперечливо описують бренди, тому звірте фактичну tow-hook thread авто перед замовленням. Стійка завдовжки 3″; виміряйте зазор від бампера до різьби. Камера й GoPro accessories не входять.', detailsEn: 'Choose Type 1 (E) or Type 2 (VW). The supplier text inconsistently describes brand applications, so verify the vehicle tow-hook thread before ordering. The post is 3 inches long; measure bumper-to-thread clearance. Camera and GoPro accessories are not included.',
    fitUa: 'Для автомобіля VW/Audi з відповідною tow-hook різьбою й достатнім 3″ кліренсом. Підбір лише за маркою недостатній — звірте тип різьби.', fitEn: 'For VW/Audi vehicles with the matching tow-hook thread and 3-inch clearance. Make alone is insufficient; confirm thread type.'
  },
  'bms-billet-aluminum-windshield-washer-fluid-reservoir-cap-for-e-chassis-bmw': {
    titleUa: 'BMS Billet Washer Reservoir Cap для BMW E81/E82/E87/E88/E9x/X1 E84', titleEn: 'BMS Billet Washer Reservoir Cap for BMW E81/E82/E87/E88/E9x/X1 E84',
    shortUa: 'Однокомпонентна алюмінієва заміна пластикової кришки бачка омивача; оберіть Red, Blue або Silver.', shortEn: 'One-piece aluminum replacement for the plastic washer cap; choose Red, Blue, or Silver.',
    benefitUa: 'CNC billet washer cap замінює крихку пластикову заводську кришку бачка склоомивача. Анодований алюміній призначений для довговічного використання та оновлює вигляд підкапотного простору.', benefitEn: 'The CNC billet washer cap replaces the brittle plastic factory cap on the windshield-washer reservoir. Anodized aluminum is designed for durable service and refreshes the engine-bay appearance.',
    detailsUa: 'Це повна заміна кришки, не декоративна накладка. Оберіть Anodized Red, Blue або Silver; монтаж — зняти стару та встановити нову без спеціального інструмента.', detailsEn: 'This is a replacement cap, not a decorative overlay. Choose Anodized Red, Blue, or Silver; installation removes the old cap and fits the new one without special tools.',
    fitUa: 'BMW 1 Series E81/E82/E87/E88 2005–2013, 3 Series E90/E91/E92/E93 2005–2013 та X1 E84 2010–2015 за переліком Burger. Звірте бачок і горловину.', fitEn: 'For Burger-listed 2005–2013 BMW 1 Series E81/E82/E87/E88, 2005–2013 3 Series E90/E91/E92/E93, and 2010–2015 X1 E84. Verify reservoir and filler neck.'
  },
  'bms-billet-coolant-expansion-tank-radiator-cap-for-vw-golf-mk7-audi-s3-8v-8y': {
    titleUa: 'BMS Billet Coolant Reservoir Cap для VW / Audi / SEAT / Škoda', titleEn: 'BMS Billet Coolant Reservoir Cap for VW / Audi / SEAT / Škoda',
    shortUa: 'Металева кришка бачка охолодження замінює OEM plastic; перенесіть factory pressure-release valve.', shortEn: 'Metal expansion-tank cap replaces OEM plastic; transfer the factory pressure-release valve.',
    benefitUa: 'BMS billet coolant cap замінює пластикову кришку розширювального бачка на металічну деталь, розраховану на теплові цикли й герметичне закриття. Вона поєднує міцну конструкцію з кольоровим оформленням моторного відсіку.', benefitEn: 'The BMS billet coolant cap replaces the plastic expansion-tank cap with a metal part designed for heat cycles and a secure seal. It combines a durable construction with a colored engine-bay finish.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. Під час монтажу зніміть заводський pressure-release valve плоскою викруткою та перенесіть його у нову кришку; не встановлюйте без клапана. Ущільніть за інструкцією виробника.', detailsEn: 'Choose Anodized Red, Blue, or Black. During installation, remove the factory pressure-release valve with a flat screwdriver and transfer it to the new cap; do not install without the valve. Seal according to supplier instructions.',
    fitUa: 'Перелічені VW Golf 6/7/8, GTI/R, Passat, Arteon, T-Roc R, Tiguan II, Jetta/GLI, Audi та споріднені VAG із відповідним бачком. Звірте конструкцію factory cap.', fitEn: 'For listed VW Golf 6/7/8, GTI/R, Passat, Arteon, T-Roc R, Tiguan II, Jetta/GLI, Audi, and related VAG applications with the matching reservoir. Verify factory-cap design.'
  },
  'bms-billet-air-conditioning-line-caps-for-e-chassis-bmw-r-chassis-mini': {
    titleUa: 'BMS Billet A/C Line Caps для BMW E-Chassis / MINI R-Chassis — пара', titleEn: 'BMS Billet A/C Line Caps for BMW E-Chassis / MINI R-Chassis — Pair',
    shortUa: 'Два billet cover накладаються на OEM A/C caps; у комплекті Allen wrench, Red або Blue finish.', shortEn: 'Two billet covers fit over OEM A/C caps; Allen wrench included, Red or Blue finish.',
    benefitUa: 'Пара BMS caps накриває сірі пластикові кришки кондиціонера, додаючи захист від подряпин і кольоровий акцент у моторному відсіку. Штатні A/C service caps залишаються на місці, тому декоративні covers не замінюють системні ущільнення.', benefitEn: 'The BMS cap pair covers gray plastic A/C service caps, adding protection from scratches and a colored engine-bay accent. Factory A/C service caps stay in place, so these decorative covers do not replace system seals.',
    detailsUa: 'У комплекті одна велика та одна мала billet cap і Allen wrench. Оберіть Anodized Red або Blue; set screw затягується на штатній кришці. Джерело вимагає точний OE fit: 64538387438 і 64538387437.', detailsEn: 'The package contains one large and one small billet cap plus an Allen wrench. Choose Anodized Red or Blue; a set screw secures each cover over the factory cap. The supplier specifies OE references 64538387438 and 64538387437.',
    fitUa: 'Перелічені BMW E81/E82/E87/E88/E36/E46/E90–E93/E60/E61/E63/E64/E38/E65/E66/E31/X1 E84/X3 E83/X5 E70/X6 E71/Z4 E85/E86/E89 та MINI R50–R57. Інші сірі caps можуть мати інший розмір.', fitEn: 'For listed BMW E81/E82/E87/E88/E36/E46/E90–E93/E60/E61/E63/E64/E38/E65/E66/E31/X1 E84/X3 E83/X5 E70/X6 E71/Z4 E85/E86/E89 and MINI R50–R57. Other gray caps may differ.'
  },
  'bms-magnetic-billet-aluminum-oil-filter-cap-for-2015-2020-ford-f150': {
    titleUa: 'BMS Magnetic Billet Oil Filter Cap для Ford F-150 2.7L V6 2015–2020', titleEn: 'BMS Magnetic Billet Oil Filter Cap for 2015–2020 Ford F-150 2.7L V6',
    shortUa: 'Алюмінієва магнітна заміна пластикової oil-filter cap із 32 мм hex; зберігає OEM filter і seal.', shortEn: 'Magnetic aluminum replacement for the plastic filter cap, with 32 mm hex; retains OEM filter and seal.',
    benefitUa: 'BMS billet cap замінює пластикову кришку корпуса масляного фільтра Ford і має вбудований samarium-cobalt magnet для збирання металевих частинок з оливи. Суцільний алюмінієвий корпус спрощує сервіс завдяки вбудованому 32 мм hex.', benefitEn: 'The BMS billet cap replaces the Ford plastic oil-filter housing cap and uses an integrated samarium-cobalt magnet to capture metal particles in the oil. A solid aluminum body adds a built-in 32 mm hex for service access.',
    detailsUa: 'Оберіть Red, Blue або Black. Кришка використовує OEM oil filter, housing O-ring і filter insert; вони не замінюються цією позицією. Для монтажу потрібен 3/8″ drive або відповідний 32 мм інструмент; дотримуйтеся torque Ford.', detailsEn: 'Choose Red, Blue, or Black. The cap reuses the OEM oil filter, housing O-ring, and filter insert; they are not replaced by this item. Use a 3/8-inch drive or matching 32 mm tool and follow Ford torque specifications.',
    fitUa: 'Ford F-150 2015–2020 з 2.7L V6 у застосуваннях Burger. Звірте рік, об’єм двигуна й тип корпуса фільтра.', fitEn: 'For Burger-listed 2015–2020 Ford F-150 with 2.7L V6. Verify year, engine, and filter-housing type.'
  },
  'b58-s58-s58-bmw-billet-oil-filler-breather-cap': {
    titleUa: 'BMS Billet Oil Filler Breather Cap для BMW B58 / S58 / S68 — вибір fitting', titleEn: 'BMS Billet Oil Filler Breather Cap for BMW B58 / S58 / S68 — Select Fitting',
    shortUa: 'Оберіть engine та block-off або AN breather fitting для підключення crankcase вентиляції.', shortEn: 'Select engine and block-off or AN breather fitting for crankcase ventilation.',
    benefitUa: 'BMS billet cap замінює заводську маслозаливну кришку та додає ORB порт для вентиляції картера. Обраний elbow можна з’єднати з catch can, або встановити block-off cap, якщо зовнішнє vent line не потрібне.', benefitEn: 'The BMS billet cap replaces the factory oil-filler cap and adds an ORB port for crankcase ventilation. Choose an elbow fitting to connect an oil catch can or a block-off cap when no external vent line is needed.',
    detailsUa: 'Оберіть Engine: B58, S58 або S68 і fitting: Black Removable Block-Off, -12ORB 90° to -12AN або -10ORB 90° to -10AN (останній лише для S68). Кришка встановлюється поворотом у пази горловини, не як OEM кришка; повністю посадіть і ущільніть її, щоб уникнути витоку.', detailsEn: 'Select Engine (B58, S58, or S68) and fitting: Black Removable Block-Off, -12ORB 90° to -12AN, or -10ORB 90° to -10AN (S68 only). The cap locks into filler-neck grooves rather than threading like OE; seat and seal it fully to prevent leaks.',
    fitUa: 'Для перелічених BMW із B58/S58/S68, включно з G8x M, G-Chassis B58 і S68 M/7/X models. -10AN fitting підходить лише до S68; перед монтажем звірте покоління горловини.', fitEn: 'For listed BMW with B58/S58/S68, including G8x M, G-Chassis B58, and S68 M/7/X models. The -10AN fitting is S68 only; verify filler-neck generation.'
  },
  'magnetic-billet-oil-filter-cap-for-ford-bronco': {
    titleUa: 'BMS Magnetic Billet Oil Filter Cap для Ford Bronco 2.7L V6 2021+', titleEn: 'BMS Magnetic Billet Oil Filter Cap for 2021+ Ford Bronco 2.7L V6',
    shortUa: 'Магнітна billet заміна пластикової oil-filter cap із 32 мм hex; використовує штатний фільтр.', shortEn: 'Magnetic billet replacement for the plastic filter cap with 32 mm hex; uses the factory filter.',
    benefitUa: 'BMS cap замінює пластикову кришку корпуса масляного фільтра Bronco та вбудованим samarium-cobalt magnet затримує металеві частинки в оливі. Алюмінієвий корпус має 32 мм hex для простого зняття звичайним інструментом.', benefitEn: 'The BMS cap replaces the Bronco plastic oil-filter housing cap and uses an integrated samarium-cobalt magnet to capture metal debris in the oil. The aluminum body has a 32 mm hex for service with common tools.',
    detailsUa: 'Оберіть Red, Blue або Black. Повторно використовуються OEM oil filter, filter housing O-ring і insert; вони не входять. Зніміть стару кришку та встановіть нову за моментом затягування Ford.', detailsEn: 'Choose Red, Blue, or Black. Reuse the OEM oil filter, housing O-ring, and insert; they are not included. Replace the old cap and tighten to Ford specification.',
    fitUa: 'Для Ford Bronco 2021+ з 2.7L V6 за сторінкою Burger. Звірте двигун і корпус фільтра; це не cap для 2.3L.', fitEn: 'For Burger-listed 2021+ Ford Bronco with 2.7L V6. Verify engine and filter housing; not for the 2.3L.'
  },
  'bms-billet-oil-filter-cap-for-s58-bmw-m3-m4-x3m-x4m': {
    titleUa: 'BMS Magnetic Billet Oil Filter Cap для BMW S58 M2 / M3 / M4 / X3M / X4M', titleEn: 'BMS Magnetic Billet Oil Filter Cap for BMW S58 M2 / M3 / M4 / X3M / X4M',
    shortUa: 'Магнітна алюмінієва кришка замінює пластиковий S58 housing cap і має вбудований 32 мм hex.', shortEn: 'Magnetic aluminum cap replaces the plastic S58 housing cover and has an integrated 32 mm hex.',
    benefitUa: 'BMS magnetic billet cap замінює слабку OEM plastic oil-filter cap двигуна S58. Інтегрований samarium-cobalt magnet призначений збирати металеву стружку з оливи, а міцний алюміній має 32 мм hex для сервісу без спеціального інструмента.', benefitEn: 'The BMS magnetic billet cap replaces the S58 factory plastic oil-filter cover. Its integrated samarium-cobalt magnet is designed to capture metal debris in engine oil, while the aluminum body provides a 32 mm hex for servicing without a special tool.',
    detailsUa: 'Оберіть Red, Blue, Black або Silver. Використовує OEM filter, O-ring і filter insert; ці деталі змінюються за регламентом окремо. Під час монтажу перенесіть factory bypass valve, якщо цього вимагає конкретна версія кришки.', detailsEn: 'Choose Red, Blue, Black, or Silver. It uses the OEM filter, O-ring, and filter insert; service those separately. Transfer the factory bypass valve if required by the specific cap revision.',
    fitUa: 'BMW S58 G87 M2, G80 M3, G82/G83 M4 та F97/F98 X3M/X4M у переліку Burger. Підтвердьте двигун S58 і номер корпуса.', fitEn: 'For Burger-listed BMW S58 G87 M2, G80 M3, G82/G83 M4, and F97/F98 X3M/X4M. Confirm S58 engine and housing reference.'
  },
  'billet-bmw-power-steering-reservoir-cap-upgrade': {
    titleUa: 'BMS Billet Power Steering Reservoir Cap для BMW — з новим O-Ring', titleEn: 'BMS Billet Power Steering Reservoir Cap for BMW — Includes New O-Ring',
    shortUa: 'CNC алюмінієва заміна пластикової кришки power steering reservoir із новим ущільнювальним кільцем.', shortEn: 'CNC aluminum replacement for the plastic steering reservoir cap, with a new sealing O-ring.',
    benefitUa: 'BMS cap замінює пластикову кришку резервуара гідропідсилювача BMW. Billet-алюміній витримує теплові цикли, а новий heavy-duty O-ring допомагає герметично закрити горловину.', benefitEn: 'The BMS cap replaces the plastic BMW power-steering reservoir cap. Billet aluminum withstands engine-bay heat cycles, and a new heavy-duty O-ring supports a secure seal.',
    detailsUa: 'Оберіть Anodized Blue, Red, Black або Silver. Це повна заміна кришки та ущільнення, не накладка. Перед відкручуванням очистіть зону навколо резервуара, щоб бруд не потрапив до рідини.', detailsEn: 'Choose Anodized Blue, Red, Black, or Silver. This is a replacement cap and seal, not an overlay. Clean around the reservoir before opening to keep debris out of the fluid.',
    fitUa: 'Для BMW із сумісним power-steering reservoir cap. Перевірте форму кришки та резервуар, оскільки не всі кузови використовують однаковий cap.', fitEn: 'For BMW with the matching power-steering reservoir cap. Verify cap and reservoir shape because not all chassis use the same part.'
  },
  'bms-billet-belt-cover-upgrade-for-subaru': {
    titleUa: 'BMS Billet Alternator Belt Cover для Subaru WRX / Legacy XT', titleEn: 'BMS Billet Alternator Belt Cover for Subaru WRX / Legacy XT',
    shortUa: 'CNC billet belt cover замінює OEM Subaru 23774AA131; у наборі кронштейни та кріплення.', shortEn: 'CNC billet belt cover replaces Subaru OE 23774AA131; brackets and hardware included.',
    benefitUa: 'Білетний belt cover BMS замінює пластиковий кожух ременя допоміжних агрегатів Subaru. Це захист і візуальне оновлення моторного відсіку з алюмінієвою конструкцією замість заводського пластику.', benefitEn: 'The BMS billet belt cover replaces the factory plastic accessory-drive belt cover on Subaru. It adds an aluminum shield and engine-bay finish in place of the stock plastic part.',
    detailsUa: 'У комплекті billet cover, спеціальні bracket і dowel bracket та чотири screws. OE reference 23774AA131. Під час монтажу використайте штатний 10 мм болт, посадіть dowel у гумову втулку й перевірте затягнення комплектних гвинтів.', detailsEn: 'The package contains the billet cover, custom bracket and dowel bracket, and four screws. OE reference 23774AA131. Installation reuses the factory 10 mm bolt and rubber grommet; check supplied screws are tight.',
    fitUa: 'Subaru WRX 2022+ та Legacy XT 2020+ 2.4L Turbo за Burger. Інші Subaru згадані як можливі, але потребують фото двигуна та підтвердження.', fitEn: 'For Burger-listed 2022+ Subaru WRX and 2020+ Legacy XT 2.4L turbo. Other Subaru applications are unconfirmed and require engine-photo verification.'
  },
  'bms-billet-radiator-cap-upgrade-for-subaru': {
    titleUa: 'BMS Billet Radiator Fill Cap для Subaru WRX / STI / Legacy XT', titleEn: 'BMS Billet Radiator Fill Cap for Subaru WRX / STI / Legacy XT',
    shortUa: 'Анодована алюмінієва кришка радіатора замінює відповідну OEM cap; Red, Blue або Black.', shortEn: 'Anodized aluminum radiator cap replaces the matching OEM cap; Red, Blue, or Black.',
    benefitUa: 'BMS billet radiator cap оновлює штатну кришку заливної горловини Subaru. Це механічна заміна деталі для охолоджувальної системи з анодованим фінішем; значення тиску має відповідати заводській специфікації.', benefitEn: 'The BMS billet radiator cap updates the factory Subaru radiator fill cap. It is a functional cooling-system cap with an anodized finish; pressure rating must match factory specification.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. Переконайтеся, що купуєте саме кришку радіатора потрібного тиску, а не декоративну накладку, та відкривайте систему лише на холодному двигуні.', detailsEn: 'Choose Anodized Red, Blue, or Black. Confirm the cap is the correct radiator pressure component, not a decorative cover, and open the cooling system only when the engine is cold.',
    fitUa: 'Subaru WRX 2002+, STI 2004+ та Legacy XT 2020+ 2.4L Turbo у переліку Burger. Звірте форму та тиск OEM cap.', fitEn: 'For Burger-listed 2002+ Subaru WRX, 2004+ STI, and 2020+ Legacy XT 2.4L turbo. Verify factory cap shape and pressure rating.'
  },
  'bms-billet-battery-tie-down-upgrade-for-subaru': {
    titleUa: 'BMS Billet Battery Tie-Down для Subaru — з billet bolt bracket', titleEn: 'BMS Billet Battery Tie-Down for Subaru — With Billet Bolt Bracket',
    shortUa: 'CNC billet тримач замінює сталевий battery tie-down і фіксує акумулятор у штатних точках.', shortEn: 'CNC billet hold-down replaces the steel battery tie-down and secures the battery at factory points.',
    benefitUa: 'BMS tie-down замінює тонкий заводський сталевий затискач акумулятора міцною billet-алюмінієвою деталлю. Правильне кріплення утримує акумулятор на місці; анодований фініш додає кольорову деталь моторному відсіку.', benefitEn: 'The BMS tie-down replaces the thin factory steel battery clamp with a billet-aluminum part. Proper retention keeps the battery in place; the anodized finish adds a colored engine-bay detail.',
    detailsUa: 'У комплекті billet tie-down і matching billet front bolt/bracket. Оберіть Anodized Red, Blue або Black. Використовуйте штатні точки кріплення та після монтажу перевірте, що корпус батареї не рухається й клеми не натягнуті.', detailsEn: 'The package includes the billet tie-down and matching billet front bolt/bracket. Choose Anodized Red, Blue, or Black. Use factory mounting points and confirm the battery is secure without stressing terminals.',
    fitUa: 'Для Subaru із відповідною штатною battery tray і номерами OE 82182AG001 / 82161AG001 / 82161AG011 / 902370049 у списку Burger. Звірте батарейний кронштейн.', fitEn: 'For Subaru with matching factory battery tray and Burger-listed OE references 82182AG001 / 82161AG001 / 82161AG011 / 902370049. Verify battery bracket.'
  },
  'bms-billet-oil-filter-cover-upgrade-for-subaru': {
    titleUa: 'BMS Billet Oil Filter Cover з heat sinks для Subaru WRX / BRZ / Legacy XT', titleEn: 'BMS Billet Oil Filter Cover with Heat Sinks for Subaru WRX / BRZ / Legacy XT',
    shortUa: 'Декоративно-функціональна billet cover накриває OEM oil filter і має cooling fins та новий O-Ring.', shortEn: 'Billet cover fits over the OEM oil filter with cooling fins and a new O-ring.',
    benefitUa: 'BMS billet cover захищає та закриває корпус масляного фільтра Subaru, додаючи heat-sink fins для відведення тепла й брендований вигляд. Це накладний корпус навколо сумісного фільтра, не сам oil filter.', benefitEn: 'The BMS billet cover surrounds the Subaru oil filter and adds heat-sink fins for heat dissipation and a branded finish. It is a cover around the compatible filter, not the filter itself.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. Комплект містить cover і новий sealing O-ring; монтаж і демонтаж не потребують інструмента. Підходить лише з OEM Subaru filter 15208AA170 або aftermarket filter подібної висоти; не сумісний із деякими aftermarket oil-cooler kits.', detailsEn: 'Choose Anodized Red, Blue, or Black. The package contains the cover and a new sealing O-ring; installation/removal is tool-free. Use Subaru OE filter 15208AA170 or a similar-height aftermarket filter. Not compatible with some aftermarket oil-cooler kits.',
    fitUa: 'Subaru WRX 2015+, BRZ 2013+ та Legacy XT 2020+ 2.4L Turbo за Burger. Перевірте фільтр і наявність aftermarket cooler перед замовленням.', fitEn: 'For Burger-listed 2015+ Subaru WRX, 2013+ BRZ, and 2020+ Legacy XT 2.4L turbo. Check filter height and aftermarket cooler before ordering.'
  },
  'bms-billet-oil-fill-cap-upgrade-for-subaru': {
    titleUa: 'BMS Billet Oil Filler Cap для Subaru — OE SOA3881310 / SOA3881280', titleEn: 'BMS Billet Oil Filler Cap for Subaru — OE SOA3881310 / SOA3881280',
    shortUa: 'CNC billet кришка замінює жовтий OEM oil cap; комплектується новим ущільнювальним O-Ring.', shortEn: 'CNC billet cap replaces the yellow OEM oil cap and includes a new sealing O-ring.',
    benefitUa: 'BMS oil filler cap повністю замінює штатну пластикову кришку заливної горловини Subaru. Суцільний billet-алюміній, анодування та нове ущільнення забезпечують сервісну кришку з оновленим виглядом.', benefitEn: 'The BMS oil-filler cap fully replaces the factory plastic Subaru filler cap. Solid billet aluminum, anodizing, and a new seal provide a serviceable replacement with an updated appearance.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. У комплекті новий O-ring; OE references SOA3881310 і SOA3881280. Перевірте, що різьба й профіль збігаються з вашою горловиною, та закривайте кришку без перекосу.', detailsEn: 'Choose Anodized Red, Blue, or Black. A new O-ring is included; OE references are SOA3881310 and SOA3881280. Confirm the thread and profile match the filler neck and avoid cross-threading.',
    fitUa: 'Для Subaru, що використовують OE cap SOA3881310 або SOA3881280. Звірте номер деталі на штатній кришці.', fitEn: 'For Subaru applications using OE cap SOA3881310 or SOA3881280. Verify the part number on the factory cap.'
  },
  'billet-radiator-cap-cover-for-nissan-z-infiniti-q50-q60': {
    titleUa: 'BMS Billet Radiator Cap Cover для Infiniti Q50/Q60 / Nissan Z — 1 шт.', titleEn: 'BMS Billet Radiator Cap Cover for Infiniti Q50/Q60 / Nissan Z — Each',
    shortUa: 'Декоративний cover накладається на OEM radiator cap; одна штука, для передньої пари замовляйте дві.', shortEn: 'Decorative cover fits over the OEM radiator cap; sold each, order two for the front pair.',
    benefitUa: 'Billet cover оновлює вигляд штатних передніх радіаторних кришок Infiniti/Nissan, не змінюючи тиск чи функцію OEM cap. CNC-оброблений алюміній анодований у колір і кріпиться високотемпературною 3M adhesive.', benefitEn: 'The billet cover updates factory front radiator caps on Infiniti/Nissan without changing the OEM cap pressure or function. CNC-machined aluminum is anodized and attaches with high-temperature 3M adhesive.',
    detailsUa: 'Оберіть Crimson Red, Azure Blue або Jet Black. Ціна та комплектація за одну штуку; Q50/Q60 3.0L і Nissan Z потребують двох передніх covers. Не підходить до третьої задньої кришки й не є повною pressure cap заміною.', detailsEn: 'Choose Crimson Red, Azure Blue, or Jet Black. Sold as one cover; Q50/Q60 3.0L and Nissan Z need two front covers. It does not fit the third rear cap and is not a replacement pressure cap.',
    fitUa: 'Infiniti Q50 2016–2024/Q60 2017–2022 та Nissan Z 2023+ у двигунах зі сторінки Burger. Перевірте factory cap shape та необхідну кількість.', fitEn: 'For Burger-listed 2016–2024 Infiniti Q50, 2017–2022 Q60, and 2023+ Nissan Z applications. Verify factory cap shape and quantity.'
  },
  'billet-radiator-cap-cover-for-mazda': {
    titleUa: 'BMS Billet Radiator Cap Cover для Mazda — Red / Blue / Black', titleEn: 'BMS Billet Radiator Cap Cover for Mazda — Red / Blue / Black',
    shortUa: 'Алюмінієвий декоративний cover встановлюється поверх штатної radiator cap, не замінює її.', shortEn: 'Aluminum decorative cover fits over the factory radiator cap; it does not replace it.',
    benefitUa: 'BMS cover додає billet-алюмінієве оздоблення штатній кришці радіатора Mazda. Він приклеюється поверх OEM cap, тому заводський тиск і функція клапана залишаються незмінними.', benefitEn: 'The BMS cover adds billet-aluminum trim to a Mazda factory radiator cap. It attaches over the OEM cap, leaving its pressure rating and valve function unchanged.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. Це декоративна накладка з високотемпературною двосторонньою adhesive, не сервісна pressure cap. Перед купівлею звірте форму кришки з фото, оскільки джерело вказує лише «більшість Mazda 2013+» із відповідною кришкою.', detailsEn: 'Choose Anodized Red, Blue, or Black. This is a decorative overlay using high-temperature double-sided adhesive, not a service pressure cap. Match the factory cap to the source photo; Burger only says most 2013+ Mazda models with the same cap.',
    fitUa: 'Більшість Mazda 2013+ лише за умови однакової форми OEM radiator cap. Порівняйте кришку автомобіля перед замовленням.', fitEn: 'Most 2013+ Mazda only when the factory radiator cap shape matches. Compare the vehicle cap before ordering.'
  },
  'billet-radiator-cap-cover-for-kia-hyundai-genesis': {
    titleUa: 'BMS Billet Radiator Cap Cover для Kia / Hyundai / Genesis', titleEn: 'BMS Billet Radiator Cap Cover for Kia / Hyundai / Genesis',
    shortUa: 'Кольоровий billet overlay встановлюється поверх factory radiator cap; оберіть Red, Blue або Black.', shortEn: 'Colored billet overlay fits over the factory radiator cap; choose Red, Blue, or Black.',
    benefitUa: 'Накладка BMS додає billet-алюмінієве оздоблення штатній радіаторній кришці Kia/Hyundai/Genesis. Factory cap лишається всередині й продовжує відповідати за тиск системи охолодження.', benefitEn: 'The BMS overlay adds billet-aluminum trim to the factory Kia/Hyundai/Genesis radiator cap. The original cap remains in place and continues to control cooling-system pressure.',
    detailsUa: 'Оберіть Anodized Red, Blue або Black. Накладка приклеюється високотемпературною adhesive поверх OEM кришки; не знімайте клапан і не використовуйте її як заміну pressure cap. Виробник вказує більшість моделей 2018+ з формою кришки як на фото.', detailsEn: 'Choose Anodized Red, Blue, or Black. The cover attaches over the OEM cap with high-temperature adhesive; do not remove the valve or use it as a pressure-cap replacement. The supplier lists most 2018+ models with the pictured cap shape.',
    fitUa: 'Kia/Hyundai/Genesis 2018+ із відповідною формою штатної radiator cap. Перевірте сумісність за фото до купівлі.', fitEn: 'For 2018+ Kia/Hyundai/Genesis with the matching factory radiator-cap shape. Verify with the product photo before purchase.'
  },
  'billet-coolant-overflow-reservoir-cap-cover-for-kia-hyundai-genesis': {
    titleUa: 'BMS Billet Coolant Overflow Cap Cover для Kia / Hyundai / Genesis', titleEn: 'BMS Billet Coolant Overflow Cap Cover for Kia / Hyundai / Genesis',
    shortUa: 'Billet overlay закриває OEM coolant recovery reservoir cap; Red, Blue або Black.', shortEn: 'Billet overlay covers the OEM coolant recovery reservoir cap; Red, Blue, or Black.',
    benefitUa: 'Цей cover оздоблює пластикову кришку coolant overflow/recovery tank. Він не замінює герметичну кришку й не змінює тиск охолоджувальної системи; OEM компонент залишається на місці.', benefitEn: 'This cover dresses the plastic coolant overflow/recovery tank cap. It does not replace the sealing cap or alter cooling-system pressure; the OEM part remains installed.',
    detailsUa: 'Оберіть Anodized Blue, Red або Black. Накладка притискається поверх штатної кришки й додатково фіксується high-temperature double-sided tape. Під час монтажу не повинно залишитися видимого краю чорної OEM cap; перевірте форму резервуара.', detailsEn: 'Choose Anodized Blue, Red, or Black. The overlay presses over the factory cap and uses high-temperature double-sided tape. The supplier says no edge of the black OEM cap should show; verify tank shape.',
    fitUa: 'Більшість Kia/Hyundai/Genesis 2018+ з відповідним coolant overflow cap за фото Burger. Це не повна заміна бачка чи кришки.', fitEn: 'Most 2018+ Kia/Hyundai/Genesis with the matching coolant-overflow cap shown by Burger. Not a replacement tank or sealing cap.'
  },
  'billet-brake-fluid-reservoir-tank-master-cylinder-cap-cover-for-ford': {
    titleUa: 'BMS Billet Brake Reservoir Cap Cover для Ford Bronco / Edge / Escape / Maverick', titleEn: 'BMS Billet Brake Reservoir Cap Cover for Ford Bronco / Edge / Escape / Maverick',
    shortUa: 'Декоративний billet cover для OEM гальмівного бачка Ford K2GZ2162B; Red, Blue або Black.', shortEn: 'Decorative billet cover for Ford OE brake reservoir K2GZ2162B; Red, Blue, or Black.',
    benefitUa: 'BMS cover оновлює вигляд заводської кришки гальмівної рідини на Ford і залишає OEM cap на місці. CNC billet-алюміній анодований; рідина та герметичність залишаються під контролем заводського резервуара.', benefitEn: 'The BMS cover updates the factory Ford brake-fluid cap while leaving the OEM cap installed. CNC billet aluminum is anodized; fluid sealing remains the responsibility of the original reservoir cap.',
    detailsUa: 'Оберіть Anodized Blue, Red або Black. Це накладка, а не pressure cap replacement; фіксується високотемпературною двосторонньою tape. OE reference Ford K2GZ2162B; перевірте номер на вашій кришці.', detailsEn: 'Choose Anodized Blue, Red, or Black. This is an overlay, not a replacement pressure cap; it attaches with high-temperature double-sided tape. Ford OE reference K2GZ2162B; verify your cap number.',
    fitUa: 'Ford Bronco/Bronco Sport 2021+, Edge 2020+, Escape 2020+, Maverick 2021+ та Mustang Mach-E 2021+ за Burger із OE cap K2GZ2162B.', fitEn: 'For Burger-listed Ford Bronco/Bronco Sport 2021+, Edge 2020+, Escape 2020+, Maverick 2021+, and Mustang Mach-E 2021+ using OE cap K2GZ2162B.'
  },
  'billet-brake-fluid-reservoir-tank-cap-cover-for-mazda': {
    titleUa: 'BMS Billet Brake Reservoir Cap Cover для Mazda — Red / Blue / Black', titleEn: 'BMS Billet Brake Reservoir Cap Cover for Mazda — Red / Blue / Black',
    shortUa: 'Billet cover встановлюється поверх OEM brake-fluid cap; звірте форму резервуара Mazda.', shortEn: 'Billet cover fits over the OEM brake-fluid cap; verify the Mazda reservoir shape.',
    benefitUa: 'Накладка BMS додає анодоване billet оздоблення штатному бачку гальмівної рідини Mazda. OEM sealing cap залишається на місці, тому кришка продовжує виконувати заводську функцію герметизації.', benefitEn: 'The BMS overlay adds anodized billet trim to the Mazda brake-fluid reservoir. The OEM sealing cap remains in place and continues its factory sealing function.',
    detailsUa: 'Оберіть Anodized Blue, Red або Black. Перед монтажем очистіть поверхню та зафіксуйте cover високотемпературною двосторонньою tape. Переконайтеся, що форма штатної кришки збігається; аксесуар не замінює сам cap.', detailsEn: 'Choose Anodized Blue, Red, or Black. Clean the surface and attach with high-temperature double-sided tape. Confirm the factory-cap shape matches; the accessory does not replace the cap itself.',
    fitUa: 'Для Mazda з бачком гальмівної рідини тієї форми, що показана Burger. Порівняйте резервуар автомобіля перед замовленням.', fitEn: 'For Mazda applications with the brake reservoir shape shown by Burger. Compare the vehicle reservoir before ordering.'
  },
  'bms-billet-oil-filter-cap-b58-bmw-toyota-engines': {
    titleUa: 'BMS Billet Oil Filter Cap для BMW / Toyota B58 — V1 або V2 Magnetic', titleEn: 'BMS Billet Oil Filter Cap for BMW / Toyota B58 — V1 or V2 Magnetic',
    shortUa: 'Оберіть V1 Black/Silver або V2 Red/Blue із вбудованим magnet; обидві версії використовують OEM filter.', shortEn: 'Choose V1 Black/Silver or V2 Red/Blue with integrated magnet; both retain OEM filter.',
    benefitUa: 'Білетна кришка BMS замінює пластиковий oil-filter cap B58 і спрощує обслуговування завдяки 32 мм hex та 3/8″ drive. V2 має закріплений samarium-cobalt magnet для збирання металевих частинок з оливи; V1 — немагнітна версія.', benefitEn: 'The BMS billet cap replaces the plastic B58 oil-filter cover and adds a 32 mm hex and 3/8-inch drive for service. V2 includes a secured samarium-cobalt magnet to capture metal particles in oil; V1 is the non-magnetic version.',
    detailsUa: 'Оберіть V2 Red Magnetic або V2 Blue Magnetic, чи V1 Black/Silver. Використовуються OEM filter, housing O-ring, filter insert і bypass valve — перенесіть bypass valve зі штатної кришки та замініть зовнішнє ущільнення за інструкцією.', detailsEn: 'Choose V2 Red Magnetic, V2 Blue Magnetic, or V1 Black/Silver. Reuse the OEM filter, housing O-ring, filter insert, and bypass valve; transfer the bypass valve from the factory cap and replace the outer seal as instructed.',
    fitUa: 'Більшість BMW Gen 1/Gen 2 B58 і Toyota Supra B58 у застосуваннях Burger. Не припускайте сумісність із B58 Gen 3; звірте двигун та корпус фільтра.', fitEn: 'For most Burger-listed BMW Gen 1/Gen 2 B58 and Toyota Supra B58 applications. Do not assume Gen 3 B58 fitment; verify engine and filter housing.'
  },
  'jack-pad-adapter-for-2020-toyota-supra': {
    titleUa: 'BMS Billet Jack Pad Adapter для Toyota GR Supra Mk5 2020–2026 — 1 / 2 / 4 шт.', titleEn: 'BMS Billet Jack Pad Adapter for 2020–2026 Toyota GR Supra Mk5 — 1 / 2 / 4 Pack',
    shortUa: 'Алюмінієвий адаптер утворює пласку опору в factory jack point; оберіть колір і кількість.', shortEn: 'Aluminum adapter makes a flat support at the factory jack point; choose finish and quantity.',
    benefitUa: 'BMS jack pad адаптер створює стабільну площину між домкратом і штатною точкою підйому Supra. Це допомагає не зім’яти jack point або пошкодити днище при піднятті для сервісу.', benefitEn: 'The BMS jack-pad adapter creates a stable surface between a floor jack and the Supra factory lift point, helping avoid crushed jack points or underbody damage during service.',
    detailsUa: 'Оберіть Billet Silver, Red, Blue або Black та кількість: 1, 2 або 4. Форма повторює штатний jack point; нижня honeycomb grip допомагає утримати адаптер на домкраті. Не використовувати з jack stands чи bottle jacks; це інструмент підйому, не залишайте його в точках під час руху.', detailsEn: 'Choose Billet Silver, Red, Blue, or Black and quantity: 1, 2, or 4. The shape matches the factory jack point and the honeycomb bottom grips a floor jack. Do not use with jack stands or bottle jacks; remove the adapters before driving.',
    fitUa: 'Для Toyota GR Supra Mk5 2020–2026 у factory jack points. Переконайтеся, що обрана кількість покриває потрібні точки підйому.', fitEn: 'For 2020–2026 Toyota GR Supra Mk5 factory jack points. Select enough units for the intended lifting points.'
  },
  'n54-coolant-port-fitting': {
    titleUa: 'BMS Billet Coolant Port Fitting для BMW N54 / N52 / N53 / N20', titleEn: 'BMS Billet Coolant Port Fitting for BMW N54 / N52 / N53 / N20',
    shortUa: 'Металева CNC заміна пластикового coolant flange, що схильний до тріщин; у комплекті O-ring і clamp.', shortEn: 'Metal CNC replacement for the crack-prone plastic coolant flange; includes O-ring and clamp.',
    benefitUa: 'Billet coolant fitting замінює пластиковий перехідник системи охолодження BMW, який з часом стає крихким через цикли нагрівання й може тріснути під час сервісу. Алюмінієва деталь призначена для надійнішої заміни штатного фланця.', benefitEn: 'The billet coolant fitting replaces a BMW plastic cooling-system connector that can become brittle through heat cycles and crack during service. The aluminum part provides a sturdier replacement for the factory flange.',
    detailsUa: 'У комплекті billet coolant-port flange, heavy-duty O-ring і stainless hose clamp. Перед розбиранням охолодіть двигун і злийте тиск; після монтажу видаліть повітря із системи та перевірте витоки.', detailsEn: 'The package includes a billet coolant-port flange, heavy-duty O-ring, and stainless hose clamp. Let the engine cool and release system pressure before service; bleed the system and check for leaks after installation.',
    fitUa: 'BMW N54 3.0L turbo 135i/335i/335ix/1M та перелічені N52/N53/N20 застосування, включно з 2006–2010 325i/330i/525i/528i/530i, N52 X3 та Z4 2013+. Звірте OE references зі сторінки Burger.', fitEn: 'For BMW N54 3.0L turbo 135i/335i/335ix/1M and listed N52/N53/N20 applications, including 2006–2010 325i/330i/525i/528i/530i, N52 X3, and 2013+ Z4. Match OE references from Burger.'
  },
  'bmw-floor-jack-pad-adapter': {
    titleUa: 'BMS Billet Floor Jack Pad Adapter для BMW / MINI — 1 / 2 / 4 шт.', titleEn: 'BMS Billet Floor Jack Pad Adapter for BMW / MINI — 1 / 2 / 4 Pack',
    shortUa: 'Вставка відтворює заводський scissor-jack profile BMW; оберіть Red/Blue/Black/Silver та кількість.', shortEn: 'Adapter mimics the factory BMW scissor-jack profile; choose finish and one, two, or four.',
    benefitUa: 'BMS jack pad adapter входить у заводську точку підйому BMW/MINI та створює пласку опору для floor jack. Це допомагає захистити factory jack point, rocker panel і днище під час сервісу.', benefitEn: 'The BMS jack-pad adapter fits the BMW/MINI factory lift point and creates a flat support for a floor jack, helping protect jack points, rocker panels, and underbody during service.',
    detailsUa: 'Оберіть Red, Blue, Black або Billet Silver і комплект із 1, 2 чи 4 адаптерів. CNC billet-aluminum адаптер має honeycomb grip знизу; підходить для більшості floor jacks. Не використовувати з jack stands чи bottle jacks; зніміть перед поїздкою.', detailsEn: 'Choose Red, Blue, Black, or Billet Silver and a set of 1, 2, or 4. CNC billet aluminum has a honeycomb grip underneath and fits many floor jacks. Do not use with jack stands or bottle jacks; remove before driving.',
    fitUa: 'Для BMW і MINI із заводською jack point, що відповідає адаптеру. Звірте розмір вставної частини, особливо для нестандартного кузова.', fitEn: 'For BMW/MINI with matching factory jack points. Verify insert dimensions, especially on unusual chassis.'
  },
  'billet-bmw-oil-filter-cap-removal-tool': {
    titleUa: 'BMS Billet BMW Oil Filter Cap Wrench — 27 мм', titleEn: 'BMS Billet BMW Oil Filter Cap Wrench — 27 mm',
    shortUa: 'Алюмінієвий інструмент знімає гладкий BMW oil-filter cap через 27 мм wrench/socket або 3/8 drive.', shortEn: 'Aluminum tool removes smooth BMW oil-filter caps using a 27 mm wrench/socket or 3/8 drive.',
    benefitUa: 'BMS billet wrench захоплює гладку поверхню oil-filter housing cap, щоб відкручувати й затягувати її без пошкодження корпусу. Інструмент зручно застосовувати при самостійному сервісі BMW.', benefitEn: 'The BMS billet wrench grips a smooth oil-filter housing cap for removal and installation without damaging the housing, supporting DIY BMW service.',
    detailsUa: 'Чорний анодований billet-aluminum tool має сумісність із 27 мм socket/wrench, adjustable wrench або 3/8″ drive. Застосовуйте torque з інструкції BMW; не перетягуйте пластиковий OEM cap.', detailsEn: 'The black-anodized billet-aluminum tool works with a 27 mm socket/wrench, adjustable wrench, or 3/8-inch drive. Follow BMW torque specifications and do not overtighten a plastic OEM cap.',
    fitUa: 'Для гладких BMW oil-filter caps відповідного розміру, зазначених Burger. Перед купівлею перевірте форму housing і діаметр.', fitEn: 'For the smooth BMW oil-filter caps of matching size listed by Burger. Check housing shape and diameter before ordering.'
  },
  'tow-hook-camera-mount-for-gopro-cameras': {
    titleUa: 'BMW / MINI Tow-Hook Camera Mount для GoPro — E або F Chassis', titleEn: 'BMW / MINI Tow-Hook Camera Mount for GoPro — E or F Chassis',
    shortUa: 'CNC billet GoPro mount кріпиться у front/rear tow hook без свердління; оберіть E або F chassis.', shortEn: 'CNC billet GoPro mount fits the front/rear tow hook without drilling; choose E or F chassis.',
    benefitUa: 'Tow-hook GoPro mount фіксує камеру спереду чи позаду BMW/MINI, не торкаючись пофарбованих поверхонь і не покладаючись на suction cup. Суцільний billet-aluminum тримач зменшує вібрацію під час зйомки.', benefitEn: 'The tow-hook GoPro mount secures a camera at the front or rear of a BMW/MINI without touching painted surfaces or relying on a suction cup. Solid billet aluminum helps limit vibration during filming.',
    detailsUa: 'Оберіть E Chassis або F Chassis. X1 E84 потребує F-Chassis версію за джерелом; mount не підходить до BMW Z4. Стійка GoPro та камера продаються окремо. Перевірте tow-hook thread, кузовний код і довжину до бампера.', detailsEn: 'Choose E Chassis or F Chassis. Burger specifies the F-Chassis mount for X1 E84; it does not fit BMW Z4. GoPro camera and attachment are separate. Confirm tow-hook thread, chassis code, and bumper clearance.',
    fitUa: 'Для відповідних BMW/MINI E- або F-Chassis зі штатною tow-hook точкою. На дату джерела обидва варіанти позначені out of stock — перевірте фактичну наявність.', fitEn: 'For matching BMW/MINI E- or F-Chassis with factory tow-hook point. Both options are marked out of stock in the source snapshot; verify current availability.'
  },
  'vw-billet-black-out-windshield-washer-cap': {
    titleUa: 'BMS Billet Windshield Washer Reservoir Cap для VW / Audi / Honda', titleEn: 'BMS Billet Windshield Washer Reservoir Cap for VW / Audi / Honda',
    shortUa: 'Чорна CNC billet кришка замінює синю factory washer cap; лазерний BMS логотип.', shortEn: 'Black CNC billet replacement for the blue factory washer cap, with laser-etched BMS logo.',
    benefitUa: 'BMS washer cap повністю замінює синю пластикову кришку бачка омивача на сумісних VW, Audi та Honda. Чорне анодування захищає алюмінієву деталь і створює стриманий factory-style вигляд.', benefitEn: 'The BMS washer cap replaces the blue plastic washer-reservoir cap on compatible VW, Audi, and Honda vehicles. Black anodizing protects the aluminum and keeps a restrained factory-style look.',
    detailsUa: 'Це повна кришка, CNC-оброблена з billet aluminum і вигравірувана логотипом BMS. Перед замовленням порівняйте форму горловини з fitment list: вона охоплює багато Audi A3/A4/A5/S3/S4/S5/TT і VW Golf/Jetta/Passat/Tiguan, а також окремі Honda 2016+ 1.5/2.0L.', detailsEn: 'This is a full cap machined from billet aluminum and etched with the BMS logo. Compare the filler neck against the fitment list: many Audi A3/A4/A5/S3/S4/S5/TT and VW Golf/Jetta/Passat/Tiguan, plus select 2016+ Honda 1.5/2.0L.',
    fitUa: 'Для точних моделей/кузовів зі сторінки Burger, що використовують синю washer reservoir cap такого профілю. Звірте форму до купівлі.', fitEn: 'For exact Burger-listed models/chassis using the matching blue washer-reservoir cap profile. Verify shape before purchase.'
  },
  'corvette-1997-present-floor-jack-pad-adapter': {
    titleUa: 'BMS Jack Pad Adapter для Chevrolet Corvette C5 / C6 / C7 / C8 — 1 шт.', titleEn: 'BMS Jack Pad Adapter for Chevrolet Corvette C5 / C6 / C7 / C8 — Each',
    shortUa: 'Уретановий pad із locking tab фіксується в factory jack receptacle; продається по одному.', shortEn: 'Urethane pad with locking tab fits the factory jack receptacle; sold individually.',
    benefitUa: 'BMS pad створює точку опори для підйому Corvette на factory jack point, допомагаючи зменшити ризик подряпати раму чи пошкодити rocker panels. Поворотний locking tab утримує адаптер у заводському гнізді під час позиціювання floor jack.', benefitEn: 'The BMS pad provides a support point at the Corvette factory jack location to help prevent frame scratches or rocker damage. A quarter-turn locking tab holds it in the factory receptacle while positioning a floor jack.',
    detailsUa: 'Один hard-urethane honeycomb pad діаметром близько 2.5″ і заввишки 1.2″. Вставте у точку, поверніть на чверть оберту, підніміть авто та зніміть після роботи. Продається по одному; не для jack stands, і не можна залишати під час руху.', detailsEn: 'One hard-urethane honeycomb pad, about 2.5 inches wide and 1.2 inches tall. Insert into the jack point, turn a quarter-turn, lift, then remove after service. Sold each; not for jack stands and do not drive with it installed.',
    fitUa: 'Chevrolet Corvette C5/C6/C7/C8 1997+ усіх моделей за Burger. Звірте кількість потрібних точок підйому; кожна одиниця продається окремо.', fitEn: 'For Burger-listed 1997+ Chevrolet Corvette C5/C6/C7/C8. Select the number of lifting points needed; each adapter is sold separately.'
  },
  'honda-billet-oil-filler-cap-by-bms': {
    titleUa: 'BMS Billet Oil Filler Cap для Honda / Acura / Kia / Hyundai / Genesis', titleEn: 'BMS Billet Oil Filler Cap for Honda / Acura / Kia / Hyundai / Genesis',
    shortUa: 'Однокомпонентна billet заміна пластикової screw-type oil cap з oversized oil-proof gasket.', shortEn: 'One-piece billet replacement for screw-type plastic oil cap, with oversized oil-proof gasket.',
    benefitUa: 'BMS billet oil cap замінює заводську пластикову кришку заливної горловини на сумісному Honda, Acura, Kia, Hyundai або Genesis. CNC-алюміній і велике маслостійке ущільнення забезпечують щільну посадку й просте відкручування.', benefitEn: 'The BMS billet oil cap replaces the plastic factory filler cap on compatible Honda, Acura, Kia, Hyundai, or Genesis engines. CNC aluminum and an oversized oil-resistant gasket provide a secure fit and easy twist removal.',
    detailsUa: 'Оберіть Anodized Red, Blue, Black або Silver. Ця версія призначена лише для screw-type oil filler cap. Перевірте різьбу та діаметр горловини; push-on caps не сумісні.', detailsEn: 'Choose Anodized Red, Blue, Black, or Silver. This version fits screw-type oil filler caps only. Verify thread and filler-neck diameter; push-on caps are not compatible.',
    fitUa: 'Honda/Acura/Kia/Hyundai/Genesis, де встановлена відповідна screw-type cap за fitment list Burger. Порівняйте заводську кришку до замовлення.', fitEn: 'Honda/Acura/Kia/Hyundai/Genesis with the matching screw-type cap in Burger’s fitment list. Compare the factory cap before ordering.'
  },
  'bms-billet-bmw-oil-filter-housing-for-n54-n55-s55-n51-n52-n20-bmw-engines': {
    titleUa: 'BMS V2 Magnetic Billet Oil Filter Cap для BMW N54 / N55 / S55 / N52 / N20', titleEn: 'BMS V2 Magnetic Billet Oil Filter Cap for BMW N54 / N55 / S55 / N52 / N20',
    shortUa: 'V2 billet cap має integrated magnet, heat sinks і 3/8 drive; повторно використовує OEM filter cage.', shortEn: 'V2 billet cap has an integrated magnet, heat sinks, and 3/8 drive; reuses OEM filter cage.',
    benefitUa: 'BMS V2 billet cap замінює пластикову BMW oil-filter cover міцним алюмінієм із cooling fins. Інтегрований samarium-cobalt magnet призначений затримувати металеву стружку, а 3/8″ drive допомагає обслуговувати кришку без спеціального інструмента.', benefitEn: 'The BMS V2 billet cap replaces the plastic BMW oil-filter cover with an aluminum part featuring heat sinks. An integrated samarium-cobalt magnet is designed to capture metal debris, and the 3/8-inch drive simplifies service without a special tool.',
    detailsUa: 'Оберіть Anodized Red, Blue, Black або Silver. Кришка використовує OEM filter, housing O-ring і filter cage; їх слід перенести/обслуговувати окремо. Джерело містить різні згадки 19/21 мм hex, тому у цій картці не вказуємо окремий розмір шестигранника.', detailsEn: 'Choose Anodized Red, Blue, Black, or Silver. The cap reuses the OEM filter, housing O-ring, and filter cage; service these separately. The supplier text conflicts between 19 mm and 21 mm hex references, so this listing does not specify a hex size.',
    fitUa: 'Для перелічених BMW N54/N55/S55/N51/N52/N20/N26 двигунів, OE cap 11427525334. Звірте номер корпуса фільтра та рік перед покупкою.', fitEn: 'For listed BMW N54/N55/S55/N51/N52/N20/N26 engines using OE cap 11427525334. Verify filter housing and year before ordering.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Що це дає</h3>\n<p>${item.benefitUa}</p>\n<h3>Опції та комплектність</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and benefit</h3>\n<p>${item.benefitEn}</p>\n<h3>Options and package</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
