// Source-checked accessories, service parts, and digital item copy; local draft only.
const rows = {
  'labor-75': {
    titleUa: 'Сервісна робота Burger Motorsports — позиція $75', titleEn: 'Burger Motorsports Labor Service — $75 Line Item',
    shortUa: 'Сервісна позиція роботи Burger на $75; додавайте лише коли її погоджено для конкретного замовлення.', shortEn: 'Burger $75 service-labor line item; add only when approved for a specific order.',
    benefitUa: 'Це сервісна позиція для обліку роботи Burger Motorsports, а не автомобільна деталь або самостійний товар. Вона потрібна лише тоді, коли постачальник або майстер окремо виставив роботу у конкретному замовленні.', benefitEn: 'This is a Burger Motorsports service-labor line item, not an automotive part or standalone retail product. Use it only when the supplier or installer has specifically quoted labor on an order.',
    detailsUa: 'Назва джерела вказує суму $75. Перед додаванням перевірте фактичну послугу, суму, валюту та те, чи не включена робота до іншої позиції. Це не фізичне відправлення і не повинно отримувати вагу чи доставку деталі.', detailsEn: 'The supplier title lists $75. Before adding it, confirm the actual service, amount, currency, and that labor is not already included elsewhere. This is not a physical shipment and should not receive a part weight or shipping charge.',
    fitUa: 'Відображати лише як узгоджену сервісну позицію у відповідному кошторисі; не показувати як запчастину для автомобіля.', fitEn: 'Use only as an approved service line in the applicable quote; do not present it as a vehicle part.', internalOptionOnly: true
  },
  'jb4-magnetic-cell-phone-vent-mount-holder-for-magsafe': {
    titleUa: 'JB4 MagSafe-Compatible Phone Mount — вентиляційний або магнітний', titleEn: 'JB4 MagSafe-Compatible Phone Mount — Vent or Magnetic',
    shortUa: 'Оберіть Vent Mount або Magnetic/Adhesive Mount для кріплення телефона з регульованим кутом огляду.', shortEn: 'Choose Vent Mount or Magnetic/Adhesive Mount for adjustable phone positioning.',
    benefitUa: 'Тримач утримує телефон у полі зору для навігації, Dragy або моніторингу JB4 Mobile. Конструкція сумісна з MagSafe і дає змогу змінювати кут огляду; вибір типу основи визначає, куди саме кріпиться тримач.', benefitEn: 'The holder keeps a phone visible for navigation, Dragy, or JB4 Mobile monitoring. It is MagSafe-compatible with an adjustable viewing angle; the mount-style choice determines how the holder attaches.',
    detailsUa: 'Оберіть Vent Mount для фіксації на автомобільній вентиляційній решітці або Magnetic/Adhesive Mount для монтажу магнітами до металу чи комплектною клейкою основою до неметалевої поверхні. Перевірте тип решітки й поверхню перед вибором.', detailsEn: 'Vent Mount attaches to a vehicle air vent. Magnetic/Adhesive Mount attaches magnetically to metal or uses the included adhesive pad on a non-metal surface. Check vent style and mounting surface before selecting.',
    fitUa: 'Для телефонів із MagSafe або відповідною магнітною пластиною. Тримач не додає телефон чи Dragy; переконайтеся, що обрана основа підходить до місця монтажу.', fitEn: 'For MagSafe phones or compatible magnetic plates. Phone and Dragy device are not included; confirm the chosen base suits the installation location.'
  },
  'official-burger-motorsports-jb4-clothing': {
    titleUa: 'Офіційний одяг Burger Motorsports JB4 — оберіть модель і розмір', titleEn: 'Official Burger Motorsports JB4 Apparel — Choose Style and Size',
    shortUa: 'Оберіть JB4 Juice Box футболку, Burger Town футболку або худі та розмір S–XXL.', shortEn: 'Choose a JB4 Juice Box tee, Burger Town tee, or hoodie in sizes Small through XXL.',
    benefitUa: 'Одяг Burger Motorsports дає змогу носити логотип JB4 та мотив Burger Town для фанатів автомобільного тюнінгу. На сторінці описані футболки й середньої щільності худі; це фірмовий одяг, не технічний компонент автомобіля.', benefitEn: 'Burger Motorsports apparel features JB4 branding and Burger Town artwork for automotive enthusiasts. The page describes T-shirts and a mid-weight hoodie; this is branded clothing, not a vehicle component.',
    detailsUa: 'Оберіть Style: JB4 Juice Box T-Shirt, Burger Town Hoodie або Burger Town T-Shirt, потім Size: Small, Medium, Large, XL чи XXL. Для худі джерело вказує суміш 80% cotton / 20% polyester, колір Charcoal Grey та вагу тканини 8.05 oz; характеристики футболок можуть відрізнятися.', detailsEn: 'Choose Style first: JB4 Juice Box T-Shirt, Burger Town Hoodie, or Burger Town T-Shirt; then select Small, Medium, Large, XL, or XXL. The source lists the hoodie as 80% cotton/20% polyester, charcoal grey, and 8.05 oz fabric; T-shirt specifications may differ.',
    fitUa: 'Перед замовленням звірте розмір із таблицею постачальника. Зображення дизайну, фасон і матеріал залежать від обраного стилю.', fitEn: 'Check the supplier size chart before ordering. Artwork, cut, and material depend on the selected style.'
  },
  'fuel-it-keychain': {
    titleUa: 'Fuel-It! Flight Keychain — брелок або комплект із двох', titleEn: 'Fuel-It! Flight Keychain — Single or Two-Pack',
    shortUa: 'Гнучкий 5-дюймовий Fuel-It! брелок із вишитим логотипом з обох боків; оберіть один або два.', shortEn: 'Flexible 5-inch Fuel-It! keychain with double-sided embroidered logo; choose one or two.',
    benefitUa: 'Фірмовий Fuel-It! Flight keychain тримає ключі та позначає автомобільне паливне обладнання бренду. Гнучкий матеріал зручний для повсякденного використання, логотип вишитий з обох боків.', benefitEn: 'The branded Fuel-It! Flight keychain keeps keys together and shows the Fuel-It! name. Its flexible material is suited to everyday use and the logo is embroidered on both sides.',
    detailsUa: 'Оберіть Single або 2 Pack. Один брелок має приблизно 5″ завдовжки та 1″ завширшки. Варіант із двох містить два брелоки; колір у селекторі не змінюється.', detailsEn: 'Choose Single or 2 Pack. Each keychain measures about 5 inches long by 1 inch wide. The two-pack contains two keychains; color is not selected in this listing.',
    fitUa: 'Універсальний аксесуар для ключів. Це не пристрій для вимірювання етанолу й не частина Fuel-It! ECA kit.', fitEn: 'A general key accessory. It is not an ethanol measurement device or part of a Fuel-It! ECA kit.'
  },
  'burger-motorsports-jb4-banner': {
    titleUa: 'Burger Motorsports / JB4 — рекламний банер 6 × 2 фути', titleEn: 'Burger Motorsports / JB4 Promotional Banner — 6 × 2 ft',
    shortUa: 'UV- і погодостійкий банер 6 × 2 фути з металевими люверсами для гаража, майстерні чи заходу.', shortEn: 'UV- and weather-resistant 6 × 2 ft banner with metal grommets for a shop, garage, or event.',
    benefitUa: 'Великий рекламний банер Burger Motorsports / JB4 допомагає оформити майстерню, гараж, виставку або автомобільний захід фірмовою графікою. UV- та погодостійке виконання допускає внутрішнє й зовнішнє використання.', benefitEn: 'The large Burger Motorsports / JB4 banner displays brand graphics in a shop, garage, trade show, or car event. UV- and weather-resistant construction supports indoor or outdoor use.',
    detailsUa: 'Розмір близько 6 футів завдовжки × 2 фути заввишки. По периметру є металеві люверси для кріплення; троси, стійки та монтажні гачки не зазначені як комплектні.', detailsEn: 'The banner measures approximately 6 feet long by 2 feet tall and has metal grommets for hanging. Cables, stands, and mounting hooks are not listed as included.',
    fitUa: 'Універсальний промобанер для приміщення або вулиці. Перевірте доступне місце та спосіб кріплення перед замовленням.', fitEn: 'A general indoor/outdoor promotional banner. Check available space and mounting method before ordering.'
  },
  'high-flow-intake-tube-upgrade': {
    titleUa: 'High-Flow Intake Tube Upgrade — службова опція конфігуратора', titleEn: 'High-Flow Intake Tube Upgrade — Configurator Option Record',
    shortUa: 'Службова позиція для додаткової опції intake; не є окремою товарною карткою для замовлення.', shortEn: 'Internal record for an intake add-on; not a standalone product listing.',
    benefitUa: 'У Burger ця позиція прихована та використовується застосунком Product Options для вибору додаткової high-flow intake tube в іншому товарі. Окремих характеристик, застосування або комплектності для самостійного продажу сторінка не містить.', benefitEn: 'Burger marks this record as hidden and uses it in the Product Options app for an intake-tube add-on on another product. The source page does not provide standalone specifications, fitment, or package contents.',
    detailsUa: 'Не додавати у кошик як самостійний фізичний товар. Ціну, вагу й сумісність потрібно брати з основної товарної картки та фактично обраної опції.', detailsEn: 'Do not order as a standalone physical product. Price, weight, and fitment must come from the parent product and the selected option.',
    fitUa: 'Використовувати лише як внутрішній запис опції Product Options, пов’язаний із батьківським intake товаром.', fitEn: 'Use only as an internal Product Options record linked to its parent intake product.', internalOptionOnly: true
  },
  'jb4-magnetic-vent-cell-phone-mount': {
    titleUa: 'JB4 Magnetic Air-Vent Phone Mount — логотип Red або White', titleEn: 'JB4 Magnetic Air-Vent Phone Mount — Red or White Logo',
    shortUa: 'Магнітний тримач телефона для вентиляційної решітки з обертом 360°; виберіть колір JB4 логотипа.', shortEn: 'Magnetic phone holder for an air vent with 360° rotation; choose the JB4 logo color.',
    benefitUa: 'Тримач дає змогу закріпити телефон або Dragy на вентиляційній решітці в полі зору. Чотири вбудовані рідкоземельні магніти й регулювання на 360° допомагають повернути екран для навігації чи JB4 Mobile.', benefitEn: 'The holder attaches to an air vent and keeps a phone or Dragy in view. Four built-in rare-earth magnets and 360-degree adjustment let you orient the display for navigation or JB4 Mobile.',
    detailsUa: 'Оберіть Red JB4 logo або White JB4 logo. За описом, у комплекті два тонкі металеві диски з логотипом; конструкція кріпиться на горизонтальні або вертикальні ламелі, але не на круглі дефлектори. Перед монтажем перевірте форму решітки та сумісність чохла.', detailsEn: 'Choose a Red or White JB4 logo. Burger lists two thin metallic logo plates. The mount fits horizontal or vertical vent slats, but not round vents. Check vent style and case compatibility before installation.',
    fitUa: 'Підходить для більшості телефонів із металевою пластиною або сумісним чохлом. Телефон і Dragy у комплект не входять.', fitEn: 'Fits many phones with a metal plate or compatible case. Phone and Dragy device are not included.'
  },
  'fsb-for-jb4-control': {
    titleUa: 'FSB for JB4 Control — службовий запис опції', titleEn: 'FSB for JB4 Control — Internal Option Record',
    shortUa: 'Прихована службова позиція Burger для конфігуратора JB4; не замовляється окремо без основного товару.', shortEn: 'Hidden Burger record for a JB4 configurator; not ordered separately from a parent product.',
    benefitUa: 'Джерело позначає цю картку як прихований товар для застосунку Product Options. Назва вказує на FSB для керування JB4, але окрема картка не містить технічного опису чи переліку сумісних автомобілів.', benefitEn: 'The supplier marks this record as a hidden Product Options item. Its name references an FSB for JB4 control, but the standalone page contains no technical specification or vehicle fitment.',
    detailsUa: 'Використовуйте тільки як внутрішній add-on до основної сумісної JB4 конфігурації. Не оцінюйте як окремий контролер без підтвердження потрібної версії та комплектності у батьківській картці.', detailsEn: 'Use only as an internal add-on to a compatible parent JB4 configuration. Do not treat it as a standalone controller without confirming the required version and package in the parent listing.',
    fitUa: 'Внутрішня опція Product Options; не має відображатися в загальному автомобільному пошуку як самостійна позиція.', fitEn: 'Internal Product Options record; it should not appear as a standalone item in general vehicle search.', internalOptionOnly: true
  },
  'official-jb4-tuned-flight-keychain': {
    titleUa: 'JB4 Tuned Flight Keychain — один брелок або 2-Pack', titleEn: 'JB4 Tuned Flight Keychain — Single or Two-Pack',
    shortUa: 'Гнучкий 5 × 1″ брелок із двосторонньою вишивкою JB4 Tuned; оберіть один або два.', shortEn: 'Flexible 5 × 1 in JB4 Tuned keychain with double-sided embroidery; choose one or two.',
    benefitUa: 'Офіційний JB4 Tuned Flight keychain утримує ключі та додає брендову деталь для прихильника JB4. Гнучка основа та вишитий з обох боків логотип розраховані на щоденне носіння.', benefitEn: 'The official JB4 Tuned Flight keychain keeps keys together and adds a branded detail for JB4 enthusiasts. A flexible body and double-sided embroidery suit everyday carry.',
    detailsUa: 'Оберіть Single або 2 Pack. Один брелок приблизно 5″ × 1″; за описом Burger доступні кольори Blue, Red, Black, Pink і Green залежно від партії. У selector опції кольору немає, тому перед відправленням колір слід підтвердити.', detailsEn: 'Choose Single or 2 Pack. Each keychain is about 5 × 1 inches. Burger lists Blue, Red, Black, Pink, and Green subject to stock. Color is not exposed as a selector here, so confirm before dispatch.',
    fitUa: 'Універсальний аксесуар для ключів; не є електронікою JB4 або деталлю автомобіля.', fitEn: 'A general key accessory; not JB4 electronics or a vehicle part.'
  },
  'jb4-flexfit-hat': {
    titleUa: 'Офіційна чорна JB4 Flexfit Hat — логотип Red / White / Black / Blue', titleEn: 'Official Black JB4 Flexfit Hat — Red / White / Black / Blue Logo',
    shortUa: 'Чорна Flexfit кепка з вишитим JB4 логотипом унизу спереду; оберіть колір логотипа.', shortEn: 'Black Flexfit hat with an embroidered JB4 logo low on the front; choose logo color.',
    benefitUa: 'Офіційна кепка JB4 × Flexfit додає стриману фірмову графіку на чорній snapback-моделі. Логотип вишитий на нижній передній частині кепки.', benefitEn: 'The official JB4 × Flexfit cap adds understated branding to a black snapback hat. The logo is embroidered on the lower front of the crown.',
    detailsUa: 'Оберіть вишивку White, Black, Red або Blue. Це вибір кольору логотипа, а не кольору кепки. Перед замовленням перевірте посадку Flexfit і наявність потрібного кольору.', detailsEn: 'Choose White, Black, Red, or Blue embroidery. The selector changes logo color, not hat color. Check Flexfit sizing and color availability before ordering.',
    fitUa: 'Універсальний аксесуар одягу; розмір і фактичний крій визначаються моделлю кепки постачальника.', fitEn: 'A general apparel accessory; fit and cut follow the supplier hat model.'
  },
  'fuel-it-logo-sticker-sheet-two-pack': {
    titleUa: 'Fuel-It! Vinyl Logo Stickers — аркуші, комплект 2-Pack', titleEn: 'Fuel-It! Vinyl Logo Stickers — Two-Sheet Pack',
    shortUa: 'Водостійкі Fuel-It! вінілові наклейки; оберіть зелений, срібний, чорний, червоний, білий або синій.', shortEn: 'Waterproof Fuel-It! vinyl stickers; choose green, silver, black, red, white, or blue.',
    benefitUa: 'Комплект Fuel-It! decals дає змогу брендувати автомобіль, інструментальний ящик, ноутбук чи іншу чисту гладку поверхню. Наклейки водостійкі й розраховані на просте нанесення через applicator tape.', benefitEn: 'The Fuel-It! decal pack can brand a vehicle, toolbox, laptop, or other clean smooth surface. The vinyl stickers are described as waterproof and use application tape for straightforward placement.',
    detailsUa: 'У цій позиції два аркуші; оберіть колір: Fuel-It! Green, Metallic Silver, Jet Black, Red, Alpine White або Blue. Для нанесення очистіть поверхню, притисніть плівку до transfer tape, зніміть підкладку, розгладьте наклейку й обережно зніміть плівку.', detailsEn: 'This listing is a two-sheet pack. Choose Fuel-It! Green, Metallic Silver, Jet Black, Red, Alpine White, or Blue. Clean the surface, press the decal onto the transfer tape, remove the backing, smooth it down, then peel the application film carefully.',
    fitUa: 'Для чистих гладких поверхонь автомобіля, інструментів або електроніки. Не наносіть на брудну, вологу чи текстуровану поверхню.', fitEn: 'For clean, smooth vehicle, tool, or electronics surfaces. Do not apply to dirty, wet, or textured surfaces.'
  },
  'jb4-car-emblem': {
    titleUa: 'Офіційна емблема JB4 для автомобіля — 2.25 × 1.25″', titleEn: 'Official JB4 Car Emblem — 2.25 × 1.25 in',
    shortUa: 'Самоклейна емблема JB4 приблизно 2.25 × 1.25″ для рівної чистої панелі кузова.', shortEn: 'Self-adhesive JB4 emblem, about 2.25 × 1.25 in, for a clean flat body panel.',
    benefitUa: 'Офіційна JB4 logo badge дає змогу додати емблему на кузов автомобіля. Літери J і B4 переносяться разом на прозорій transfer film, щоб зберегти правильне вирівнювання.', benefitEn: 'The official JB4 logo badge adds a branded emblem to a vehicle. The J and B4 transfer together on clear application film to help maintain alignment.',
    detailsUa: 'Розмір близько 2.25″ × 1.25″. Монтуйте лише на рівну, очищену поверхню: вирівняйте малярною стрічкою, зніміть білу підкладку, легко притисніть, потім утримуйте близько 10 секунд і зніміть прозору плівку. Емблему можна фарбувати окремо.', detailsEn: 'The emblem measures about 2.25 × 1.25 inches. Apply it to a clean flat surface: align with masking tape, remove the white backing, press lightly, hold for about 10 seconds, and remove the clear film. The emblem can be painted separately.',
    fitUa: 'Універсальна емблема для рівної ділянки кузова. Не клеїти на криволінійні або неочищені поверхні.', fitEn: 'A universal badge for a flat body panel. Do not apply to curved or unprepared surfaces.'
  },
  'burger-motorsports-jb4-stickers': {
    titleUa: 'Burger Motorsports / JB4 Stickers — наклейки, декалі та набори', titleEn: 'Burger Motorsports / JB4 Stickers — Decals and Logo Packs',
    shortUa: 'Оберіть набір BMS/JB4, окрему JB4 декаль або лобове маркування з доступних кольорів.', shortEn: 'Choose a BMS/JB4 sticker pack, individual JB4 decal, or windshield graphic in listed colors.',
    benefitUa: 'Лінійка вінілових декалей Burger Motorsports і JB4 призначена для автомобіля, toolbox, вікна, ноутбука чи іншої гладкої поверхні. Водостійка основа та transfer tape спрощують нанесення; варіант у меню визначає конкретний дизайн і колір.', benefitEn: 'Burger Motorsports and JB4 vinyl decals are made for vehicles, toolboxes, windows, laptops, and other smooth surfaces. Waterproof material and transfer tape support application; the selected option determines design and color.',
    detailsUa: 'У меню є набори BMS/JB4 3-in-1, окремі JB4 або JB4 Tuned stickers і великі наклейки на лобове скло. Оберіть повний текст варіанта з потрібним дизайном та кольором. JB4 Tuned варіант доступний лише Alpine White; його розмір на сторінці — приблизно 3.5″ × 1.1″.', detailsEn: 'Options include BMS/JB4 3-in-1 packs, individual JB4 or JB4 Tuned stickers, and large windshield decals. Select the full option matching the design and color. The JB4 Tuned decal is listed only in Alpine White and measures about 3.5 × 1.1 inches.',
    fitUa: 'Для гладких, чистих поверхонь. Перед оплатою звірте вибраний тип наклейки, колір і кількість; це декалі, не автомобільні номерні знаки.', fitEn: 'For clean, smooth surfaces. Confirm sticker style, color, and quantity before checkout; these are decals, not license plates.'
  },
  'performance-air-filter-cleaning-oil-kit-1': {
    titleUa: 'S&B / BMS Performance Air Filter Cleaning Kit — Red або Blue Oil', titleEn: 'S&B / BMS Performance Air Filter Cleaning Kit — Red or Blue Oil',
    shortUa: 'Набір очищення й повторного просочення оливлених фільтрів; оберіть червону або синю оливу.', shortEn: 'Cleaning and re-oiling kit for oiled filters; choose red or blue filter oil.',
    benefitUa: 'Набір допомагає обслуговувати сумісний багаторазовий оливлений повітряний фільтр: очищувач змиває бруд, аплікатор наносить нову оливу. Регулярне обслуговування підтримує роботу фільтра без його заміни після кожного сервісного інтервалу.', benefitEn: 'The kit services a compatible reusable oiled air filter: cleaner removes dirt and the applicator applies fresh filter oil. Regular service maintains the filter without replacing it at every interval.',
    detailsUa: 'Оберіть Red Oil або Blue Oil за кольором фільтра. Burger оцінює комплект як достатній приблизно на 3–4 очищення і радить сервіс близько кожних 20 000 миль для оливлених фільтрів. Dry filters не потребують оливи; не застосовуйте до них re-oiling step.', detailsEn: 'Choose Red Oil or Blue Oil to match the filter color. Burger estimates three to four cleanings per kit and suggests servicing oiled filters about every 20,000 miles. Dry filters do not require oil; do not apply the re-oiling step to them.',
    fitUa: 'Для сумісних reusable oiled-cotton air filters, зокрема BMS/S&B за інструкцією виробника. Переконайтеся, що фільтр не є dry-type.', fitEn: 'For compatible reusable oiled-cotton air filters, including BMS/S&B when specified by the manufacturer. Confirm that the filter is not a dry type.'
  },
  'jb4-cell-phone-holder': {
    titleUa: 'JB4 Magnetic Phone Mount — клейке кріплення на панель', titleEn: 'JB4 Magnetic Phone Mount — Adhesive Dash Base',
    shortUa: 'Магнітний JB4 тримач телефона з регульованим кутом і металевою пластиною на клейкій основі.', shortEn: 'Magnetic JB4 phone holder with adjustable angle and an adhesive metal phone plate.',
    benefitUa: 'Тримач закріплює телефон на панелі в полі зору для використання JB4 Mobile. Регульований кут допомагає спрямувати екран на водія, а магнітна система утримує телефон через тонку металеву пластину.', benefitEn: 'The mount positions a phone on the dash for viewing JB4 Mobile. Its adjustable angle helps point the display toward the driver, and a magnetic head holds the phone through a thin metal plate.',
    detailsUa: 'У комплекті металева пластина для телефона або чохла та чорний/сірий JB4 logo; сторінка також згадує червоний overlay sticker. Монтуйте тільки на гладку чисту поверхню, знежирену спиртом, і притискайте основу близько 30 секунд. Burger вказує новішу MagSafe модель як наступника цього товару.', detailsEn: 'The package includes a metal plate for the phone or case and a black/gray JB4 logo; the page also mentions a red overlay sticker. Install only on a clean smooth surface, wiped with alcohol, and press the base for about 30 seconds. Burger identifies a newer MagSafe model as its successor.',
    fitUa: 'Для телефона з комплектною металевою пластиною та рівної панелі. Не монтуйте на текстурований пластик; перед оплатою перевірте доступність legacy-моделі.', fitEn: 'For a phone using the included metal plate and a flat dash surface. Do not install on textured plastic; confirm availability of this legacy model before ordering.'
  },
  'short-throw-clutch-stop-for-nissan-infiniti': {
    titleUa: 'BMS Clutch Stop для Nissan / Infiniti — лише механічна КПП', titleEn: 'BMS Clutch Stop for Nissan / Infiniti — Manual Transmission Only',
    shortUa: 'Змінний clutch stop прибирає зайвий хід педалі зчеплення; сумісність тільки з переліченими МКПП.', shortEn: 'Replacement clutch stop removes excess pedal travel; fitment is limited to listed manual cars.',
    benefitUa: 'Змінний clutch stop BMS зменшує мертвий хід педалі зчеплення біля підлоги, тому точка повного натискання стає чіткішою. Це може зробити перемикання швидшим і послідовнішим для водія; вузол повністю зворотний і не потребує іншого тюнінгу.', benefitEn: 'The BMS replacement clutch stop reduces unused pedal travel near the floor, making the fully depressed point more defined. This may help the driver shift more quickly and consistently; installation is reversible and requires no other tune.',
    detailsUa: 'Деталь защіпається на місце заводського stop buffer і замінює OE Nissan 46543-Q0400. Монтаж або демонтаж займає кілька хвилин. Перед використанням перевірте, що зчеплення повністю роз’єднується й педаль повертається без перешкод.', detailsEn: 'The part snaps in place of the factory stop buffer and replaces OE Nissan 46543-Q0400. Installation or removal takes minutes. Confirm full clutch disengagement and unobstructed pedal return after fitting.',
    fitUa: 'Тільки механічна трансмісія: Nissan 300ZX 1990–1996, 350Z 2003–2008, 370Z 2009+, Z 2023+; Infiniti G35/G37 та FX у роках зі сторінки Burger. Не для автомата.', fitEn: 'Manual transmission only: Nissan 300ZX 1990–1996, 350Z 2003–2008, 370Z 2009+, 2023+ Z, and Burger-listed Infiniti G35/G37/FX years. Not for automatic transmissions.'
  },
  'short-throw-clutch-stop-for-bmw-mini-supra-volkswagen': {
    titleUa: 'Регульований BMS Clutch Stop для BMW / MINI / Supra / VW — МКПП', titleEn: 'Adjustable BMS Clutch Stop for BMW / MINI / Supra / VW — Manual',
    shortUa: 'Регульований упор із гумовими шайбами прибирає dead travel педалі; тільки для механічної трансмісії.', shortEn: 'Adjustable stop with rubberized shims removes pedal dead travel; manual transmission only.',
    benefitUa: 'BMS adjustable clutch stop задає чіткішу кінцеву точку педалі зчеплення, прибираючи зайвий хід до підлоги. Гумові регулювальні шайби дають змогу налаштувати висоту без брязкоту металевих шайб; результат допомагає водієві робити повторювані перемикання.', benefitEn: 'The BMS adjustable clutch stop creates a clearer clutch-pedal endpoint by removing excess travel to the floor. Rubberized shims adjust stop height without rattling metal washers, supporting repeatable shifts.',
    detailsUa: 'Упор встановлюється у штатне місце, повністю знімається й не потребує свердління. Підбирайте товщину шайб так, щоб зчеплення повністю вимикалося, а педаль поверталася без перешкод. Після монтажу перевірте роботу авто на місці.', detailsEn: 'The stop fits the factory location, is removable, and requires no drilling. Adjust shim thickness so the clutch fully disengages and the pedal returns freely. Test pedal operation before driving.',
    fitUa: 'Для ручних BMW 2006+, MINI, Toyota Supra та VW у застосуваннях Burger; окремі старі BMW можуть підійти, але потребують перевірки. Не для автоматичної трансмісії.', fitEn: 'For Burger-listed manual-transmission BMW from 2006+, MINI, Toyota Supra, and VW; some older BMWs may fit but require verification. Not for automatic transmissions.'
  },
  'bms-short-throw-clutch-stop-1982-2005': {
    titleUa: 'BMS Clutch Stop для BMW E30 / E36 / E46 / Z3 / Z4 1982–2005', titleEn: 'BMS Clutch Stop for 1982–2005 BMW E30 / E36 / E46 / Z3 / Z4',
    shortUa: 'Змінний clutch stop прибирає надлишковий хід педалі на класичних BMW з механічною коробкою.', shortEn: 'Replacement clutch stop reduces excess pedal travel on classic manual BMW models.',
    benefitUa: 'BMS clutch stop задає чітку кінцеву точку натискання педалі та прибирає невикористаний хід до підлоги. Це може зробити роботу зчеплення більш послідовною й швидшою для водія без змін трансмісії чи двигуна.', benefitEn: 'The BMS clutch stop creates a defined pedal endpoint and removes unused travel to the floor. This can make clutch operation more consistent for the driver without changing the transmission or engine.',
    detailsUa: 'Деталь вкручується на місце штатного упора та повністю знімається за потреби. Після монтажу перевірте, що зчеплення повністю роз’єднується на першому натисканні; не використовуйте авто, якщо педаль або зчеплення працюють некоректно.', detailsEn: 'The part screws into the factory stop location and can be removed. After installation, confirm the clutch fully disengages at the first press; do not operate the vehicle if pedal or clutch function is affected.',
    fitUa: 'BMW E30, E36, E46 включно з відповідними M3, а також Z3 і Z4 у застосуваннях Burger 1982–2005. Тільки механічна трансмісія.', fitEn: 'Burger-listed 1982–2005 BMW E30, E36, E46 including matching M3 applications, plus Z3 and Z4. Manual transmission only.'
  },
  'window-mount-for-dragy': {
    titleUa: 'Dragy Window Mount — магнітне кріплення на скло', titleEn: 'Dragy Window Mount — Magnetic Glass Holder',
    shortUa: 'Магнітна підставка кріпить Dragy на склі для стабільного огляду супутників; пристрій продається окремо.', shortEn: 'Magnetic glass mount positions Dragy for clear satellite reception; device sold separately.',
    benefitUa: 'Window Mount утримує сумісний Dragy на вікні автомобіля, допомагаючи розмістити GPS-пристрій у стабільному місці для прийому сигналу. Магнітне кріплення дає змогу швидко зняти пристрій для заряджання або зберігання.', benefitEn: 'The window mount holds a compatible Dragy on the vehicle glass, positioning the GPS device consistently for reception. Magnetic retention lets you remove the unit for charging or storage.',
    detailsUa: 'У комплекті тільки кріплення; Dragy GPS device не входить. Очистіть скло перед монтажем і розмістіть пристрій за інструкцією Dragy. Опційна акційна знижка при спільній купівлі тут не включена в опис або розрахунок ціни.', detailsEn: 'The package is the mount only; the Dragy GPS device is not included. Clean the glass before fitting and position the unit according to Dragy instructions. A source bundle discount is not included in this listing copy or price calculation.',
    fitUa: 'Для сумісних пристроїв Dragy, що утримуються магнітом. Перед замовленням підтвердьте модель пристрою та площу скла.', fitEn: 'For compatible magnet-retained Dragy devices. Confirm device model and glass mounting area before ordering.'
  },
  'billet-aluminum-rear-license-plate-bracket-upgrade-2020-2026-toyota-supra-mk5': {
    titleUa: 'BMS Billet Rear License Plate Bracket для Toyota GR Supra Mk5 2020–2026', titleEn: 'BMS Billet Rear License Plate Bracket for 2020–2026 Toyota GR Supra Mk5',
    shortUa: 'Чорний CNC-алюмінієвий задній кронштейн замінює пластиковий Supra bracket і захищає лак від гвинтів.', shortEn: 'Black CNC aluminum rear bracket replaces the plastic Supra holder and cushions screws from paint.',
    benefitUa: 'Кронштейн BMS замінює штатний пластиковий задній тримач номерного знака Toyota Supra металевою деталлю з billet-алюмінію. Чотири силіконові pads притискаються до задньої панелі, зменшуючи деренчання та ізолюючи гвинти від лакофарбового покриття.', benefitEn: 'The BMS bracket replaces the factory plastic rear license-plate holder on the Toyota Supra with a billet-aluminum part. Four silicone pads cushion the panel, reduce rattles, and keep screws from contacting the paint.',
    detailsUa: 'CNC-оброблений кронштейн анодований чорним і має 4 molded silicone pads. У джерелі зазначені захисні hex security screws. Перед монтажем використовуйте штатні точки кріплення й перевірте відповідність місцевого номерного знака.', detailsEn: 'The CNC-machined bracket is black anodized and uses four molded silicone pads. The source lists security hex screws. Use the factory mounting points and confirm plate dimensions for your market.',
    fitUa: 'Для Toyota GR Supra Mk5 2020–2026. Не підходить автоматично до інших поколінь Supra або стандартів номерних знаків інших ринків.', fitEn: 'For 2020–2026 Toyota GR Supra Mk5. Fitment for other Supra generations or license-plate standards is not implied.'
  },
  'billet-aluminum-bmw-license-plate-bracket-upgrade': {
    titleUa: 'BMS Billet Rear License Plate Bracket для BMW / MINI', titleEn: 'BMS Billet Rear License Plate Bracket for BMW / MINI',
    shortUa: 'Чорний CNC billet bracket замінює пластикове кріплення багажника BMW/MINI та пом’якшує закривання.', shortEn: 'Black CNC billet bracket replaces BMW/MINI plastic trunk holder and cushions the closing sound.',
    benefitUa: 'Кронштейн BMS замінює задній пластиковий holder номерного знака на BMW або MINI точнішою металевою деталлю. Чотири силіконові pads ізолюють гвинти від кузова, зменшують деренчання та створюють м’якший контакт кришки багажника.', benefitEn: 'The BMS bracket replaces the rear plastic license-plate holder on BMW or MINI with a precision metal part. Four silicone pads isolate screws from the body, reduce rattles, and soften contact at the trunk lid.',
    detailsUa: 'Кронштейн оброблений на CNC з billet-алюмінію та має чорне анодування. Сторінка вказує 4 силіконові pads; сумісність кріпильних гвинтів залежить від кузова. Перед купівлею звірте задню панель і форму заводського держателя.', detailsEn: 'The bracket is CNC-machined billet aluminum with a black anodized finish. The page lists four silicone pads; screw fitment varies by chassis. Check rear-panel and factory-holder shape before ordering.',
    fitUa: 'BMW 1999+ і MINI 2000+ за списком Burger; модельні виключення можуть залежати від кришки багажника. Звірте OEM bracket і отвори.', fitEn: 'For Burger-listed BMW 1999+ and MINI 2000+; model exclusions may depend on trunk-lid design. Verify the OE bracket and mounting holes.'
  },
  'license-plate-screws-for-bmw-mini-pair': {
    titleUa: 'License Plate Screws для BMW / MINI — пара, дрібна або крупна різьба', titleEn: 'BMW / MINI License Plate Screws — Pair, Fine or Coarse Thread',
    shortUa: 'Пара 8 мм гвинтів для номерного знака: black/chrome fine thread або black coarse thread.', shortEn: 'Pair of 8 mm plate screws: black/chrome fine thread or black coarse thread.',
    benefitUa: 'Змінні гвинти BMW/MINI кріплять номерний знак штатної довжини приблизно 8 мм. Доступ до дрібної й крупної різьби дає змогу підібрати гвинт до конкретного кузовного різьблення, не пошкоджуючи різьбу під час монтажу.', benefitEn: 'Replacement BMW/MINI screws secure a license plate with standard 8 mm screw length. Fine- and coarse-thread choices help match the vehicle body thread and avoid cross-threading.',
    detailsUa: 'У комплекті два гвинти. Оберіть Black Fine Thread, Chrome Fine Thread або Black Coarse Thread. Перевірте старий гвинт перед замовленням: передня та задня панелі одного авто можуть мати різну різьбу. Не вкручуйте гвинт із силою, якщо він не заходить вільно.', detailsEn: 'The package contains two screws. Choose Black Fine Thread, Chrome Fine Thread, or Black Coarse Thread. Check the original screw before ordering; front and rear plate mounts can use different threads on the same car. Do not force a screw that does not thread freely.',
    fitUa: 'Для BMW/MINI, де використовується відповідна різьба та 8 мм довжина. Різьбу слід визначити фізично, не лише за маркою авто.', fitEn: 'For BMW/MINI applications using the matching thread and 8 mm length. Identify the thread physically rather than by make alone.'
  },
  'front-license-plate-holder-tow-hook': {
    titleUa: 'Phoenix Racing No-Drill Tow-Hook Front Plate Holder — оберіть авто', titleEn: 'Phoenix Racing No-Drill Tow-Hook Front Plate Holder — Select Car',
    shortUa: 'Знімний фронтальний номерний держатель кріпиться у tow hook без свердління бампера; оберіть модель авто.', shortEn: 'Removable front plate holder mounts at the tow hook without drilling; select your vehicle.',
    benefitUa: 'Phoenix Racing holder переносить передній номерний знак на tow-hook точку, щоб не свердлити бампер і не закривати центральні решітки, інтеркулер або повітрозабірники. Кріплення можна зняти, коли передній номер не потрібен.', benefitEn: 'The Phoenix Racing holder relocates the front plate to the tow-hook point, avoiding bumper drilling and keeping central grilles, intercoolers, or intakes clearer. The mount can be removed when the front plate is not needed.',
    detailsUa: 'Оберіть кузовну версію: BMW F-Chassis, BMW E-Chassis, Infiniti Q50/Q60, Kia Stinger або Subaru. Різьба tow hook і адаптер залежать від автомобіля. Перед монтажем перевірте доступ до точки буксирування, напрямок різьби та габарит номерного знака.', detailsEn: 'Choose the chassis-specific version: BMW F-Chassis, BMW E-Chassis, Infiniti Q50/Q60, Kia Stinger, or Subaru. Tow-hook thread and adapter depend on the vehicle. Check access to the tow point, thread direction, and plate dimensions before installation.',
    fitUa: 'Лише для обраної версії зі списку та сумісної tow-hook різьби. Варіант Kia Stinger позначений у джерелі як відсутній на складі; наявність потрібно підтвердити.', fitEn: 'Only for the selected application with matching tow-hook thread. Burger marks the Kia Stinger version out of stock; verify availability.'
  },
  'license-plate-frame-jb4-tuned': {
    titleUa: 'Офіційні JB4 License Plate Accessories — рамка або металева вставка', titleEn: 'Official JB4 License Plate Accessories — Frame or Metal Insert',
    shortUa: 'Оберіть одну 3D JB4 Tuned рамку, набір із двох рамок або металеву JB4 вставку.', shortEn: 'Choose one 3D JB4 Tuned frame, a two-frame pack, or a metal JB4 plate insert.',
    benefitUa: 'Фірмові JB4 номерні аксесуари додають брендинг автомобілю без змін кузова. Рамка утримує край стандартного номерного знака, а металева 3D вставка кріпиться як окремий декоративний елемент.', benefitEn: 'JB4-branded plate accessories personalize the vehicle without modifying bodywork. The frame surrounds a standard plate, while the 3D metal insert attaches as a separate decorative piece.',
    detailsUa: 'Оберіть одну 3D JB4 Tuned frame, 2-Pack frame або Metal 3D JB4 License Plate Insert. Кожний варіант продається окремо. Рамка використовує штатні гвинти, але має задні tabs, у які вставляється номер; перевірте, що це сумісно з формою вашого знака.', detailsEn: 'Choose one 3D JB4 Tuned frame, a two-pack, or the Metal 3D JB4 License Plate Insert. Each option is sold separately. The frame uses existing fasteners and has rear tabs that the plate slides into; check compatibility with your plate shape.',
    fitUa: 'Для стандартних номерних знаків і штатних точок кріплення відповідного авто. Регіональні розміри номерів можуть відрізнятися.', fitEn: 'For standard plates and the vehicle’s factory mounting points. Regional plate dimensions may vary.'
  },
  'stinger-g70-3-3t-tcu-map-digital-download': {
    digitalProduct: true,
    titleUa: 'BMS ECU / TCU Maps для Kia Stinger / Genesis G70 3.3T — EK1', titleEn: 'BMS ECU / TCU Maps for Kia Stinger / Genesis G70 3.3T — EK1',
    shortUa: 'Оберіть ECU або TCU map для EK1 і конкретну конфігурацію; лише моделі 2018–2023, цифровий товар.', shortEn: 'Select an EK1 ECU or TCU map for your setup; 2018–2023 models only, digital product.',
    benefitUa: 'Це цифрове калібрування BMS ECU або TCU для завантаження через EK1 flashing system. ECU maps змінюють цільові параметри суміші й керування двигуном, а TCU map коригує логіку коробки; конкретний ефект залежить від обраної карти, пального, обладнання й стану авто.', benefitEn: 'This is a digital BMS ECU or TCU calibration for use with the EK1 flashing system. ECU maps adjust engine targets and control; the TCU map changes transmission behavior. Results depend on map choice, fuel, hardware, and vehicle condition.',
    detailsUa: 'Оберіть одну карту: ECU RACE, варіант без burble, E85 IGN19, ECU RACE IGN19 або BMS TCU. Потрібен EK1 flasher і сумісна calibration ID. Burger переніс карти до EK1 Map Store; якщо потрібної калібровки немає, постачальник просить надати calibration ID та назву карти.', detailsEn: 'Select one map: ECU RACE, no-burble version, E85 IGN19, ECU RACE IGN19, or BMS TCU. An EK1 flasher and compatible calibration ID are required. Burger moved maps to the EK1 Map Store; if a calibration is missing, the supplier requests the calibration ID and map name.',
    fitUa: 'Burger пропонує карти лише для Kia Stinger / Genesis G70 2018–2023; 2024+ не підтримуються на сторінці. Це цифрове завантаження, не фізичний пристрій EK1 і не JB4 tuner.', fitEn: 'Burger lists maps only for 2018–2023 Kia Stinger / Genesis G70; 2024+ is not supported on this page. Digital download only; EK1 device and JB4 tuner are not included.'
  },
  'replacement-o-ring-for-b58-s58-s68-bmw-billet-oil-filler-breather-cap': {
    titleUa: 'Replacement O-Ring для BMW B58 / S58 / S68 Billet Breather Cap', titleEn: 'Replacement O-Ring for BMW B58 / S58 / S68 Billet Breather Cap',
    shortUa: 'Змінне ущільнення для BMS billet oil-filler breather cap; саму кришку потрібно замовляти окремо.', shortEn: 'Replacement seal for the BMS billet oil-filler breather cap; cap sold separately.',
    benefitUa: 'Це змінне O-ring/gasket для BMS billet oil filler breather cap на сумісному двигуні BMW. Заміна пошкодженого чи зношеного ущільнення допомагає відновити герметичність кришки.', benefitEn: 'This is a replacement O-ring/gasket for the BMS billet oil-filler breather cap on compatible BMW engines. Replacing a worn or damaged seal helps restore the cap seal.',
    detailsUa: 'У позиції лише O-ring/gasket. Billet cap, кріплення та інші деталі продаються окремо. Перед покупкою звірте форму канавки та покоління кришки, щоб ущільнення відповідало вашому B58/S58/S68 комплекту.', detailsEn: 'This listing is for the O-ring/gasket only. The billet cap, hardware, and other parts are sold separately. Match seal profile and cap generation to your B58/S58/S68 assembly before ordering.',
    fitUa: 'Для BMS billet oil filler breather cap на BMW B58, S58 або S68, якщо профіль ущільнення відповідає вашій кришці. Це не паливний або турбопровідний O-ring.', fitEn: 'For the BMS billet oil-filler breather cap on BMW B58, S58, or S68 when the seal profile matches your cap. Not a fuel-system or turbo-line O-ring.'
  },
  'jb4-obdii-replacement': {
    titleUa: 'Replacement OBDII Cable для JB4 — V1 / V2, довжина та роз’єм', titleEn: 'JB4 Replacement OBDII Cable — V1 / V2, Length and Connector',
    shortUa: 'Оберіть 4-position V1 або 2-position V2 кабель, довжину та JB4 Molex connector за вашим блоком.', shortEn: 'Choose 4-position V1 or 2-position V2, cable length, and Molex connector for your JB4 board.',
    benefitUa: 'Змінний OBDII кабель з’єднує сумісний JB4 із діагностичним портом під панеллю приладів. Це потрібно для зв’язку JB4 з OBDII/CAN автомобіля; правильний тип контактів і роз’єму з боку JB4 є обов’язковим.', benefitEn: 'The replacement OBDII cable connects a compatible JB4 to the diagnostic port under the dash. It carries the JB4 vehicle OBD/CAN connection; matching pin count and JB4-side connector are essential.',
    detailsUa: 'Оберіть один варіант: 4-position V1 на 7 або 13 футів; 4-position V1 із Molex JB4 connector; або 2-position V2 на 7, 8 чи 13 футів. V1 та V2 не взаємозамінні автоматично. Перевірте роз’єм старого кабелю й потрібну довжину до покупки.', detailsEn: 'Choose one option: 4-position V1 in 7 or 13 feet; 4-position V1 with Molex JB4 connector; or 2-position V2 in 7, 8, or 13 feet. V1 and V2 are not automatically interchangeable. Check the old cable connector and required length before ordering.',
    fitUa: 'Для JB4 установок, де кабель іде до OBDII порту. Підбирайте за версією плати, кількістю контактів і конектором JB4.', fitEn: 'For JB4 installations that connect to the OBDII port. Match board generation, pin count, and JB4-side connector.'
  },
  'replacement-jb4-control-boards': {
    titleUa: 'Replacement JB4 Control Board — оберіть двигун і покоління системи', titleEn: 'Replacement JB4 Control Board — Select Engine and System Generation',
    shortUa: 'Змінна плата JB4 для вибраної платформи; код двигуна, джгут і покоління системи мають збігатися.', shortEn: 'Replacement JB4 board for the selected platform; engine, harness, and system generation must match.',
    benefitUa: 'Змінна control board допомагає відновити керування JB4 у випадку несправності або переходу на іншу платформну версію. Це електронна плата, не повний комплект JB4, джгут або окреме налаштування двигуна.', benefitEn: 'A replacement control board restores JB4 control when a board fails or a platform-specific version is needed. It is an electronic board, not a complete JB4 kit, harness, or engine tune.',
    detailsUa: 'У меню Engine Type доступні плати для BMW B48/B58, S58, F90, N55, N20, N54, S55, S63TU, N63, Mercedes C, VW/Audi, Kia V1/V2/V3, Infiniti VR30, GM, Ford, Mazda та інших зазначених систем. Оберіть точний варіант за платою й джгутом. Старі N55 E-Series можуть вимагати перенесення power wire.', detailsEn: 'The Engine Type menu covers BMW B48/B58, S58, F90, N55, N20, N54, S55, S63TU, N63, Mercedes C, VW/Audi, Kia V1/V2/V3, Infiniti VR30, GM, Ford, Mazda, and other listed systems. Match the exact board and harness; older N55 E-Series may require a power-wire relocation.',
    fitUa: 'Лише для відповідної моделі JB4 і двигуна. До оплати звірте ревізію плати, джгут, з’єднання й потребу в оновленні прошивки з Burger.', fitEn: 'For the matching JB4 model and engine only. Confirm board revision, harness, connectors, and firmware requirements with Burger before purchase.'
  },
  'programmed-jb4-replacemnt-and-upgrade-chips': {
    titleUa: 'JB4 Replacement / Upgrade Chips — оберіть прошивку за платформою', titleEn: 'JB4 Replacement / Upgrade Chips — Select Firmware by Platform',
    shortUa: 'Програмований master chip або драйвер для сумісної JB4 плати; оберіть точну платформу та версію.', shortEn: 'Programmed master chip or driver for a compatible JB4 board; choose exact platform and version.',
    benefitUa: 'Змінний 2580 master chip містить комунікаційні дані JB4 і прошивку для певної платформи. Burger пропонує його як заміну несправному чипу зв’язку або для вибору іншої сумісної конфігурації; це не повний тюнер і не універсальний чип для різних плат.', benefitEn: 'The replaceable 2580 master chip contains JB4 communications data and platform-specific firmware. Burger offers it to replace a failed communication chip or load a compatible platform setup; it is not a complete tuner or a universal chip for all boards.',
    detailsUa: 'У списку є окремі чипи для BMW N54/N55/N20/S55/S58/S63/N63/B48/B58, VW, Kia/Hyundai, Infiniti, GM, Ford, Mercedes та Toyota Tundra. Оберіть точний engine/chassis/board version. Під час заміни вимкніть авто, дайте ECU заснути, встановіть chip із правильною орієнтацією мітки та дотримуйтеся інструкції Burger.', detailsEn: 'Options cover distinct BMW N54/N55/N20/S55/S58/S63/N63/B48/B58, VW, Kia/Hyundai, Infiniti, GM, Ford, Mercedes, and Toyota Tundra applications. Select the exact engine/chassis/board version. Power the vehicle down, allow the ECU to sleep, orient the chip notch correctly, and follow Burger instructions.',
    fitUa: 'Сумісність визначається конкретною JB4 control board та engine family. Перевірте модель плати й номер старого чипа; неправильна версія може не з’єднатися або не підтримувати авто.', fitEn: 'Compatibility depends on the specific JB4 control board and engine family. Check board model and old chip reference; the wrong version may fail to connect or support the vehicle.'
  },
  'jb4-cell-phone-holder': {
    titleUa: 'JB4 Magnetic Phone Mount — legacy Dash Mount з клейкою основою', titleEn: 'JB4 Magnetic Phone Mount — Legacy Adhesive Dash Mount',
    shortUa: 'Старіша магнітна модель для гладкої панелі з металевою пластиною та регульованим кутом.', shortEn: 'Legacy magnetic mount for a smooth dash, with metal plate and adjustable viewing angle.',
    benefitUa: 'Магнітна підставка фіксує телефон на панелі для перегляду JB4 Mobile. Кут регулюється, а тонка металева пластина кріпиться на телефон або чохол.', benefitEn: 'The magnetic base holds a phone on the dash for viewing JB4 Mobile. The angle adjusts and a thin metal plate attaches to the phone or case.',
    detailsUa: 'У комплекті adhesive disk base, металева пластина, чорний/сірий JB4 логотип і, за описом джерела, червоний overlay. Поверхня має бути гладкою та чистою; очищайте ізопропіловим спиртом і притискайте основу 30 секунд. Burger зазначає, що ця модель замінена новішим MagSafe тримачем.', detailsEn: 'The package includes an adhesive disk base, metal plate, black/gray JB4 logo, and the red overlay mentioned by the supplier. Surface must be clean and smooth; wipe with rubbing alcohol and press the base for 30 seconds. Burger says this model has been superseded by a newer MagSafe mount.',
    fitUa: 'Для сумісного телефона та гладкої панелі. Перевірте, що саме legacy-модель доступна, і не встановлюйте на текстуровану поверхню.', fitEn: 'For a compatible phone and smooth dash surface. Confirm the legacy model is available and do not install on textured surfaces.'
  },
  'dragy': {
    titleUa: 'Dragy GPS Performance Meter — стандартний або PRO, новий чи Refurbished', titleEn: 'Dragy GPS Performance Meter — Standard or PRO, New or Refurbished',
    shortUa: 'Оберіть DRG70/DRG70-C або Dragy PRO і стан Refurbished / новий; записує GPS-прискорення та заїзди.', shortEn: 'Choose DRG70/DRG70-C or Dragy PRO, refurbished or new; records GPS acceleration and runs.',
    benefitUa: 'Dragy — GPS performance meter, що разом із мобільним додатком записує прискорення та дистанційні заміри, зокрема 0–60 mph, 60–130 mph, чверть милі й 100–200 км/год. Додаток зберігає заїзди та формує звіти з графіками й показниками швидкості; це вимірювальний інструмент, не ECU tune.', benefitEn: 'Dragy is a GPS performance meter that records acceleration and distance tests with its mobile app, including 0–60 mph, 60–130 mph, quarter-mile, and 100–200 km/h. The app saves runs and creates reports with charts and speed metrics; it is a measurement tool, not an ECU tune.',
    detailsUa: 'Оберіть Dragy Refurbished (DRG70), новий Dragy (DRG70-C), Dragy PRO Refurbished або новий Dragy PRO. Стан пристрою залежить від опції; не змішуйте refurbished і новий варіанти. Window Mount продається окремо. Для запису потрібен сумісний смартфон і Dragy app.', detailsEn: 'Choose refurbished Dragy (DRG70), new Dragy (DRG70-C), refurbished Dragy PRO, or new Dragy PRO. Device condition follows the selected option; do not treat refurbished and new versions as identical. Window Mount is sold separately. A compatible phone and Dragy app are required.',
    fitUa: 'Для водіїв, яким потрібне GPS-логування замірів на закритій трасі або безпечному майданчику. Перед використанням перевірте модель, підтримку додатка та місцеві правила вимірювання.', fitEn: 'For drivers who want GPS logging on a closed course or safe test area. Check device model, app support, and local rules before testing.'
  },
  'replacement_carb_stickers': {
    titleUa: 'Replacement CARB Sticker для сумісного Burger продукту', titleEn: 'Replacement CARB Sticker for an Eligible Burger Product',
    shortUa: 'Оберіть наклейку за двигуном і продуктом; постачальник вимагає підтвердження CARB схвалення до відправки.', shortEn: 'Select the sticker by engine and product; supplier requires proof of CARB approval before shipment.',
    benefitUa: 'Ця replacement наклейка замінює маркування CARB для вже схваленого сумісного продукту Burger. Наклейка сама не надає сертифікацію, не робить непогоджений тюнінг легальним і не підтверджує схвалення іншого номера деталі.', benefitEn: 'This replacement sticker replaces CARB labeling on an already approved eligible Burger product. The sticker itself does not grant certification, legalize an unapproved tune, or certify a different part number.',
    detailsUa: 'Оберіть точний тип: N54 JB+, N54 DCI, B58 JB+, B58 JB4, F-150/Raptor JB4, N55 Stage 1 або MINI N18 JB+. Burger вимагає підтвердження схваленого BMS продукту до відправлення, тому наявність відповідної наклейки на сайті не є доказом відповідності конкретного автомобіля.', detailsEn: 'Choose the exact type: N54 JB+, N54 DCI, B58 JB+, B58 JB4, F-150/Raptor JB4, N55 Stage 1, or MINI N18 JB+. Burger requires proof of the approved BMS product before shipment; a sticker listing is not proof that a specific vehicle is compliant.',
    fitUa: 'Тільки для схваленого продукту й автомобіля, які підтвердив Burger. До відвантаження потрібно зіставити номер деталі та документ про схвалення.', fitEn: 'Only for a product and vehicle confirmed as approved by Burger. Match the part number and approval evidence before dispatch.'
  },
  'bms-performance-filter-for-corvette-c7-grand-sport-stingray-z06-zr1': {
    titleUa: 'BMS Dry Drop-In Air Filter для Chevrolet Corvette C7 — вибір airbox', titleEn: 'BMS Dry Drop-In Air Filter for Chevrolet Corvette C7 — Select Airbox',
    shortUa: 'Сухий фільтр Corvette C7 для заводського GM airbox або Performance Jake airbox; оливлення не потрібне.', shortEn: 'Dry Corvette C7 filter for factory GM or Performance Jake airbox; no filter oil required.',
    benefitUa: 'BMS dry drop-in filter замінює елемент у вибраному Corvette C7 airbox. Сухий матеріал не використовує оливу й не створює ризику її надлишку біля MAF; профіль нижньої частини розрахований на з’єднання з відповідним корпусом. Burger заявляє потенційний приріст у тестовій конфігурації, але фактичний результат залежить від авто й модифікацій.', benefitEn: 'The BMS dry drop-in filter replaces the element in the selected Corvette C7 airbox. Dry media requires no oil, avoiding excess oil near the MAF; the base shape is designed for the matching housing. Burger advertises potential gains in its test setup, but actual results depend on vehicle and modifications.',
    detailsUa: 'Оберіть Factory GM Airbox або GM Performance Corvette Racing Jake Airbox with Clear Window. Це різні корпуси, тому неправильна опція може не ущільнитися. Фільтр залишається dry-type: не просочуйте його оливою для звичайних oiled-cotton елементів.', detailsEn: 'Choose Factory GM Airbox or GM Performance Corvette Racing Jake Airbox with Clear Window. These are different housings, so the wrong option may not seal. The filter is dry-type; do not apply oil used for oiled-cotton elements.',
    fitUa: 'Для Corvette C7 Grand Sport, Stingray, Z06 або ZR1 із вибраним airbox за переліком Burger. Перед монтажем звірте корпус і вимоги до dry filter.', fitEn: 'For Burger-listed Corvette C7 Grand Sport, Stingray, Z06, or ZR1 with the selected airbox. Confirm housing and dry-filter requirement before installation.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Призначення та користь</h3>\n<p>${item.benefitUa}</p>\n<h3>Вибір і комплектація</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність та важливі умови</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and benefit</h3>\n<p>${item.benefitEn}</p>\n<h3>Selection and package</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment and important notes</h3>\n<p>${item.fitEn}</p>`,
}]));
