// Source-checked ignition, spark-plug, and service-tool copy; local draft only.
const rows = {
  'bms-high-output-ignition-coil-kits-for-vw-audi': {
    titleUa: 'BMS High Output Ignition Coils для VW / Audi / Porsche — 4 або 5 шт.', titleEn: 'BMS High Output Ignition Coils for VW / Audi / Porsche — 4 or 5 Pack',
    shortUa: 'Оберіть комплект для EA888 Gen 3, Gen 4 або 2.5T RS3 / TT RS: 4 чи 5 котушок відповідно до двигуна.', shortEn: 'Choose an EA888 Gen 3, Gen 4, or 2.5T RS3/TT RS set: four or five coils for the selected engine.',
    benefitUa: 'BMS high-output ignition coils замінюють штатні котушки запалювання та подають іскру до свічок. За описом Burger, котушки plug-and-play і мають до 10% вищу енергію виходу, що може підтримати стабільніше запалювання на штатному або налаштованому моторі. Це не самостійний тюнінг потужності; результат залежить від стану системи запалювання та налаштування авто.', benefitEn: 'BMS high-output ignition coils replace the factory ignition coils and deliver spark to the plugs. Burger states plug-and-play fitment and up to 10% more energy output, which may support consistent ignition on stock or tuned engines. They are not a standalone power tune; results depend on the ignition system and vehicle calibration.',
    detailsUa: 'Оберіть саме потрібний комплект: MK7 EA888 Gen 3 2.0T — 4 котушки; Audi RS3/TT RS Quattro 2.5L — 5; MK8 EA888 Gen 4 2.0T — 4. Кольору в цьому селекторі немає: кількість і застосування визначаються поколінням двигуна. Звірте engine code та кількість циліндрів.', detailsEn: 'Select the correct package: MK7 EA888 Gen 3 2.0T uses four coils; Audi RS3/TT RS Quattro 2.5L uses five; MK8 EA888 Gen 4 2.0T uses four. This selector is for engine application and pack count. Confirm the engine code and cylinder count.',
    fitUa: 'Для вказаних VW/Audi 2.0T EA888 Gen 3 або Gen 4 та Audi RS3/TT RS 2.5L Quattro. Переконайтеся, що покоління двигуна відповідає обраній позиції.', fitEn: 'For the listed VW/Audi 2.0T EA888 Gen 3 or Gen 4 and Audi RS3/TT RS 2.5L Quattro. Match the engine generation to the selected option.'
  },
  'bms-high-output-ignition-coil-kits-for-bmw-mini-supra': {
    titleUa: 'BMS High Output Ignition Coils для BMW / MINI / Toyota Supra', titleEn: 'BMS High Output Ignition Coils for BMW / MINI / Toyota Supra',
    shortUa: 'Оберіть колір і двигун; набір котушок підбирається за кількістю циліндрів та серією мотора.', shortEn: 'Select coil color and engine; choose the kit by engine family and cylinder count.',
    benefitUa: 'Комплект BMS замінює котушки запалювання на сумісному BMW, MINI або Toyota Supra. Виробник заявляє до 10% більшої енергії виходу за штатні котушки; це може допомогти підтримати запалювання на навантаженому двигуні, але не є гарантією приросту потужності чи усунення несправності свічок.', benefitEn: 'The BMS set replaces ignition coils on compatible BMW, MINI, or Toyota Supra applications. The supplier states up to 10% higher energy output than stock coils; this may support ignition under load, but does not guarantee a power increase or fix faulty spark plugs.',
    detailsUa: 'Конфігуратор має два незалежні вибори: Engine і Color. Доступні двигуни B36/B38/B46/B48 (4 циліндри), B58/S58 (6), N20/N26 (4), N52/N54/N55/N62/N63/S55 (6) і S63 (8); оберіть колір Blue, Red або Black. Кількість котушок повинна відповідати кількості циліндрів.', detailsEn: 'The configurator has separate Engine and Color choices. Listed engines are B36/B38/B46/B48 (4-cylinder), B58/S58 (6), N20/N26 (4), N52/N54/N55/N62/N63/S55 (6), and S63 (8). Choose Blue, Red, or Black. Coil quantity must match cylinder count.',
    fitUa: 'Сумісність визначається точним двигуном і його поколінням, а не лише маркою авто. Для Supra звірте мотор B58; для BMW/MINI перед оплатою перевірте engine code та роз’єм котушки.', fitEn: 'Fitment depends on the exact engine and generation, not make alone. For Supra, verify the B58 application; for BMW/MINI, confirm the engine code and coil connector before ordering.'
  },
  'n54-n55-to-b58-bmw-coil-upgrade-adapter-kit': {
    titleUa: 'BMS Adapter Kit для встановлення котушок BMW B58 на N54 / N55', titleEn: 'BMS Adapter Kit to Fit BMW B58 Coils on N54 / N55',
    shortUa: 'Оберіть N54 або N55 і колір billet-адаптерів; котушки B58 продаються окремо.', shortEn: 'Choose N54 or N55 and billet-adapter color; B58 ignition coils are sold separately.',
    benefitUa: 'Комплект адаптерів дає змогу встановити B58 coil-on-plug котушки на BMW N54 або N55. Він замінює штатне кріплення котушок, щоб використати сумісні B58 coils без свічкових проводів; самі котушки не включені в цю картку.', benefitEn: 'This adapter kit lets you install B58 coil-on-plug ignition coils on a BMW N54 or N55. It replaces the factory coil mounting arrangement so compatible B58 coils can be used without plug wires; the coils themselves are not included in this listing.',
    detailsUa: 'Оберіть Engine: N54 або N55, потім колір анодованих billet-алюмінієвих кронштейнів: Red, Blue або Silver. Burger описує адаптерні кронштейни та plug-and-play з’єднувачі; B58 ignition coils виробник радить придбати окремо. Перевірте сумісність обраних котушок до встановлення.', detailsEn: 'Select Engine (N54 or N55) and then the anodized billet-aluminum bracket color (Red, Blue, or Silver). Burger describes adapter brackets and plug-and-play connectors; B58 ignition coils are recommended separately. Confirm compatibility of the selected coils before installation.',
    fitUa: 'Для BMW із двигуном N54 або N55 у конфігураціях, перелічених Burger. Адаптерний комплект не є котушками; окремо потрібні сумісні B58 coils.', fitEn: 'For Burger-listed BMW applications with an N54 or N55 engine. The adapter kit is not a coil set; compatible B58 coils must be sourced separately.'
  },
  'brisk-racing-iridium-plugs-spark-plug-for-bmw-s58-b58-engines-copy': {
    titleUa: 'Brisk Racing Iridium Spark Plugs для BMW S58 / B58 та Supra', titleEn: 'Brisk Racing Iridium Spark Plugs for BMW S58 / B58 and Supra',
    shortUa: 'Оберіть одну свічку, комплект із 6 або набір із інструментами; перевірте двигун S58 чи B58 Gen 2.', shortEn: 'Choose one plug, a six-pack, or a tool bundle; verify S58 or Gen 2 B58 engine fitment.',
    benefitUa: 'Свічки Brisk Racing з іридієвим електродом призначені для запалювання на BMW S58 і B58 Gen 2, включно з налаштованими моторами та конфігураціями E85/WMI, переліченими виробником. Вони мають відводити тепло й стабільно працювати в умовах високого навантаження; свічки не додають потужності без відповідної системи та калібрування.', benefitEn: 'Brisk Racing iridium plugs are specified for BMW S58 and Gen 2 B58 engines, including tuned and E85/WMI configurations listed by the supplier. Their electrode design targets heat transfer and ignition under demanding conditions; plugs do not add power without a suitable engine setup and calibration.',
    detailsUa: 'Оберіть Single Plug, комплект із 6 свічок або COMBO DEAL із шістьма свічками, 12 мм інструментом для зазору, щупом і торцевою головкою. Комплект із шести призначений для шестициліндрового двигуна; перед монтажем звірте рекомендований зазор для конкретного рівня наддуву й інструкцію Brisk.', detailsEn: 'Choose a single plug, a six-plug set, or the combo with six plugs, a 12 mm gap tool, feeler gauge, and socket. The six-pack is intended for six-cylinder applications; verify the recommended gap for the specific boost setup and follow Brisk guidance.',
    fitUa: 'Для BMW S58 та B58 другого покоління / Toyota Supra з цим двигуном за сторінкою Burger. Не переносіть сумісність на B58 Gen 1 або інші двигуни без перевірки номера свічки.', fitEn: 'For Burger-listed BMW S58 and second-generation B58 / Toyota Supra applications. Do not assume fitment on B58 Gen 1 or other engines without checking the plug reference.'
  },
  'ngk-96206-spark-plug-for-bmw-s58-and-gen-2-3-b58-engines': {
    titleUa: 'NGK 96206 Laser Iridium Spark Plug для BMW S58 / B58 Gen 2 і 3', titleEn: 'NGK 96206 Laser Iridium Spark Plug for BMW S58 / B58 Gen 2 and 3',
    shortUa: 'NGK 96206 для S58 і B58 Gen 2/3: одна свічка, 6 шт. або комплект із інструментами для сервісу.', shortEn: 'NGK 96206 for S58 and B58 Gen 2/3: single plug, six-pack, or service-tool bundle.',
    benefitUa: 'Оригінальна NGK 96206 Laser Iridium є замінною свічкою для вказаних двигунів BMW S58 і B58 Gen 2/3. За описом Burger, її використовують як у стандартних, так і в налаштованих конфігураціях, зокрема E85/WMI або збільшеною турбіною. Для зміненого наддуву важливо виставити зазор відповідно до конфігурації авто.', benefitEn: 'The NGK 96206 Laser Iridium is a replacement spark plug for listed BMW S58 and B58 Gen 2/3 engines. Burger describes it for stock and tuned applications, including E85/WMI or larger turbo setups. On a modified boost setup, set the gap to match the vehicle configuration.',
    detailsUa: 'Оберіть одну свічку, комплект із шести або combo з 6 NGK 96206, 12 мм gap tool, feeler gauge та socket. Burger радить зазор 0.022″ для своїх застосувань. Перед монтажем перевірте потрібну кількість і зазор за поточним тюнінгом двигуна.', detailsEn: 'Choose one plug, a six-pack, or the combo with six NGK 96206 plugs, a 12 mm gap tool, feeler gauge, and socket. Burger suggests a 0.022-inch gap for its applications. Confirm quantity and gap against the current engine tune before installation.',
    fitUa: 'Для BMW із S58 та B58 Gen 2 або Gen 3, як зазначено Burger. Не підміняйте цю свічку номером NGK для B58 Gen 1; звірте код двигуна й part number.', fitEn: 'For Burger-listed BMW S58 and B58 Gen 2 or Gen 3 applications. Do not substitute this plug for the NGK reference used on B58 Gen 1; verify engine code and part number.'
  },
  'subaru-magnetic-spark-plug-socket': {
    titleUa: 'BMS Thin-Wall Magnetic Spark Plug Socket для Subaru', titleEn: 'BMS Thin-Wall Magnetic Spark Plug Socket for Subaru',
    shortUa: 'Тонкостінна магнітна головка утримує свічку у глибокому колодязі під час демонтажу й монтажу.', shortEn: 'Thin-wall magnetic socket holds the plug while removing or installing it in a deep Subaru plug well.',
    benefitUa: 'Спеціальна тонкостінна головка BMS розрахована на свічкові колодязі Subaru, де звичайний socket може не поміститися. Вбудований rare-earth magnet утримує свічку під час підйому й опускання, зменшуючи ризик упустити її у важкодоступному місці.', benefitEn: 'The BMS thin-wall socket is designed for Subaru spark-plug wells where a standard socket may not fit. An integrated rare-earth magnet holds the plug while lifting or lowering it, reducing the chance of dropping it into a deep, hard-to-reach well.',
    detailsUa: 'Це сервісний інструмент для зняття та встановлення свічок, не комплект свічок. Магніт утримує свічку без гумового або металевого вставного фіксатора. Перевірте розмір посадки й привід socket для вашого мотора перед використанням.', detailsEn: 'This is a service tool for removing and installing plugs, not a spark-plug set. The magnet retains the plug without a rubber or metal tension insert. Confirm socket size and drive compatibility for the engine before use.',
    fitUa: 'Для Subaru конфігурацій, що потребують зазначеної BMS thin-wall головки. Звірте розмір свічки та доступ до колодязя з посібником сервісу.', fitEn: 'For Subaru applications requiring the listed BMS thin-wall socket. Verify plug size and access requirements against the service manual.'
  },
  'bosch-replacement-n54-spark-plug': {
    titleUa: 'Bosch ZGR6STE2 — змінна свічка запалювання для BMW N54', titleEn: 'Bosch ZGR6STE2 Replacement Spark Plug for BMW N54',
    shortUa: 'Оберіть одну оригінальну Bosch ZGR6STE2 або комплект із 6 свічок для шестициліндрового N54.', shortEn: 'Choose one authentic Bosch ZGR6STE2 or a six-pack for the six-cylinder N54.',
    benefitUa: 'Bosch ZGR6STE2 — заводська замінна триелектродна свічка для BMW N54, яку Burger рекомендує для багатьох стандартних турбоконфігурацій. За описом постачальника, вона не потребує ручного виставлення зазору та має довший ресурс порівняно з NGK у зазначеному застосуванні. Перевірте стан і специфікацію свічок перед сервісом.', benefitEn: 'Bosch ZGR6STE2 is a factory-replacement three-electrode plug for BMW N54, which Burger recommends for many stock-turbo applications. The supplier says it does not require manual gapping and offers longer service life than NGK for the listed use. Check the vehicle specification and plug condition before service.',
    detailsUa: 'Оберіть одну свічку або шестикомплект для всіх циліндрів. Сторінка вказує 14 мм double-hex drive. Виробник також застерігає щодо підробок; купуйте за перевіреним part number і не змішуйте різні типи свічок в одному двигуні без рекомендації калібратора.', detailsEn: 'Choose a single plug or a six-pack for all cylinders. The page specifies a 14 mm double-hex drive. The supplier warns about counterfeit parts; match the part number and avoid mixing plug types in one engine unless the tuner recommends it.',
    fitUa: 'Для BMW N54 за каталогом Burger. Назва джерела позначає товар як відсутній на складі, тому наявність потрібно перевірити окремо від сумісності.', fitEn: 'For BMW N54 as listed by Burger. The supplier title marks this item out of stock, so availability must be confirmed separately from fitment.'
  },
  'ngk-94201-spark-plug': {
    titleUa: 'NGK 94201 Laser Iridium для BMW B48 / B58 Gen 1 — свічка або комплект', titleEn: 'NGK 94201 Laser Iridium for BMW B48 / B58 Gen 1 — Single or Set',
    shortUa: 'Оберіть кількість свічок NGK 94201 або combo з gap tool, щупом і socket; зазор залежить від турбіни.', shortEn: 'Choose NGK 94201 quantity or a combo with gap tool, gauge, and socket; plug gap depends on turbo setup.',
    benefitUa: 'NGK 94201 Laser Iridium — сервісна свічка для сумісних BMW B48/B58 Gen 1, які використовуються на штатних та налаштованих автомобілях. Burger також вказує використання з E85, WMI та збільшеною турбіною; правильний тепловий діапазон і зазор слід узгодити з вашим тюнінгом.', benefitEn: 'NGK 94201 Laser Iridium is a service spark plug for compatible BMW B48/B58 Gen 1 applications, stock or tuned. Burger also lists E85, WMI, and larger-turbo setups; confirm the heat range and gap with the vehicle tune.',
    detailsUa: 'Конфігуратор дає вибір однієї свічки, комплекту з 4 або 6 шт., а також combo з відповідною кількістю свічок, 12 мм інструментом для зазору, щупом і socket. Burger радить 0.028″ зі штатною турбіною або 0.022″ з aftermarket turbo. Не застосовуйте один зазор до всіх конфігурацій.', detailsEn: 'Choose one plug, a four- or six-pack, or a matching combo with plugs, 12 mm gap tool, feeler gauge, and socket. Burger suggests 0.028 inches with the factory turbo or 0.022 inches with an aftermarket turbo. Do not apply one gap to every setup.',
    fitUa: 'Для BMW B48/B58 Gen 1 у застосуваннях, перелічених Burger. Оскільки текст джерела окремо наголошує B58, перевірте OEM номер і двигун конкретного автомобіля перед підбором.', fitEn: 'For Burger-listed BMW B48/B58 Gen 1 applications. Since the source text specifically emphasizes B58, verify the OE reference and exact engine before ordering.'
  },
  'denso-5347-2-step-high-performance-spark-plugs': {
    titleUa: 'Denso 5347 IKH27 — на 2 кроки холодніша свічка для Kia / Hyundai 3.3T', titleEn: 'Denso 5347 IKH27 Two-Step-Colder Plug for Kia / Hyundai 3.3T',
    shortUa: 'Оберіть свічку, комплект із 6 або combo; звірте зазор і склад combo з артикулом Denso 5347.', shortEn: 'Choose a single plug, six-pack, or combo; verify the gap and bundle contents against Denso 5347.',
    benefitUa: 'Denso 5347 IKH27 — холодніша performance spark plug для налаштованих Kia/Hyundai 3.3L Turbo, де умови роботи можуть вимагати іншого теплового діапазону. Burger радить зазор 0.020″ для агресивних налаштувань 3.3T. Зазор і тепловий діапазон мають відповідати тюнінгу та рекомендаціям майстра.', benefitEn: 'Denso 5347 IKH27 is a colder-range performance plug for tuned Kia/Hyundai 3.3L turbo applications where operating conditions may call for a different heat range. Burger suggests a 0.020-inch gap for aggressive 3.3T tunes. Match the heat range and gap to the calibration and installer guidance.',
    detailsUa: 'Опції: одна свічка, 6-pack або combo із шістьма свічками та інструментами. У supplier description є неузгодженість: назва й товарний номер вказують 5347 IKH27, але текст комплекту згадує 5346 IKH24. Підтвердіть артикул і вміст combo перед продажем; у цьому описі не гарантуємо комплектність combo.', detailsEn: 'Options include one plug, a six-pack, or a tool combo. The supplier description has a mismatch: the title and product number say 5347 IKH27, while the bundle text mentions 5346 IKH24. Confirm the plug number and combo contents before sale; this copy does not promise the disputed bundle contents.',
    fitUa: 'Для Kia Stinger GT / Genesis G70 3.3L Turbo та інших сумісних 3.3T конфігурацій за підтвердженням Burger. Звірте номер 5347, двигун і рекомендований зазор.', fitEn: 'For Kia Stinger GT / Genesis G70 3.3L turbo and other 3.3T setups only when confirmed by Burger. Verify part 5347, engine, and recommended gap.'
  },
  'denso-ikh24-iri-spark-plug': {
    titleUa: 'Denso 5346 IKH24 — на 1 крок холодніша свічка для Kia / Hyundai 3.3T', titleEn: 'Denso 5346 IKH24 One-Step-Colder Plug for Kia / Hyundai 3.3T',
    shortUa: 'Denso 5346 IKH24 для Kia/Hyundai 3.3T: одна свічка, 6-pack або combo із сервісним інструментом.', shortEn: 'Denso 5346 IKH24 for Kia/Hyundai 3.3T: single plug, six-pack, or service-tool combo.',
    benefitUa: 'Denso 5346 IKH24 — свічка на один крок холодніша за штатний тепловий діапазон для Kia/Hyundai 3.3L Turbo. За Burger, вона призначена для стандартних і налаштованих автомобілів; виробник радить зазор 0.022″ для 3.3T. Остаточний зазор потрібно підтвердити з фахівцем відповідно до наддуву та палива.', benefitEn: 'Denso 5346 IKH24 is one heat range colder than stock for Kia/Hyundai 3.3L turbo applications. Burger lists it for stock and tuned vehicles and suggests a 0.022-inch gap for 3.3T. Confirm final gap with the installer based on boost and fuel.',
    detailsUa: 'Оберіть одну свічку, шестикомплект або combo з шістьма Denso 5346 IKH24, інструментом для зазору, щупом і socket згідно з обраною опцією. Пакет із шести свічок покриває V6. Не плутайте цей варіант із холоднішою на два кроки Denso 5347 IKH27.', detailsEn: 'Choose one plug, a six-pack, or the combo with six Denso 5346 IKH24 plugs, a gap tool, feeler gauge, and socket as specified by the option. The six-pack covers a V6. Do not confuse it with the two-step-colder Denso 5347 IKH27.',
    fitUa: 'Для Kia Stinger GT / Genesis G70 3.3L Turbo та інших застосувань, прямо підтверджених Burger. Звірте part number 5346 IKH24 і зазор перед монтажем.', fitEn: 'For Kia Stinger GT / Genesis G70 3.3L turbo and other applications explicitly confirmed by Burger. Verify part 5346 IKH24 and plug gap before installation.'
  },
  'hks-m45il-m45xl-spark-plugs-for-kia-hyundai': {
    titleUa: 'HKS Super Fire Racing M45IL / M45XL для Kia та Hyundai Turbo', titleEn: 'HKS Super Fire Racing M45IL / M45XL for Kia and Hyundai Turbo',
    shortUa: 'Оберіть 6 свічок M45IL для 3.3T або 4 свічки M45XL для 1.6T / 2.0T / 2.5T.', shortEn: 'Choose six M45IL plugs for 3.3T or four M45XL plugs for 1.6T, 2.0T, or 2.5T.',
    benefitUa: 'Свічки HKS M-Series Super Fire Racing мають іридієвий електрод і призначені для підвищених вимог до запалювання, довговічності та протидії нагару в турбодвигунах Kia/Hyundai. Підбір залежить від двигуна: M45IL для 3.3T, M45XL для платформ 1.6T, 2.0T і 2.5T. Це різні part number, вони не взаємозамінні.', benefitEn: 'HKS M-Series Super Fire Racing plugs use an iridium electrode and target ignition performance, durability, and resistance to carbon buildup in Kia/Hyundai turbo engines. Selection depends on engine: M45IL for 3.3T and M45XL for 1.6T, 2.0T, and 2.5T platforms. These are different part numbers and are not interchangeable.',
    detailsUa: 'Оберіть набір: 6-Pack HKS 50003-M45IL або 4-Pack HKS 50003-M45XL. За Burger, свічки мають заводський зазор 0.028″; для максимально навантажених конфігурацій пропонується 0.022″. Перед монтажем підбирайте зазор до тюнінгу, а не лише до назви автомобіля.', detailsEn: 'Choose the set: six HKS 50003-M45IL plugs or four HKS 50003-M45XL plugs. Burger states a factory gap of 0.028 inches and suggests 0.022 inches for maximum-performance setups. Set the gap for the tune, not by vehicle name alone.',
    fitUa: 'M45IL призначені для 3.3T Stinger/G70; M45XL — для 1.6T, 2.0T і 2.5T Kia/Hyundai, зазначених Burger. Підтвердьте кількість циліндрів і номер свічки.', fitEn: 'M45IL is for 3.3T Stinger/G70; M45XL is for the listed 1.6T, 2.0T, and 2.5T Kia/Hyundai applications. Confirm cylinder count and plug reference.'
  },
  '2020-toyota-supra-magnetic-spark-plug-socket': {
    titleUa: 'BMS Magnetic Spark Plug Socket для Toyota GR Supra Mk5 2020–2026', titleEn: 'BMS Magnetic Spark Plug Socket for 2020–2026 Toyota GR Supra Mk5',
    shortUa: 'Тонкостінний socket із магнітом допомагає витягати й встановлювати свічки у глибоких колодязях Supra.', shortEn: 'Thin-wall magnetic socket helps remove and install plugs in the Supra engine’s deep wells.',
    benefitUa: 'Спеціальна тонкостінна магнітна головка BMS створена для доступу до свічок Toyota GR Supra Mk5. Вбудований rare-earth magnet утримує свічку під час виймання та встановлення в глибокому колодязі, допомагаючи не впустити її в моторному відсіку.', benefitEn: 'The BMS thin-wall magnetic socket is designed to access spark plugs on the Toyota GR Supra Mk5. Its integrated rare-earth magnet holds the plug while removing or installing it in a deep well, helping prevent drops in the engine bay.',
    detailsUa: 'Це один сервісний інструмент, а не комплект свічок. За описом Burger, конструкція не покладається на гумовий або металевий фіксатор, який зношується. Перевірте розмір головки й інструментальний привід та дотримуйтеся моменту затягування свічок Toyota.', detailsEn: 'This is one service tool, not a spark-plug set. Burger describes a design that does not rely on a wear-prone rubber or metal retaining insert. Confirm socket size and drive, and follow Toyota spark-plug torque specifications.',
    fitUa: 'Для Toyota GR Supra Mk5 2020–2026 із двигуном, що використовує відповідну свічку. Звірте покоління Supra та розмір головки перед замовленням.', fitEn: 'For 2020–2026 Toyota GR Supra Mk5 applications using the matching plug. Verify Supra generation and socket size before ordering.'
  },
  'infiniti-nissan-magnetic-spark-plug-socket': {
    titleUa: 'BMS Magnetic Spark Plug Socket для Infiniti / Nissan Z', titleEn: 'BMS Magnetic Spark Plug Socket for Infiniti / Nissan Z',
    shortUa: 'Магнітний тонкостінний socket утримує свічку під час роботи у глибоких колодязях Infiniti та Nissan.', shortEn: 'Thin-wall magnetic socket retains plugs while servicing deep Infiniti and Nissan plug wells.',
    benefitUa: 'BMS magnetic spark plug socket допомагає знімати й ставити свічки в глибоких колодязях турбодвигунів Infiniti та Nissan. Інтегрований rare-earth magnet утримує свічку на головці під час опускання або витягування й не дає їй випасти до того, як її можна буде дістати.', benefitEn: 'The BMS magnetic spark-plug socket helps remove and install plugs in deep Infiniti and Nissan turbo-engine wells. Its integrated rare-earth magnet holds the plug on the socket while lowering or lifting it, reducing the chance of dropping it before it can be reached.',
    detailsUa: 'Один спеціалізований socket; свічки та тріскачка до цього товару не входять. Перед використанням звірте розмір шестигранника конкретної свічки, глибину колодязя та привід інструмента. Не перевищуйте момент затягування виробника двигуна.', detailsEn: 'One specialty socket; spark plugs and ratchet are not included. Check the exact plug hex size, well depth, and tool drive before use. Follow the engine manufacturer torque specification.',
    fitUa: 'Для відповідних Infiniti/Nissan застосувань із глибокими свічковими колодязями за переліком Burger. Звірте модель, двигун і розмір свічки до замовлення.', fitEn: 'For Burger-listed Infiniti/Nissan applications with deep spark-plug wells. Verify model, engine, and plug size before ordering.'
  },
  'specialty-spark-plug-feeler-gauge-size-018-020-022-024': {
    titleUa: 'BMS Specialty Spark Plug Feeler Gauge — щупи 0.018″–0.024″', titleEn: 'BMS Specialty Spark Plug Feeler Gauge — 0.018–0.024 in Blades',
    shortUa: 'Чотири промарковані леза 0.018″, 0.020″, 0.022″ і 0.024″ для перевірки зазору свічок.', shortEn: 'Four marked blades measure 0.018, 0.020, 0.022, and 0.024-inch spark-plug gaps.',
    benefitUa: 'Щуп допомагає перевірити та виставити іскровий зазор свічки під конкретну конфігурацію двигуна. Чотири товщини дають змогу точно порівняти встановлений проміжок із рекомендованим тюнером або виробником свічки.', benefitEn: 'This feeler gauge helps check and set spark-plug gap for a specific engine setup. Four blade thicknesses make it easier to compare the measured gap with the tuner or spark-plug manufacturer recommendation.',
    detailsUa: 'У наборі чотири леза: 0.018″, 0.020″, 0.022″ і 0.024″; кожне має помітне маркування. Працюйте без надмірного зусилля, щоб не деформувати тонкий електрод, і перевіряйте зазор кілька разів після коригування.', detailsEn: 'The set includes four marked blades: 0.018, 0.020, 0.022, and 0.024 inches. Use light pressure so the fine electrode is not bent, and recheck the gap after adjustment.',
    fitUa: 'Універсальний сервісний вимірювальний інструмент для свічок із рекомендованим зазором у цьому діапазоні. Це щуп, не свічка й не інструмент для зміни зазору.', fitEn: 'A service measuring tool for spark plugs with a recommended gap in this range. It is a gauge, not a spark plug or gap-adjustment tool.'
  },
  'bmw-specialty-spark-plug-socket-tool': {
    titleUa: 'BMS Thin-Wall Magnetic Spark Plug Socket для BMW / MINI', titleEn: 'BMS Thin-Wall Magnetic Spark Plug Socket for BMW / MINI',
    shortUa: 'BMW/MINI socket зі тонкими стінками й магнітом полегшує роботу зі свічками у глибоких колодязях.', shortEn: 'Thin-wall BMW/MINI socket with a magnet helps handle plugs in deep engine wells.',
    benefitUa: 'Спеціальна головка BMS дає доступ до свічок запалювання в тісному просторі BMW/MINI. Вбудований rare-earth magnet утримує свічку під час зняття й встановлення в глибокому колодязі; на відміну від гумового вкладиша, магніт не зношується як захоплювальна вставка.', benefitEn: 'The BMS specialty socket accesses spark plugs in the tight space on BMW/MINI applications. An integrated rare-earth magnet retains the plug while removing or installing it in a deep well; unlike a rubber insert, the magnet does not serve as a wear-prone gripping sleeve.',
    detailsUa: 'Це один сервісний socket, свічки до комплекту не входять. Зіставте шестигранник зі свічкою на вашому двигуні та використовуйте відповідний привід і момент затягування. Після робіт перевірте, що ущільнювальна шайба та різьба свічки не пошкоджені.', detailsEn: 'This listing is one service socket; spark plugs are not included. Match the socket hex to the plug used by the engine and use the correct drive and torque. After service, inspect the plug washer and threads for damage.',
    fitUa: 'Для BMW і MINI, де потрібен цей розмір тонкостінної магнітної головки. Уточніть розмір свічки для конкретного двигуна перед купівлею.', fitEn: 'For BMW and MINI applications requiring this thin-wall magnetic socket size. Confirm the engine’s spark-plug size before ordering.'
  },
  'ngk-97506-2-step-colder-spark-plug': {
    titleUa: 'NGK 97506 Laser Iridium — свічки на 2 кроки холодніші для BMW Turbo', titleEn: 'NGK 97506 Laser Iridium Two-Step-Colder Plugs for BMW Turbo',
    shortUa: 'Оберіть 4, 6 чи 8 свічок або combo з інструментами; номер 97506 не призначений для B58.', shortEn: 'Choose four, six, or eight plugs or a tool combo; NGK 97506 is not for B58 engines.',
    benefitUa: 'NGK 97506 — свічка Laser Iridium на два кроки холодніша за штатну для вибраних турбодвигунів BMW, коли це передбачено налаштуванням, підвищеним наддувом чи паливом E85/WMI. Вона не універсальна для всіх BMW: Burger окремо вказує, що B58 потребує іншого NGK part number.', benefitEn: 'NGK 97506 Laser Iridium is two heat ranges colder than stock for listed BMW turbo engines when required by the tune, increased boost, or E85/WMI setup. It is not universal across BMW; Burger specifies a different NGK part number for B58.',
    detailsUa: 'Оберіть 4-, 6- або 8-комплект чи відповідний combo зі свічками, 12 мм gap tool, socket і feeler gauge. Burger радить зазор 0.020″. Комплект і комбінацію інструментів обирайте за числом циліндрів; не застосовуйте до B58.', detailsEn: 'Choose a four-, six-, or eight-plug set or a matching combo with plugs, 12 mm gap tool, socket, and feeler gauge. Burger suggests a 0.020-inch gap. Select by cylinder count; do not use this part for B58.',
    fitUa: 'За Burger: N20, N54, N55, S55, N63, N63TU, S63 і S63TU у перелічених турбоконфігураціях. Номер 97506 не підходить до B58; звірте двигун і калібрування.', fitEn: 'Burger lists N20, N54, N55, S55, N63, N63TU, S63, and S63TU turbo applications. Part 97506 is not for B58; verify engine and calibration.'
  },
  '17mm-magnetic-spark-plug-socket': {
    titleUa: 'BMS 16 мм Magnetic Swivel Spark Plug Socket для VW / Kia та інших авто', titleEn: 'BMS 16 mm Magnetic Swivel Spark Plug Socket for VW / Kia and Other Cars',
    shortUa: 'Шарнірний магнітний socket для більшості свічок із шестигранником 16 мм; перевірте розмір перед роботою.', shortEn: 'Swivel magnetic socket for many 16 mm spark plugs; verify plug hex size before service.',
    benefitUa: 'Тонкостінний шарнірний socket полегшує доступ до свічок у глибоких колодязях і тісних моторних відсіках. Вбудований рідкоземельний магніт утримує свічку під час виймання та встановлення, зменшуючи ризик її падіння.', benefitEn: 'The thin-wall swivel socket helps access plugs in deep wells and tight engine bays. Its integrated rare-earth magnet retains the plug during removal and installation, reducing the chance of dropping it.',
    detailsUa: 'Попри цифру 17 у handle URL, назва сторінки Burger та опис вказують інструмент для 16 мм свічок. Перевірте шестигранник конкретної свічки перед використанням. За рекомендацією джерела, момент затягування — 17 lb-ft (23 Н·м) лише для застосувань, де це допускає виробник авто.', detailsEn: 'Although the handle URL contains 17, the Burger page title and copy specify a socket for 16 mm plugs. Verify the plug hex before use. The page cites 17 lb-ft (23 Nm), but follow that torque only where the vehicle manufacturer specifies it.',
    fitUa: 'Для більшості свічок із шестигранником 16 мм, включно з відповідними VW/Kia застосуваннями. Це інструмент, а не комплект свічок.', fitEn: 'For many spark plugs with a 16 mm hex, including matching VW/Kia applications. This is a tool, not a spark-plug set.'
  },
  'bms_spark_plug_gapping_tool': {
    titleUa: 'BMS Billet Spark Plug Gapper — 12 мм або 14 мм, з щупом чи без', titleEn: 'BMS Billet Spark Plug Gapper — 12 mm or 14 mm, With or Without Gauge',
    shortUa: 'Оберіть різьбу 12 мм для BMW/MINI або 14 мм для Kia/Hyundai 3.3T і додайте щуп за потреби.', shortEn: 'Choose 12 mm for BMW/MINI or 14 mm for Kia/Hyundai 3.3T, with an optional feeler gauge.',
    benefitUa: 'Billet gapper BMS дає змогу коригувати зазор свічки контрольованим натисканням, щоб не пошкодити тонкий електрод. Точний зазор важливий для стабільного запалювання, особливо на турбомоторі; значення потрібно брати з рекомендації виробника двигуна або калібратора.', benefitEn: 'The BMS billet gapper lets you adjust plug gap with controlled pressure to avoid damaging the fine electrode. Correct gap supports consistent ignition, especially on a turbo engine; use the engine or tuner specification for the target value.',
    detailsUa: 'Оберіть 12 мм для BMW/MINI та подібних застосувань або 14 мм для Kia/Hyundai 3.3L, а потім вирішіть, чи потрібен specialty feeler gauge. Опції зі щупом додають чотири леза 0.018″, 0.020″, 0.022″ і 0.024″. Переконайтеся у діаметрі свічки до замовлення.', detailsEn: 'Choose the 12 mm version for BMW/MINI applications or 14 mm for Kia/Hyundai 3.3L, then select whether you need the specialty feeler gauge. Gauge bundles add four blades: 0.018, 0.020, 0.022, and 0.024 inches. Confirm plug diameter before ordering.',
    fitUa: 'Для свічок із відповідною різьбою 12 мм або 14 мм. Колір/розмір інструмента не визначає тепловий діапазон свічки; перевірте її part number окремо.', fitEn: 'For plugs with the matching 12 mm or 14 mm thread size. Tool size does not determine spark-plug heat range; verify the plug part number separately.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Що дає ця деталь</h3>\n<p>${item.benefitUa}</p>\n<h3>Комплектація та вибір</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>What this part does</h3>\n<p>${item.benefitEn}</p>\n<h3>Package and selection</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
