// Source-checked Burger copy batch 16; local draft only.
export default {
  "vr30-o2-adapters-infiniti-q50-q60-nissan-z": {
    "sourceUrl": "https://burgertuning.com/products/vr30-o2-adapters-infiniti-q50-q60-nissan-z",
    "titleUa": "JB4 O2 адаптери для Infiniti Q50 / Q60 і Nissan Z VR30",
    "titleEn": "JB4 O2 adapters for Infiniti Q50 / Q60 and Nissan Z VR30",
    "shortUa": "Пара plug-and-play O2 адаптерів спрощує підключення та демонтаж JB4 fuel wire на двигунах VR30 Infiniti й Nissan Z.",
    "shortEn": "A pair of plug-and-play O2 adapters simplifies JB4 fuel-wire installation and removal on Infiniti and Nissan Z VR30 engines.",
    "descUa": "<h3>Для чого потрібні O2 адаптери VR30</h3>\n<p>Ця пара перехідників спрощує монтаж і зняття паливного дроту JB4 на двигунах VR30. OEM-style роз’єми дають змогу підключити джгут без переробки штатної проводки, що робить обслуговування акуратнішим. Адаптери самостійно не змінюють роботу двигуна й не додають потужності — це монтажний аксесуар для відповідної системи JB4.</p>\n<h3>Комплектність</h3>\n<p>У комплекті два адаптери. JB4 та його паливний дріт до цієї картки не входять. Перед замовленням перевірте, що ваша версія джгута й роз’ємів відповідає конфігурації автомобіля.</p>\n<h3>Сумісність</h3>\n<p>За списком Burger: Infiniti Q50 VR30 3.0L 2016–2024, Infiniti Q60 VR30 3.0L 2017–2022 та Nissan Z VR30 3.0L 2023+ включно з Nismo. Підтвердіть код двигуна та рік випуску.</p>",
    "descEn": "<h3>What the VR30 O2 adapters are for</h3>\n<p>This pair simplifies installation and removal of the JB4 fuel wire on VR30 engines. OEM-style connectors allow the harness to connect without modifying the factory wiring, making service more straightforward. The adapters do not tune the engine or add power on their own; they are an installation accessory for the compatible JB4 system.</p>\n<h3>Package contents</h3>\n<p>The package contains two adapters. The JB4 and its fuel wire are not included. Confirm that your harness and connector version match the vehicle before ordering.</p>\n<h3>Fitment</h3>\n<p>Burger lists the 2016–2024 Infiniti Q50 3.0L VR30, 2017–2022 Infiniti Q60 3.0L VR30 and 2023+ Nissan Z 3.0L VR30, including Nismo. Verify engine code and model year.</p>"
  },
  "bms-billet-brake-fluid-master-cylinder-fill-cap-upgrade-for-subaru": {
    "sourceUrl": "https://burgertuning.com/products/bms-billet-brake-fluid-master-cylinder-fill-cap-upgrade-for-subaru",
    "titleUa": "BMS billet накладка бачка гальмівної рідини Subaru",
    "titleEn": "BMS billet brake-fluid reservoir cap cover for Subaru",
    "shortUa": "CNC-оброблена анодована алюмінієва накладка з логотипом BMS кріпиться поверх штатної кришки бачка. Доступна у трьох кольорах.",
    "shortEn": "CNC-machined anodized aluminum BMS cover fits over the factory brake-fluid reservoir cap. Available in three colors.",
    "descUa": "<h3>Що змінює billet накладка BMS</h3>\n<p>Алюмінієва накладка додає оздоблення моторному відсіку Subaru та робить штатну кришку бачка зручнішою для захоплення завдяки рельєфним граням. Деталь виточена з billet-алюмінію, має логотип BMS і кольорове анодування.</p>\n<h3>Оберіть колір і врахуйте конструкцію</h3>\n<p>Доступні червоний, синій або чорний анодований варіант. Це декоративна накладка, а не повна заміна штатної кришки: вона встановлюється поверх оригінальної за допомогою термостійкої двосторонньої стрічки та щільної посадки. У комплекті одна накладка; штатна кришка бачка лишається на автомобілі.</p>\n<h3>Сумісність</h3>\n<p>Burger перелічує Subaru WRX, STI, Ascent, Outback, Legacy, Impreza, BRZ, Crosstrek і Forester зазначених на сторінці років. Перед купівлею звірте форму штатної кришки та модель у списку застосувань.</p>",
    "descEn": "<h3>What the BMS billet cover changes</h3>\n<p>This aluminum cover adds a finished detail to the Subaru engine bay and provides raised grip surfaces over the factory reservoir cap. It is machined from billet aluminum, engraved with the BMS logo and color anodized.</p>\n<h3>Choose a color and note the design</h3>\n<p>Select anodized red, blue or black. This is a decorative cover, not a replacement cap: it fits over the original cap using high-temperature double-sided tape and a snug fit. One cover is included; the factory reservoir cap remains on the vehicle.</p>\n<h3>Fitment</h3>\n<p>Burger lists Subaru WRX, STI, Ascent, Outback, Legacy, Impreza, BRZ, Crosstrek and Forester applications for the years shown on its page. Check the factory cap shape and your model against the application list before ordering.</p>"
  },
  "stage-1-replacement-fuel-line": {
    "sourceUrl": "https://burgertuning.com/products/stage-1-replacement-fuel-line",
    "titleUa": "Змінна паливна лінія Fuel-It! Stage 1 для BMW E-Series",
    "titleEn": "Fuel-It! Stage 1 replacement fuel line for BMW E-Series",
    "shortUa": "Змінна лінія для Stage 1 LPFP: сумісний із E85 шланг SAE J30R10, швидкороз’єм до штатного насоса та конектор Walbro GSL392.",
    "shortEn": "Replacement line for the Stage 1 LPFP kit: E85-compatible SAE J30R10 hose, factory-pump quick connect and Walbro GSL392 connector.",
    "descUa": "<h3>Для чого ця змінна лінія</h3>\n<p>Паливна лінія призначена для системи BMW E-Series Stage 1 LPFP і з’єднує вузли допоміжного насоса. Вона виготовлена зі шланга SAE J30R10, сумісного з E85, та має швидкороз’єм до штатного паливного насоса й конектор для Walbro GSL392 (255).</p>\n<h3>Комплектність і сумісність</h3>\n<p>Це саме змінна лінія з указаними з’єднаннями, а не повний Stage 1 LPFP upgrade. Насоси, проводка та інші компоненти комплекту окремо не заявлені як вміст цієї картки. Перед замовленням звірте тип установленого Stage 1 комплекту й роз’єми насоса.</p>\n<h3>Застереження щодо монтажу</h3>\n<p>Паливні з’єднання мають бути підібрані точно й перевірені на герметичність після встановлення. Монтаж виконуйте на охолодженому автомобілі без джерел займання.</p>",
    "descEn": "<h3>What this replacement line is for</h3>\n<p>This fuel line is intended for the BMW E-Series Stage 1 LPFP system and connects its auxiliary pump components. It uses SAE J30R10 hose compatible with E85, with a quick connect for the factory fuel pump and a connector for the Walbro GSL392 (255).</p>\n<h3>Package scope and compatibility</h3>\n<p>This listing is the replacement line with the specified connections, not a complete Stage 1 LPFP upgrade. Pumps, wiring and other system components are not identified as included on this page. Confirm your installed Stage 1 kit and pump connectors before ordering.</p>\n<h3>Installation note</h3>\n<p>Fuel connections must match correctly and be checked for leaks after installation. Work on a cool vehicle away from ignition sources.</p>"
  },
  "bms-silicone-intake-pipe-hose-upgrade-for-b58-bmw-g3x-g1x-g0x": {
    "sourceUrl": "https://burgertuning.com/products/bms-silicone-intake-pipe-hose-upgrade-for-b58-bmw-g3x-g1x-g0x",
    "titleUa": "BMS силіконова впускна труба для BMW B58 G-Series",
    "titleEn": "BMS silicone intake pipe upgrade for BMW B58 G-Series",
    "shortUa": "Замінює резонатор і гофровану секцію впускного патрубка перед турбіною для плавнішого потоку. Підходить до штатного або BMS Billet Intake.",
    "shortEn": "Replaces the intake resonator and accordion section upstream of the turbo for a smoother inlet path. Works with factory or BMS Billet Intake.",
    "descUa": "<h3>Що змінює силіконова труба BMS</h3>\n<p>Комплект замінює верхній заводський акустичний резонатор і нижню гофровану секцію впускного патрубка перед входом у турбіну. Гладкіший тракт усуває ці дві штатні секції та звільняє місце в моторному відсіку; деталь працює зі штатним впуском або BMS Billet Intake.</p>\n<h3>Комплектність і додаткова функція</h3>\n<p>У комплекті одна силіконова труба та два хомути. Для BMW X5 G05 40i та X6 G06 40i з двигуном B58 ця модернізація також потрібна для встановлення BMS Oil Catch Can за описом виробника. Фільтр або повний intake kit до цієї картки не входять.</p>\n<h3>Сумісність</h3>\n<p>Застосування B58/B48 у кузовах G-Series, серед яких 540i G30, 740i G11/G12, 840i G14/G15/G16, X3 G01, X4 G02, X5 G05, X6 G06 та X7 G07 у роках, зазначених Burger. Для частини X3/X4 потрібна перевірка схеми. Звірте двигун, рік і конфігурацію впуску до замовлення.</p>",
    "descEn": "<h3>What the BMS silicone pipe changes</h3>\n<p>The kit replaces the factory upper acoustic resonator and lower accordion section of the intake pipe upstream of the turbo inlet. The smoother path removes those two factory sections and clears space in the engine bay; it works with either the factory intake or BMS Billet Intake.</p>\n<h3>Package contents and additional function</h3>\n<p>The package includes one silicone tube and two clamps. On B58 BMW X5 G05 40i and X6 G06 40i, the manufacturer also requires this upgrade for installation of the BMS Oil Catch Can. A filter or complete intake kit is not included with this listing.</p>\n<h3>Fitment</h3>\n<p>Burger lists B58/B48 applications across G-Series models including 540i G30, 740i G11/G12, 840i G14/G15/G16, X3 G01, X4 G02, X5 G05, X6 G06 and X7 G07 for the years shown. Some X3/X4 configurations require diagram verification. Confirm engine, year and intake layout before ordering.</p>"
  }
};
