// Source-checked strut-brace and turbo-inlet copy; local draft only.
const rows = {
  'bms-billet-strut-cross-braces-toyota-gr-supra': {
    titleUa: 'BMS Billet Strut Cross Braces для Toyota GR Supra Mk5 — пара', titleEn: 'BMS Billet Strut Cross Braces for Toyota GR Supra Mk5 — Pair',
    shortUa: 'Пара суцільних billet-алюмінієвих розпірок для Supra; оберіть колір і версію кріплення за роком авто.', shortEn: 'Pair of solid billet-aluminum braces for Supra; choose color and mounting-hardware version by year.',
    benefitUa: 'BMS strut cross braces замінюють заводські розпірки між передніми опорами підвіски. Суцільна конструкція з billet-алюмінію підсилює жорсткість кузова й зменшує його деформацію в поворотах; це структурне підсилення шасі та оновлення вигляду моторного відсіку.', benefitEn: 'BMS strut cross braces replace the factory braces between the front suspension towers. Their solid billet-aluminum construction adds chassis rigidity and reduces flex in corners, while updating the engine-bay appearance.',
    detailsUa: 'У комплекті пара. Виберіть колір та спосіб монтажу: для Supra 2020 виробник передбачає версію з новим кріпленням; для 2021+ — використання штатного кріплення. Це не просто різниця кольору: монтажні комплекти не слід міняти місцями. Болтове встановлення не потребує свердління.', detailsEn: 'The package is a pair. Select color and mounting method: Burger lists a version with included hardware for 2020 Supra and a version that reuses factory hardware for 2021+. The hardware options are not interchangeable. Bolt-on installation requires no drilling.',
    fitUa: 'Toyota GR Supra Mk5 B58 3.0L: 2020 — оберіть варіант із кріпленням; 2021+ — варіант зі штатним кріпленням. Перед замовленням звірте рік і комплектацію.', fitEn: 'Toyota GR Supra Mk5 B58 3.0L: choose the hardware-included option for 2020 and the factory-hardware option for 2021+. Verify model year and trim.'
  },
  'titanium-strut-shock-tower-nut-upgrade-kit-for-e-chassis-bmw': {
    titleUa: 'BMS Titanium Shock-Tower Nuts для BMW E-Chassis — комплект із 6', titleEn: 'BMS Titanium Shock-Tower Nuts for BMW E-Chassis — Six-Piece Set',
    shortUa: 'Шість CNC титанових гайок замінюють штатне кріплення передніх опор BMW E-Chassis; встановлюйте вручну.', shortEn: 'Six CNC titanium nuts replace BMW E-Chassis front tower hardware; install by hand, without power tools.',
    benefitUa: 'Комплект BMS оновлює гайки передніх амортизаційних стійок BMW на титанові. Деталі виготовлені на CNC із суцільного титану, легші за сталеві та мають ручне кольорове випалювання. Це заміна кріплення з візуальним ефектом, а не зміна налаштувань підвіски.', benefitEn: 'The BMS set replaces BMW front shock-tower nuts with CNC-machined titanium hardware. The solid-titanium parts are lighter than steel and individually hand-colored by heat. This is a hardware and appearance upgrade, not a suspension calibration change.',
    detailsUa: 'У набір входить 6 гайок, різьба M8×1.25, шестигранник 13 мм; замінюють BMW OE 31 31 6 769 731. Через ручне випалювання відтінок кожної гайки унікальний і може відрізнятися від фото. Накручуйте лише вручну, не використовуйте impact або електроінструмент.', detailsEn: 'The set contains six nuts with M8×1.25 threads and a 13 mm hex, replacing BMW OE 31 31 6 769 731. Hand heat-coloring makes each finish unique and slightly different from photos. Thread by hand and do not use impact or powered tools.',
    fitUa: 'Для BMW E-Chassis із відповідними передніми опорами та різьбою. Підтвердьте OE номер гайки й кількість перед монтажем; затягуйте моментом із сервісної документації BMW.', fitEn: 'For BMW E-Chassis vehicles with matching front towers and thread specification. Confirm the OE nut reference and quantity before installation; use BMW service-manual torque.'
  },
  'bms-billet-strut-cross-braces-for-g30-g31-5-series-bmw': {
    titleUa: 'BMS Billet Strut Cross Braces для BMW 5 Series G30/G31 і 8 Series G14/G15/G16', titleEn: 'BMS Billet Strut Cross Braces for BMW 5 Series G30/G31 and 8 Series G14/G15/G16',
    shortUa: 'Пара billet-алюмінієвих розпірок зміцнює передню частину кузова; оберіть колір для свого шасі.', shortEn: 'Pair of billet-aluminum braces reinforces the front chassis; choose a finish for the correct chassis.',
    benefitUa: 'BMS strut braces замінюють передні заводські розпірки та зменшують деформацію кузова під боковим навантаженням. Суцільні billet-алюмінієві деталі допомагають зберігати жорсткість передньої частини під час поворотів і надають моторному відсіку завершеного вигляду.', benefitEn: 'BMS strut braces replace the front factory braces and reduce chassis flex under cornering load. Solid billet-aluminum parts support front-end rigidity through turns and add a finished look to the engine bay.',
    detailsUa: 'Товар продається парою; оберіть анодований Black, Red або Blue, або Silver якщо доступний. Установка болтами, без свердління; використання штатних точок кріплення. У конфігураторі оберіть тільки підтверджений для вашого кузова варіант.', detailsEn: 'Sold as a pair. Choose anodized Black, Red, or Blue, or Silver when available. Bolt-on installation uses factory mounting points and requires no drilling. Select only the option confirmed for your chassis.',
    fitUa: 'BMW 5 Series G30/G31/G38 та 8 Series G14/G15/G16 у двигунах і роках, перелічених Burger, зокрема B46/B48/B58 і окремих V8-версій. Звірте кузов і конструкцію штатних розпірок до замовлення.', fitEn: 'For Burger-listed BMW 5 Series G30/G31/G38 and 8 Series G14/G15/G16 engines and years, including B46/B48/B58 and selected V8 applications. Verify chassis and factory-brace layout before ordering.'
  },
  'bms-billet-strut-cross-braces-for-bmw-x3-x4-x3m-x4m': {
    titleUa: 'BMS Billet Strut Cross Braces для BMW X3 / X4 / X3M / X4M — пара', titleEn: 'BMS Billet Strut Cross Braces for BMW X3 / X4 / X3M / X4M — Pair',
    shortUa: 'Пара billet-розпірок для кузовів G01/G02 і F97/F98: додає жорсткості передньому шасі та зменшує flex.', shortEn: 'Pair of billet braces for G01/G02 and F97/F98; adds front-chassis rigidity and reduces flex.',
    benefitUa: 'Ці однокомпонентні BMS розпірки замінюють передні strut braces BMW та підсилюють з’єднання між опорами. За описом Burger, вони зменшують flex кузова в поворотах, водночас оновлюючи вигляд моторного відсіку.', benefitEn: 'These one-piece BMS braces replace the front BMW strut braces and reinforce the connection between towers. Burger describes reduced chassis flex in corners along with an updated engine-bay appearance.',
    detailsUa: 'У коробці пара. Оберіть анодований колір: Blue, Red, Black або Silver. Версія використовує штатні кріпильні болти й встановлюється без свердління; затягніть кріплення за сервісною специфікацією BMW.', detailsEn: 'The package contains a pair. Choose anodized Blue, Red, Black, or Silver. This version reuses factory mounting bolts and installs without drilling; tighten hardware to BMW service specifications.',
    fitUa: 'За Burger: BMW X3/X4 G01/G02 із B48/B58 та X3M/X4M F97/F98 із S58 у вказаних роках. Не обирайте варіант тільки за назвою X3/X4 — звірте покоління кузова.', fitEn: 'Burger lists BMW X3/X4 G01/G02 with B48/B58 and X3M/X4M F97/F98 with S58 in specified years. Do not select by X3/X4 name alone; confirm chassis generation.'
  },
  'bms-billet-strut-cross-braces-for-genesis-g70': {
    titleUa: 'BMS Billet Strut Cross Braces для Genesis G70 — пара', titleEn: 'BMS Billet Strut Cross Braces for Genesis G70 — Pair',
    shortUa: 'Пара суцільних billet-алюмінієвих розпірок замінює штатні трубчасті braces та зменшує flex кузова G70.', shortEn: 'Pair of solid billet-aluminum braces replaces stock tubular braces and reduces G70 chassis flex.',
    benefitUa: 'Розпірки BMS замінюють передні штатні порожнисті трубчасті braces Genesis G70 суцільними billet-алюмінієвими деталями. Вони створені для підвищення жорсткості кузова та зменшення його руху під час поворотів; встановлення також змінює вигляд моторного відсіку.', benefitEn: 'BMS braces replace the Genesis G70 factory hollow-tube front braces with solid billet-aluminum parts. They are designed to increase chassis rigidity and reduce movement in corners while changing the engine-bay appearance.',
    detailsUa: 'У комплекті пара розпірок. Оберіть анодований колір: Black, Blue, Silver або Red. За джерелом, монтаж використовує штатні болти й точки кріплення та не вимагає свердління. Переконайтеся, що комплект охоплює саме ваш рік G70.', detailsEn: 'The package includes a pair. Choose anodized Black, Blue, Silver, or Red. Burger describes installation with factory bolts and mounting points, without drilling. Confirm the kit matches your G70 model year.',
    fitUa: 'Для Genesis G70 2018+ у версіях і роках, перелічених Burger. Звірте форму опор і заводських розпірок перед купівлею.', fitEn: 'For Burger-listed 2018+ Genesis G70 versions and years. Verify tower and factory-brace layout before purchase.'
  },
  'bms-billet-strut-cross-braces-for-bmw-g29-z4': {
    titleUa: 'BMS Billet Strut Cross Braces для BMW Z4 G29 2019+ — пара', titleEn: 'BMS Billet Strut Cross Braces for 2019+ BMW Z4 G29 — Pair',
    shortUa: 'Пара billet-розпірок для Z4 G29 посилює передню частину шасі; використовує заводське кріплення.', shortEn: 'Pair of billet braces strengthens the Z4 G29 front chassis and reuses factory hardware.',
    benefitUa: 'BMS cross braces замінюють заводські передні розпірки BMW Z4 і зменшують flex кузова в поворотах. Суцільний billet-алюміній без з’єднань додає опорам жорсткості та підкреслює вигляд моторного відсіку.', benefitEn: 'BMS cross braces replace the factory front braces on the BMW Z4 and reduce chassis flex in corners. One-piece billet aluminum supports tower rigidity and adds a clean engine-bay appearance.',
    detailsUa: 'Продається пара; у конфігураторі виберіть Black, Blue або Red. Ця версія G29 використовує штатне кріплення автомобіля. Свердління не потрібне; дотримуйтеся заводського моменту затягування.', detailsEn: 'Sold as a pair; choose Black, Blue, or Red in the selector. This G29 version reuses factory vehicle hardware. No drilling is required; follow factory torque specifications.',
    fitUa: 'Для BMW Z4 G29 30i та 40i 2019+ згідно з переліком Burger. Перед замовленням підтвердьте кузов G29 і рік випуску.', fitEn: 'For 2019+ BMW Z4 G29 30i and 40i as listed by Burger. Confirm G29 chassis and model year before ordering.'
  },
  'bms-billet-strut-cross-braces-for-2019-g20-bmw-m340i-and-m340ix': {
    titleUa: 'BMS Billet Strut Cross Braces для BMW G20/G21/G42 і 4 Series G22–G26', titleEn: 'BMS Billet Strut Cross Braces for BMW G20/G21/G42 and 4 Series G22–G26',
    shortUa: 'Оберіть кузов і колір: седани G20/G21/G42 із кріпленням у комплекті або купе/4 Series зі штатним hardware.', shortEn: 'Choose chassis and finish: G20/G21/G42 with included hardware or 4 Series using factory hardware.',
    benefitUa: 'Пара суцільних billet-алюмінієвих розпірок замінює штатні передні braces та допомагає зменшити flex кузова під час поворотів. Це болтове підсилення шасі без свердління; не призначене для зміни підвіски чи кліренсу.', benefitEn: 'A pair of solid billet-aluminum braces replaces the factory front braces and helps reduce chassis flex through corners. This is a bolt-on chassis upgrade without drilling; it does not change suspension tuning or ride height.',
    detailsUa: 'У конфігураторі оберіть кузовну групу та один із чотирьох кольорів: Red, Silver, Blue або Black. Для G20/G21/G42 Burger указує монтажне кріплення в комплекті; для G22/G23/G26 використовується factory hardware. Важливо вибрати правильну групу: комплекти відрізняються кріпленням.', detailsEn: 'Select the chassis group and one of four finishes: Red, Silver, Blue, or Black. Burger lists included mounting hardware for G20/G21/G42, while G22/G23/G26 reuse factory hardware. Choose the correct group because the mounting packages differ.',
    fitUa: 'Для перелічених BMW G20/G21 3 Series, G42 2 Series та G22/G23/G26 4 Series. Виробник застерігає про несумісність із BMS B58 Billet Intake; інший BMS Competition Intake зазначений як сумісний. Перевірте наявність aftermarket впуску.', fitEn: 'For listed BMW G20/G21 3 Series, G42 2 Series, and G22/G23/G26 4 Series. The supplier warns these do not fit the BMS B58 Billet Intake; a separate BMS Competition Intake is listed as compatible. Check for aftermarket intake interference.'
  },
  'bms-billet-strut-cross-brace-bolts-for-kia-stinger-genesis-g70': {
    titleUa: 'BMS Strut Brace Bolts для Kia Stinger / Genesis G70 — 4 шт.', titleEn: 'BMS Strut Brace Bolts for Kia Stinger / Genesis G70 — 4 Pack',
    shortUa: 'Комплект із 4 декоративних кріпильних болтів 10×1.25 мм: billet-алюміній або ручне titanium burn.', shortEn: 'Four decorative 10×1.25 mm bolts in billet aluminum or hand-colored titanium.',
    benefitUa: 'Ці болти замінюють штатне кріплення strut cross braces Kia Stinger та Genesis G70, додаючи акцент моторному відсіку. Це косметичне оновлення кріплення, яке використовує штатні точки та не потребує свердління.', benefitEn: 'These bolts replace the factory strut cross-brace hardware on Kia Stinger and Genesis G70, adding an engine-bay accent. This is a hardware appearance upgrade using factory mounting points without drilling.',
    detailsUa: 'У комплекті 4 болти з різьбою M10×1.25. Оберіть Red/Blue/Black/Silver billet-алюміній або Hand Burned Rainbow/Blue Titanium. Титанові деталі мають індивідуальний візерунок, тому відтінок відрізняється між комплектами. Перевірте різьбу та довжину штатного кріплення.', detailsEn: 'The set contains four bolts with M10×1.25 threads. Choose Red/Blue/Black/Silver billet aluminum or Hand Burned Rainbow/Blue Titanium. Titanium pieces have individual heat-color patterns, so appearance varies by set. Confirm thread and factory bolt length.',
    fitUa: 'Для кріплень розпірок Kia Stinger і Genesis G70 із різьбою M10×1.25. Це лише болти, не strut braces.', fitEn: 'For Kia Stinger and Genesis G70 brace mounts using M10×1.25 threads. Bolts only; strut braces are not included.'
  },
  'bms-billet-strut-cross-braces-for-kia-stinger': {
    titleUa: 'BMS Billet Strut Cross Braces для Kia Stinger 2018–2023 — пара', titleEn: 'BMS Billet Strut Cross Braces for 2018–2023 Kia Stinger — Pair',
    shortUa: 'Пара суцільних billet-розпірок замінює заводські braces Stinger і додає жорсткості передній частині кузова.', shortEn: 'Pair of solid billet braces replaces Stinger factory braces and adds front-chassis rigidity.',
    benefitUa: 'BMS cross braces замінюють заводські трубчасті розпірки Kia Stinger деталями з цільного billet-алюмінію. Вони розраховані на зменшення flex передньої частини кузова під час поворотів і змінюють вигляд моторного відсіку.', benefitEn: 'BMS cross braces replace the Kia Stinger factory tubular braces with solid billet-aluminum parts. They are designed to reduce front-chassis flex through corners and update the engine-bay appearance.',
    detailsUa: 'У комплекті пара. Оберіть анодований Blue, Black, Silver або Red; варіант High Gloss Black має окреме порошкове покриття й може бути недоступним. Монтаж виконується замість штатних braces, без свердління. Перевірте наявність опції кольору окремо від її опису.', detailsEn: 'The set contains a pair. Choose anodized Blue, Black, Silver, or Red; the High Gloss Black option has a separate powder-coated finish and may be unavailable. Installation replaces the factory braces without drilling. Confirm color availability separately.',
    fitUa: 'Для Kia Stinger 2018–2023 у версіях, перелічених Burger. Перевірте конструкцію заводських розпірок і сумісність із обладнанням підкапотного простору.', fitEn: 'For Burger-listed 2018–2023 Kia Stinger versions. Check the factory-brace layout and clearance with under-hood equipment.'
  },
  'bms-g-chassis-b48-bmw-aluminum-long-turbo-inlet-upgrade': {
    titleUa: 'BMS Long Aluminum Turbo Inlet для BMW G-Chassis B48', titleEn: 'BMS Long Aluminum Turbo Inlet for BMW G-Chassis B48',
    shortUa: 'Довгий алюмінієвий inlet замінює два обмежувальні штатні елементи між впуском і турбіною на G-Chassis B48.', shortEn: 'Long aluminum inlet replaces two restrictive factory pieces between intake and turbo on G-Chassis B48.',
    benefitUa: 'Довгий BMS turbo inlet є суцільною заміною верхнього резонатора та нижнього пластикового входу турбіни. Гладкий перехід прибирає звуження на шляху повітря, прибирає штатний резонатор і може покращити відгук турбіни; фактичний результат залежить від решти впуску й налаштування.', benefitEn: 'The long BMS turbo inlet replaces the upper resonator and lower plastic turbo inlet as one assembly. Its smoother path removes factory restrictions and the resonator and may improve turbo response; actual results depend on the rest of the intake and calibration.',
    detailsUa: 'Алюмінієва труба є direct replacement для двох штатних пластикових частин, має CNC turbo fitting і зберігає штатний вигляд монтажу. Перевірте, чи потрібна саме довга версія inlet, а не коротка версія Gen 2 B48; це різні деталі.', detailsEn: 'The aluminum pipe directly replaces two factory plastic sections and uses a CNC turbo fitting in an OEM-style installation. Confirm that the long inlet is required rather than the separate short Gen 2 B48 version; they are different parts.',
    fitUa: 'Для G-Chassis BMW із B48, зокрема застосувань G42, G20/G21, G22/G23/G26 та інших, перелічених Burger. Не підходить лише на підставі позначення B48: звірте покоління кузова й впуск.', fitEn: 'For Burger-listed G-Chassis BMW with B48, including G42, G20/G21, G22/G23/G26 and other listed applications. B48 engine code alone is insufficient; verify chassis generation and intake layout.'
  },
  'g-chassis-b48-bmw-aluminum-short-turbo-inlet-upgrade': {
    titleUa: 'BMS Short Aluminum Turbo Inlet для BMW G-Chassis Gen 2 B48', titleEn: 'BMS Short Aluminum Turbo Inlet for BMW G-Chassis Gen 2 B48',
    shortUa: 'Короткий inlet для Gen 2 B48 замінює штатну пластикову трубу; розрахований на BMS Competition Air Intake.', shortEn: 'Short inlet replaces the stock Gen 2 B48 plastic pipe and is designed for the BMS Competition Air Intake.',
    benefitUa: 'Алюмінієвий короткий BMS turbo inlet замінює пластиковий штатний елемент і прибирає його акустичний резонатор. Плавніший канал зменшує локальні обмеження потоку та може поліпшити відгук турбіни. Burger визначає цю деталь як пару до BMS B48 Competition Air Intake.', benefitEn: 'The short BMS aluminum turbo inlet replaces the factory plastic section and removes its sound resonator. A smoother passage reduces local flow restrictions and may improve turbo response. Burger identifies it for use with the BMS B48 Competition Air Intake.',
    detailsUa: 'Це коротка версія inlet для Gen 2 B48; не плутайте її з довгою трубою, яка замінює верхній і нижній резонатори. Перед замовленням перевірте тип встановленого intake, покоління двигуна та наявність місця для труби.', detailsEn: 'This is the short inlet for Gen 2 B48; do not confuse it with the long pipe that replaces both upper and lower resonators. Confirm intake type, engine generation, and available clearance before ordering.',
    fitUa: 'Для G-Chassis BMW із Gen 2 B48, перелічених Burger, у поєднанні з BMS Competition Air Intake. Для штатного airbox використовуйте лише коли сумісність прямо підтверджена постачальником.', fitEn: 'For Burger-listed G-Chassis BMW with Gen 2 B48 when paired with the BMS Competition Air Intake. Use with a factory airbox only when the supplier explicitly confirms compatibility.'
  },
  'bms-high-flow-silicone-turbo-inlet-for-kia-k5-and-sonata': {
    titleUa: 'BMS High-Flow Silicone Turbo Inlet для Kia K5 / Hyundai Sonata 1.6T', titleEn: 'BMS High-Flow Silicone Turbo Inlet for Kia K5 / Hyundai Sonata 1.6T',
    shortUa: 'Силіконовий inlet замінює пластиковий резонатор і використовує OEM reference Kia 28130-L1400.', shortEn: 'Silicone inlet replaces the plastic resonator and references Kia OE 28130-L1400.',
    benefitUa: 'BMS silicone turbo inlet замінює вузький пластиковий заводський resonator pipe між впуском і турбіною. Ширший гладкий канал покликаний поліпшити потік і відгук турбіни та прибирає акустичну камеру штатної деталі. Виробник також позиціонує його як доповнення до свого intake або factory airbox.', benefitEn: 'The BMS silicone turbo inlet replaces the narrow factory plastic resonator pipe between the intake and turbo. Its wider, smoother path targets improved flow and turbo response while removing the factory acoustic chamber. The supplier describes it for use with its intake or factory airbox.',
    detailsUa: 'Труба виготовлена з армованого силікону з фірмовими fitting. Burger вказує Kia OE part 28130-L1400. Переконайтеся, що в автомобілі 1.6L Turbo, і звірте патрубки, оскільки рік початку продажу K5/Sonata відрізняється за ринком.', detailsEn: 'The inlet uses heavy-duty silicone with the listed fittings. Burger references Kia OE part 28130-L1400. Confirm the 1.6L turbo engine and check pipe connections because K5/Sonata model-year availability varies by market.',
    fitUa: 'Для Kia K5 і Hyundai Sonata 1.6L Turbo за переліком Burger: K5 2021+ та Sonata 2020+. Не переносіть сумісність на 2.0T, 2.5T чи інші двигуни.', fitEn: 'For Burger-listed Kia K5 2021+ and Hyundai Sonata 2020+ with the 1.6L turbo. Not for 2.0T, 2.5T, or other engines unless separately confirmed.'
  },
  'line-upgrade-kit-for-klm-big-turbos': {
    titleUa: 'KLM Big Turbo Braided Line Kit — вибір авто, соленоїда і 3/4 портів', titleEn: 'KLM Big Turbo Braided Line Kit — Choose Car, Solenoid, and 3/4 Port',
    shortUa: 'Армовані сталеві лінії для Turbosmart Gen V: оберіть M340i/Supra, MAC solenoid та 3-port або 4-port.', shortEn: 'Braided lines for Turbosmart Gen V; select M340i/Supra, MAC solenoid, and 3-port or 4-port.',
    benefitUa: 'Комплект замінює лінії керування зовнішнім wastegate на сталеві армовані магістралі для KLM big-turbo kit. Така лінія краще протистоїть пошкодженню від тепла, яке може вивести штатні hose з ладу та спричинити неконтрольований наддув. Це компонент керування wastegate, не паливна магістраль.', benefitEn: 'This kit replaces external-wastegate control lines with stainless braided lines for a KLM big-turbo setup. The upgraded line resists heat damage that can compromise a factory hose and lead to uncontrolled boost. It is a wastegate-control component, not a fuel line.',
    detailsUa: 'Послідовно оберіть Vehicle: M340i або Supra (B58), Add MAC solenoid: Yes/No та Port Quantity: 3-Port/4-Port. За Burger, 3-port підтримує до 2.5× тиску пружини wastegate, 4-port — до 4×; підбір робіть за турбіною та налаштуванням. Підходить тільки для Turbosmart Gen V із портами 1/8 NPT.', detailsEn: 'Select Vehicle (M340i or Supra B58), MAC solenoid (Yes/No), and Port Quantity (3-port or 4-port). Burger lists capacity up to 2.5× wastegate spring pressure for 3-port and 4× for 4-port; match the system to the turbo and tune. Only for Turbosmart Gen V with 1/8 NPT ports.',
    fitUa: 'Для KLM big turbo на BMW M340i або Toyota Supra B58 у сумісній конфігурації та Turbosmart Gen V 1/8 NPT. Перевірте кількість портів і тип wastegate до підключення.', fitEn: 'For a compatible KLM big-turbo BMW M340i or Toyota Supra B58 setup with Turbosmart Gen V 1/8 NPT. Verify port count and wastegate type before installation.'
  },
  'bms-high-flow-silicone-turbo-inlets-for-kia-stinger-genesis-g70': {
    titleUa: 'BMS High-Flow Turbo Inlets для Kia Stinger / Genesis G70 3.3T', titleEn: 'BMS High-Flow Turbo Inlets for Kia Stinger / Genesis G70 3.3T',
    shortUa: 'Оберіть патрубки для BMS intake або штатного airbox: від цього залежить правильний номер inlet.', shortEn: 'Choose inlets for BMS intake or factory airbox; the intake type determines the correct part.',
    benefitUa: 'Пара силіконових BMS turbo inlets замінює гофровані штатні патрубки перед турбінами й формує ширший перехід повітря. Це може поліпшити відгук турбін і додати звук впуску; Burger наводить приріст до близько 10 whp лише для агресивно налаштованих тестових авто, тому такий результат не гарантований.', benefitEn: 'The BMS silicone inlet pair replaces the factory accordion pipes ahead of the turbos with a wider, smoother path. It may improve turbo response and intake sound; Burger cites up to about 10 whp only on aggressively tuned test cars, so this result is not guaranteed.',
    detailsUa: 'Оберіть один тип: «For use with BMS intake only» або «For use with factory airbox only». Це різні деталі, оскільки геометрія inlet залежить від системи впуску. Джерело наводить OEM references 28140-J5350 і 28130-J5300; звірте номери, патрубки та комплектність до монтажу.', detailsEn: 'Select one type: “For use with BMS intake only” or “For use with factory airbox only.” These are different parts because inlet geometry depends on the intake system. Burger lists OE references 28140-J5350 and 28130-J5300; verify references, pipes, and package before installation.',
    fitUa: 'Для Kia Stinger GT і Genesis G70 3.3L Turbo у відповідній конфігурації впуску. Комплект для штатного airbox не підходить до BMS intake і навпаки.', fitEn: 'For Kia Stinger GT and Genesis G70 3.3L turbo with the matching intake configuration. The factory-airbox version does not fit the BMS intake version, or vice versa.'
  },
  'bms-f-series-b58-bmw-turbo-inlet-upgrade-for-f2x-240-f3x-340-440': {
    titleUa: 'BMS Aluminum Turbo Inlet для BMW F-Chassis B58 M140i / M240i / 340i / 440i', titleEn: 'BMS Aluminum Turbo Inlet for BMW F-Chassis B58 M140i / M240i / 340i / 440i',
    shortUa: 'Алюмінієвий inlet замінює пластикову штатну трубу та прибирає резонатор на BMW F-Series B58.', shortEn: 'Aluminum inlet replaces the factory plastic pipe and resonator on BMW F-Series B58.',
    benefitUa: 'BMS aluminum turbo inlet замінює обмежувальну пластикову трубу між впуском і турбіною на F-Chassis BMW B58. Гладший перехід може поліпшити потік і відгук турбіни та додає звук впуску після видалення штатного резонатора. Реальний ефект залежить від решти конфігурації.', benefitEn: 'The BMS aluminum turbo inlet replaces the restrictive factory plastic pipe between intake and turbo on F-Chassis BMW B58. A smoother passage may improve flow and turbo response, with added intake sound after removing the factory resonator. Actual results depend on the complete setup.',
    detailsUa: 'Однокомпонентна алюмінієва заміна має CNC turbo fitting і штатний вигляд монтажу. Перевірте комплектність за джерелом та огляньте сумісність із вашим intake; не вважайте всі F-Series із позначкою B58 однаковими за розташуванням патрубків.', detailsEn: 'The one-piece aluminum replacement uses a CNC turbo fitting and an OEM-style installation. Check package contents against the supplier listing and verify intake clearance; not every F-Series B58 has identical pipe routing.',
    fitUa: 'За Burger: BMW F20/F21 M140i 2015–2019, F22/F23 M240i 2016–2021, F30/F31/F34 340i 2016–2019 і F32/F33/F36 440i 2016–2020 із B58. Звірте кузов, двигун і xDrive.', fitEn: 'Burger lists 2015–2019 BMW F20/F21 M140i, 2016–2021 F22/F23 M240i, 2016–2019 F30/F31/F34 340i, and 2016–2020 F32/F33/F36 440i with B58. Verify chassis, engine, and xDrive.'
  },
  'bms-high-flow-silicone-turbo-inlet-for-n55-bmw-f2x-f3x-235-335-435-m2': {
    titleUa: 'BMS High-Flow Silicone Turbo Inlet для BMW N55 F-Series', titleEn: 'BMS High-Flow Silicone Turbo Inlet for BMW N55 F-Series',
    shortUa: 'Посилений силіконовий inlet замінює штатний резонатор і гофру для турбіни BMW N55.', shortEn: 'Reinforced silicone inlet replaces the factory resonator and accordion pipe on BMW N55.',
    benefitUa: 'BMS high-flow inlet замінює штатний пластиковий/гофрований канал перед турбіною N55 ширшою силіконовою деталлю. Вона прибирає акустичний резонатор і спрямована на рівніший потік до компресора та кращий відгук. Це компонент впуску; сам по собі він не є тюнінгом ECU.', benefitEn: 'The BMS high-flow inlet replaces the factory plastic/accordion section ahead of the N55 turbo with a wider silicone part. It removes the acoustic resonator and targets smoother flow into the compressor and improved response. It is an intake component, not an ECU tune.',
    detailsUa: 'Перед монтажем звірте форму штатної труби, турбіну та наявні кріплення з переліком Burger. Силіконова конструкція гнучкіша за штатний пластик, але не повинна перекручуватися чи торкатися гарячих поверхонь після встановлення.', detailsEn: 'Before installation, match the factory pipe shape, turbo, and fittings against the Burger listing. The silicone part is more flexible than factory plastic, but must not be twisted or contact hot surfaces after installation.',
    fitUa: 'Для перелічених BMW F2x/F3x із N55, зокрема 235i/335i/435i та M2 з відповідним N55. Не підходить автоматично до N54 або B58.', fitEn: 'For listed BMW F2x/F3x with N55, including matching 235i/335i/435i and N55 M2 applications. Not automatically compatible with N54 or B58.'
  },
  'bms-silicon-single-turbo-filter-bms_stf': {
    titleUa: 'BMS High-Temperature Silicone Single Turbo Filter для 4″ Inlet', titleEn: 'BMS High-Temperature Silicone Single Turbo Filter for 4-inch Inlet',
    shortUa: 'Оберіть синій або червоний фільтр висотою 4.5″ чи Shorty 3.75″ за доступом і простором у моторному відсіку.', shortEn: 'Choose blue or red in 4.5-inch or 3.75-inch Shorty height for available engine-bay clearance.',
    benefitUa: 'BMS silicone single-turbo filter призначений для безпосереднього монтажу на 4″ turbo inlet. Високотемпературний силіконовий фланець розрахований на тепло біля турбіни, а площа фільтрації більша за компактний елемент, згаданий Burger. Фільтр очищує повітря перед компресором; продуктивність залежить від повної конфігурації турбіни.', benefitEn: 'The BMS silicone single-turbo filter mounts directly to a 4-inch turbo inlet. Its high-temperature silicone flange is designed for heat near the turbo, and the filter area is larger than the compact element discussed by Burger. It filters inlet air; overall performance depends on the complete turbo setup.',
    detailsUa: 'Оберіть колір Red/Blue та висоту: стандартна 4.5″ або Shorty 3.75″. Джерело зазначає, що стандартний фільтр підходить до деяких FFTEC top-mount turbos, тоді як VM top-mount потребує Shorty. Для bottom-mount та інших систем виміряйте вільний простір до замовлення.', detailsEn: 'Choose Red or Blue and filter height: standard 4.5 inches or Shorty 3.75 inches. Burger notes the standard height for some FFTEC top-mount turbos and the Shorty for VM top-mount. Measure clearance for bottom-mount and other systems before ordering.',
    fitUa: 'Для систем із 4″ inlet та достатньою монтажною глибиною. Перевірте діаметр фланця й висоту до кузова/капота; тип турбокіта сам по собі не гарантує посадку.', fitEn: 'For systems with a 4-inch inlet and matching installation clearance. Verify flange diameter and clearance to bodywork/hood; turbo-kit name alone does not guarantee fit.'
  },
  'turbo-inlet-only': {
    titleUa: 'BMS Elite Aluminum Turbo Inlet для VW / Audi EA888 Gen 3', titleEn: 'BMS Elite Aluminum Turbo Inlet for VW / Audi EA888 Gen 3',
    shortUa: 'Алюмінієвий inlet прибирає обмеження штатної пластикової труби та зберігає заводські emissions fittings.', shortEn: 'Aluminum inlet replaces the restrictive factory plastic pipe while retaining factory emissions fittings.',
    benefitUa: 'BMS Elite turbo inlet замінює пластиковий штатний вхід турбіни EA888 Gen 3 гладкою алюмінієвою трубою. Burger описує кращий потік до турбокомпресора та можливий швидший відгук; штатні emission-control connections залишаються. Ця деталь не є повною системою cold-air intake.', benefitEn: 'The BMS Elite turbo inlet replaces the factory EA888 Gen 3 plastic turbo entry with a smoother aluminum pipe. Burger describes improved flow to the turbo and potential response gains while retaining factory emissions connections. This is not a complete cold-air intake system.',
    detailsUa: 'Прямий replacement зворотний до стандартного монтажу. Перевірте наявність усіх штатних emissions fittings і відсутність interference з сусідніми компонентами. Заявлені виробником відсотки потоку та приросту залежать від автомобіля й конфігурації; не трактуйте їх як гарантовану потужність.', detailsEn: 'This is a direct replacement designed to remain reversible. Confirm all factory emissions fittings are present and that neighboring components clear the pipe. Supplier airflow or power figures depend on vehicle and setup and are not guaranteed output.',
    fitUa: 'Для перелічених Audi A3/S3/TT/TTS 8V, VW MQB Golf/GTI/R, Alltrack, Tiguan, Arteon, Jetta GLI та Passat із EA888 Gen 3 1.8/2.0 TSI. Звірте покоління двигуна й турбіни.', fitEn: 'For listed Audi A3/S3/TT/TTS 8V and VW MQB Golf/GTI/R, Alltrack, Tiguan, Arteon, Jetta GLI, and Passat with EA888 Gen 3 1.8/2.0 TSI. Verify engine and turbo generation.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Призначення та користь</h3>\n<p>${item.benefitUa}</p>\n<h3>Опції та встановлення</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and benefit</h3>\n<p>${item.benefitEn}</p>\n<h3>Options and installation</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
