// Next source-checked Burger copy batch; local draft only.
export default {
  "n63-stage1": {
    "sourceUrl": "https://burgertuning.com/products/n63-stage1",
    "titleUa": "BMW N63 Stage 1 — plug-and-play тюнер для V8 4.4L",
    "titleEn": "BMW N63 Stage 1 plug-and-play tuner for 4.4L V8",
    "shortUa": "Stage 1 для BMW N63 змінює цілі наддуву, запалювання й подачі пального; до 40 whp на звичайному бензині за даними Burger. Оберіть тип роз’єму.",
    "shortEn": "BMW N63 Stage 1 adjusts boost, timing and fueling targets; Burger lists up to 40 whp on pump gas. Select the correct harness connector.",
    "descUa": "<h3>Що змінює BMW N63 Stage 1</h3>\n<p>Модуль підключається до датчиків у моторному відсіку й коригує сигнали керування наддувом, запалюванням і паливоподачею у взаємодії зі штатним DME. Це підвищує цілі наддуву під навантаженням і може зменшити відчуття турбозатримки. Burger заявляє до 40 whp на звичайному бензині та до 60 whp на паливі 93+ октану; фактичний результат залежить від октанового числа, стану авто й модифікацій.</p>\n<h3>Оберіть правильний джгут</h3>\n<p>Варіанти A і B мають різні роз’єми відповідно до періоду виробництва. Звірте тип конектора на автомобілі перед замовленням: рік моделі сам по собі не завжди визначає дату виробництва або джгут.</p>\n<h3>Сумісність</h3>\n<p>Для BMW з двигуном N63, зокрема 550i/M550i, 650i, 750i/750Li та M850i у переліку Burger. Перевірте кузов, рік, версію двигуна й фізичний роз’єм. Тюнер не замінює професійне калібрування інших змін двигуна.</p>",
    "descEn": "<h3>What BMW N63 Stage 1 changes</h3>\n<p>The module connects to engine-bay sensors and adjusts boost, ignition and fueling signals while working with the factory DME. This raises boost targets under load and may reduce perceived turbo lag. Burger lists gains of up to 40 whp on pump gas and up to 60 whp on 93+ octane fuel; actual results depend on fuel octane, vehicle condition and modifications.</p>\n<h3>Select the correct harness</h3>\n<p>Harness A and B use different connectors for their listed production periods. Check the connector on your vehicle before ordering; model year alone may not identify the production date or harness.</p>\n<h3>Fitment</h3>\n<p>For Burger-listed BMW vehicles with the N63 engine, including 550i/M550i, 650i, 750i/750Li and M850i applications. Confirm chassis, year, engine version and physical connector. The tuner does not replace calibration for other engine modifications.</p>"
  },
  "stage-1-bms-q50-q60-3-0t-performance-tuner": {
    "sourceUrl": "https://burgertuning.com/products/stage-1-bms-q50-q60-3-0t-performance-tuner",
    "titleUa": "BMS Stage 1 тюнер для Infiniti Q50 / Q60 3.0T VR30",
    "titleEn": "BMS Stage 1 tuner for Infiniti Q50 / Q60 3.0T VR30",
    "shortUa": "Plug-and-play модуль VR30 коригує сигнали наддуву, зберігаючи штатне керування ECU сумішшю та запалюванням. Базове збільшення — 3 psi.",
    "shortEn": "The VR30 plug-and-play module adjusts boost signals while the factory ECU retains timing and fueling control. Default boost increase is 3 psi.",
    "descUa": "<h3>Що дає Stage 1 для VR30</h3>\n<p>Модуль підключається до двох датчиків у моторному відсіку та коригує сигнали керування наддувом. Він не змінює штатний сигнал опорного тиску у впускному колекторі, тож ECU продовжує розраховувати запалювання й паливоподачу за власними даними. Заводське базове налаштування додає 3 psi до штатного наддуву; для зміни параметра потрібен додатковий BMS data cable.</p>\n<h3>Встановлення й налаштування</h3>\n<p>За описом Burger, модуль під’єднується plug-and-play до доступних датчиків. Його можна використовувати окремо або разом із flash-калібруванням, якщо це підтримує конкретне налаштування. Підбирайте паливо та калібрування відповідно до конфігурації двигуна й уникайте непідтверджених цілей наддуву.</p>\n<h3>Сумісність</h3>\n<p>Для Infiniti Q50 та Q60 із 3.0T V6 VR30 за списком Burger. Перед купівлею звірте модель, рік, роз’єми датчиків і поточні модифікації автомобіля.</p>",
    "descEn": "<h3>What Stage 1 does for the VR30</h3>\n<p>The module connects to two accessible engine-bay sensors and adjusts boost-control signals. It leaves the factory manifold-pressure reference intact, allowing the ECU to continue calculating timing and fueling from its own data. Burger's default setting adds 3 psi over stock; changing the boost setting requires an optional BMS data cable.</p>\n<h3>Installation and tuning</h3>\n<p>Burger describes a plug-and-play connection to accessible sensors. The module can be used on its own or with a compatible flash calibration. Match fuel and calibration to the engine setup and avoid boost targets that have not been validated for the vehicle.</p>\n<h3>Fitment</h3>\n<p>For Burger-listed Infiniti Q50 and Q60 vehicles with the 3.0T VR30 V6. Confirm model, year, sensor connectors and existing modifications before ordering.</p>"
  },
  "fuel-it-bmw-e-chassis-stage-1-lpfp-upgrade": {
    "sourceUrl": "https://burgertuning.com/products/fuel-it-bmw-e-chassis-stage-1-lpfp-upgrade",
    "titleUa": "Fuel-It! Stage 1 LPFP для BMW E-Series N54 / N55",
    "titleEn": "Fuel-It! Stage 1 LPFP upgrade for BMW E-Series N54 / N55",
    "shortUa": "Лінійний Walbro 255LPH Stage 1 підтримує штатний LPFP і, за даними Burger, дає близько 50% більше потоку. Оберіть комплект із насосом або без.",
    "shortEn": "The inline Walbro 255LPH Stage 1 supports the factory LPFP and is listed for about 50% more flow. Choose the kit with or without the pump.",
    "descUa": "<h3>Що змінює Stage 1 LPFP</h3>\n<p>Цей апгрейд додає допоміжний низьконапірний насос Walbro 255 LPH послідовно зі штатним паливним насосом BMW. Burger вказує приблизно на 50% більший потік у поєднанні зі штатним LPFP. Це допомагає підтримати подачу пального в модифікованих N54/N55, але не є гарантією потужності: результат залежить від усієї паливної системи, тиску та налаштування.</p>\n<h3>Що містять варіанти</h3>\n<p>«No thank you» — комплект проводів і з’єднань без насоса Walbro; насос потрібно мати окремо. «Yes» — зібраний комплект із насосом Walbro 255 LPH, готовий для встановлення разом зі штатним насосом. Оберіть відповідно до наявних деталей.</p>\n<h3>Сумісність і монтаж</h3>\n<p>Для перелічених BMW E-Series із N54 або N55; точні дати виробництва відрізняються за моделлю та кузовом. Перевірте список застосувань Burger і паливні з’єднання свого авто. Монтаж паливної системи має виконуватися без витоків та з перевіркою тиску.</p>",
    "descEn": "<h3>What the Stage 1 LPFP upgrade changes</h3>\n<p>This upgrade adds a Walbro 255 LPH low-pressure pump in line with the factory BMW fuel pump. Burger lists approximately 50% more flow when used with the stock LPFP. It can support fueling on modified N54/N55 builds, but does not guarantee a power level; results depend on the complete fuel system, pressure and calibration.</p>\n<h3>What each option includes</h3>\n<p>“No thank you” is the wiring and connection kit without the Walbro pump; source the pump separately. “Yes” is the assembled kit with the Walbro 255 LPH pump, ready to install with the factory pump. Choose based on the parts you already have.</p>\n<h3>Fitment and installation</h3>\n<p>For Burger-listed BMW E-Series applications with N54 or N55 engines; production dates vary by model and chassis. Check Burger's fitment list and your vehicle's fuel connections. Installation must be leak-free and followed by a fuel-pressure check.</p>"
  },
  "stage-1-stage-2-upgrade-kit-for-bms-high-flow-mazda-3-intake": {
    "sourceUrl": "https://burgertuning.com/products/stage-1-stage-2-upgrade-kit-for-bms-high-flow-mazda-3-intake",
    "titleUa": "BMS Stage 1 → Stage 2 intake upgrade для Mazda 3 Turbo 2.5L",
    "titleEn": "BMS Stage 1 to Stage 2 intake upgrade for Mazda 3 Turbo 2.5L",
    "shortUa": "Комплект додає до наявного BMS Stage 1 Intake вторинну трубу 3″, силіконову муфту й хомути. Оберіть глянцеве або матове покриття.",
    "shortEn": "Adds a secondary 3-inch intake pipe, silicone coupler and clamps to an existing BMS Stage 1 intake. Choose gloss or matte finish.",
    "descUa": "<h3>Що дає перехід на Stage 2</h3>\n<p>Це комплект модернізації для власників наявного BMS Stage 1 Intake на Mazda 3 Turbo 2.5L. Він додає вторинну збільшену впускну трубу діаметром 3″, силіконову муфту 3″ та два хомути, щоб розширити систему до конфігурації Stage 2.</p>\n<h3>Вибір покриття та комплектність</h3>\n<p>Оберіть глянцеве або матове покриття труби. Ця картка є саме апгрейдом Stage 1 → Stage 2 і розрахована на наявний Stage 1 intake; повна базова система Stage 1 тут не включена. Перевірте, що ваш початковий комплект відповідає зазначеній системі BMS перед замовленням.</p>\n<h3>Сумісність</h3>\n<p>Для Mazda 3 2021+ із турбодвигуном SKYACTIV-G 2.5L за списком Burger. Перед встановленням перевірте наявність Stage 1 intake та відповідність конфігурації моторного відсіку.</p>",
    "descEn": "<h3>What the Stage 2 upgrade adds</h3>\n<p>This upgrade is for owners who already have the BMS Stage 1 Intake on a Mazda 3 Turbo 2.5L. It adds a larger secondary 3-inch intake pipe, a 3-inch silicone coupler and two clamps to extend the system to the Stage 2 configuration.</p>\n<h3>Finish and package contents</h3>\n<p>Choose gloss or matte finish for the pipe. This listing is the Stage 1-to-Stage 2 upgrade and assumes the Stage 1 intake is already installed; the complete Stage 1 base system is not included. Confirm your existing intake matches the specified BMS system before ordering.</p>\n<h3>Fitment</h3>\n<p>For 2021+ Mazda 3 with the SKYACTIV-G 2.5L turbo engine, as listed by Burger. Verify that the Stage 1 intake is present and that the engine-bay configuration matches before installation.</p>"
  }
};
