// Source-checked cooling and JB+ product copy; local draft only.
const rows = {
  'b58-turbo-intake-heat-shield': {
    titleUa: 'BMS Turbo / Intake Heat Shield для BMW / Supra B58 — Gen 1 / 2 / 3', titleEn: 'BMS Turbo / Intake Heat Shield for BMW / Supra B58 — Gen 1 / 2 / 3',
    shortUa: '8 мм тепловий екран відводить променисте тепло від турбіни й колектора; перевірте покоління B58.', shortEn: '8 mm heat shield blocks radiant turbo/manifold heat; verify B58 generation before ordering.',
    benefitUa: 'BMS heat shield відокремлює впуск і сусідні компоненти від променистого тепла турбіни та випускного колектора B58. Він допомагає стримувати heat soak у моторному відсіку й підтримувати нижчу температуру впускного повітря; це теплозахист, а не гарантія приросту потужності.', benefitEn: 'The BMS heat shield separates the intake and surrounding components from radiant heat at the B58 turbo and exhaust manifold. It helps limit engine-bay heat soak and support lower intake temperatures; it is a heat-management part, not a guaranteed power gain.',
    detailsUa: 'Екран завтовшки приблизно 8 мм (0.3″) встановлюється болтами у штатні точки й підходить до OE та hybrid turbos за описом Burger. Опція Engine має Gen1, Gen2 і Gen3, але основний fitment-текст джерела підтверджує Gen2/Gen3; для Gen1 перед продажем потрібне окреме підтвердження.', detailsEn: 'The shield is about 8 mm (0.3 in) thick, installs with factory bolts, and is listed for OE and hybrid turbos. The Engine selector offers Gen1, Gen2, and Gen3, but the supplier fitment text specifically confirms Gen2/Gen3; confirm Gen1 separately before sale.',
    fitUa: 'BMW і Toyota Supra з B58 у переліку Burger. Оберіть покоління двигуна; для Gen1 звірте установчі розміри до замовлення через розбіжність у джерелі.', fitEn: 'For Burger-listed BMW and Toyota Supra B58 applications. Select the engine generation; confirm Gen1 dimensions before ordering because the source text is inconsistent.'
  },
  'bms-g-chassis-b58-bmw-transmission-oil-cooler': {
    titleUa: 'BMS High-Capacity Automatic Transmission Cooler для BMW G-Chassis / Supra B58', titleEn: 'BMS High-Capacity Automatic Transmission Cooler for BMW G-Chassis / Supra B58',
    shortUa: 'Повітряний радіатор замінює малий factory heat exchanger і знижує теплове навантаження АКПП.', shortEn: 'Air-to-fluid radiator replaces the small factory exchanger to reduce automatic-transmission heat.',
    benefitUa: 'Комплект BMS замінює невеликий coolant-to-transmission heat exchanger окремим повітряним радіатором. Більша поверхня охолодження допомагає знижувати температуру ATF під час високого навантаження й послідовних заїздів, коли штатний теплообмінник може не відводити надлишок тепла.', benefitEn: 'The BMS kit replaces the small coolant-to-transmission heat exchanger with a dedicated air-to-fluid radiator. Greater cooling area helps reduce ATF temperature under sustained load and repeated runs when the stock exchanger may be overwhelmed.',
    detailsUa: 'За Burger, площа поверхні на 50% більша за заводський cooler; комплект встановлюється перед радіатором і використовує наявні отвори. OE reference: 17219494828. Це комплект для автоматичної трансмісії; до замовлення звірте точну версію коробки й кузов.', detailsEn: 'Burger lists 50% more surface area than the factory cooler. The kit mounts ahead of the radiator using existing openings. OE reference: 17219494828. This is for automatic transmissions; verify exact gearbox and chassis before ordering.',
    fitUa: 'Для BMW G-Chassis B58 і Toyota Supra з автоматичною трансмісією у роках/версіях, перелічених Burger. Не для механічної коробки або іншого покоління без підтвердження.', fitEn: 'For Burger-listed BMW G-Chassis B58 and Toyota Supra with automatic transmission. Not for manual gearboxes or other generations unless confirmed.'
  },
  'improved-racing-bmw-oil-cooler-thermostat': {
    titleUa: 'Improved Racing 180°F Oil Thermostat для BMW — колір і адаптер ліній', titleEn: 'Improved Racing 180°F Oil Thermostat for BMW — Color and Line Adapter',
    shortUa: '180°F термостат регулює потік до масляного охолоджувача; оберіть колір і чи потрібен заводський line adapter.', shortEn: '180°F thermostat controls oil-cooler flow; choose color and factory-line adapter option.',
    benefitUa: 'Термостатичний адаптер Improved Racing керує потоком моторної оливи через зовнішній oil cooler. Він сприяє швидкому прогріванню, запобігає зайвому переохолодженню та відкриває повну продуктивність охолоджувача за потреби; це відрізняється від вільного байпаса без температурного регулювання.', benefitEn: 'The Improved Racing thermostat adapter regulates engine-oil flow through an external oil cooler. It supports warm-up, helps prevent overcooling, and provides full cooler flow when needed, unlike an unrestricted bypass without temperature control.',
    detailsUa: 'Оберіть Silver або Black, потім Add Factory Oil Cooler Line Adapter: Yes/No. Опційний адаптер дає змогу використати заводські масляні лінії; без нього конфігурація може вимагати aftermarket cooler і AN fittings. Для частини SUV із water-to-oil exchanger потрібна інша схема підключення — перевірте її до монтажу.', detailsEn: 'Choose Silver or Black, then Factory Oil Cooler Line Adapter: Yes/No. The optional adapter allows factory oil lines; without it, an aftermarket cooler and AN fittings may be required. Some SUVs use a water-to-oil exchanger and need different plumbing; confirm the setup before installation.',
    fitUa: 'BMW N20, N26, N51, N52, N53, N54, N55 і S55 у відповідній системі зовнішнього масляного охолодження. Звірте тип теплообмінника та ліній; не встановлюйте без перевірки масляного маршруту.', fitEn: 'For BMW N20, N26, N51, N52, N53, N54, N55, and S55 with the matching external oil-cooling system. Verify exchanger and line type; do not install without confirming oil routing.'
  },
  'bms-intercooler-stencil': {
    titleUa: 'BMS Intercooler Stencil — трафарет логотипа для FMIC', titleEn: 'BMS Intercooler Stencil — Logo Template for FMIC',
    shortUa: 'Клейкий трафарет наносить логотип BMS на front-mount intercooler перед фарбуванням.', shortEn: 'Adhesive stencil applies a BMS logo to a front-mount intercooler before painting.',
    benefitUa: 'Трафарет BMS допомагає нанести фірмовий логотип на передній front-mount intercooler за допомогою фарби. Він задає чіткий контур без друкованої наклейки, яка може відклеїтися від гарячої поверхні.', benefitEn: 'The BMS stencil helps paint the brand logo onto a front-mount intercooler. It provides a defined outline without leaving a printed decal that could lift from a hot surface.',
    detailsUa: 'Наклейте трафарет на чисту поверхню кулера, закрийте малярною маскою ділянки від overspray і нанесіть фарбу. Burger рекомендує високотемпературну фарбу. Трафарет і фарба не замінюють intercooler; у джерелі є можливість придбання разом із кулером.', detailsEn: 'Apply the stencil to a clean cooler surface, mask surrounding areas against overspray, then paint. Burger recommends high-temperature paint. The stencil and paint do not include or replace an intercooler; the source offers it alongside a cooler.',
    fitUa: 'Для рівної поверхні FMIC, яку можна безпечно фарбувати. Перед нанесенням переконайтеся, що фарба сумісна з покриттям кулера.', fitEn: 'For a flat FMIC surface that can be safely painted. Confirm paint compatibility with the cooler finish before application.'
  },
  'e-chassis-bmw-race-intercooler-silicone-replacements': {
    titleUa: 'Replacement Silicone Couplers для BMS BMW E-Chassis RACE Intercooler', titleEn: 'Replacement Silicone Couplers for BMS BMW E-Chassis RACE Intercooler',
    shortUa: 'Змінні силіконові з’єднувальні муфти для сумісного BMS Race intercooler E-Chassis.', shortEn: 'Replacement silicone couplers for the compatible BMS E-Chassis Race intercooler.',
    benefitUa: 'Ці силіконові couplers з’єднують патрубки із сумісним BMS Race intercooler на BMW E-Chassis. Заміна потрібна, коли муфта потріскалася, розм’якшилася або не тримає наддув; це сервісні з’єднання, не сам intercooler.', benefitEn: 'These silicone couplers connect charge pipes to a compatible BMS E-Chassis Race intercooler. Replace them if a coupler cracks, softens, or no longer holds boost; these are service connectors, not an intercooler.',
    detailsUa: 'У товарі лише змінні муфти за переліком Burger. Патрубки, кулер, clamps і кріплення не входять, якщо їх окремо не вказано в замовленні. Перед покупкою звірте діаметр і тип intercooler.', detailsEn: 'The listing is for the replacement couplers described by Burger. Pipes, cooler, clamps, and hardware are not included unless separately listed. Confirm diameter and intercooler type before ordering.',
    fitUa: 'Для відповідного BMS Race intercooler на BMW E-Chassis. Не підбирайте за поколінням кузова без перевірки розміру муфт.', fitEn: 'For the matching BMS Race intercooler on BMW E-Chassis. Do not select by chassis generation alone; verify coupler size.'
  },
  'bms-high-capacity-intercooler-heat-exchanger-for-f80-m3-f82-f83-m4': {
    titleUa: 'BMS High-Capacity Heat Exchanger для BMW S55 F80 M3 / F82 F83 M4', titleEn: 'BMS High-Capacity Heat Exchanger for BMW S55 F80 M3 / F82 F83 M4',
    shortUa: 'Збільшений bolt-in heat exchanger подвоює площу охолодження S55 відносно штатного блока.', shortEn: 'Larger bolt-in heat exchanger doubles S55 cooling area versus the factory unit.',
    benefitUa: 'BMS heat exchanger замінює штатний теплообмінник наддувного повітря на S55 на блок із більшою площею охолодження та об’ємом рідини. Це допомагає контролювати температуру повітря на послідовних заїздах і зменшує heat soak, коли штатний cooler перевантажується.', benefitEn: 'The BMS heat exchanger replaces the factory S55 charge-air cooling unit with a larger core and fluid capacity. It helps manage intake temperatures during repeated runs and reduces heat soak when the stock cooler is overwhelmed.',
    detailsUa: 'За джерелом, площа поверхні приблизно вдвічі більша, а об’єм рідини — більш ніж утричі за штатний блок. Монтаж bolt-in і зворотний без доробок; товар у назві Burger позначений out of stock, тож наявність треба перевірити до продажу.', detailsEn: 'Burger lists about twice the surface area and more than three times the fluid volume of the stock unit. Installation is bolt-in and reversible without modification. The supplier title marks it out of stock; verify availability before sale.',
    fitUa: 'Для BMW F80 M3 2015–2019 та F82/F83 M4 2015–2020 із S55, включно з GTS/CS у списку Burger. Не плутайте з водяним intercooler core.', fitEn: 'For Burger-listed 2015–2019 BMW F80 M3 and 2015–2020 F82/F83 M4 with S55, including GTS/CS. Do not confuse it with the water-side intercooler core.'
  },
  'kia-stinger-intercooler': {
    titleUa: 'BMS High-Performance Intercooler для Kia Stinger / Genesis G70 3.3T', titleEn: 'BMS High-Performance Intercooler for Kia Stinger / Genesis G70 3.3T',
    shortUa: 'Оберіть версію Stinger або G70; великий direct-fit core знижує heat soak на 3.3T.', shortEn: 'Choose Stinger or G70 version; oversized direct-fit core reduces heat soak on the 3.3T.',
    benefitUa: 'BMS intercooler має збільшений core для охолодження стисненого повітря на Kia/Genesis 3.3T. Більший теплообмінник зменшує перепад тиску та допомагає утримувати продуктивність під час повторних прискорень, коли стандартна деталь нагрівається.', benefitEn: 'The BMS intercooler uses a larger core to cool compressed air on Kia/Genesis 3.3T applications. Increased cooling area reduces pressure drop and helps maintain performance during repeated pulls when the stock unit heat-soaks.',
    detailsUa: 'Оберіть Type: Stinger або G70. Це direct replacement зі стандартними з’єднаннями; у core є порт 1/8″ NPT для WMI або Fuel-It! CPI. Розмір core — приблизно 24″ × 11″ × 3.5″; перед купівлею звірте конфігурацію авто та потребу в порті.', detailsEn: 'Choose Type: Stinger or G70. This is a direct replacement with factory-style connections and a 1/8-inch NPT port for WMI or Fuel-It! CPI. Core dimensions are about 24 × 11 × 3.5 inches; confirm vehicle layout and port requirements before ordering.',
    fitUa: 'Kia Stinger 3.3L Turbo 2018–2023 або Genesis G70 3.3L Turbo 2018+ у відповідному варіанті. Австралійським застосуванням Burger радить уточнити посадку перед замовленням.', fitEn: 'For 2018–2023 Kia Stinger 3.3L turbo or 2018+ Genesis G70 3.3L turbo in the matching version. Burger asks Australian buyers to confirm fitment before ordering.'
  },
  's63tu-dual-intercoolers-for-bmw-m5-m6': {
    titleUa: 'BMS Performance Intercoolers для BMW S63TU F10 M5 / F12 F13 M6', titleEn: 'BMS Performance Intercoolers for BMW S63TU F10 M5 / F12 F13 M6',
    shortUa: 'Пара charge-air coolers із більшим core знижує heat soak і має порти 1/8″ NPT для WMI/CPI.', shortEn: 'Pair of larger-core charge-air coolers reduces heat soak and includes 1/8-inch NPT WMI/CPI ports.',
    benefitUa: 'Пара BMS intercoolers збільшує охолодження наддувного повітря на двигуні S63TU, допомагаючи зменшувати heat soak під час довгих швидкісних заїздів. Більша площа core зменшує перепад тиску й підтримує роботу турбін у повторних навантаженнях.', benefitEn: 'The BMS intercooler pair increases charge-air cooling on the S63TU and helps reduce heat soak during sustained high-speed runs. A larger core area reduces pressure drop and supports turbo operation under repeated load.',
    detailsUa: 'У комплекті пара прямозамінних кулерів із литими end tanks, двома портами 1/8″ NPT за intercooler, покриттям і монтажним hardware за описом Burger. Порти призначені для додавання WMI або CPI лише за відповідною системою; переконайтеся, що всі порти заглушені, якщо вони не використовуються.', detailsEn: 'The package is a pair of direct-replacement coolers with cast end tanks, two post-intercooler 1/8-inch NPT ports, finish, and installation hardware as listed by Burger. Ports can support WMI or CPI when configured; cap unused ports securely.',
    fitUa: 'Для BMW F10 M5/F12 F13 M6 із S63TU у конфігураціях Burger. Звірте OE references 17517843119 і 17517843123 перед замовленням.', fitEn: 'For Burger-listed BMW F10 M5/F12 F13 M6 with S63TU. Verify OE references 17517843119 and 17517843123 before ordering.'
  },
  'phoenix-racing-high-capacity-replacement-s55-m3-m4-f8x-intercooler': {
    titleUa: 'Phoenix Racing High-Capacity Intercooler для BMW S55 F8x M2C / M3 / M4', titleEn: 'Phoenix Racing High-Capacity Intercooler for BMW S55 F8x M2C / M3 / M4',
    shortUa: 'S55 replacement intercooler із core на 60% більшим, dual-pass і прямим bolt-on монтажем.', shortEn: 'S55 replacement intercooler with a 60% larger core, dual-pass design, and bolt-on fitment.',
    benefitUa: 'Phoenix Racing intercooler має високощільний core приблизно на 60% більший за штатний і dual-pass конструкцію з flow diverters. Він призначений підвищити охолодження повітря наддуву та зменшити heat soak на S55 під час повторних прискорень.', benefitEn: 'The Phoenix Racing intercooler uses a high-density core about 60% larger than stock and a dual-pass layout with flow diverters. It is designed to improve charge-air cooling and reduce heat soak on the S55 during repeated pulls.',
    detailsUa: 'Цільноалюмінієва герметична конструкція має литі end tanks і заводські точки підключення для прямого bolt-on монтажу. Установка замінює штатний cooler; перевірте ущільнення та повітряні з’єднання після робіт.', detailsEn: 'The sealed all-aluminum assembly uses cast end tanks and factory-style connections for bolt-on installation. It replaces the factory cooler; check seals and charge connections after fitting.',
    fitUa: 'Для BMW F87 M2 Competition 2018–2022 тільки з S55, F80 M3 2015–2020 і F82/F83 M4 2015–2020, включно з GTS/CS у переліку Burger. Не для M2 з N55.', fitEn: 'For Burger-listed 2018–2022 BMW F87 M2 Competition with S55 only, 2015–2020 F80 M3, and 2015–2020 F82/F83 M4 including GTS/CS. Not for N55 M2.'
  },
  'sport-oil-cooler-valve': {
    titleUa: 'Sport Oil Cooler Valve для BMW N54 / N55 — зовнішній oil cooler', titleEn: 'Sport Oil Cooler Valve for BMW N54 / N55 — External Oil Cooler',
    shortUa: 'Менш обмежувальний клапан збільшує потік до штатного зовнішнього масляного радіатора.', shortEn: 'Less-restrictive valve increases flow to the factory external engine-oil cooler.',
    benefitUa: 'Sport oil cooler valve збільшує потік моторної оливи до штатного fender-mounted oil-to-air cooler на BMW N54/N55. За описом Burger, це може знизити температуру оливи під тривалим навантаженням і підтримати стабільнішу роботу; клапан не замінює сам радіатор.', benefitEn: 'The sport oil-cooler valve increases engine-oil flow to the factory fender-mounted oil-to-air cooler on BMW N54/N55. Burger says it may lower oil temperature under sustained load and support consistent operation; it does not replace the cooler itself.',
    detailsUa: 'CNC-оброблений анодований клапан є зворотною заміною та працює з OE BMW 11427573212 / 11427564892. Потрібен зовнішній sport oil cooler. N54 з датою виробництва до або включно з березнем 2007 не підходить; перевірте door-jamb build date перед замовленням.', detailsEn: 'The CNC-machined, anodized valve is a reversible replacement and works with OE BMW 11427573212 / 11427564892. An external sport oil cooler is required. N54 cars built on or before March 2007 are not compatible; check the door-jamb build date before ordering.',
    fitUa: 'BMW N54/N55 із зовнішнім двигунним oil cooler; для N54 перевірте дату виробництва та OE клапана. Не для системи лише з water-to-oil exchanger.', fitEn: 'For BMW N54/N55 with an external engine-oil cooler; verify build date and OE valve on N54. Not for a water-to-oil-only system.'
  },
  'bms-replacement-intercooler-for-e-chassis-bmw': {
    titleUa: 'BMS Replacement Intercooler для BMW E-Chassis N54 / N55', titleEn: 'BMS Replacement Intercooler for BMW E-Chassis N54 / N55',
    shortUa: 'Збільшений direct-fit intercooler знижує heat soak на E-Chassis N54/N55; зворотний монтаж.', shortEn: 'Larger direct-fit intercooler reduces heat soak on E-Chassis N54/N55 and remains reversible.',
    benefitUa: 'Збільшений BMS intercooler має більшу площу core, ніж штатний, щоб відводити більше тепла від наддувного повітря. Це допомагає утримувати продуктивність під час тривалих прискорень і повторних заїздів; заявлені Burger результати залежать від умов, наддуву й tune.', benefitEn: 'The larger BMS intercooler core provides more surface area than stock to remove heat from charge air. It helps maintain performance through extended pulls and repeated runs; supplier-reported gains depend on conditions, boost, and tune.',
    detailsUa: 'Direct replacement із розмірами core приблизно 20″ × 5.25″ × 5.25″; за Burger, додаткове кріплення не потрібне, установка зворотна. Джерело орієнтує стандартний core на конфігурації близько 500 whp, а окремий 7.5″ Race core — на значно вищі. Це рекомендації виробника, а не гарантія потужності.', detailsEn: 'Direct replacement with core dimensions about 20 × 5.25 × 5.25 inches; Burger says no additional hardware is required and installation is reversible. The source positions the standard core around 500 whp and the separate 7.5-inch Race core for higher-output setups. These are supplier guidance, not a power guarantee.',
    fitUa: 'Для перелічених BMW E82/E87/E88 135i, E82 1M та E-Chassis N54/N55 моделей. Звірте кузов, двигун і патрубки; не вважайте сумісними всі E-Series.', fitEn: 'For Burger-listed BMW E82/E87/E88 135i, E82 1M, and E-Chassis N54/N55 applications. Verify chassis, engine, and pipe connections; not all E-Series fit.'
  },
  'bms-replacement-intercooler-for-f-chassis-bmw': {
    titleUa: 'BMS Replacement Intercooler для BMW F-Chassis N20 / N26 / N55', titleEn: 'BMS Replacement Intercooler for BMW F-Chassis N20 / N26 / N55',
    shortUa: 'Прямозамінний intercooler для конкретних F-Chassis з N20/N26/N55; не підходить до 5 Series чи кабріолетів.', shortEn: 'Direct-fit intercooler for listed F-Chassis N20/N26/N55; not for 5 Series or convertibles.',
    benefitUa: 'BMS intercooler замінює заводський F-Chassis cooler більшим core для підвищення охолодження наддувного повітря та зменшення heat soak на довгих заїздах. Менший перепад тиску допомагає турбосистемі підтримувати повітряний потік; реальна різниця залежить від двигуна й tune.', benefitEn: 'The BMS intercooler replaces the factory F-Chassis cooler with a larger core for improved charge-air cooling and reduced heat soak during longer pulls. Lower pressure drop supports turbo airflow; actual results depend on engine and calibration.',
    detailsUa: 'У комплекті потрібне кріплення за описом Burger; установка зворотна, без постійної модифікації. Джерело прямо виключає BMW 5 Series та всі моделі, не перелічені на сторінці, а також кабріолети для зазначених 2-Series/4-Series застосувань. Уважно звірте точний кузов.', detailsEn: 'Required hardware is listed by Burger and the installation is reversible. The source explicitly excludes BMW 5 Series and any model not listed, as well as convertibles for specified 2-Series/4-Series applications. Match the exact chassis carefully.',
    fitUa: 'Лише перелічені F20/F21 M135i, F22/F23 228i/M235i/N55 M2 (не convertible), F30/F31/F34 320i/328i/335i та F32/F36 428i/435i coupe/gran coupe. Не для F10/F11 5 Series.', fitEn: 'Only listed F20/F21 M135i, F22/F23 228i/M235i/N55 M2 (not convertible), F30/F31/F34 320i/328i/335i, and F32/F36 428i/435i coupe/gran coupe. Not for F10/F11 5 Series.'
  },
  'bms-high-capacity-intercooler-heat-exchanger-for-infiniti-q50-q60': {
    titleUa: 'BMS High-Capacity Heat Exchanger для Infiniti Q50 / Q60 VR30', titleEn: 'BMS High-Capacity Heat Exchanger for Infiniti Q50 / Q60 VR30',
    shortUa: 'Збільшений VR30 heat exchanger має вдвічі більшу площу й утричі більший об’єм рідини за OEM.', shortEn: 'Larger VR30 heat exchanger has twice the surface and over three times the fluid volume of stock.',
    benefitUa: 'BMS heat exchanger збільшує місткість системи охолодження наддувного повітря на платформі Infiniti VR30. Більший теплообмінник допомагає зменшувати heat soak під час послідовних прискорень, коли заводська місткість може бути недостатньою.', benefitEn: 'The BMS heat exchanger increases charge-air cooling capacity on the Infiniti VR30 platform. A larger exchanger helps control heat soak during repeated pulls when factory capacity may be overwhelmed.',
    detailsUa: 'За Burger, площа поверхні приблизно вдвічі більша, а об’єм рідини — більш ніж утричі порівняно зі штатним cooler. Прямий bolt-in монтаж. Джерело вказує сумісність і з авто, які мають, і з тими, що не мають заводського oil cooler.', detailsEn: 'Burger lists about twice the surface area and more than three times the fluid volume of the stock cooler. Direct bolt-in installation. The source says it fits vehicles with or without a factory oil cooler.',
    fitUa: 'Infiniti Q50 3.0t Lux / Silver Sport / Red Sport і Q60 Silver Sport / Red Sport 2016+ згідно з Burger. Звірте VR30 комплектацію до замовлення.', fitEn: 'For Burger-listed 2016+ Infiniti Q50 3.0t Lux/Silver Sport/Red Sport and Q60 Silver Sport/Red Sport. Verify VR30 configuration before ordering.'
  },
  'e-chassis-race-replacement-intercooler': {
    titleUa: 'BMS 7.5″ High-Density RACE Intercooler для BMW E-Chassis N54 / N55', titleEn: 'BMS 7.5-inch High-Density RACE Intercooler for BMW E-Chassis N54 / N55',
    shortUa: '7.5″ Race core для N54/N55 з upgraded або single turbo; може вимагати підрізання пластикового кожуха.', shortEn: '7.5-inch Race core for N54/N55 with upgraded or single turbo; minor plastic-shroud trimming may be needed.',
    benefitUa: 'BMS Race intercooler має глибокий високощільний 7.5″ core для збільшеного охолодження на серйозних N54/N55 конфігураціях. Він зменшує heat soak під довгим навантаженням і перепад тиску порівняно зі штатним блоком, підтримуючи високопотужний turbo setup.', benefitEn: 'The BMS Race intercooler uses a deep, high-density 7.5-inch core to increase cooling for serious N54/N55 builds. It reduces heat soak under sustained load and pressure drop versus the factory unit for upgraded-turbo applications.',
    detailsUa: 'Direct replacement і повністю зворотний після встановлення; Burger вказує всі необхідні кріплення та внутрішній hot-side flow diverter. Монтаж може вимагати незначного підрізання пластикового shroud. Перевірте габарити та простір із вашим турбо-китом.', detailsEn: 'Direct replacement and reversible after installation; Burger lists required hardware and an internal hot-side flow diverter. Installation may require minor trimming of the plastic shroud. Check dimensions and clearance with the turbo kit.',
    fitUa: 'Для BMW E-Chassis із N54 або N55, особливо з upgraded turbo чи single-turbo kits. Це більший Race core; для стандартних конфігурацій може бути доцільніший окремий replacement intercooler.', fitEn: 'For BMW E-Chassis with N54 or N55, especially upgraded-turbo or single-turbo kits. This is the larger Race core; a separate standard replacement intercooler may suit stock setups better.'
  },
  'jb-plus-replacement-enclosure': {
    titleUa: 'JB+ Replacement Enclosure з гвинтами для бензинових двигунів', titleEn: 'JB+ Replacement Enclosure with Screws for Gasoline Engines',
    shortUa: 'Двокомпонентний корпус із двома гвинтами замінює пошкоджений корпус BMS JB+ tuner.', shortEn: 'Two-piece case with two screws replaces a damaged BMS JB+ tuner enclosure.',
    benefitUa: 'Змінний корпус захищає плату JB+ та повертає їй фізичну оболонку, якщо оригінальний case тріснув або загубився. Це корпус для JB+ пристрою, не сам тюнер і не електронна плата.', benefitEn: 'The replacement case protects a JB+ board when its original enclosure is cracked or missing. This is the enclosure only, not the tuner or control board.',
    detailsUa: 'У комплекті дві половини корпуса та два гвинти. Виробник зазначає бензинові двигуни. Перед замовленням звірте форму корпусу й монтажні точки з вашою JB+ версією.', detailsEn: 'The package contains a two-piece enclosure and two screws. The supplier specifies gasoline engines. Match the case shape and mounting points to your JB+ version before ordering.',
    fitUa: 'Для сумісного Burger JB Plus tuner на бензиновому автомобілі. Не є корпусом JB4 або готовим тюнером.', fitEn: 'For a compatible Burger JB Plus tuner on a gasoline vehicle. Not a JB4 enclosure or complete tuner.'
  },
  'mk5-toyota-supra-jb-plus-quick-install-tuner': {
    titleUa: 'JB+ Quick-Install Tuner для Toyota GR Supra A90 B48 / B58 2020–2026', titleEn: 'JB+ Quick-Install Tuner for 2020–2026 Toyota GR Supra A90 B48 / B58',
    shortUa: 'Підключний JB+ дає змогу коригувати наддув до +4.5 psi на Supra 2.0 B48 або 3.0 B58.', shortEn: 'Plug-in JB+ adjusts boost up to +4.5 psi on Supra 2.0 B48 or 3.0 B58.',
    benefitUa: 'JB+ — підключний piggyback тюнер із регулюванням наддуву відносно штатного. На B58 Burger заявляє до 40 whp і 50 wtq у відповідному налаштуванні; запалювання й паливом продовжує керувати DME. Фактичний результат залежить від пального, температури та стану автомобіля.', benefitEn: 'JB+ is a plug-in piggyback tuner with user-adjustable boost over stock. Burger claims up to 40 whp and 50 wtq on the B58 in a suitable setup; the DME continues to manage ignition and fueling. Actual results depend on fuel, temperature, and vehicle condition.',
    detailsUa: 'Налаштування наддуву користувач може підняти до +4.5 psi. Пристрій автоматично визначає застосування й швидко знімається; у джерелі вказані виробництво в США та 5-річна гарантія. Це спрощений JB+, без data logging та керування картами як у JB4.', detailsEn: 'User-adjustable boost is listed up to +4.5 psi. The unit detects its application and can be installed or removed quickly; Burger lists US manufacture and a five-year warranty. JB+ is the simpler option and lacks JB4 data logging and map control.',
    fitUa: 'Toyota GR Supra Mk5 A90 2020–2026 із 2.0L B48 Gen 2 або 3.0L B58 Gen 2 за переліком Burger. Перевірте рік, мотор і роз’єм перед встановленням.', fitEn: 'For Burger-listed 2020–2026 Toyota GR Supra Mk5 A90 with 2.0L B48 Gen 2 or 3.0L B58 Gen 2. Verify year, engine, and connector before installation.'
  },
  'mercedes-benz-2010-2014-w204-c250-and-e250-jb': {
    titleUa: 'BMS JB+ Tuner для Mercedes-Benz C250 / E250 / SLK250 M271 1.8T', titleEn: 'BMS JB+ Tuner for Mercedes-Benz C250 / E250 / SLK250 M271 1.8T',
    shortUa: 'Підключний JB+ для Mercedes M271 посилює тягу в середньому діапазоні без перепрограмування ECU.', shortEn: 'Plug-in JB+ for Mercedes M271 adds midrange response without reflashing the ECU.',
    benefitUa: 'BMS JB+ змінює сигнал наддуву на турбомоторі M271, щоб посилити прискорення на низьких і середніх обертах. Burger заявляє до 20 whp і 40 wtq; це граничні показники виробника, а не гарантований результат кожного автомобіля.', benefitEn: 'The BMS JB+ adjusts boost signaling on the M271 turbo engine for stronger low- and midrange acceleration. Burger claims up to 20 whp and 40 wtq; these are supplier maximum figures, not guaranteed on every vehicle.',
    detailsUa: 'Підключення використовує заводські конектори й не потребує постійної зміни ECU; модуль можна зняти. Перевірте двигун M271 і роз’єми. Перед встановленням переконайтеся, що автомобіль справний і має якісне паливо.', detailsEn: 'The unit uses factory-style connectors and does not require a permanent ECU change; it can be removed. Confirm M271 engine and connectors. Ensure the vehicle is in good condition and use suitable fuel.',
    fitUa: 'Mercedes-Benz C250 1.8L M271 W204 2011–2015, E250 M271 W212/S212 2009–2013 та SLK250 M271 R172 2011–2016 за списком Burger. Не плутайте з C/E-Class іншого двигуна.', fitEn: 'For Burger-listed 2011–2015 Mercedes C250 1.8L M271 W204, 2009–2013 E250 M271 W212/S212, and 2011–2016 SLK250 M271 R172. Not for other C/E engines.'
  },
  'cooper-s-n18-jb': {
    titleUa: 'JB+ Quick-Install Tuner для MINI Cooper S / JCW N18 1.6T', titleEn: 'JB+ Quick-Install Tuner for MINI Cooper S / JCW N18 1.6T',
    shortUa: 'Підключний MINI N18 JB+ коригує наддув на 2–4 psi; у джерелі вказаний CARB EO D-744.', shortEn: 'Plug-in MINI N18 JB+ adjusts boost by 2–4 psi; supplier lists CARB EO D-744.',
    benefitUa: 'JB+ для MINI N18 змінює запит наддуву, залишаючи керування сумішшю та запалюванням штатному DME. Burger заявляє до 20 whp і 30 wtq та середнє підвищення наддуву на 2–4 psi залежно від умов; результат не гарантований.', benefitEn: 'The N18 JB+ modifies boost request while the factory DME continues managing fueling and ignition. Burger claims up to 20 whp and 30 wtq with a typical 2–4 psi boost increase depending on conditions; results are not guaranteed.',
    detailsUa: 'Швидке підключення без постійних змін, установлення/демонтаж менш ніж за 30 секунд за джерелом. Burger вказує CARB Executive Order D-744 для MINI Cooper S/JCW 1.6L N18 2011–2015; перевірте, чи відповідає EO вашому авто й регіону.', detailsEn: 'Quick plug-in installation with removal in under 30 seconds per the supplier. Burger lists CARB Executive Order D-744 for 2011–2015 MINI Cooper S/JCW 1.6L N18; verify that the EO covers your exact vehicle and location.',
    fitUa: 'Для MINI Cooper S/JCW N18 1.6L у кузовах R55/R56/R57/R58/R59/R60/R61 за роками Burger. Не для N14, N18 іншого ринку без перевірки, або новішого B48.', fitEn: 'For Burger-listed MINI Cooper S/JCW N18 1.6L in R55/R56/R57/R58/R59/R60/R61 years. Not for N14, unverified market variants, or newer B48.'
  },
  'n54-jb-quick-install': {
    titleUa: 'BMW N54 JB+ Quick-Install Tuner — опційний drop-in фільтр', titleEn: 'BMW N54 JB+ Quick-Install Tuner — Optional Drop-In Filter',
    shortUa: 'N54 JB+ піднімає наддув до +4 psi; оберіть, чи додавати drop-in фільтр у комплект.', shortEn: 'N54 JB+ adjusts boost up to +4 psi; choose whether to add a drop-in filter.',
    benefitUa: 'JB+ quick-install tuner змінює запит наддуву на BMW N54 та за базового налаштування близько +3 psi дає помітнішу тягу. Burger заявляє середні результати близько 30 whp і 40 lb-ft, з регулюванням до +4 psi; фактичний ефект залежить від стану авто, пального й клімату.', benefitEn: 'The JB+ quick-install tuner adjusts boost request on BMW N54. Burger cites typical settings around +3 psi with claimed averages near 30 whp and 40 lb-ft, adjustable up to +4 psi; actual results depend on vehicle health, fuel, and conditions.',
    detailsUa: 'Оберіть Yes, щоб додати drop-in performance air filter, або No, щоб отримати лише тюнер. Фільтр є окремим фізичним компонентом і додається до коробки лише за вибору Yes. Тюнер встановлюється без доступу до ECU та знімається без постійних змін.', detailsEn: 'Choose Yes to add the drop-in performance air filter or No for the tuner only. The filter is a separate physical component and is included only with Yes. The tuner installs without accessing the ECU and can be removed without permanent changes.',
    fitUa: 'Для BMW N54 3.0L Twin Turbo: 135i, 335i/xi, 535i, Z4 та 335is у роках зі сторінки Burger. Підтвердіть модель і DME до замовлення.', fitEn: 'For Burger-listed BMW N54 3.0L twin-turbo 135i, 335i/xi, 535i, Z4, and 335is years. Confirm model and DME before ordering.'
  },
  'f-series-jb-quick-install-tuner': {
    titleUa: 'JB+ Quick-Install Tuner для BMW F-Series N20 / N26 / N55', titleEn: 'JB+ Quick-Install Tuner for BMW F-Series N20 / N26 / N55',
    shortUa: 'Один підключний JB+ автоматично визначає сумісний N20/N26/N55 і коригує наддув; є регулювання до +4 psi.', shortEn: 'One plug-in JB+ detects compatible N20/N26/N55 and adjusts boost up to +4 psi.',
    benefitUa: 'JB+ змінює сигнал наддуву на BMW F-Series, залишаючи DME керування запалюванням і подачею пального. Burger заявляє до 25 whp/35 wtq для N20/N26 та до 35 whp/45 wtq для N55; значення залежать від умов і не є гарантією.', benefitEn: 'JB+ adjusts boost signaling on BMW F-Series while the DME retains ignition and fueling control. Burger claims up to 25 whp/35 wtq for N20/N26 and 35 whp/45 wtq for N55; figures depend on conditions and are not guaranteed.',
    detailsUa: 'Наддув регулюється до +4 psi відносно штатного; модуль автоматично визначає N20/N26/N55 та підтримує pneumatic/electronic wastegate за описом. Порівняно зі Stage 1 не має MAP-sensor control і data logging. Постачальник зазначає обмеження продажу/використання в Каліфорнії — перевірте актуальні вимоги вашого регіону.', detailsEn: 'Boost is adjustable up to +4 psi over stock; the unit auto-detects N20/N26/N55 and lists pneumatic/electronic wastegate support. Compared with Stage 1, it lacks MAP-sensor control and data logging. The supplier states a California sales/use restriction; verify current requirements for your location.',
    fitUa: 'BMW F-Series із N20, N26 або N55 у конфігураціях Burger. Не для інших двигунів або E-Chassis без окремої перевірки; перед встановленням звірте wastegate тип.', fitEn: 'For Burger-listed BMW F-Series with N20, N26, or N55. Not for other engines or E-Chassis without confirmation; verify wastegate type before installation.'
  },
  'b38-b46-b48-b58-bmw-jb-plus-tuner': {
    titleUa: 'BMW / MINI JB+ Quick-Install Tuner — вибір B38 / B46 / B48 / B58', titleEn: 'BMW / MINI JB+ Quick-Install Tuner — Select B38 / B46 / B48 / B58',
    shortUa: 'Оберіть покоління двигуна та 3- або 4-wire роз’єм; один JB+ не підходить до всіх кузовів.', shortEn: 'Select engine generation and 3- or 4-wire connector; one JB+ type does not fit every chassis.',
    benefitUa: 'JB+ — підключний piggyback модуль для корекції наддуву BMW/MINI B-Series. Burger заявляє до 30 whp/40 wtq для B48 і до 40 whp/50 wtq для B58 у відповідних умовах; штатний DME продовжує керувати паливом і запалюванням. Фактичний результат залежить від авто й пального.', benefitEn: 'JB+ is a plug-in piggyback module that adjusts boost on BMW/MINI B-Series. Burger claims up to 30 whp/40 wtq for B48 and 40 whp/50 wtq for B58 under suitable conditions; the factory DME continues to control fueling and ignition. Actual results depend on vehicle and fuel.',
    detailsUa: 'Оберіть точний Type: B58 Gen1/Gen2 (3-wire); B58/B48 Gen3 (більшість моделей 2025+); B48 FWD MINI/X1/X2/M235 Gen1/Gen2 (4-wire); або B48 230i/330i RWD Gen1/Gen2 (3-wire). Покоління, привід і роз’єм визначають harness; не обирайте лише за робочим об’ємом.', detailsEn: 'Choose the exact Type: B58 Gen1/Gen2 (3-wire); B58/B48 Gen3 (most 2025+ models); B48 FWD MINI/X1/X2/M235 Gen1/Gen2 (4-wire); or B48 230i/330i RWD Gen1/Gen2 (3-wire). Engine generation, drive layout, and connector determine the harness; do not choose by displacement alone.',
    fitUa: 'Для сумісних BMW/MINI із B38/B46/B48/B58 у поколінні та конфігурації обраної опції. Перед встановленням звірте рік, двигун, привід, harness і форму роз’єму.', fitEn: 'For compatible BMW/MINI with B38/B46/B48/B58 matching the selected generation and layout. Verify model year, engine, drive layout, harness, and connector before installation.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Що дає ця деталь</h3>\n<p>${item.benefitUa}</p>\n<h3>Опції та монтаж</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>What this part does</h3>\n<p>${item.benefitEn}</p>\n<h3>Options and installation</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
