// Source-checked charge-pipe kits and service parts; local draft only.
const rows = {
  'bmw-b48-charge-pipe-blow-off-valve-bov-kit': {
    titleUa: 'BMS B48 / B46 Charge Pipe і Turbosmart RacePort BOV Kit — Gen 1/2 або Gen 3', titleEn: 'BMS B48 / B46 Charge Pipe and Turbosmart RacePort BOV Kit — Gen 1/2 or Gen 3',
    shortUa: 'Алюмінієва charge pipe, RacePort BOV, два 1/8″ NPT ports і кріплення; оберіть B48 покоління.', shortEn: 'Aluminum charge pipe, RacePort BOV, two 1/8-inch NPT ports, and hardware; select B48 generation.',
    benefitUa: 'BMS Elite charge pipe замінює штатний пластиковий duct на алюмінієву трубу з Turbosmart RacePort blow-off valve. Клапан відводить надлишкове повітря при скиданні газу, створює виразний звук і за описом виробника допомагає зменшити compressor surge. Два NPT ports дають змогу під’єднати boost gauge або WMI.', benefitEn: 'The BMS Elite charge pipe replaces the factory plastic duct with an aluminum pipe and Turbosmart RacePort blow-off valve. It vents excess air when lifting off the throttle for a distinct sound and is intended to reduce compressor surge. Two NPT ports support a boost gauge or WMI connection.',
    detailsUa: 'Оберіть B48 Gen 1 & 2 або Gen 3. У комплекті RacePort BOV, charge pipe, silicone coupler, O-ring, clip і монтажне кріплення. Джерело позначає товар out of stock на дату snapshot; наявність перевіряйте окремо. Для factory intake Burger радить відповідний long turbo inlet.', detailsEn: 'Choose B48 Gen 1 & 2 or Gen 3. Package includes RacePort BOV, charge pipe, silicone coupler, O-ring, clip, and installation hardware. The supplier snapshot marks the item out of stock; verify availability separately. Burger recommends a matching long turbo inlet for factory intake.',
    fitUa: 'BMW/Supra із B46/B48 Gen 1/2 або B48 Gen 3 у конфігураціях Burger. Перевірте engine generation, transmission layout і OE duct reference 13718601683.', fitEn: 'For Burger-listed BMW/Supra B46/B48 Gen 1/2 or B48 Gen 3. Verify engine generation, transmission layout, and OE duct reference 13718601683.'
  },
  'bms-bmw-b46-b48-gen1-charge-pipe': {
    titleUa: 'BMS Aluminum Charge Pipe для BMW / Supra B46 / B48 — Gen 1/2 або Gen 3', titleEn: 'BMS Aluminum Charge Pipe for BMW / Supra B46 / B48 — Gen 1/2 or Gen 3',
    shortUa: 'Алюмінієвий replacement charge pipe має два 1/8″ NPT ports; оберіть покоління B48.', shortEn: 'Aluminum replacement charge pipe has two 1/8-inch NPT ports; select B48 generation.',
    benefitUa: 'BMS charge pipe замінює пластиковий factory charge-air duct алюмінієвою деталлю з більшим проходом і CNC фланцями. Металевий корпус призначений витримувати підвищений наддув, а NPT порти можна використати для boost gauge або methanol injection.', benefitEn: 'The BMS charge pipe replaces the plastic factory charge-air duct with an aluminum part, larger passage, and CNC flanges. The metal body is designed for increased boost; NPT ports can support a boost gauge or methanol injection.',
    detailsUa: 'Оберіть B48 Gen 1 & 2 або Gen 3. У комплекті coupler, O-rings, clamps і монтажне hardware за списком Burger; для NPT ports використовуються заглушки, якщо додаткове обладнання не встановлено. У назві джерела товар позначений очікуваним до жовтня — уточніть складський статус.', detailsEn: 'Choose B48 Gen 1 & 2 or Gen 3. Burger lists a coupler, O-rings, clamps, and installation hardware; cap unused NPT ports. Supplier title shows an estimated October restock, so confirm availability.',
    fitUa: 'BMW/Supra з B46/B48 у поколінні, обраному в меню. Джерело попереджає, що окремим 220i/320i/420i потрібна перевірка перед замовленням; звірте кузов і transmission-specific shape.', fitEn: 'For BMW/Supra with B46/B48 matching the selected generation. Burger flags certain 220i/320i/420i applications for review; verify chassis and transmission-specific pipe shape.'
  },
  'x2-o-rings-gaskets-for-bms-s58-intake': {
    titleUa: 'Комплект із 2 O-Rings для BMS S58 G8x Intake', titleEn: 'Set of 2 O-Rings for BMS S58 G8x Intake',
    shortUa: 'Два змінні ущільнення для BMS intake на S58 BMW M2 / M3 / M4.', shortEn: 'Two replacement seals for the BMS intake on S58 BMW M2 / M3 / M4.',
    benefitUa: 'Пара replacement O-rings призначена для відновлення герметичності стику BMS intake на двигуні S58. Ущільнення варто замінити, якщо старі затверділи, розтягнулися чи пошкодилися під час сервісу.', benefitEn: 'The replacement O-ring pair restores sealing at the BMS S58 intake joint. Replace seals if the originals harden, stretch, or are damaged during service.',
    detailsUa: 'У комплекті рівно два O-rings/gaskets. BMS intake, повітряні фільтри, затискачі та інші деталі не входять, якщо їх окремо не зазначено. Перед замовленням звірте форму посадки з вашим intake.', detailsEn: 'The package contains two O-rings/gaskets only. BMS intake, filters, clamps, and other parts are not included unless separately listed. Match the seal profile to your intake before ordering.',
    fitUa: 'Для BMS G8x M2/M3/M4 S58 intake за сторінкою Burger. Не вважайте сумісними OEM intake або інші BMS покоління без підтвердження.', fitEn: 'For Burger-listed BMS G8x M2/M3/M4 S58 intake. Do not assume fitment for OEM intakes or other BMS generations.'
  },
  'bms-aluminum-replacement-charge-pipe-upgrade-for-b58-f-chassis-bmw': {
    titleUa: 'BMS Elite Aluminum Charge Pipe для BMW F-Chassis Gen 1 B58 — OEM / BOV', titleEn: 'BMS Elite Aluminum Charge Pipe for BMW F-Chassis Gen 1 B58 — OEM / BOV',
    shortUa: 'Оберіть штатну replacement версію або Tial flange з Turbosmart/Tial BOV; BOV версія позначена race use.', shortEn: 'Choose standard replacement or Tial-flange version with Turbosmart/Tial BOV; BOV option is race use.',
    benefitUa: 'BMS Elite charge pipe замінює слабкий пластиковий duct Gen 1 B58 на алюмінієвий корпус з CNC фланцями. Це знижує ризик розриву заводської труби при підвищеному наддуві; два 1/8″ NPT бунги доступні для gauge або WMI-з’єднання.', benefitEn: 'The BMS Elite charge pipe replaces the weak plastic Gen 1 B58 duct with an aluminum body and CNC flanges. It reduces the chance of factory-pipe failure under higher boost; two 1/8-inch NPT bungs support gauge or WMI connections.',
    detailsUa: 'Оберіть OEM Replacement або With BOV Flange & Turbosmart BOV. BOV варіант — лише для racing use за попередженням Burger; третій selector choice включає Tial BOV, тоді як версія лише з flange клапана не містить. Установлюється на штатні точки, зберігає emissions fittings і може бути повернутий до стоку.', detailsEn: 'Choose OEM Replacement or With BOV Flange & Turbosmart BOV. The BOV option is marked race use only by Burger; the third selector choice includes a Tial BOV, while flange-only does not. Factory mounting and emissions fittings are retained, and installation is reversible.',
    fitUa: 'BMW F-Chassis Gen 1 B58: F20/F21 M140i, F22/F23 M240i, F30/F31/F34 340i, F32/F33/F36 440i та перелічені G-Chassis Gen 1 540i/640i/X applications. Звірте кузов і двигун.', fitEn: 'For BMW F-Chassis Gen 1 B58 F20/F21 M140i, F22/F23 M240i, F30/F31/F34 340i, F32/F33/F36 440i, and listed G-Chassis Gen 1 540i/640i/X applications. Verify chassis and engine.'
  },
  'bms-m3-m4-s55-silicone-charge-pipes': {
    titleUa: 'BMS Silicone Charge Pipes для BMW S55 F87 M2C / F80 M3 / F82 M4 — пара', titleEn: 'BMS Silicone Charge Pipes for BMW S55 F87 M2C / F80 M3 / F82 M4 — Pair',
    shortUa: 'Пара посилених 2″ silicone charge pipes із billet inlet couplers і монтажним hardware для S55.', shortEn: 'Pair of reinforced 2-inch silicone charge pipes with billet inlet couplers and mounting hardware for S55.',
    benefitUa: 'BMS reinforced silicone pipes замінюють плоскі пластикові S55 boost tubes, які можуть тріснути чи зірватися з intercooler coupler. Внутрішній діаметр близько 2″ створює плавніший прохід, а гнучкий посилений матеріал розрахований на наддув.', benefitEn: 'The BMS reinforced silicone pipes replace flattened plastic S55 boost tubes that can crack or slip from intercooler couplers. About 2-inch inner diameter creates a smoother path, while reinforced silicone is designed for boost pressure.',
    detailsUa: 'У комплекті дві silicone pipes, дві billet flanges, чотири clamps і M6 кріплення. Глянцевий чорний фініш без логотипів. Джерело позначає товар out of stock; підтвердіть наявність до продажу.', detailsEn: 'The set includes two silicone pipes, two billet flanges, four clamps, and M6 hardware. Gloss-black finish without visible logos. Supplier snapshot marks it out of stock; confirm availability.',
    fitUa: 'BMW F87 M2 Competition 2018–2021 із S55, F80 M3 2015–2020 і F82/F83 M4 2015–2020 у Burger list. Не для стандартного N55 M2.', fitEn: 'For Burger-listed 2018–2021 BMW F87 M2 Competition with S55, 2015–2020 F80 M3, and F82/F83 M4. Not for standard N55 M2.'
  },
  'bms-elite-aluminum-replacement-n55-bmw-chargepipe': {
    titleUa: 'BMS Elite Aluminum Charge Pipe для BMW E-Chassis N55 — OE 13717615026', titleEn: 'BMS Elite Aluminum Charge Pipe for BMW E-Chassis N55 — OE 13717615026',
    shortUa: 'Алюмінієва direct-fit заміна N55 charge duct; перенесіть factory gasket і clip зі старої труби.', shortEn: 'Direct-fit aluminum N55 charge-duct replacement; transfer factory gasket and clip.',
    benefitUa: 'BMS Elite charge pipe замінює пластиковий BMW N55 charge-air duct міцною алюмінієвою деталлю з CNC фланцями та заводськими точками монтажу. Вона розрахована зменшити ризик, що factory duct зіскочить або розірветься під наддувом.', benefitEn: 'The BMS Elite charge pipe replaces the BMW N55 plastic charge-air duct with a durable aluminum part, CNC flanges, and factory mounting. It is designed to reduce the chance of the stock duct blowing off or splitting under boost.',
    detailsUa: 'OE reference 13717615026. За джерелом, потрібно перенести factory charge-pipe gasket і clip зі знятої труби; перевірте їх стан і за потреби замовте окремо. Товар позначено out of stock у snapshot; монтаж зберігає заводські emissions fittings.', detailsEn: 'OE reference 13717615026. Burger says to transfer the factory charge-pipe gasket and clip from the removed pipe; inspect them and order replacements separately if needed. Snapshot marks the item out of stock; factory emissions fittings are retained.',
    fitUa: 'BMW E82/E88 135i 2011–2013 та E90/E91/E92/E93 335i N55 у роках зі сторінки. Не для F-Chassis N55.', fitEn: 'For Burger-listed 2011–2013 BMW E82/E88 135i and E90/E91/E92/E93 335i with N55. Not for F-Chassis N55.'
  },
  'n55-bms-charge-pipe-for-e-chassis-bmw': {
    titleUa: 'BMS Aluminum Charge Pipe для BMW E-Chassis N55 — 2 NPT ports', titleEn: 'BMS Aluminum Charge Pipe for BMW E-Chassis N55 — Two NPT Ports',
    shortUa: 'Чорна алюмінієва direct-fit труба з двома 1/8″ NPT ports, coupler, clamps і plugs.', shortEn: 'Black direct-fit aluminum pipe with two 1/8-inch NPT ports, coupler, clamps, and plugs.',
    benefitUa: 'Алюмінієвий BMS charge pipe замінює пластиковий заводський N55 duct, щоб зменшити ризик розриву або зіскакування під наддувом. CNC фланці, factory-style монтаж і два NPT бунги дають точки для gauge чи methanol injection.', benefitEn: 'The BMS aluminum charge pipe replaces the plastic factory N55 duct to reduce failure or blow-off risk under boost. CNC flanges, factory-style mounting, and two NPT bungs provide ports for a gauge or methanol injection.',
    detailsUa: 'У комплекті труба, heavy-duty silicone coupler, clamps і два 1/8 NPT bung plugs. Встановлення потребує перенесення gasket/clip зі штатної труби, якщо ваш автомобіль використовує їх у цьому вузлі; звірте OE 13717615026.', detailsEn: 'The package includes the pipe, heavy-duty silicone coupler, clamps, and two 1/8 NPT bung plugs. Transfer the factory gasket/clip if used by the vehicle assembly; verify OE reference 13717615026.',
    fitUa: 'BMW E82/E88 135i та E90/E91/E92/E93 335i/335ix N55 2011–2013 у переліку Burger. Не для F-Chassis N55.', fitEn: 'For Burger-listed 2011–2013 BMW E82/E88 135i and E90/E91/E92/E93 335i/335ix with N55. Not for F-Chassis N55.'
  },
  '1-8-npt-bung-plugs-w-thread-sealer-2-pack': {
    titleUa: '1/8″ NPT Bung Plugs — 2 шт. із попередньо нанесеним thread sealer', titleEn: '1/8-inch NPT Bung Plugs — 2-Pack with Pre-Applied Thread Sealer',
    shortUa: 'Дві внутрішньошестигранні заглушки 1/8″ NPT для закриття невикористаних ports у charge pipe.', shortEn: 'Two internal-hex 1/8-inch NPT plugs for closing unused charge-pipe ports.',
    benefitUa: 'Bung plugs закривають невикористані threaded ports у charge pipe, щоб зберегти герметичність системи наддуву. На різьбу вже нанесений thread sealer, що допомагає ущільнити монтаж.', benefitEn: 'The bung plugs close unused threaded ports in a charge pipe to preserve charge-system sealing. Thread sealer is pre-applied to support a sealed installation.',
    detailsUa: 'У комплекті дві заглушки з внутрішнім hex і різьбою 1/8″ NPT. Підходять до BMS charge pipes та інших компонентів із точно таким NPT port. Не перетягуйте в алюмінієвому корпусі.', detailsEn: 'The set includes two internal-hex plugs with 1/8-inch NPT thread. Fits BMS charge pipes and other components with matching NPT ports. Avoid overtightening in aluminum housings.',
    fitUa: 'Для відкритих 1/8″ NPT bungs. Перевірте тип і розмір різьби; NPT не взаємозамінна з metric чи straight threads.', fitEn: 'For open 1/8-inch NPT bungs. Confirm thread type and size; NPT is not interchangeable with metric or straight threads.'
  },
  'n54-n55-silicone-chargepipe-elbow-and-2-clamps': {
    titleUa: 'Silicone Charge Pipe Elbow 2.5″–3″ 45° для BMW E-Chassis — 2 clamps', titleEn: '2.5-to-3-inch 45° Silicone Charge-Pipe Elbow for BMW E-Chassis — 2 Clamps',
    shortUa: 'З’єднувач 45° переходить із 2.5″ на 3″; комплект має два T-clamps для E-Chassis.', shortEn: '45° coupler transitions from 2.5 to 3 inches and includes two T-clamps for E-Chassis.',
    benefitUa: '45° силіконовий elbow з’єднує charge pipe різних діаметрів і допомагає прокласти патрубок у моторному відсіку BMW E-Chassis. Перехід 2.5″–3″ забезпечує правильне стикування відповідних труб.', benefitEn: 'The 45-degree silicone elbow joins charge pipes of different diameters and routes the pipe in a BMW E-Chassis engine bay. A 2.5-to-3-inch transition connects matching tube ends.',
    detailsUa: 'У комплекті один silicone elbow і два T-clamps. Джерело вказує E-Chassis лише; виміряйте зовнішній діаметр обох патрубків і кут до замовлення, оскільки це не універсальний прямий coupler.', detailsEn: 'The package contains one silicone elbow and two T-clamps. Supplier specifies E-Chassis only; measure both pipe outside diameters and angle before ordering because this is not a universal straight coupler.',
    fitUa: 'BMW E-Chassis N54/N55 charge-pipe конфігурації з 2.5″ та 3″ з’єднанням. Не застосовуйте до іншого діаметра або кузова без вимірювання.', fitEn: 'For BMW E-Chassis N54/N55 charge-pipe setups with 2.5- and 3-inch connections. Do not use on other diameters/chassis without measuring.'
  },
  'replacement-n54-n55-chargepipe-gasket-e-and-f-chassis': {
    titleUa: 'Replacement Charge Pipe O-Ring для BMW N54 / N55 E- та F-Chassis', titleEn: 'Replacement Charge-Pipe O-Ring for BMW N54 / N55 E- and F-Chassis',
    shortUa: 'Змінне ущільнення сідає у groove з’єднання throttle body та charge pipe.', shortEn: 'Replacement seal fits the groove at the throttle-body/charge-pipe joint.',
    benefitUa: 'O-ring створює герметичний стик між throttle body та charge pipe на BMW N54/N55. Нове ущільнення допомагає усунути витік наддуву, якщо старе стало пласким, твердим або пошкодилося під час демонтажу.', benefitEn: 'The O-ring seals the throttle-body-to-charge-pipe joint on BMW N54/N55. A fresh seal can restore boost sealing if the original has flattened, hardened, or been damaged during removal.',
    detailsUa: 'У позиції одне heavy-duty O-ring/gasket для канавки charge pipe. Труба, throttle body та кріплення не входять. Очистіть groove і перевірте розмір до встановлення; не затискайте ущільнення насухо, якщо сервісна інструкція вимагає lubricant.', detailsEn: 'The listing is one heavy-duty O-ring/gasket for the charge-pipe groove. Pipe, throttle body, and hardware are not included. Clean the groove and verify size; follow service instructions for any required lubricant.',
    fitUa: 'BMW N54/N55 charge-pipe з’єднання E- та F-Chassis, де профіль gasket збігається з канавкою. Звірте стару деталь.', fitEn: 'For BMW N54/N55 E- and F-Chassis charge-pipe joints with a matching groove profile. Compare the removed seal.'
  },
  'replacement-n54-n55-chargepipe-clip-e-and-f-chassis': {
    titleUa: 'Replacement Charge Pipe Clip для BMW N54 / N55 E- та F-Chassis', titleEn: 'Replacement Charge-Pipe Clip for BMW N54 / N55 E- and F-Chassis',
    shortUa: 'Посилений retaining clip фіксує N54/N55 charge pipe у з’єднанні з дроселем.', shortEn: 'Heavy-duty retaining clip secures the N54/N55 charge pipe at the throttle connection.',
    benefitUa: 'Змінний charge-pipe clip утримує патрубок у посадковому з’єднанні N54/N55, допомагаючи запобігти зіскакуванню при наддуві. Замініть затискач, якщо штатний clip зігнувся чи втратив силу фіксації.', benefitEn: 'The replacement charge-pipe clip retains the N54/N55 pipe at its joint to help prevent blow-off under boost. Replace it if the factory clip is bent or no longer locks securely.',
    detailsUa: 'У комплекті retaining clip, без труби та ущільнення. Перед монтажем перевірте паз і переконайтеся, що clip повністю защіпнувся по колу.', detailsEn: 'The package is the retaining clip only, without pipe or seal. Inspect the groove and confirm the clip locks fully around the joint after installation.',
    fitUa: 'Для BMW N54 та N55, усіх E- та F-Chassis за Burger. Звірте тип стику та форму старого clip.', fitEn: 'For Burger-listed BMW N54/N55 across E- and F-Chassis. Match the joint and old clip shape.'
  },
  'bms-aluminum-replacement-n54-bmw-chargepipe': {
    titleUa: 'BMS Aluminum Charge Pipe для BMW N54 E-Chassis — OEM DV або Tial BOV', titleEn: 'BMS Aluminum Charge Pipe for BMW N54 E-Chassis — OEM DV or Tial BOV',
    shortUa: 'Оберіть OEM diverter valves, Tial flange лише для race use, або варіант із Tial BOV у комплекті.', shortEn: 'Choose OEM diverter valves, race-use Tial flange, or version with Tial BOV included.',
    benefitUa: 'BMS aluminum charge pipe замінює пластиковий N54 duct, який може тріснути чи зіскочити під наддувом. CNC фланці, OEM монтаж і два 1/8″ NPT ports створюють міцну заміну; Tial BOV опція змінює спосіб скидання надлишкового тиску.', benefitEn: 'The BMS aluminum charge pipe replaces the plastic N54 duct that may crack or blow off under boost. CNC flanges, OEM mounting, and two 1/8-inch NPT ports provide a stronger replacement; the Tial BOV option changes pressure release.',
    detailsUa: 'Оберіть N54 w/OEM DVs, Tial BOV flange (race use only), або flange разом із Tial Black BOV. Варіант із flange-only не містить клапан. Усі варіанти зберігають factory emissions fittings; gasket і retaining clip потрібно перенести зі старої труби або придбати окремо.', detailsEn: 'Choose N54 with OEM DVs, Tial BOV flange (race use only), or flange with Tial Black BOV included. Flange-only does not include a valve. Factory emissions fittings are retained; transfer the old gasket/clip or source replacements separately.',
    fitUa: 'BMW E82/E88 135i, 1M, E90/E91/E92/E93 335i/335ix та 335is N54 у роках Burger. Не для 535i; звірте кузов і DV/BOV конфігурацію.', fitEn: 'For Burger-listed BMW E82/E88 135i, 1M, E90/E91/E92/E93 335i/335ix and 335is with N54. Not for 535i; verify chassis and DV/BOV configuration.'
  },
  'chargepipe-kit-for-2011-2017-n55-535i-640i-740i-f15-x5-f16-x6-f10-f11-f12-f13-e70-e71': {
    titleUa: 'BMS Aluminum Charge Pipe Kit для N55 BMW 535i / 640i / 740i / X5 / X6', titleEn: 'BMS Aluminum Charge Pipe Kit for N55 BMW 535i / 640i / 740i / X5 / X6',
    shortUa: 'Алюмінієва заміна N55 duct із двома 1/8″ NPT bungs; перенесіть factory gaskets і clips.', shortEn: 'Aluminum N55 duct replacement with two 1/8-inch NPT bungs; transfer factory gaskets/clips.',
    benefitUa: 'BMS charge pipe замінює пластиковий N55 duct алюмінієвою деталлю, щоб знизити ризик розриву чи зіскакування під наддувом. Два 1/8″ NPT порти можна використати для датчика наддуву або methanol injection.', benefitEn: 'The BMS charge pipe replaces the plastic N55 duct with aluminum to reduce the chance of splitting or blowing off under boost. Two 1/8-inch NPT ports can support a boost gauge or methanol injection.',
    detailsUa: 'У комплекті charge pipe, coupler, clamps і NPT bungs згідно з варіантом джерела. Під час монтажу перенесіть factory gasket і retaining clips зі старої труби; вони можуть замовлятися окремо. Два бунги залишайте заглушеними, якщо не використовуєте.', detailsEn: 'Package includes the charge pipe, coupler, clamps, and NPT bungs as listed. Transfer the factory gasket and retaining clips from the old pipe; these may need to be ordered separately. Keep unused bungs plugged.',
    fitUa: 'Перелічені N55 BMW F10/F11 535i, F12/F13 640i, 740i, F15 X5/F16 X6 та E70/E71 X5/X6 у роках Burger. Звірте точний двигун і кузов.', fitEn: 'For Burger-listed N55 BMW F10/F11 535i, F12/F13 640i, 740i, F15 X5/F16 X6, and E70/E71 X5/X6 years. Verify exact engine and chassis.'
  },
  'm3-m4-s55-replacement-aluminum-chargepipes': {
    titleUa: 'BMS Elite S55 Aluminum Charge Pipes — combo / hot-side / cold-side J-pipe', titleEn: 'BMS Elite S55 Aluminum Charge Pipes — Combo / Hot-Side / Cold-Side J-Pipe',
    shortUa: 'Оберіть повний kit, лише hot-side pair або cold-side J-pipe для BMW S55.', shortEn: 'Choose complete kit, hot-side pair only, or cold-side J-pipe for BMW S55.',
    benefitUa: 'BMS Elite алюмінієві charge pipes замінюють крихкі пластикові S55 boost tubes, що можуть тріснути чи зіскочити з муфти. CNC flanges і виступний край створюють OEM-style фіксацію; заглушений NPT bung у кожній трубі доступний для WMI чи gauge.', benefitEn: 'BMS Elite aluminum charge pipes replace fragile S55 plastic boost tubes that may crack or slip off couplers. CNC flanges and a retaining lip create OEM-style fit; capped NPT bungs support WMI or gauge connections.',
    detailsUa: 'Оберіть BMS Elite Hot Side Pipes & Cold Side J Pipe COMBO, Hot Side Pipes Only або Cold Side J Pipe. Комплектний hot-side set має дві труби, couplers, clamps, bung plugs і кріплення; J-pipe-only постачається окремо зі своїм coupler/clip/O-ring. Не вважайте одну опцію повною системою.', detailsEn: 'Choose the Hot Side Pipes & Cold Side J-Pipe Combo, Hot Side Pipes Only, or Cold Side J-Pipe. The hot-side set includes two pipes, couplers, clamps, bung plugs, and hardware; J-pipe-only is a separate part with its own coupler/clip/O-ring. One option is not a full system.',
    fitUa: 'BMW F87 M2 Competition із S55, F80 M3 2015–2020 і F82/F83 M4 2015–2020 у списку Burger. Не для звичайного M2 з N55.', fitEn: 'For Burger-listed BMW F87 M2 Competition with S55, 2015–2020 F80 M3, and F82/F83 M4. Not for standard N55 M2.'
  },
  'f10-m5-replacement-aluminum-chargepipes': {
    titleUa: 'BMS Elite Aluminum Charge Pipes для BMW F10 M5 / F12 F13 M6 S63TU', titleEn: 'BMS Elite Aluminum Charge Pipes for BMW F10 M5 / F12 F13 M6 S63TU',
    shortUa: 'Пара порошково-пофарбованих алюмінієвих труб із 2.5″ couplers, reducers, clamps і 1/8″ NPT ports.', shortEn: 'Pair of powder-coated aluminum pipes with 2.5-inch couplers, reducers, clamps, and NPT ports.',
    benefitUa: 'Комплект BMS Elite замінює штатні S63TU charge pipes на алюмінієві труби зі штатною функцією й двома заглушеними 1/8″ NPT ports. Це посилена заміна заводських патрубків наддуву, не окремий тюнінг двигуна.', benefitEn: 'The BMS Elite kit replaces S63TU factory charge pipes with aluminum tubes retaining stock function and two capped 1/8-inch NPT ports. It is a reinforced charge-pipe replacement, not an engine tune.',
    detailsUa: 'У комплекті дві powder-coated pipes, 2.5″ silicone couplers, reducers 2.5″→2.25″, hose clamps і дві 1/8″ NPT fittings/plugs згідно з переліком Burger. Перед установленням звірте кількість і передбачене використання ports.', detailsEn: 'Burger lists two powder-coated pipes, 2.5-inch silicone couplers, 2.5-to-2.25-inch reducers, hose clamps, and two 1/8-inch NPT fittings/plugs. Confirm port configuration and package contents before installation.',
    fitUa: 'BMW F10 M5 2012–2017 та F12/F13 M6 2012–2017 із S63TU за Burger. Перевірте кузов і покоління двигуна.', fitEn: 'For Burger-listed 2012–2017 BMW F10 M5 and F12/F13 M6 with S63TU. Verify chassis and engine generation.'
  },
  'race-intercooler-j-pipe': {
    titleUa: 'BMS Race Intercooler J-Pipe — 2.5″ pipe або 3″ kit з couplers', titleEn: 'BMS Race Intercooler J-Pipe — 2.5-inch Pipe or 3-inch Coupler Kit',
    shortUa: 'Оберіть 2.5″ pipe для factory-style layout або 3″ версію для E-Series Race intercooler / big turbo.', shortEn: 'Choose 2.5-inch pipe for factory-style layout or 3-inch version for E-Series Race cooler/big turbo.',
    benefitUa: 'Збільшений J-pipe підтримує плавніше з’єднання між intercooler і throttle body. Версія 3″ дає змогу зберегти 3″ тракт для високого потоку, тоді як 2.5″ варіант призначений для автомобілів зі штатною 2.4″ конфігурацією J-pipe.', benefitEn: 'The larger J-pipe provides a smoother connection between intercooler and throttle body. The 3-inch option maintains a 3-inch path for higher flow, while 2.5-inch is intended for vehicles with the factory 2.4-inch J-pipe layout.',
    detailsUa: 'Оберіть 2.5″ Pipe Only — використовує couplers від Race Intercooler — або 3″ Including matching IC & Chargepipe couplers. 3″ варіант сумісний лише з E-Series Race Intercooler; Burger радить його для aftermarket turbos.', detailsEn: 'Choose 2.5-inch Pipe Only, which reuses Race Intercooler couplers, or 3-inch including matching intercooler and charge-pipe couplers. The 3-inch option fits only the E-Series Race Intercooler; Burger recommends it for aftermarket turbos.',
    fitUa: 'Для відповідних BMW E-Series з BMS Race intercooler і сумісною charge pipe. Перевірте діаметр патрубків і чи є в авто one-piece factory J-pipe.', fitEn: 'For matching BMW E-Series with BMS Race intercooler and compatible charge pipe. Verify pipe diameters and whether the car has a one-piece factory J-pipe.'
  },
  'bms-n55-f30-replacement-aluminum-chargepipe': {
    titleUa: 'BMS Aluminum Charge Pipe для BMW F-Chassis N55 — вибір коробки / приводу', titleEn: 'BMS Aluminum Charge Pipe for BMW F-Chassis N55 — Select Transmission / Drive',
    shortUa: 'Оберіть automatic RWD, manual RWD або xDrive версію з двома заглушеними 1/8″ NPT ports.', shortEn: 'Choose automatic RWD, manual RWD, or xDrive version with two capped 1/8-inch NPT ports.',
    benefitUa: 'BMS charge pipe замінює крихкий пластиковий патрубок F-Chassis N55 на direct-fit алюміній із CNC фланцями. Два 1/8″ NPT ports підходять для boost gauge, WMI чи діагностики; міцніший корпус зменшує ризик пошкодження під тиском.', benefitEn: 'The BMS charge pipe replaces the fragile F-Chassis N55 plastic tube with direct-fit aluminum and CNC flanges. Two 1/8-inch NPT ports support a boost gauge, WMI, or diagnostics; the stronger body reduces pressure-related pipe failure risk.',
    detailsUa: 'Оберіть Automatic transmission (RWD), Manual transmission (RWD) або All iX Models. Версія для manual має додаткову гумову заглушку для непотрібного auto-trans vent port. Перевірте кузов, привід та коробку перед вибором.', detailsEn: 'Choose Automatic transmission (RWD), Manual transmission (RWD), or All iX Models. Manual version includes an extra rubber cap for the unused automatic-transmission vent port. Verify chassis, drivetrain, and transmission.',
    fitUa: 'BMW F20/F21 M135i, F22/F23 M235i, F87 M2 N55, F30/F31 335i/335xi та F32/F33/F36 435i/435xi N55 у переліку Burger. Опція залежить від коробки й xDrive.', fitEn: 'For Burger-listed BMW F20/F21 M135i, F22/F23 M235i, F87 N55 M2, F30/F31 335i/335xi, and F32/F33/F36 435i/435xi with N55. Select by transmission and xDrive.'
  },
  'bms-m3-m4-s55-replacement-chargepipes': {
    titleUa: 'BMS S55 Aluminum Charge Pipes — combo або окремо hot-side / cold-side J-pipe', titleEn: 'BMS S55 Aluminum Charge Pipes — Combo or Separate Hot-Side / Cold-Side J-Pipe',
    shortUa: 'Оберіть комплект charge pipes, лише hot-side pair або cold-side J-pipe; варіанти продаються окремо.', shortEn: 'Choose charge-pipe combo, hot-side pair, or cold-side J-pipe; options are sold separately.',
    benefitUa: 'Алюмінієві BMS труби замінюють пластикові S55 boost tubes, що можуть тріснути або зіскочити під наддувом. CNC фланці та retaining lip створюють надійну OEM-style посадку; pre-capped NPT bungs доступні для gauge/WMI.', benefitEn: 'BMS aluminum pipes replace S55 plastic boost tubes that can crack or slip off under boost. CNC flanges and a retaining lip create secure OEM-style fit; capped NPT bungs support gauge/WMI connections.',
    detailsUa: 'Оберіть один із трьох варіантів: Hot Side Pipes & Cold Side J Pipe combo, Cold Side J Pipe або Hot Side Pipes Only. Combo містить дві metal pipes, couplers, clamps, bung plugs і окремий J-pipe з clip/O-ring за списком. Ціна й комплектність залежать від вибору; не додавайте деталі, яких немає у вибраній опції.', detailsEn: 'Choose one of three options: Hot Side Pipes & Cold Side J-Pipe combo, Cold Side J-Pipe, or Hot Side Pipes Only. Combo contains two metal pipes, couplers, clamps, bung plugs, and the J-pipe with clip/O-ring as listed. Price and package depend on selection; do not assume parts absent from the chosen option.',
    fitUa: 'BMW F87 M2 Competition S55, F80 M3 2015–2020 і F82/F83 M4 2015–2020 у fitment Burger. Не для стандартного N55 M2.', fitEn: 'For Burger-listed S55 F87 M2 Competition, 2015–2020 F80 M3, and 2015–2020 F82/F83 M4. Not for standard N55 M2.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Функція та користь</h3>\n<p>${item.benefitUa}</p>\n<h3>Опції та склад</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Function and benefit</h3>\n<p>${item.benefitEn}</p>\n<h3>Options and contents</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
