// Source-checked wheel spacers, wheel hardware, and tools; local draft only.
const rows = {
  'toyota-supra-mk5-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для Toyota GR Supra Mk5 — Classic або Lightweight', titleEn: 'BMS Wheel Spacers for Toyota GR Supra Mk5 — Classic or Lightweight',
    shortUa: 'Оберіть Classic або Lightweight та ширину 10–20 мм для hub-centric комплекту 5×112 / 66.6 мм.', shortEn: 'Choose Classic or Lightweight and 10–20 mm width for the 5×112 / 66.6 mm hub-centric kit.',
    benefitUa: 'BMS spacers відсувають колесо назовні, щоб скоригувати посадку, заповнення арки та clearance до гальм або підвіски. Hub-centric обробка за центром 66.6 мм допомагає утримувати колесо від вібрації, якщо розмір і монтаж відповідають авто.', benefitEn: 'BMS spacers move the wheel outward to adjust fitment, fender position, and clearance to brakes or suspension. The 66.6 mm hub-centric design helps center the wheel when size and installation match the vehicle.',
    detailsUa: 'Оберіть Classic або Lightweight та товщину. Classic: 10/13/15 мм із 10 розширеними 10.9-grade bolts. Lightweight: 10/13/15/20 мм із concentric floating-seat 12.9-grade bolts. Комплект містить пару spacers і болти для двох коліс; для всіх чотирьох потрібні два комплекти.', detailsEn: 'Choose Classic or Lightweight and thickness. Classic: 10/13/15 mm with ten extended 10.9-grade bolts. Lightweight: 10/13/15/20 mm with concentric floating-seat 12.9-grade bolts. One kit covers two wheels; two kits are needed for all four.',
    fitUa: 'Toyota GR Supra Mk5 2020–2026, pattern 5×112, center bore 66.6 mm. Виміряйте потрібне винесення й перевірте 10 мм Classic clearance warning перед замовленням.', fitEn: 'For 2020–2026 Toyota GR Supra Mk5, 5×112 pattern and 66.6 mm center bore. Measure the desired offset and confirm the 10 mm Classic clearance warning before ordering.'
  },
  'f-chassis-burger-motorsports-bmw-wheel-spacer-kit-2-spacers-w-10-extended-lug-bolts': {
    titleUa: 'BMS Wheel Spacers для BMW F-Chassis — Classic / Lightweight 10–20 мм', titleEn: 'BMS Wheel Spacers for BMW F-Chassis — Classic / Lightweight 10–20 mm',
    shortUa: 'Пара hub-centric spacers 5×120 / 72.6 мм; оберіть Classic або Lightweight і потрібну товщину.', shortEn: 'Pair of 5×120 / 72.6 mm hub-centric spacers; choose Classic or Lightweight and thickness.',
    benefitUa: 'Проставки BMS зміщують диски BMW F-Chassis назовні для бажаної посадки колеса й додаткового місця до супорта чи підвіски. Hub-centric профіль 72.6 мм центрується на маточині для правильної установки.', benefitEn: 'BMS spacers move BMW F-Chassis wheels outward for the selected stance and additional clearance to calipers or suspension. The 72.6 mm hub-centric profile centers on the factory hub for correct installation.',
    detailsUa: 'Оберіть Classic 10/12/15/18/20 мм або Lightweight 10/12/15 мм. Комплект — 2 spacers і 10 extended bolts; Classic bolts 10.9 grade, Lightweight — 12.9 grade floating-seat. Для 10 мм Classic сторінка має окреме попередження — підтвердьте зазор до супорта.', detailsEn: 'Choose Classic 10/12/15/18/20 mm or Lightweight 10/12/15 mm. Kit includes two spacers and ten extended bolts; Classic uses 10.9-grade bolts, Lightweight uses 12.9-grade floating-seat bolts. The 10 mm Classic option has a supplier warning; confirm caliper clearance.',
    fitUa: 'Для сумісних BMW F-Chassis із 5×120 pattern і 72.6 mm hub. Звірте модель, центральний отвір, різьбу болтів та посадку колеса до купівлі.', fitEn: 'For compatible BMW F-Chassis with 5×120 pattern and 72.6 mm hub. Verify model, bore, bolt thread, and wheel seat before purchase.'
  },
  'g-chassis-burger-motorsports-bmw-wheel-spacer-kit-w-10-bolts': {
    titleUa: 'BMS Wheel Spacers для BMW G / U / I-Chassis — Classic або Lightweight', titleEn: 'BMS Wheel Spacers for BMW G / U / I-Chassis — Classic or Lightweight',
    shortUa: 'Оберіть тип і товщину для BMW 5×112, 66.6 мм; набір для двох коліс із подовженими bolts.', shortEn: 'Choose style and width for BMW 5×112, 66.6 mm; kit for two wheels with extended bolts.',
    benefitUa: 'Проставки відсувають диски від маточини, змінюючи stance та додаючи clearance для окремих гальм, шин чи підвіски. Точне hub-centric кріплення під 66.6 мм допомагає колесам центруватися на BMW відповідного шасі.', benefitEn: 'The spacers move wheels away from the hub to adjust stance and add clearance for selected brakes, tires, or suspension. The 66.6 mm hub-centric fit centers wheels on compatible BMW chassis.',
    detailsUa: 'Оберіть Classic або Lightweight. Classic має 10/13/15 мм і десять 10.9-grade extended bolts; Lightweight 10/13/15/18/20 мм та 12.9-grade floating-seat bolts. Упаковка містить пару spacers для двох коліс; для повного авто потрібно два комплекти.', detailsEn: 'Choose Classic or Lightweight. Classic is available in 10/13/15 mm with ten 10.9-grade extended bolts; Lightweight in 10/13/15/18/20 mm with 12.9-grade floating-seat bolts. One package covers two wheels; a full car needs two kits.',
    fitUa: 'BMW G/U/I та вибрані F-Chassis із 5×112 bolt pattern і 66.6 мм center bore. Перевірте, чи ваша модель належить до переліку, бо не всі F-Series сумісні.', fitEn: 'For BMW G/U/I and selected F-Chassis with 5×112 pattern and 66.6 mm center bore. Confirm the exact model because not all F-Series fit.'
  },
  'hub-centric-wheel-spacers-for-kia-hyundai-genesis': {
    titleUa: 'BMS Hub-Centric Wheel Spacers для Kia Stinger / Genesis G70 — 15 або 20 мм', titleEn: 'BMS Hub-Centric Wheel Spacers for Kia Stinger / Genesis G70 — 15 or 20 mm',
    shortUa: 'Пара проставок із 10 studs і lug nuts для двох коліс; оберіть 15 або 20 мм товщини.', shortEn: 'Pair with ten studs and lug nuts for two wheels; choose 15 or 20 mm thickness.',
    benefitUa: 'Проставки зміщують колеса Stinger/G70 назовні для зміни посадки, clearance до підвіски й ширшої колії. Hub-centric конструкція має центруватися на штатній маточині для вібраційно-стійкої установки.', benefitEn: 'The spacers move Stinger/G70 wheels outward to adjust stance and clearance to suspension, while widening track. Hub-centric design centers on the factory hub for a vibration-resistant fit.',
    detailsUa: 'Оберіть 15 мм або 20 мм. Один комплект містить два spacers, десять попередньо встановлених 10.9-grade studs і десять lug nuts та покриває два колеса; для всіх чотирьох потрібні два комплекти. Зміряйте фактичний потрібний винос до покупки.', detailsEn: 'Choose 15 or 20 mm. One kit includes two spacers, ten pre-installed 10.9-grade studs, and ten lug nuts for two wheels; a full car needs two kits. Measure the desired wheel position before ordering.',
    fitUa: 'Kia Stinger / Genesis G70 2018+ у конфігураціях Burger. Перевірте bolt pattern, center bore та довжину різьби за вашим автомобілем.', fitEn: 'For Burger-listed 2018+ Kia Stinger / Genesis G70. Verify bolt pattern, center bore, and thread against the vehicle.'
  },
  '2025-toyota-4runner-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для Toyota 4Runner 2025+ — 1″ або 1.5″', titleEn: 'BMS Wheel Spacers for 2025+ Toyota 4Runner — 1 or 1.5 in',
    shortUa: 'Hub-centric пара spacer з pre-installed studs і lug nuts; оберіть 1″ або 1.5″ на колесо.', shortEn: 'Hub-centric spacer pair with pre-installed studs and lug nuts; choose 1 or 1.5 inches.',
    benefitUa: 'Проставки BMS виносять колеса Toyota 4Runner назовні для ширшої колії, іншого вигляду й clearance для більших шин або підвіски. Hub-centric профіль допомагає сумістити проставку зі штатною маточиною.', benefitEn: 'BMS spacers move Toyota 4Runner wheels outward for a wider track, changed stance, and clearance for selected larger tires or suspension. Hub-centric fit helps align each spacer to the factory hub.',
    detailsUa: 'Оберіть товщину 1″ (25.4 мм) або 1.5″ (38.1 мм). Комплект для двох коліс містить пару 7075-T6 spacers, 12 pre-installed studs і 12 lug nuts; для всіх чотирьох коліс потрібно два набори. Перевірте виліт і різьбу перед монтажем.', detailsEn: 'Choose 1 inch (25.4 mm) or 1.5 inches (38.1 mm). A two-wheel kit includes a pair of 7075-T6 spacers, 12 pre-installed studs, and 12 lug nuts; four wheels require two kits. Verify offset and thread before installation.',
    fitUa: 'Toyota 4Runner 2025+ за списком Burger. Звірте bolt pattern, center bore та сумісність із колесами/підвіскою.', fitEn: 'For Burger-listed 2025+ Toyota 4Runner. Verify bolt pattern, center bore, and wheel/suspension clearance.'
  },
  'racing-wheel-stud-conversion-kit-for-mini': {
    titleUa: 'MINI Racing Wheel Stud Conversion Kit — 4/5 lug, thread і довжина', titleEn: 'MINI Racing Wheel Stud Conversion Kit — 4/5 Lug, Thread and Length',
    shortUa: 'Оберіть 4- або 5-lug, thread за датою виробництва й stud length для потрібної товщини spacers.', shortEn: 'Choose 4- or 5-lug, thread by build date, and stud length for your spacer thickness.',
    benefitUa: 'Комплект переводить колеса MINI зі штатних болтів на різьбові stud, що полегшує встановлення колеса та spacers на треку чи під час сервісу. Гайки затягуються на встановлених у маточину studs.', benefitEn: 'The kit converts MINI from wheel bolts to threaded studs, simplifying wheel and spacer installation for track use or service. Lug nuts secure the wheel to studs mounted in the hub.',
    detailsUa: 'Виберіть 4 Lug або 5 Lug, thread і довжину. M14×1.25 підходить для авто від серпня 2006: 75 мм із 60 мм shank підтримує spacers до 12 мм; 90 мм із 75 мм shank — до 20 мм. MINI до липня 2006 зазвичай використовує M12×1.5. Комплект на дві маточини; кількість studs відповідає 4/5-lug.', detailsEn: 'Select 4 Lug or 5 Lug, thread, and length. M14×1.25 is listed for cars built from Aug 2006: 75 mm total / 60 mm shank supports spacers up to 12 mm; 90 mm / 75 mm shank supports up to 20 mm. MINI built through July 2006 typically uses M12×1.5. Kit converts two wheels; stud count follows 4/5-lug.',
    fitUa: 'Для MINI з датою виробництва та кількістю lug, що відповідають опції. Підтвердьте різьбу за VIN або фізичним виміром; не підбирайте лише за роком реєстрації.', fitEn: 'For MINI matching selected build date and lug count. Confirm thread by VIN or physical measurement; registration year alone is insufficient.'
  },
  'lightweight-g90-g91-bmw-m5-wheel-spacers-w-10-bolts': {
    titleUa: 'Lightweight Wheel Spacers для BMW G90 / G99 M5 — 13 або 15 мм', titleEn: 'Lightweight Wheel Spacers for BMW G90 / G99 M5 — 13 or 15 mm',
    shortUa: 'Легкі hub-centric spacers для нового M5; оберіть ширину 13 або 15 мм із floating-seat bolts.', shortEn: 'Lightweight hub-centric spacers for the new M5; choose 13 or 15 mm with floating-seat bolts.',
    benefitUa: 'Lightweight BMS spacers зміщують колесо назовні для посадки та clearance, зменшуючи масу порівняно з їхнім Classic варіантом. Hub-centric профіль центрується на маточині; floating-seat bolts призначені дати правильну посадку болта в колесо.', benefitEn: 'Lightweight BMS spacers move the wheel outward for stance and clearance with less mass than their Classic version. Hub-centric fit centers on the hub; floating-seat bolts provide the specified mating surface at the wheel.',
    detailsUa: 'Оберіть 13 або 15 мм. Комплект містить пару spacer і десять zinc-coated 12.9-grade Motorsport bolts із concentric floating-seat washer за джерелом. Перевірте товщину на кожній осі та переконайтеся, що довжина болтів відповідає дискам.', detailsEn: 'Choose 13 or 15 mm. The kit includes a spacer pair and ten zinc-coated 12.9-grade Motorsport bolts with concentric floating-seat washers per the source. Confirm thickness by axle and verify bolt length for the wheels.',
    fitUa: 'BMW M5 G90 Sedan / G99 Touring у застосуваннях Burger. Перевірте bolt pattern, центр і фактичний clearance до арки.', fitEn: 'For Burger-listed BMW M5 G90 Sedan / G99 Touring. Verify bolt pattern, hub bore, and fender clearance.'
  },
  '2022-lexus-lx600-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для Lexus LX600 2022+ — 1″ або 1.5″', titleEn: 'BMS Wheel Spacers for 2022+ Lexus LX600 — 1 or 1.5 in',
    shortUa: 'Hub-centric пара із 12 studs і lug nuts; оберіть 1″ або 1.5″ та рахуйте два комплекти на авто.', shortEn: 'Hub-centric pair with 12 studs and lug nuts; choose 1 or 1.5 inches, two kits for a full vehicle.',
    benefitUa: 'Проставки зміщують колеса LX600 назовні для ширшої посадки та clearance при підборі іншого offset чи більших шин. CNC 7075-T6 алюміній і hub-centric посадка розраховані на центроване встановлення.', benefitEn: 'The spacers move LX600 wheels outward for a wider stance and clearance when using different offsets or larger tires. CNC 7075-T6 aluminum and hub-centric fit are designed for centered installation.',
    detailsUa: 'Оберіть 1″ або 1.5″. У коробці пара spacer з 12 pre-installed 10.9-grade studs і 12 lug nuts для двох коліс. Для всього SUV потрібні два комплекти; обміряйте front/rear окремо й перевірте виліт до замовлення.', detailsEn: 'Choose 1 or 1.5 inches. The package is a pair with 12 pre-installed 10.9-grade studs and 12 lug nuts for two wheels. A full SUV requires two kits; measure front/rear separately and verify offset before ordering.',
    fitUa: 'Lexus LX600 2022+ за списком Burger. Перевірте bolt pattern, center bore, диски та фактичний зазор.', fitEn: 'For Burger-listed 2022+ Lexus LX600. Verify bolt pattern, center bore, wheels, and actual clearance.'
  },
  '2024-toyota-tacoma-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для Toyota Tacoma 2024+ — 1″ або 1.5″', titleEn: 'BMS Wheel Spacers for 2024+ Toyota Tacoma — 1 or 1.5 in',
    shortUa: 'Пара чорних 7075-T6 hub-centric spacers зі studs/lug nuts; оберіть 1″ або 1.5″.', shortEn: 'Pair of black 7075-T6 hub-centric spacers with studs/lug nuts; choose 1 or 1.5 inches.',
    benefitUa: 'BMS spacers виносять Tacoma wheels назовні для іншої ширини колії, посадки та clearance до підвіски чи ширших шин. Hub-centric конструкція з власним центрувальним буртом призначена для точної посадки.', benefitEn: 'BMS spacers move Tacoma wheels outward for track width, stance, and clearance to suspension or wider tires. Hub-centric design with an integrated lip is intended for precise seating.',
    detailsUa: 'Оберіть 1″ або 1.5″. Комплект містить два 7075-T6 spacers, 12 pre-installed 10.9-grade studs і 12 lug nuts на дві маточини; для всіх чотирьох потрібні два комплекти. Дотримуйтеся torque specs виробника та повторно перевірте затягування після пробігу.', detailsEn: 'Choose 1 or 1.5 inches. The kit includes two 7075-T6 spacers, twelve pre-installed 10.9-grade studs, and twelve lug nuts for two hubs; four wheels need two kits. Follow vehicle torque specs and recheck after initial mileage.',
    fitUa: 'Toyota Tacoma 2024+ у застосуваннях Burger. Перевірте версію коліс, bolt pattern і центр до замовлення.', fitEn: 'For Burger-listed 2024+ Toyota Tacoma. Verify wheel trim, bolt pattern, and center bore before ordering.'
  },
  'bms-elite-titanium-lug-nuts-for-tesla-21mm-hex-m14x1-5-cone-seat-set-of-20': {
    titleUa: 'BMS Elite Titanium Lug Nuts для Tesla M14×1.5 — 20 шт., Short / Tuner', titleEn: 'BMS Elite Titanium Lug Nuts for Tesla M14×1.5 — Set of 20, Short / Tuner',
    shortUa: '20 Grade 5 titanium nuts із 21 мм hex і 60° cone seat; оберіть Blue/Black та стандартну чи високу форму.', shortEn: '20 Grade 5 titanium nuts with 21 mm hex and 60° cone seat; select color and height.',
    benefitUa: 'Комплект titanium lug nuts зменшує не підресорену масу порівняно зі сталевими гайками та дає корозійно-стійке кріплення. Це колесне кріплення, де різьба й seat мають точно збігтися з диском.', benefitEn: 'The titanium lug-nut set reduces unsprung mass versus steel and resists corrosion. Wheel hardware must match both hub thread and wheel-seat profile exactly.',
    detailsUa: 'Оберіть Burned Blue або Shadow Black і Standard (Short) чи Tuner (Tall). У наборі 20 гайок, M14×1.5, 21 мм hex, 60° cone seat; стандартна гайка важить близько 23 г. Перевірте, чи потрібна висока гайка для конкретного диска.', detailsEn: 'Choose Burned Blue or Shadow Black and Standard (Short) or Tuner (Tall). Set of 20, M14×1.5, 21 mm hex, 60° cone seat; a standard nut is about 23 g. Confirm whether the wheel requires the taller nut.',
    fitUa: 'Tesla Model 3/Y/S/X у застосуваннях Burger з M14×1.5 і 60° cone seat. Перевірте профіль seat і довжину різьби; встановлюйте torque за Tesla.', fitEn: 'For Burger-listed Tesla Model 3/Y/S/X using M14×1.5 and 60° cone seats. Confirm seat profile and thread engagement; torque to Tesla specification.'
  },
  'bms-elite-titanium-lug-nuts-m14x1-25-cone-seat-set-of-20': {
    titleUa: 'BMS Elite Titanium Lug Nuts M14×1.25 — 20 шт., 17 мм hex', titleEn: 'BMS Elite Titanium Lug Nuts M14×1.25 — Set of 20, 17 mm Hex',
    shortUa: '20 Grade 5 titanium open lug nuts, 60° cone seat і 17 мм hex; оберіть Burned Blue або Shadow Black.', shortEn: '20 Grade 5 titanium open lug nuts, 60° cone seat, 17 mm hex; choose blue or black.',
    benefitUa: 'Титанові гайки BMS мають меншу масу за еквівалентні сталеві та стійкі до корозії й теплового впливу. Вони підходять лише до дисків із відповідною конічною посадкою та M14×1.25 різьбою.', benefitEn: 'BMS titanium nuts weigh less than equivalent steel hardware and resist corrosion and heat. They fit only wheels with matching conical seats and M14×1.25 threads.',
    detailsUa: 'Оберіть Burned Blue або Shadow Black. У комплекті 20 відкритих гайок Grade 5 Ti-6Al-4V, 17 мм hex, 60° cone seat, близько 22 г кожна. Не використовуйте air/power tools, щоб не пошкодити фініш; перевірте різьбу та seat до монтажу.', detailsEn: 'Choose Burned Blue or Shadow Black. Set of 20 open Grade 5 Ti-6Al-4V nuts, 17 mm hex, 60° cone seat, about 22 g each. Avoid air/power tools to protect finish; verify thread and seat before installation.',
    fitUa: 'Для маточин із різьбою M14×1.25 та дисків із 60° конічним seat. Не сумісні з M14×1.5 чи сферичним seat.', fitEn: 'For hubs with M14×1.25 threads and wheels with 60° cone seats. Not compatible with M14×1.5 or ball seats.'
  },
  'wheel-stud-conversion-kit-for-toyota-supra-mk5-m14x1-25': {
    titleUa: 'Racing Wheel Stud Kit для Toyota GR Supra Mk5 — 75 або 90 мм', titleEn: 'Racing Wheel Stud Kit for Toyota GR Supra Mk5 — 75 or 90 mm',
    shortUa: 'Набір на дві маточини: 10 studs і lug nuts; оберіть довжину під wheel spacer 13 або 20 мм.', shortEn: 'Two-hub set with ten studs and lug nuts; choose length for up to 13 or 20 mm spacers.',
    benefitUa: 'Stud conversion kit змінює Supra з колісних болтів на встановлені в маточину studs, щоб швидше центрувати колесо та обслуговувати його на вулиці чи треку. Гайки насаджуються на studs, а не вкручуються щоразу в маточину.', benefitEn: 'The stud-conversion kit changes Supra from wheel bolts to hub-mounted studs for easier wheel alignment and service on street or track. Lug nuts fasten to the studs instead of repeatedly threading into the hub.',
    detailsUa: 'Оберіть M14×1.25×75 мм (60 мм shank) для spacers до 13 мм або ×90 мм (75 мм shank) для spacers до 20 мм. У комплекті 10 studs і 10 lug nuts — на два колеса. За наявності spacer перевірте довжину engagement і посадку гайок.', detailsEn: 'Choose M14×1.25×75 mm (60 mm shank) for spacers up to 13 mm or ×90 mm (75 mm shank) for spacers up to 20 mm. Includes ten studs and ten lug nuts for two wheels. With spacers, verify thread engagement and nut seating.',
    fitUa: 'Toyota GR Supra Mk5 з M14×1.25 hub threads. Підтвердьте thread і необхідну довжину за товщиною spacer до замовлення.', fitEn: 'For Toyota GR Supra Mk5 with M14×1.25 hub threads. Confirm thread and required length for spacer thickness before ordering.'
  },
  'bmw-wheel-stud-conversion-kit': {
    titleUa: 'BMW Racing Wheel Stud Kit — оберіть M14 / M12 thread і довжину', titleEn: 'BMW Racing Wheel Stud Kit — Select M14 / M12 Thread and Length',
    shortUa: 'Комплект 10 studs/lug nuts конвертує дві маточини; thread залежить від E або F/G Chassis.', shortEn: 'Ten studs/lug nuts convert two hubs; thread depends on E or F/G chassis.',
    benefitUa: 'Stud conversion kit полегшує встановлення колеса й spacers на BMW, замінюючи різьбові wheel bolts на шпильки в маточині. Це сервісне/track hardware; сумісність залежить від різьби конкретного кузова.', benefitEn: 'The stud kit eases wheel and spacer installation by replacing wheel bolts with hub-mounted studs. This is service/track hardware; compatibility depends on the chassis thread.',
    detailsUa: 'Оберіть M14×1.25×75 мм або ×90 мм для більшості F/G-Chassis, чи M12×1.5×90 мм для більшості E-Chassis. 75 мм підтримує spacer до 12 мм; 90 мм — до 20 мм. У комплекті 10 studs і 10 lug nuts на дві маточини; підбирайте за фактичною різьбою.', detailsEn: 'Choose M14×1.25×75 or ×90 mm for most F/G-Chassis, or M12×1.5×90 mm for most E-Chassis. The 75 mm length supports spacers up to 12 mm; 90 mm up to 20 mm. Includes ten studs and ten lug nuts for two hubs; match actual thread.',
    fitUa: 'BMW з відповідною різьбою маточини. Перевірте thread, seat тип диска та довжину за товщиною spacer; покоління кузова — лише орієнтир.', fitEn: 'For BMW with the matching hub thread. Verify thread, wheel-seat type, and length for spacer thickness; chassis generation is only a guide.'
  },
  'bmw-xm-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для BMW XM G09 — 15 або 20 мм', titleEn: 'BMS Wheel Spacers for BMW XM G09 — 15 or 20 mm',
    shortUa: 'Пара чорних 7075-T6 hub-centric spacers із 10 extended bolts для BMW XM.', shortEn: 'Pair of black 7075-T6 hub-centric spacers with ten extended bolts for BMW XM.',
    benefitUa: 'Spacers виносять колеса BMW XM назовні, змінюючи stance та створюючи потрібне місце для диска чи підвіски. Hub-centric посадка призначена для центрування на штатній маточині.', benefitEn: 'The spacers move BMW XM wheels outward to adjust stance and create clearance for the wheel or suspension. Hub-centric fit is designed to center on the factory hub.',
    detailsUa: 'Оберіть 15 або 20 мм. У комплекті пара CNC 7075-T6 spacers, чорне анодування та 10 extended lug bolts для двох коліс; для всіх чотирьох потрібні два набори. Звірте bolt pattern, центр і довжину болтів.', detailsEn: 'Choose 15 or 20 mm. The package includes a pair of CNC 7075-T6 spacers, black anodizing, and ten extended lug bolts for two wheels; a full vehicle needs two kits. Verify bolt pattern, hub bore, and bolt length.',
    fitUa: 'Для BMW XM G09 за переліком Burger. Зміряйте винос і перевірте зазор до арки та підвіски перед встановленням.', fitEn: 'For Burger-listed BMW XM G09. Measure desired offset and verify fender and suspension clearance before installation.'
  },
  'bms-titanium-lug-nuts-m14x1-5-cone-seat-set-of-20': {
    titleUa: 'BMS Elite Titanium Lug Nuts M14×1.5 — 20 шт., 17 мм hex', titleEn: 'BMS Elite Titanium Lug Nuts M14×1.5 — Set of 20, 17 mm Hex',
    shortUa: '20 Grade 5 titanium open nuts, 60° cone seat і 17 мм hex; оберіть Burned Blue або Shadow Black.', shortEn: '20 Grade 5 titanium open nuts with 60° cone seat and 17 mm hex; choose color.',
    benefitUa: 'Легкі титанові BMS lug nuts зменшують масу колісного кріплення та стійкі до іржі й тепла. Різьба та форма посадки визначають сумісність: гайка має відповідати M14×1.5 hub і 60° cone seat диска.', benefitEn: 'BMS titanium lug nuts reduce wheel-hardware mass and resist rust and heat. Thread and seat shape determine fit: these must match an M14×1.5 hub and 60° cone-seat wheel.',
    detailsUa: 'Оберіть Burned Blue або Shadow Black. У наборі 20 open гайок Grade 5 Ti-6Al-4V, 17 мм hex, 60° conical seat, близько 22 г кожна. Не застосовуйте ударний/power tool; використовуйте non-marring socket і затягуйте за torque автовиробника.', detailsEn: 'Choose Burned Blue or Shadow Black. Set of 20 open Grade 5 Ti-6Al-4V nuts, 17 mm hex, 60° conical seat, about 22 g each. Avoid impact/power tools; use a non-marring socket and vehicle-specified torque.',
    fitUa: 'Для маточин M14×1.5 і коліс із 60° cone seat. Не сумісні з кульковою посадкою або іншим кроком різьби.', fitEn: 'For M14×1.5 hubs and wheels with 60° cone seats. Not for ball seats or different thread pitch.'
  },
  'toyota-tundra-sequoia-lexus-lx600-wheel-spacers': {
    titleUa: 'BMS Wheel Spacers для Toyota Tundra / Sequoia / Lexus LX600 — 1″ або 1.5″', titleEn: 'BMS Wheel Spacers for Toyota Tundra / Sequoia / Lexus LX600 — 1 or 1.5 in',
    shortUa: 'Hub-centric пара з 12 studs і nuts на 6×139.7 / 95 мм; оберіть товщину й два комплекти на авто.', shortEn: 'Hub-centric pair with 12 studs/nuts for 6×139.7 / 95 mm; choose thickness, two kits per vehicle.',
    benefitUa: 'Проставки допомагають скоригувати посадку великих позашляховиків, розширити колію та створити clearance для шин або aftermarket підвіски. Hub-centric адаптер точно центрується за заводською маточиною.', benefitEn: 'The spacers adjust stance on full-size SUVs, widen track, and can provide clearance for tires or aftermarket suspension. Hub-centric design centers to the factory hub.',
    detailsUa: 'Оберіть 1″ або 1.5″. Комплект на дві маточини містить пару 7075-T6 spacers, 12 pre-installed M14×1.5 10.9-grade studs і 12 lug nuts; pattern 6×139.7, center bore 95 мм. Для повного авто потрібно два набори. Затягуйте й повторно перевіряйте torque.', detailsEn: 'Choose 1 or 1.5 inches. Two-hub kit includes a pair of 7075-T6 spacers, twelve pre-installed M14×1.5 10.9-grade studs, and twelve lug nuts; 6×139.7 pattern, 95 mm bore. A full vehicle needs two kits. Torque and recheck fasteners.',
    fitUa: 'Toyota Tundra 2022+, Sequoia 2023+ та Lexus LX600 за сторінкою Burger. Перевірте 6-lug pattern і center bore перед замовленням.', fitEn: 'For Burger-listed 2022+ Toyota Tundra, 2023+ Sequoia, and Lexus LX600. Verify 6-lug pattern and center bore before ordering.'
  },
  'scratch-dent-bmw-wheel-spacers-w-10-bolts-by-burger-motorsports': {
    titleUa: 'BMS Scratch & Blem BMW Wheel Spacers — SKU-підбір, ручне підтвердження', titleEn: 'BMS Scratch & Blem BMW Wheel Spacers — SKU Selection, Manual Confirmation',
    shortUa: 'Залишки зі слідами косметичних дефектів; оберіть точне шасі/ширину й підтвердьте SKU перед оплатою.', shortEn: 'Cosmetically blemished stock; select chassis/width and confirm exact SKU before payment.',
    benefitUa: 'Це clearance залишки BMS spacers із подряпинами, ding або плямами, які не продаються як нові. Комплектація, дефект і конкретна ширина залежать від SKU, тому картка не описує один універсальний комплект.', benefitEn: 'These are BMS clearance spacers with scratches, dings, or stains that cannot be sold as new. Contents, blemish, and width vary by SKU, so this is not one universal kit.',
    detailsUa: 'Оберіть один із доступних BMW E/F/G-Chassis і spacer width. Перед оплатою потрібно підтвердити точний SKU, bolt pattern, центр, болти й стан конкретної пари. Продаж остаточний згідно з умовою постачальника; ціна/наявність виставляється вручну без автоматичного discount price.', detailsEn: 'Choose an available BMW E/F/G-Chassis and spacer width. Before payment, confirm exact SKU, bolt pattern, hub bore, bolts, and condition of the specific pair. Supplier marks sale final; price and availability require manual confirmation without an automatic discount price.',
    fitUa: 'Лише для конкретної підтвердженої пари й автомобіля. Не купуйте за загальною назвою без звірки SKU та сумісності.', fitEn: 'Only for the individually confirmed pair and vehicle. Do not order by the general title without checking SKU and fitment.', manualQuoteRequired: true
  },
  'f-j-u-chassis-mini-cooper-burger-motorsports-wheel-spacers-w-10-bolts': {
    titleUa: 'BMS Wheel Spacers для MINI F / J / U-Chassis — 10 / 13 / 15 мм', titleEn: 'BMS Wheel Spacers for MINI F / J / U-Chassis — 10 / 13 / 15 mm',
    shortUa: 'Пара 7075-T6 hub-centric spacers із 10 extended bolts; оберіть 10, 13 або 15 мм.', shortEn: 'Pair of 7075-T6 hub-centric spacers with ten extended bolts; choose 10, 13, or 15 mm.',
    benefitUa: 'MINI spacers зміщують колесо назовні, щоб скоригувати посадку й зазор до підвіски чи гальм. Hub-centric профіль центрується на штатній маточині, а сумісні довші wheel bolts фіксують колесо з spacer.', benefitEn: 'MINI spacers move the wheel outward to adjust stance and clearance to suspension or brakes. Hub-centric design centers on the factory hub, with matching longer wheel bolts securing spacer and wheel.',
    detailsUa: 'Оберіть товщину 10, 13 або 15 мм. Комплект містить пару 7075-T6 чорних spacer, десять extended lug bolts і anti-seize grease для двох коліс; повний автомобіль потребує два комплекти. Переконайтеся, що болти мають правильний seat і engagement.', detailsEn: 'Choose 10, 13, or 15 mm. The kit includes two black 7075-T6 spacers, ten extended lug bolts, and anti-seize for two wheels; a full vehicle requires two kits. Confirm bolt seat and thread engagement.',
    fitUa: 'MINI F/J/U-Chassis у застосуваннях Burger; RWD/AWD варіанти мають свої bolt specifications. Звірте кузов, pattern і hub bore.', fitEn: 'For Burger-listed MINI F/J/U-Chassis; RWD/AWD applications can use different bolt specifications. Verify chassis, pattern, and bore.'
  },
  'x5-x6-burger-motorsports-bmw-wheel-spacer-kit-w-10-bolts-e-f-chassis': {
    titleUa: 'BMS Wheel Spacers для BMW X5 / X6 E- та F-Chassis — 15 / 16 мм', titleEn: 'BMS Wheel Spacers for BMW X5 / X6 E- and F-Chassis — 15 / 16 mm',
    shortUa: 'Пара з 10 extended bolts; оберіть 15 мм non-M/non-xDrive або 16 мм для M/xDrive.', shortEn: 'Pair with ten extended bolts; choose 15 mm non-M/non-xDrive or 16 mm for M/xDrive.',
    benefitUa: 'Проставки змінюють винос коліс BMW X5/X6 для посадки та clearance, зберігаючи hub-centric центрування. Вибір товщини тут залежить від виконання автомобіля, а не лише від бажаного вигляду.', benefitEn: 'The spacers adjust BMW X5/X6 wheel position and clearance while retaining hub-centric centering. Thickness choice depends on vehicle configuration, not appearance alone.',
    detailsUa: 'Оберіть 15 мм для non-M/non-xDrive або 16 мм, якщо авто M чи xDrive. Комплект містить пару spacer, 10 extended lug bolts і anti-seize за джерелом; для чотирьох коліс потрібно два комплекти. Не підходить до E53 X5; G-Chassis X3/X5/X6 використовують інший виріб.', detailsEn: 'Choose 15 mm for non-M/non-xDrive or 16 mm for M or xDrive. The kit includes two spacers, ten extended lug bolts, and anti-seize per the source; a four-wheel set needs two kits. Not for E53 X5; G-Chassis X3/X5/X6 use another listing.',
    fitUa: 'Для BMW X5/X6 E/F-Chassis, крім E53, у варіантах, зазначених у селекторі. Не застосовуйте до G-Chassis.', fitEn: 'For listed BMW X5/X6 E/F-Chassis except E53, using the selector-defined configuration. Not for G-Chassis.'
  },
  'bms-wheel-pin-tool': {
    titleUa: 'BMS Wheel Hanger Pin — напрямна шпилька 1 або 2 шт. для різьби маточини', titleEn: 'BMS Wheel Hanger Pin — 1 or 2 Guide Pins for Hub Thread',
    shortUa: 'Напрямна шпилька центрує колесо й spacer під час монтажу; оберіть thread та 1- або 2-pack.', shortEn: 'Guide pin aligns wheel and spacer during installation; select thread and one- or two-pack.',
    benefitUa: 'Wheel hanger pin вкручується в один отвір маточини та тимчасово підтримує колесо/spacer, поки встановлюються lug bolts. Це полегшує центрування важкого колеса й зменшує потребу утримувати його вручну.', benefitEn: 'The hanger pin threads into one hub hole and temporarily supports the wheel/spacer while lug bolts are fitted. It helps align a heavy wheel and reduces the need to hold it by hand.',
    detailsUa: 'Оберіть thread: M14×1.25 для більшості BMW F/G/U/I, Supra та частини MINI; M12×1.5 для більшості BMW E і ранніх MINI; M14×1.5 для VW/Mercedes. Оберіть single pin або pack із двох. Опція має відповідати hub thread, а не розміру колісного болта на око.', detailsEn: 'Choose thread: M14×1.25 for most BMW F/G/U/I, Supra, and some MINI; M12×1.5 for most BMW E and early MINI; M14×1.5 for VW/Mercedes. Select one pin or a two-pack. Match the hub thread physically, not by appearance.',
    fitUa: 'Для різьби маточини з переліку: BMW/MINI/Supra, Volkswagen або Mercedes відповідного покоління. Перевірте thread перед замовленням.', fitEn: 'For the listed BMW/MINI/Supra, Volkswagen, or Mercedes hub threads. Verify thread before ordering.'
  },
  'mini-cooper-wheel-spacers-by-bms-pair-2-wheels-w-10-black-extended-wheel-bolts': {
    titleUa: 'BMS Wheel Spacers для MINI R60 Countryman / R61 Paceman — 10–20 мм', titleEn: 'BMS Wheel Spacers for MINI R60 Countryman / R61 Paceman — 10–20 mm',
    shortUa: 'Пара spacer із 10 black extended bolts; оберіть 10, 12, 15, 18 або 20 мм.', shortEn: 'Pair of spacers with ten black extended bolts; choose 10, 12, 15, 18, or 20 mm.',
    benefitUa: 'Проставки зміщують колеса MINI R60/R61 назовні для потрібного положення в арці й clearance до підвіски, не змінюючи самі диски. Hub-centric конструкція центрує spacer на заводській маточині.', benefitEn: 'The spacers move MINI R60/R61 wheels outward for the desired fender position and suspension clearance without changing the wheels themselves. Hub-centric design centers on the factory hub.',
    detailsUa: 'Оберіть 10/12/15/18/20 мм. Один kit містить пару spacer і 10 extended black bolts на два колеса; для всього авто потрібні два набори. Джерело рекомендує близько 18–20 мм для деяких стандартних конфігурацій, але просить виміряти арку й перевірити фактичний винос.', detailsEn: 'Choose 10/12/15/18/20 mm. One kit includes a pair and ten black extended bolts for two wheels; a full vehicle needs two kits. Burger suggests about 18–20 mm for some stock setups but advises measuring the fender and desired position.',
    fitUa: 'MINI R60 Countryman та R61 Paceman за списком Burger. Виміряйте передню й задню арки окремо та перевірте bolt length.', fitEn: 'For Burger-listed MINI R60 Countryman and R61 Paceman. Measure front and rear fenders separately and verify bolt length.'
  },
  'e-chassis-burger-motorsports-bmw-wheel-spacers-1': {
    titleUa: 'BMS Wheel Spacers для BMW E-Chassis — 10 / 12 / 15 / 18 / 20 мм', titleEn: 'BMS Wheel Spacers for BMW E-Chassis — 10 / 12 / 15 / 18 / 20 mm',
    shortUa: 'Hub-centric пара spacers з 10 extended bolts; не для E39 або E/F-Chassis X5/X6.', shortEn: 'Hub-centric spacer pair with ten extended bolts; not for E39 or X5/X6.',
    benefitUa: 'BMS spacers зміщують BMW wheel назовні для ширшої stance, покращеної посадки та clearance. Центрувальний бурт із заводським hub bore допомагає втримати колесо співвісно.', benefitEn: 'BMS spacers move BMW wheels outward for wider stance, fitment, and clearance. The hub-centric lip matches the factory bore to keep the wheel centered.',
    detailsUa: 'Оберіть 10, 12, 15, 18 або 20 мм. У комплекті пара CNC 7075-T6 анодованих spacers, десять extended bolts і anti-seize grease на два колеса; для повного авто потрібно два комплекти. Не підходять до BMW X5/X6 та E39.', detailsEn: 'Choose 10, 12, 15, 18, or 20 mm. The kit includes two CNC 7075-T6 anodized spacers, ten extended bolts, and anti-seize for two wheels; a full car requires two kits. Not for BMW X5/X6 or E39.',
    fitUa: 'Для сумісних BMW E-Chassis зі штатною маточиною відповідного розміру. Звірте центр, pattern, різьбу та bolt seat; не використовуйте на E39.', fitEn: 'For compatible BMW E-Chassis with matching factory hub. Verify bore, pattern, thread, and bolt seat; not for E39.'
  },
  'lug-bolts-only-bmw-mini': {
    titleUa: 'Extended Wheel Bolts для BMW / MINI Spacer — комплект 10 шт.', titleEn: 'Extended Wheel Bolts for BMW / MINI Spacers — Set of 10',
    shortUa: 'Лише 10 подовжених 10.9-grade bolts; оберіть E/F/G-Chassis та товщину spacer.', shortEn: 'Ten extended 10.9-grade bolts only; select E/F/G-Chassis and spacer thickness.',
    benefitUa: 'Подовжені bolts дають потрібну довжину різьби для фіксації колеса через wheel spacer. Вони замінюють штатні болти під час використання spacers і не є комплектом самих проставок.', benefitEn: 'Extended bolts provide the thread length required to secure a wheel through a spacer. They replace factory bolts when spacers are used and do not include spacers.',
    detailsUa: 'Оберіть версію для F/G або E-Chassis і товщину spacer. Кожна опція містить 10 bolts, що перевищують OEM grade за описом Burger (10.9 проти 8.9). Ніколи не використовуйте extended bolts без spacer на задній осі — можна пошкодити parking brake або hub.', detailsEn: 'Choose the F/G- or E-Chassis version and spacer thickness. Each option contains ten bolts, listed by Burger as 10.9 grade versus 8.9 OEM. Never use extended bolts without a rear spacer; they can damage the parking brake or hub.',
    fitUa: 'Для BMW/MINI spacer-систем із сумісною різьбою та посадкою. Звірте довжину spacer, thread, bolt seat і кузов до замовлення.', fitEn: 'For BMW/MINI spacer setups with matching thread and seat. Verify spacer thickness, thread, bolt seat, and chassis.'
  },
  'extra-copy-of-protective-wheel-saver-socket': {
    titleUa: 'BMS Protective Wheel Saver Socket — 17 мм / 19 мм / 21 мм', titleEn: 'BMS Protective Wheel Saver Socket — 17 mm / 19 mm / 21 mm',
    shortUa: 'Non-marring socket із polymer sleeve захищає фарбовані диски; оберіть розмір гайки або набір 3 шт.', shortEn: 'Non-marring polymer-sleeve socket protects finished wheels; choose lug size or 3-piece set.',
    benefitUa: 'Wheel saver socket накриває гайку захисною полімерною гільзою та вставкою, щоб зменшити ризик подряпати пофарбований чи лакований диск під час зняття колеса. Шестигранна конструкція розподіляє навантаження на грані гайки.', benefitEn: 'The wheel-saver socket surrounds a lug with a protective polymer sleeve and insert to reduce scratching of painted or clear-coated wheels during service. Six-point design spreads load across the lug faces.',
    detailsUa: 'Оберіть 17 мм для BMW/MINI/VW/Mercedes/Supra; 19 мм для багатьох Honda/Subaru/Volvo/американських авто; 21 мм для Infiniti/Kia/Toyota/Lexus/Scion; або комплект із 17/19/21 мм. Усі socket мають 1/2″ drive; знімна гільза підходить для thin-wall роботи.', detailsEn: 'Choose 17 mm for BMW/MINI/VW/Mercedes/Supra; 19 mm for many Honda/Subaru/Volvo/American cars; 21 mm for Infiniti/Kia/Toyota/Lexus/Scion; or the 17/19/21 mm set. Sockets use 1/2-inch drive; sleeve is removable for thin-wall access.',
    fitUa: 'Для гайок відповідного hex size. Перевірте розмір і clearance до диска; один розмір не підходить до всіх гайок конкретної марки.', fitEn: 'For lug nuts of the matching hex size. Verify size and wheel clearance; one socket size does not fit every lug on a make.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Що змінює ця деталь</h3>\n<p>${item.benefitUa}</p>\n<h3>Вибір та комплектація</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність і встановлення</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and benefit</h3>\n<p>${item.benefitEn}</p>\n<h3>Options and package</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment and installation</h3>\n<p>${item.fitEn}</p>`,
}]));
