// Source-checked BOV and BOV-adapter descriptions; local draft only.
const rows = {
  'bms-bov-spacer-for-vw-audi-ea888-gen5-2-0l': {
    titleUa: 'BMS BOV Spacer для VW Tiguan 2.0T EA888 Gen 5', titleEn: 'BMS BOV Spacer for VW Tiguan 2.0T EA888 Gen 5',
    shortUa: 'BOV spacer для Tiguan вставляється між штатним перепускним клапаном і системою наддуву та змінює звук скидання тиску.', shortEn: 'Tiguan BOV spacer fits at the factory bypass valve and changes the sound of charge-pressure release.',
    benefitUa: 'Цей BMS blow-off valve spacer змінює спосіб виходу надлишкового повітря під час скидання газу: замість тихого повернення у впуск воно виходить в атмосферу з характерним звуком. Деталь не є тюнінгом потужності й сама по собі не змінює ECU-калібрування.', benefitEn: 'This BMS blow-off valve spacer changes how excess charge air is released when you lift off the throttle: air vents to atmosphere for the characteristic sound instead of returning quietly to the intake. It is not a power tune and does not change ECU calibration.',
    detailsUa: 'Чорний spacer оброблений на CNC із billet-алюмінію та має два ущільнювальні кільця. За переліком Burger, у комплекті spacer, мале й велике O-ring та три подовжені болти. Монтується між штатним bypass solenoid і вузлом впуску; перед встановленням перевірте конструкцію клапана на конкретному автомобілі.', detailsEn: 'The black spacer is CNC-machined from billet aluminum and uses two O-rings. Burger lists the spacer, small and large O-rings, and three extended bolts in the package. It installs between the factory bypass solenoid and intake assembly; confirm the valve layout on the vehicle before installation.',
    fitUa: 'Сторінка Burger вказує VW Tiguan 2025+ потужністю 201 hp. Хоча назва товару згадує EA888 Gen 5 і Audi, не поширюйте сумісність на інші моделі без звірки двигуна, клапана та каталожної сторінки.', fitEn: 'Burger lists the 2025+ VW Tiguan rated at 201 hp. Although the product title mentions EA888 Gen 5 and Audi, verify the engine and bypass-valve layout before applying fitment to another model.'
  },
  'bms-blow-off-valve-bov-adapter-for-2022-lotus-emira-m139-2-0l': {
    titleUa: 'BMS BOV Adapter для Lotus Emira M139 2.0 Turbo', titleEn: 'BMS BOV Adapter for Lotus Emira M139 2.0 Turbo',
    shortUa: 'Адаптер BMS для Emira M139 формує атмосферний звук скидання надлишкового повітря; CNC billet-алюміній і монтажне кріплення.', shortEn: 'Emira M139 BMS adapter vents charge air for an atmospheric blow-off sound; CNC billet aluminum with mounting hardware.',
    benefitUa: 'Адаптер встановлюється між заводським bypass solenoid і системою наддуву Lotus Emira. Під час скидання газу надлишкове повітря відводиться в атмосферу, створюючи виразний blow-off звук; це акустична модифікація, а не окрема прошивка чи гарантований приріст потужності.', benefitEn: 'The adapter fits between the factory bypass solenoid and the Lotus Emira charge system. When the throttle closes, excess charge air vents to atmosphere for a more pronounced blow-off sound. This is an acoustic modification, not an ECU tune or a guaranteed power increase.',
    detailsUa: 'Деталь виконана з CNC-обробленого billet-алюмінію з чорним анодуванням. Burger перелічує spacer, мале й велике O-ring та три гвинти M6×1.0×30 мм під внутрішній шестигранник. Під час монтажу використовуйте правильний момент затягування та перевірте герметичність з’єднання.', detailsEn: 'The part is CNC-machined from billet aluminum and black anodized. Burger lists the spacer, small and large O-rings, and three M6×1.0×30 mm Allen bolts. Use the correct tightening procedure and check the joint for leaks after installation.',
    fitUa: 'Призначений для Lotus Emira 2022+ з 2.0L I4 Turbo M139. Перед замовленням звірте модельний рік, двигун і штатний клапан перепуску.', fitEn: 'For 2022+ Lotus Emira with the 2.0L M139 turbocharged inline-four. Verify model year, engine, and factory bypass valve before ordering.'
  },
  'bms-blow-off-valve-bov-adapter-for-2010-2019-ford-taurus-sho': {
    titleUa: 'BMS BOV Adapters для Ford Taurus SHO 2010–2019 — пара', titleEn: 'BMS BOV Adapters for 2010–2019 Ford Taurus SHO — Pair',
    shortUa: 'Пара BOV-адаптерів для Taurus SHO відводить надлишкове повітря в атмосферу та додає характерний звук турбомотора.', shortEn: 'Pair of Taurus SHO BOV adapters vents excess charge air to atmosphere for a turbo blow-off sound.',
    benefitUa: 'Адаптери ставляться між штатними перепускними клапанами OE та інтеркулером. Під час закриття дроселя надлишкове повітря виходить назовні й створює виразний звук blow-off; деталь не перепрограмовує двигун і не обіцяє приріст потужності.', benefitEn: 'The adapters install between the factory bypass valves and intercooler. When the throttle closes, excess charge air vents to atmosphere for a distinct blow-off sound. The parts do not reprogram the engine or promise a power increase.',
    detailsUa: 'Burger називає товар парою, однак перелік комплекту на сторінці зазначає один адаптер і кріплення. Щоб не обіцяти зайву деталь, до відвантаження слід підтвердити кількість у комплекті. У переліку також вказані чотири гвинти з нержавіючої сталі M6×1×45 мм.', detailsEn: 'Burger describes this listing as a pair, while its package list names one adapter plus hardware. Confirm the supplied quantity before dispatch so the listing does not overpromise. The page also lists four stainless M6×1×45 mm screws.',
    fitUa: 'Для Ford Taurus SHO 2010–2019 за переліком сумісності Burger. Перевірте наявність двох штатних bypass valves і форму інтеркулерних з’єднань на вашому авто.', fitEn: 'For 2010–2019 Ford Taurus SHO as listed by Burger. Check that the vehicle has the matching pair of factory bypass valves and intercooler connections.'
  },
  'bms-elite-bmw-b58tu-charge-pipe-blow-off-valve-bov-kit': {
    titleUa: 'BMS Elite Charge Pipe і Turbosmart RacePort BOV для BMW B58 Gen 2 / Supra', titleEn: 'BMS Elite Charge Pipe and Turbosmart RacePort BOV for BMW B58 Gen 2 / Supra',
    shortUa: 'Повний B58TU комплект: алюмінієвий charge pipe, Turbosmart RacePort BOV, ущільнення, з’єднувачі та фітинги.', shortEn: 'Complete B58TU package with aluminum charge pipes, Turbosmart RacePort BOV, seals, couplers, and fittings.',
    benefitUa: 'Комплект замінює верхній і нижній charge pipe та додає Turbosmart RacePort blow-off valve. Клапан випускає надлишковий тиск при скиданні газу, формує виразний звук і, за описом Burger, допомагає зменшувати компресорний surge. Збільшений діаметр і три порти 1/8 NPT передбачені для кращого потоку та підключення датчика наддуву або форсунок WMI.', benefitEn: 'This kit replaces the upper and lower charge pipes and adds a Turbosmart RacePort blow-off valve. The valve releases excess pressure when the throttle closes, creates a pronounced sound, and is intended to reduce compressor surge. The larger pipes and three 1/8 NPT ports support airflow and connections for a boost gauge or WMI nozzles.',
    detailsUa: 'У комплекті за списком Burger: RacePort BOV, верхній і нижній charge pipe, силіконовий coupler, T-bolt clamps, п’ять заглушок 1/8 NPT, O-rings, кріплення, BOV adapter із фіксатором, push-lock fittings і 30″ трубки. Два O-ring на турбінному фланці; виробник вказує сумісність зі штатним керуванням, JB4 і flash tune та можливість повернення до стандартної конфігурації.', detailsEn: 'Burger lists the RacePort valve, upper and lower charge pipes, silicone coupler, T-bolt clamps, five 1/8 NPT plugs, O-rings, mounting hardware, BOV adapter and clip, push-lock fittings, and 30-inch tubing. The turbo flange uses a dual O-ring seal. The supplier lists compatibility with factory tuning, JB4, and flash tuning, and describes the setup as reversible.',
    fitUa: 'Лише BMW із двигуном B58 Gen 2 та Toyota GR Supra Mk5 2020–2026 з B58 3.0L у перелічених Burger конфігураціях. Для X-моделей 2023+ Burger просить надіслати фото двигуна перед замовленням; Gen 3 B58TU2 не підходить за цією сторінкою.', fitEn: 'For Burger-listed BMW applications with the second-generation B58 and 2020–2026 Toyota GR Supra Mk5 3.0L B58. Burger asks for engine photos before ordering for 2023+ X models. This listing is not for the Gen 3 B58TU2.'
  },
  'bms-blow-off-valve-bov-adapter-for-bmw-gen3-b58tu2': {
    titleUa: 'BMS BOV Adapter для BMW B58 Gen 3 B58TU2', titleEn: 'BMS BOV Adapter for BMW B58 Gen 3 B58TU2',
    shortUa: 'Адаптер BMS для Gen 3 B58TU2 змінює звук перепускного клапана; перевірте покоління двигуна й рік авто.', shortEn: 'BMS adapter changes bypass-valve sound on Gen 3 B58TU2; verify engine generation and model year.',
    benefitUa: 'Адаптер встановлюється на штатний bypass solenoid і відводить повітря наддуву в атмосферу при скиданні газу. Він додає характерний звук blow-off, зберігаючи заводський клапан як основу вузла; не додає потужності без окремого налаштування двигуна.', benefitEn: 'The adapter mounts to the factory bypass solenoid and vents charge air to atmosphere when the throttle closes. It adds the characteristic blow-off sound while retaining the factory valve as the basis of the assembly; it does not add power without separate engine tuning.',
    detailsUa: 'Корпус виготовлений із billet-алюмінію на CNC та має чорне анодування. Монтаж передбачає зняття штатного клапана, встановлення адаптера між ним і автомобілем та повторне кріплення подовженими болтами. Звірте ущільнення та після монтажу перевірте систему наддуву на витоки.', detailsEn: 'The body is CNC-machined billet aluminum with a black anodized finish. Installation removes the factory valve, places the adapter between it and the vehicle, and secures the assembly with extended bolts. Check the seal and inspect the charge system for leaks after installation.',
    fitUa: 'Burger вказує Gen 3 B58: BMW M340i/M340i xDrive та M440i/M440i xDrive 2025+, 740i 2023+, X5 xDrive40i 2024+ і X7 xDrive40i 2022+. Не плутайте з адаптером для B58 Gen 2.', fitEn: 'Burger lists Gen 3 B58 fitment: 2025+ BMW M340i/M340i xDrive and M440i/M440i xDrive, 2023+ 740i, 2024+ X5 xDrive40i, and 2022+ X7 xDrive40i. Do not confuse it with the Gen 2 B58 adapter.'
  },
  'blow-off-valve-bov-adapter-for-subaru-wrx': {
    titleUa: 'Регульований BMS BOV Adapter для Subaru WRX 2022+', titleEn: 'Adjustable BMS BOV Adapter for 2022+ Subaru WRX',
    shortUa: 'Регульований BOV adapter для WRX: знімні гвинти налаштовують звук від гучного до близького до штатного.', shortEn: 'Adjustable WRX BOV adapter uses removable set screws to tune sound from loud to near-stock operation.',
    benefitUa: 'Адаптер відводить частину повітря наддуву в атмосферу при скиданні газу, додаючи характерний звук blow-off. Знімні set screws дають змогу змінювати звучання: без гвинтів воно найгучніше, три гвинти наближають роботу до штатної. Burger радить почати з двох і перевірити поведінку автомобіля.', benefitEn: 'The adapter vents charge air to atmosphere when the throttle closes, adding a blow-off sound. Removable set screws adjust the sound: no screws produce the loudest setting, while three approximate stock operation. Burger suggests beginning with two screws and evaluating the result.',
    detailsUa: 'CNC billet-алюмінієвий spacer із чорним анодуванням монтується між OE bypass solenoid і автомобілем. За переліком виробника в коробці spacer, мале та велике O-ring, три подовжені болти й три регулювальні гвинти. Після монтажу перевірте відсутність витоків і правильну роботу двигуна.', detailsEn: 'The black-anodized CNC billet-aluminum spacer fits between the OE bypass solenoid and vehicle. Burger lists the spacer, small and large O-rings, three extended bolts, and three adjustment screws. After installation, check for leaks and confirm normal engine operation.',
    fitUa: 'Для Subaru WRX 2022+ за переліком Burger. Переконайтеся, що це саме WRX потрібного модельного року, а не інша модель Subaru з подібним двигуном.', fitEn: 'For 2022+ Subaru WRX as listed by Burger. Confirm the exact WRX model year; similar Subaru engines do not establish fitment for other models.'
  },
  'blow-off-valve-bov-adapter-for-toyota-tundra': {
    titleUa: 'Регульовані BMS BOV Adapters для Toyota Tundra 3.4T / Sequoia', titleEn: 'Adjustable BMS BOV Adapters for Toyota Tundra 3.4T / Sequoia',
    shortUa: 'Регульовані BOV adapters підсилюють звук перепуску на Tundra/Sequoia 3.4T; несумісні з AFE charge pipes.', shortEn: 'Adjustable BOV adapters enhance bypass sound on Tundra/Sequoia 3.4T; incompatible with AFE charge pipes.',
    benefitUa: 'BMS adapters встановлюються на штатні diverter valves і відводять надлишкове повітря назовні при закритті дроселя. Знімні регулювальні гвинти дають змогу змінити звук: без гвинтів він найгучніший, чотири наближають роботу до штатної. Це акустична модифікація, не тюнінг потужності.', benefitEn: 'BMS adapters fit the factory diverter valves and vent excess charge air when the throttle closes. Removable set screws adjust the sound: no screws give the loudest setting, while four approximate stock operation. This is an acoustic modification, not a power tune.',
    detailsUa: 'У комплекті має бути по адаптеру для кожного застосування, ущільнення та кріплення за переліком Burger. Починайте з двох set screws і налаштовуйте поступово. Виробник прямо попереджає: адаптери не сумісні з aftermarket charge pipes AFE для Tundra.', detailsEn: 'The package uses the adapters, seals, and mounting hardware listed by Burger for the selected application. Start with two set screws and adjust gradually. The supplier explicitly warns that these adapters do not fit AFE aftermarket Tundra charge pipes.',
    fitUa: 'Для Toyota Tundra 2022+ 3.4L V6 Twin Turbo, включно з i-FORCE MAX/TRD Pro, та Sequoia 2023+ 3.4L за списком Burger. Перед замовленням перевірте тип charge pipe.', fitEn: 'For Burger-listed 2022+ Toyota Tundra 3.4L twin-turbo V6, including i-FORCE MAX/TRD Pro, and 2023+ Sequoia 3.4L. Verify the charge-pipe type before ordering.'
  },
  'blow-off-valve-bov-for-cadillac-ct5v': {
    titleUa: 'BMS BOV Adapters для Cadillac CT4 / CT5 / CT5-V — вибір двигуна', titleEn: 'BMS BOV Adapters for Cadillac CT4 / CT5 / CT5-V — Select Engine',
    shortUa: 'Оберіть двигун Cadillac: 2.0L Turbo має один BOV adapter, 3.0L Twin Turbo V6 — комплект для двох клапанів.', shortEn: 'Select the Cadillac engine: 2.0L Turbo uses one adapter; 3.0L twin-turbo V6 uses a two-valve set.',
    benefitUa: 'BMS BOV adapters встановлюються на штатні bypass solenoids і випускають надлишкове повітря наддуву в атмосферу, додаючи виразний звук при скиданні газу. Кількість клапанів відрізняється за двигуном, тому вибір опції критично важливий для правильної комплектності.', benefitEn: 'BMS BOV adapters fit the factory bypass solenoids and vent excess charge air to atmosphere for a pronounced sound when lifting off the throttle. The number of valves varies by engine, so selecting the correct option is essential for the right package.',
    detailsUa: 'Варіант 6cyl 3.0L (2 BOV) призначений для Twin Turbo V6 і містить адаптери для двох штатних клапанів; варіант 4cyl 2.0L (1 BOV) — для одного клапана. CNC-оброблений billet-алюміній і кріплення входять згідно з описом Burger. Не встановлюйте комплект 2.0L на V6 або навпаки.', detailsEn: 'The 6-cylinder 3.0L (2 BOV) option is for the twin-turbo V6 and covers two factory valves; the 4-cylinder 2.0L (1 BOV) option is for one valve. Burger describes CNC-machined billet aluminum and mounting hardware. Do not use the 2.0L configuration on the V6 or vice versa.',
    fitUa: 'Для Cadillac CT4/CT5 з 2.0L Turbo та CT5-V з 3.0L Twin Turbo V6 2020+ за сторінкою Burger. Оберіть конфігурацію за двигуном, а не лише за назвою моделі.', fitEn: 'For 2020+ Cadillac CT4/CT5 with the 2.0L turbo and CT5-V with the 3.0L twin-turbo V6, as listed by Burger. Choose by engine, not model name alone.'
  },
  'bms-blow-off-valve-bov-adapter-for-2019-ford-ranger-2-3l-ecoboost': {
    titleUa: 'BMS BOV Adapter для Ford Ranger 2.3L EcoBoost 2019+', titleEn: 'BMS BOV Adapter for 2019+ Ford Ranger 2.3L EcoBoost',
    shortUa: 'Адаптер для Ranger 2.3 EcoBoost відводить надлишкове повітря наддуву в атмосферу та додає звук blow-off.', shortEn: 'Ranger 2.3 EcoBoost adapter vents excess charge air to atmosphere for a blow-off sound.',
    benefitUa: 'Адаптер монтується між штатним bypass solenoid і системою наддуву Ford Ranger. Він спрямовує надлишкове повітря назовні при скиданні газу, створюючи характерний звук турбоклапана; не змінює заводську карту керування двигуном.', benefitEn: 'The adapter installs between the factory bypass solenoid and the Ford Ranger charge system. It vents excess air when the throttle closes for a turbo blow-off sound and does not change the factory engine calibration.',
    detailsUa: 'Корпус виготовлений із billet-алюмінію на CNC та має чорне анодування. Сторінка Burger перелічує spacer, два O-rings і три подовжені болти. Перевірте посадку з’єднань після встановлення та виконайте монтаж за інструкцією виробника.', detailsEn: 'The spacer is CNC-machined from billet aluminum with a black anodized finish. Burger lists the adapter, two O-rings, and three extended bolts. Check the connections after fitting and follow the manufacturer installation instructions.',
    fitUa: 'Для Ford Ranger 2019+ з 2.3L EcoBoost. Не переносіть сумісність автоматично на Bronco або інші моделі з тим самим двигуном.', fitEn: 'For 2019+ Ford Ranger with the 2.3L EcoBoost. Do not assume fitment on a Bronco or another model solely because it shares the engine.'
  },
  'bms-blow-off-valve-bov-adapter-for-ford-bronco': {
    titleUa: 'BMS BOV Adapter для Ford Bronco EcoBoost — 2.3L або 2.7L', titleEn: 'BMS BOV Adapter for Ford Bronco EcoBoost — 2.3L or 2.7L',
    shortUa: 'Оберіть двигун Bronco 2.3L або 2.7L: адаптер BOV формує звук скидання надлишкового тиску турбіни.', shortEn: 'Select the Bronco 2.3L or 2.7L engine; BOV adapter adds a turbo pressure-release sound.',
    benefitUa: 'Адаптер BMS встановлюється на штатний bypass solenoid і відводить невикористане повітря наддуву в атмосферу при відпусканні педалі газу. Це створює характерний звук blow-off; модифікація не є JB4 чи ECU tune і не додає гарантованої потужності.', benefitEn: 'The BMS adapter fits the factory bypass solenoid and vents unused charge air to atmosphere when you lift off the throttle. It creates the characteristic blow-off sound; it is not a JB4 or ECU tune and does not provide a guaranteed power increase.',
    detailsUa: 'Оберіть двигун саме вашого Ford Bronco: 2.3L Turbo або 2.7L Turbo. Деталь CNC-оброблена з billet-алюмінію, анодована чорним; Burger перелічує spacer, два O-rings і три подовжені болти. Після монтажу перевірте герметичність системи наддуву.', detailsEn: 'Select the exact Ford Bronco engine: 2.3L turbo or 2.7L turbo. The part is CNC-machined billet aluminum with a black anodized finish; Burger lists the spacer, two O-rings, and three extended bolts. Check the charge system for leaks after installation.',
    fitUa: 'Для Ford Bronco 2021+ з 2.3L або 2.7L EcoBoost за переліком Burger. Не плутайте з адаптером для Ford Ranger 2.3L.', fitEn: 'For 2021+ Ford Bronco with the 2.3L or 2.7L EcoBoost as listed by Burger. This is distinct from the Ford Ranger 2.3L adapter.'
  },
  'blow-off-valve-bov-adapter-for-mercedes-benz-cla-gla-a-45-amg': {
    titleUa: 'BMS BOV Adapter для Mercedes-AMG M139L 2.0 Turbo', titleEn: 'BMS BOV Adapter for Mercedes-AMG M139L 2.0 Turbo',
    shortUa: 'Адаптер для Mercedes-AMG M139L відводить повітря в атмосферу та створює виразніший звук перепускного клапана.', shortEn: 'M139L Mercedes-AMG adapter vents charge air to atmosphere for a more pronounced bypass sound.',
    benefitUa: 'BMS BOV adapter змінює вихід надлишкового повітря при скиданні газу, додаючи атмосферний blow-off звук. Він встановлюється на заводський bypass solenoid і не замінює керування двигуном або заводську програму.', benefitEn: 'The BMS BOV adapter changes how excess charge air exits when you lift off the throttle, adding an atmospheric blow-off sound. It fits the factory bypass solenoid and does not replace engine management or the factory software.',
    detailsUa: 'CNC billet-алюмінієвий spacer із чорним анодуванням постачається з малим і великим O-ring та трьома болтами M6×1.0×30 мм за переліком Burger. Монтаж виконується між штатним клапаном і автомобілем; після встановлення перевірте щільність з’єднання.', detailsEn: 'The black-anodized CNC billet-aluminum spacer is listed with small and large O-rings and three M6×1.0×30 mm bolts. It fits between the factory valve and vehicle; check the joint for a secure seal after installation.',
    fitUa: 'Burger заявляє двигун M139L для C63 2024+, C43 2023+, CLA45 2019+, A45 2020+, GLA45 2021+ та SL43 2022+. Звірте саме код двигуна M139L: схожі 2.0L AMG не гарантують сумісність.', fitEn: 'Burger lists M139L fitment for 2024+ C63, 2023+ C43, 2019+ CLA45, 2020+ A45, 2021+ GLA45, and 2022+ SL43. Confirm the M139L engine code; another similar 2.0L AMG application is not automatically compatible.'
  },
  'bms-blow-off-valve-bov-adapter-for-kia-k5': {
    titleUa: 'BMS BOV Adapter для Kia K5 / Hyundai Sonata 1.6 Turbo', titleEn: 'BMS BOV Adapter for Kia K5 / Hyundai Sonata 1.6 Turbo',
    shortUa: 'BOV adapter для K5 і Sonata 1.6T відводить повітря наддуву в атмосферу та додає характерний звук скидання.', shortEn: 'K5 and Sonata 1.6T BOV adapter vents charge air to atmosphere for a distinctive release sound.',
    benefitUa: 'Адаптер встановлюється між заводським bypass solenoid і системою наддуву, щоб невикористане повітря виходило в атмосферу при скиданні газу. Він змінює звук турбомотора, але не перепрограмовує ECU та не є самостійним засобом збільшення потужності.', benefitEn: 'The adapter fits between the factory bypass solenoid and charge system so unused air vents to atmosphere when the throttle closes. It changes the turbo sound but does not reprogram the ECU or independently increase engine power.',
    detailsUa: 'Деталь виготовлена з CNC billet-алюмінію з чорним анодуванням. Підбір проводьте за двигуном і штатним клапаном; після монтажу перевірте ущільнення та відсутність витоків наддуву. Дотримуйтеся інструкції Burger для безпечного демонтажу solenoid.', detailsEn: 'The part is CNC-machined billet aluminum with a black anodized finish. Match the engine and factory valve, then check the seal and charge system for leaks after installation. Follow Burger instructions when removing the solenoid.',
    fitUa: 'За списком Burger: Kia K5 2021+ 1.6L Turbo і Hyundai Sonata 2020+ 1.6L Turbo. Рік і двигун можуть різнитися за ринком; звірте комплектацію авто.', fitEn: 'Burger lists 2021+ Kia K5 1.6L turbo and 2020+ Hyundai Sonata 1.6L turbo. Model years can vary by market; verify the vehicle specification.'
  },
  'bms-blow-off-valve-bov-adapter-for-f30-335i-f32-435i-f21-f21-m135i': {
    titleUa: 'BMS BOV Adapter для BMW N55 F-Series — 135i / 235i / 335i / 435i', titleEn: 'BMS BOV Adapter for BMW N55 F-Series — 135i / 235i / 335i / 435i',
    shortUa: 'Адаптер BOV для N55 F-Series змінює звук перепуску; перед купівлею звірте кузов, двигун і модельний рік.', shortEn: 'N55 F-Series BOV adapter changes bypass sound; verify chassis, engine, and model year before ordering.',
    benefitUa: 'Адаптер монтується на штатний bypass solenoid BMW N55 та відводить надлишкове повітря наддуву в атмосферу, створюючи характерний blow-off звук. Він не є charge pipe чи JB4 модулем і не змінює калібрування двигуна.', benefitEn: 'The adapter mounts to the factory bypass solenoid on the BMW N55 and vents excess charge air to atmosphere for a characteristic blow-off sound. It is not a charge pipe or JB4 module and does not change engine calibration.',
    detailsUa: 'Заводська посадка зберігається за умови правильного кузова й року. Burger зазначає billet-алюмінієвий адаптер, кріплення та ущільнення; після встановлення перевірте, що штатний клапан рухається вільно й з’єднання герметичне.', detailsEn: 'The factory mounting arrangement is retained when chassis and model year match. Burger describes a billet-aluminum adapter, mounting hardware, and seals; after fitting, confirm the factory valve moves freely and the connection is sealed.',
    fitUa: 'Для перелічених N55 BMW F20/F21 M135i, F22/F23 M235i, F87 M2 лише з N55, F30/F31 335i, F34 335i GT, F32/F33/F36 435i та F10/F11/F07 535i. Не підходить автоматично до B58 або S55.', fitEn: 'For listed N55 BMW F20/F21 M135i, F22/F23 M235i, F87 M2 with N55 only, F30/F31 335i, F34 335i GT, F32/F33/F36 435i, and F10/F11/F07 535i. It is not automatically compatible with B58 or S55.'
  },
  'x2-o-rings-for-tial-q-50mm-bov': {
    titleUa: 'Комплект із 2 O-Ring для Tial Q 50 мм і Turbosmart RacePort BOV', titleEn: 'Set of 2 O-Rings for Tial Q 50 mm and Turbosmart RacePort BOV',
    shortUa: 'Два змінні ущільнювальні кільця для сумісних клапанів Tial Q 50 мм і Turbosmart RacePort.', shortEn: 'Two replacement seals for compatible Tial Q 50 mm and Turbosmart RacePort valves.',
    benefitUa: 'Це комплект із двох replacement O-rings/gaskets для обслуговування сумісного blow-off valve. Нові ущільнення допомагають відновити герметичність вузла, якщо старі кільця зношені або пошкоджені; самі клапани в цю позицію не входять.', benefitEn: 'This set contains two replacement O-rings/gaskets for servicing a compatible blow-off valve. Replacing worn or damaged seals can restore the valve joint seal; the valves themselves are not included.',
    detailsUa: 'Перед замовленням виміряйте або звірте номер клапана: Burger вказує Tial Q 50 mm та Turbosmart Raceport. Не використовуйте комплект на інших діаметрах чи моделях за схожою назвою; під час монтажу огляньте канавки та не перетискайте ущільнення.', detailsEn: 'Before ordering, confirm the valve model: Burger lists Tial Q 50 mm and Turbosmart Raceport. Do not assume compatibility with other diameters or similarly named models; inspect the seal grooves and avoid pinching the O-rings during installation.',
    fitUa: 'У комплекті рівно два ущільнення. BOV, корпуси, пружини, затискачі та монтажні деталі не входять, якщо їх окремо не зазначено у вибраному замовленні.', fitEn: 'The package contains two seals. BOVs, housings, springs, clamps, and installation parts are not included unless separately listed in the order.'
  },
  'bms-elite-m2c-m3-m4-s55-bov-kit': {
    titleUa: 'BMS Elite Charge Pipe і Turbosmart RacePort BOV для BMW S55', titleEn: 'BMS Elite Charge Pipe and Turbosmart RacePort BOV for BMW S55',
    shortUa: 'S55 комплект поєднує алюмінієву charge pipe, Turbosmart RacePort BOV, електронний контролер і MAC solenoid.', shortEn: 'S55 package combines an aluminum charge pipe, Turbosmart RacePort BOV, electronic controller, and MAC solenoid.',
    benefitUa: 'Комплект замінює charge pipe BMW S55 та додає Turbosmart RacePort blow-off valve. Клапан скидає надлишковий тиск при закритті дроселя, формує виразний звук і призначений зменшувати compressor surge при високому наддуві. За Burger, система сумісна зі штатним керуванням, JB4 і flash tuning.', benefitEn: 'This kit replaces the BMW S55 charge pipe and adds a Turbosmart Raceport blow-off valve. The valve releases excess pressure when the throttle closes, creates a pronounced sound, and is intended to reduce compressor surge at higher boost. Burger lists compatibility with factory management, JB4, and flash tuning.',
    detailsUa: 'Burger включає S55 J-pipe із BOV, Turbosmart valve, електронний BOV controller, MAC solenoid, 4-футову трубку, push-lock fittings, silicone coupler, charge pipe clip, O-ring і заглушки 1/8 NPT. Два порти 1/8 NPT можна використати для датчика наддуву або WMI згідно з конфігурацією авто.', detailsEn: 'Burger lists the S55 J-pipe with BOV, Turbosmart valve, electronic BOV controller, MAC solenoid, four-foot tubing, push-lock fittings, silicone coupler, charge-pipe clip, O-ring, and 1/8 NPT plugs. Two 1/8 NPT ports can be used for a boost gauge or WMI setup where applicable.',
    fitUa: 'Для BMW F87 M2 Competition 2018–2021, F80 M3 2015–2020 і F82/F83 M4 2015–2020 з S55. Перевірте двигун S55; це не товар для M2 із N55 або новіших моделей S58.', fitEn: 'For 2018–2021 BMW F87 M2 Competition, 2015–2020 F80 M3, and 2015–2020 F82/F83 M4 with the S55 engine. Verify S55 fitment; this is not for the N55 M2 or newer S58 models.'
  },
  'bms-blow-off-valve-bov-adapter-for-ford-raptor-3-5l-ecoboost': {
    titleUa: 'BMS BOV Adapter для Ford Raptor 3.5 EcoBoost — Gen 2 / Gen 3', titleEn: 'BMS BOV Adapter for Ford Raptor 3.5 EcoBoost — Gen 2 / Gen 3',
    shortUa: 'Адаптер для Raptor 3.5 EcoBoost додає атмосферний звук; для Gen 3 2025+ потрібна невелика доробка роз’єму.', shortEn: 'Raptor 3.5 EcoBoost adapter adds an atmospheric sound; Gen 3 models from 2025 need a minor connector modification.',
    benefitUa: 'BMS адаптер установлюється між штатним bypass solenoid і charge system та відводить невикористане повітря наддуву в атмосферу при скиданні газу. Результат — виразний звук blow-off без окремої прошивки або заяви про додаткову потужність.', benefitEn: 'The BMS adapter fits between the factory bypass solenoid and charge system, venting unused boost air to atmosphere when you lift off the throttle. It adds a blow-off sound without a separate tune or a claim of extra power.',
    detailsUa: 'У переліку Burger — billet-алюмінієвий адаптер і два гвинти M6×1×45 мм з нержавіючої сталі. Джерело попереджає: на Ford Raptor Gen 3 модельного року 2025+ потрібна незначна модифікація роз’єму BOV. Перед встановленням перевірте фактичну конструкцію вузла.', detailsEn: 'Burger lists a billet-aluminum adapter and two stainless M6×1×45 mm screws. The source warns that 2025+ Ford Raptor Gen 3 models require a minor modification to the BOV connector. Check the actual valve connector before installation.',
    fitUa: 'Для Ford Raptor 3.5L EcoBoost: Gen 2 2017–2020 та Gen 3 2021+. Для звичайних F-150 або інших двигунів сумісність цією сторінкою не підтверджена.', fitEn: 'For Ford Raptor 3.5L EcoBoost: Gen 2 2017–2020 and Gen 3 2021+. This page does not confirm fitment for standard F-150 models or other engines.'
  },
  'bms-bov-spacer-for-vw-golf-gti-mk7-mk8': {
    titleUa: 'BMS BOV Spacer для VW Golf / GTI MK7, MK7.5 і MK8', titleEn: 'BMS BOV Spacer for VW Golf / GTI MK7, MK7.5, and MK8',
    shortUa: 'Оберіть покоління Golf/GTI: MK7–MK7.5 2015–2021 або MK8 2022+; spacer додає звук скидання наддуву.', shortEn: 'Choose Golf/GTI generation: MK7–MK7.5 2015–2021 or MK8 2022+; spacer adds a boost-release sound.',
    benefitUa: 'BMS spacer встановлюється між заводським bypass solenoid і системою наддуву VW, щоб випускати надлишкове повітря в атмосферу при скиданні газу. Це додає характерний blow-off звук і не змінює програму керування двигуном.', benefitEn: 'The BMS spacer fits between the factory bypass solenoid and VW charge system, venting excess air to atmosphere when the throttle closes. It adds the characteristic blow-off sound without changing engine software.',
    detailsUa: 'Оберіть правильне покоління у списку: Golf/GTI MK7 або MK7.5 2015–2021 чи MK8 2022+. За описом Burger, CNC billet-алюмінієвий spacer комплектується малим і великим O-ring та подовженими болтами. Після монтажу перевірте герметичність і роботу штатного клапана.', detailsEn: 'Select the correct generation: Golf/GTI MK7 or MK7.5 2015–2021, or MK8 2022+. Burger describes a CNC billet-aluminum spacer supplied with small and large O-rings and extended bolts. Check the seal and factory valve operation after installation.',
    fitUa: 'Для VW Golf / GTI відповідного покоління, переліченого Burger. Варіанти MK7 і MK8 мають різні роки та посадку; перевірте покоління за VIN або кузовом.', fitEn: 'For the matching VW Golf/GTI generation listed by Burger. MK7 and MK8 have different year ranges and mounting details; verify generation by VIN or chassis.'
  },
  'bms-c43-bov-spacers': {
    titleUa: 'BMS BOV Spacer для Mercedes-Benz C43 / E43 / GLS450 та інших моделей', titleEn: 'BMS BOV Spacer for Mercedes-Benz C43 / E43 / GLS450 and Other Listed Models',
    shortUa: 'BOV spacer для переліку Mercedes-Benz C/E/G/S-Class додає атмосферний звук перепуску; сумісність звіряйте за моделлю.', shortEn: 'Mercedes C/E/G/S-Class BOV spacer adds an atmospheric bypass sound; verify exact model fitment.',
    benefitUa: 'BMS spacer монтується на штатний перепускний клапан і змінює звук під час скидання надлишкового повітря наддуву. Це спосіб отримати виразніший blow-off звук із заводським вузлом, а не модуль для збільшення потужності.', benefitEn: 'The BMS spacer fits the factory bypass valve and changes the sound as excess charge air is released. It offers a more pronounced blow-off sound using the factory assembly, rather than acting as a power module.',
    detailsUa: 'Однокомпонентний адаптер виготовлений із billet-алюмінію на CNC. Burger вказує просте встановлення та монтажне кріплення; після монтажу перевірте ущільнення. Опис сумісності на сторінці узагальнений і містить кілька класів Mercedes, тому перед продажем варто звірити модель і двигун із джерелом.', detailsEn: 'The one-piece adapter is CNC-machined from billet aluminum. Burger describes straightforward installation and mounting hardware; check the seal after fitting. The supplier fitment text groups several Mercedes classes, so verify the exact model and engine against the source before sale.',
    fitUa: 'Сторінка Burger перелічує C400/C450/C43 AMG, E400/E450/E43 AMG, GLS450, GLC43 та SLC43. Для автомобілів поза цим списком і для схожих AMG-версій не вважайте сумісність підтвердженою.', fitEn: 'Burger lists C400/C450/C43 AMG, E400/E450/E43 AMG, GLS450, GLC43, and SLC43. Fitment for vehicles outside that list or similar AMG variants is not confirmed.'
  },
  'bov-adapter-for-kia-stinger-gt-3-3': {
    titleUa: 'Tial BOV Adapter для Kia Stinger GT / Genesis G70 3.3T', titleEn: 'Tial BOV Adapter for Kia Stinger GT / Genesis G70 3.3T',
    shortUa: 'Оберіть адаптер окремо або версію з оригінальним Tial BOV; для клапана рекомендована пружина 6 psi.', shortEn: 'Choose the adapter alone or with an authentic Tial BOV; a 6 psi spring is recommended for the valve.',
    benefitUa: 'Адаптер дає змогу замінити два заводські diverter valves одним фланцевим Tial blow-off valve. При скиданні газу надлишкове повітря виходить в атмосферу, змінюючи звук турбомотора; Burger також зазначає потенційну здатність краще утримувати наддув між перемиканнями.', benefitEn: 'The adapter lets you replace the two factory diverter valves with one flange-mounted Tial blow-off valve. Excess air vents to atmosphere when you lift off the throttle, changing the turbo sound; Burger also notes potential for improved boost retention between shifts.',
    detailsUa: 'У меню оберіть «лише BOV adapter» або «authentic Tial BOV та adapter». Перша опція не містить клапана. Burger радить чорну пружину Tial 6 psi за результатами власних тестів; надто жорстка пружина може завадити правильному відкриттю BOV. Адаптер використовує штатні O-rings і містить block-off caps для впускних шлангів.', detailsEn: 'Choose “BOV adapter only” or “authentic Tial BOV and adapter.” The adapter-only option does not include a valve. Burger recommends the black 6 psi Tial spring based on its testing; an overly stiff spring may prevent correct opening. The adapter reuses factory O-rings and includes intake-hose block-off caps.',
    fitUa: 'Для Kia Stinger GT/GT1/GT2 3.3L V6 2018–2023 та Genesis G70 3.3L V6 2018+ за списком Burger. Перевірте комплектацію, двигун і тип клапанів.', fitEn: 'For Burger-listed 2018–2023 Kia Stinger GT/GT1/GT2 3.3L V6 and 2018+ Genesis G70 3.3L V6. Verify trim, engine, and valve layout.'
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Призначення та ефект</h3>\n<p>${item.benefitUa}</p>\n<h3>Конструкція та вибір</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and effect</h3>\n<p>${item.benefitEn}</p>\n<h3>Construction and selection</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment</h3>\n<p>${item.fitEn}</p>`,
}]));
