// Source-checked transmission, differential, exhaust, and fueling copy; local draft only.
const rows = {
  'bms-transmission-oil-cooler-for-2022-toyota-tundra-3-4l-twin-turbo': {
    titleUa: 'BMS Standalone Transmission Cooler для Toyota Tundra 3.4T 2022+', titleEn: 'BMS Standalone Transmission Cooler for 2022+ Toyota Tundra 3.4T',
    shortUa: 'Окремий повітряний ATF cooler подвоює охолодження, додає близько кварти оливи; не для Hybrid.', shortEn: 'Standalone air-to-ATF cooler doubles cooling and adds about a quart; not for Hybrid models.',
    benefitUa: 'Окремий BMS cooler від’єднує охолодження трансмісійної рідини від заводського теплообмінника двигуна, де ATF може нагріватися разом з охолоджувальною рідиною. Повітряний радіатор збільшує тепловідвід під час буксирування, підйомів, бездоріжжя чи роботи в спеку.', benefitEn: 'The standalone BMS cooler separates transmission-fluid cooling from the factory engine-coolant exchanger, where ATF can track engine temperature. An air-cooled radiator adds capacity for towing, grades, off-road use, or hot climates.',
    detailsUa: 'Комплект має cooler, дві 90″ армовані лінії -10AN, billet adapters, алюмінієвий кронштейн, заглушки й кріплення. За джерелом, передню частину авто знімати не потрібно; система додає близько 1 quart ATF. Не підходить до Tundra Hybrid.', detailsEn: 'The package includes the cooler, two 90-inch -10AN braided lines, billet adapters, aluminum bracket, plugs, and mounting hardware. Burger says the front of the truck need not be removed; the system adds about one quart of ATF capacity. Not for Tundra Hybrid.',
    fitUa: 'Для Toyota Tundra 2022+ 3.4L V6 Twin Turbo з автоматичною трансмісією. Гібридні моделі прямо виключені; перевірте двигун і коробку до замовлення.', fitEn: 'For 2022+ Toyota Tundra 3.4L twin-turbo V6 with automatic transmission. Hybrid models are explicitly excluded; verify engine and gearbox.'
  },
  'bms-v2-transmission-oil-cooler-for-2018-present-kia-stinger-genesis-g70-3-3t': {
    titleUa: 'BMS V2 Transmission Cooler для Kia Stinger / Genesis G70 2.0T / 3.3T', titleEn: 'BMS V2 Transmission Cooler for Kia Stinger / Genesis G70 2.0T / 3.3T',
    shortUa: 'V2 front-mount cooler має на 100% більшу площу та підключається до factory coolant lines.', shortEn: 'V2 front-mount cooler has 100% more area and connects to factory coolant lines.',
    benefitUa: 'BMS V2 додає окремий повітряний радіатор для охолодження ATF, щоб зменшити теплове навантаження під час підвищеної потужності та спеки. За Burger, core має удвічі більшу площу за штатний; додатковий об’єм допомагає стабілізувати температуру при повторних заїздах.', benefitEn: 'The BMS V2 adds an air-to-fluid radiator to reduce ATF heat under higher power or hot-weather use. Burger lists twice the surface area of stock; added fluid capacity supports temperature control during repeated runs.',
    detailsUa: 'Версія V2 підключається безпосередньо до заводських coolant lines і встановлюється за бампером. Комплект містить transmission cooler; для окремих моделей потрібне незначне підрізання внутрішнього пластику. G80 3.3T потребує модифікації кронштейнів — підтвердьте монтаж до замовлення.', detailsEn: 'Version 2 connects directly to factory coolant lines and mounts behind the bumper. The package includes the transmission cooler; some models need minor inner-bumper plastic trimming. G80 3.3T requires bracket modification, so confirm installation before ordering.',
    fitUa: 'Kia Stinger 2018–2023 2.0T/3.3T; Genesis G70 2018+ 2.0T/3.3T; G80 3.3T із модифікацією за погодженням із Burger. Автоматична трансмісія; звірте рік і коробку.', fitEn: 'For 2018–2023 Kia Stinger 2.0T/3.3T and 2018+ Genesis G70 2.0T/3.3T; G80 3.3T requires supplier-approved modification. Automatic transmission; verify year and gearbox.'
  },
  'bmw-dct-transmission-oil-pan-gasket-and-filter': {
    titleUa: 'BMW DCT Transmission Pan Gasket і Suction Filter — комплект сервісу', titleEn: 'BMW DCT Transmission Pan Gasket and Suction Filter — Service Set',
    shortUa: 'Змінна гумова прокладка та всмоктувальний фільтр для сервісу BMW DCT трансмісії.', shortEn: 'Replacement rubber pan gasket and suction filter for BMW DCT transmission service.',
    benefitUa: 'Цей сервісний комплект замінює ущільнення DCT піддона та suction filter під час обслуговування трансмісії. Свіже ущільнення допомагає уникнути витоку після зняття піддона, а новий фільтр підтримує належний потік рідини до системи зчеплення.', benefitEn: 'This service set replaces the DCT pan seal and suction filter during transmission maintenance. A new gasket helps prevent leaks after pan removal, while a fresh filter supports fluid flow to the clutch system.',
    detailsUa: 'У комплекті rubber pan gasket і suction filter. Сам DCT pan, ATF та монтажні кріплення окремо не зазначені як комплектні. Під час сервісу дотримуйтеся процедури заповнення й температури перевірки рівня BMW DCT.', detailsEn: 'The package contains a rubber pan gasket and suction filter. The DCT pan, fluid, and installation hardware are not listed as included. Follow the BMW DCT fill procedure and temperature-based level check.',
    fitUa: 'Для DCT E82/E88 135i; E90–E93 335i/335is/M3; F80/F82/F83 M2/M3/M4/M4 GTS; F10 M5; F06/F12/F13 M6; E89 Z4 у застосуваннях Burger. Не для автоматичних ZF або механічних коробок.', fitEn: 'For Burger-listed DCT E82/E88 135i, E90–E93 335i/335is/M3, F80/F82/F83 M2/M3/M4/M4 GTS, F10 M5, F06/F12/F13 M6, and E89 Z4. Not for ZF automatic or manual gearboxes.'
  },
  'bms-f-chassis-gen-1-b58-bmw-transmission-oil-cooler-m140-240-340-440': {
    titleUa: 'BMS Gen 1 B58 F-Chassis Transmission Cooler — 165°F thermostat included', titleEn: 'BMS Gen 1 B58 F-Chassis Transmission Cooler — 165°F Thermostat Included',
    shortUa: 'Передній повітряний cooler із 165°F thermostat для автоматичних F-Chassis B58; не для МКПП.', shortEn: 'Front-mounted air cooler with 165°F thermostat for automatic F-Chassis B58; not manual.',
    benefitUa: 'BMS Gen 1 B58 cooler замінює заводський coolant-to-ATF теплообмінник повітряним радіатором. Додаткове охолодження допомагає знижувати температуру ATF і ризик перегріву при збільшеному наддуві або тривалому навантаженні.', benefitEn: 'The BMS Gen 1 B58 cooler replaces the factory coolant-to-ATF exchanger with an air-cooled radiator. Added capacity helps reduce ATF temperature and overheating risk under increased boost or sustained load.',
    detailsUa: 'У комплекті cooler, кронштейни, лінії, coolant plugs і Improved Racing 165°F thermostat із fittings. Термостат підтримує мінімальну робочу температуру й допомагає уникнути переохолодження. Підключення розміщується за водійською kidney grille.', detailsEn: 'The package includes the cooler, brackets, lines, coolant plugs, and Improved Racing 165°F thermostat with fittings. The thermostat maintains a minimum operating temperature and helps prevent overcooling. The assembly mounts behind the driver-side kidney grille.',
    fitUa: 'BMW F20/F21 M140i 2015+, F22/F23 M240i 2016–2021, F30/F31/F34 340i 2016–2019, F32/F33/F36 440i 2016–2020 з B58 Gen 1 та автоматичною ZF8HP50/70. Не для МКПП.', fitEn: 'For Burger-listed BMW F20/F21 M140i 2015+, F22/F23 M240i 2016–2021, F30/F31/F34 340i 2016–2019, and F32/F33/F36 440i 2016–2020 with Gen 1 B58 and ZF8HP50/70 automatic. Not for manual transmissions.'
  },
  'n54-n55-bmw-135-335-transmission-cooler': {
    titleUa: 'BMS Transmission Cooler для BMW E-Chassis 135i / 335i — термостат опційно', titleEn: 'BMS Transmission Cooler for BMW E-Chassis 135i / 335i — Optional Thermostat',
    shortUa: 'Кулер АКПП монтується у водійському крилі; оберіть кузов і 165°F thermostat.', shortEn: 'Automatic-transmission cooler mounts in the driver-side fender; select car and 165°F thermostat.',
    benefitUa: 'BMS комплект замінює coolant-to-trans fluid heat exchanger повітряним радіатором у крилі, щоб краще відводити ATF тепло. Він корисний для автоматичних E-Chassis, які буксирують чи мають більшу турбіну та нагрівають трансмісійну рідину під навантаженням.', benefitEn: 'The BMS kit replaces the coolant-to-transmission exchanger with a fender-mounted air cooler to remove more ATF heat. It suits automatic E-Chassis cars that see higher loads or larger turbos and generate excess transmission temperature.',
    detailsUa: 'Оберіть Vehicle: 135 або 335, потім Add 165°F Thermostat: Yes/No. У комплекті cooler, лінії, coolant caps і кріплення; thermostat опційний, якщо вибрано Yes. Термостат запобігає зайвому охолодженню та допомагає трансмісії вийти на робочу температуру.', detailsEn: 'Select Vehicle (135 or 335), then Add 165°F Thermostat (Yes/No). The cooler, lines, coolant caps, and mounting hardware are listed; the thermostat is included only with Yes. It helps prevent overcooling while the transmission reaches operating temperature.',
    fitUa: 'Для автоматичних BMW E-Chassis 135i та 335i/335d у перелічених роках і моторах N54/N55/M57. Не сумісний з механічними трансмісіями; уточніть chassis до замовлення.', fitEn: 'For Burger-listed automatic BMW E-Chassis 135i and 335i/335d with N54/N55/M57 in specified years. Not compatible with manual transmissions; verify chassis before ordering.'
  },
  'billet-dct-transmission-pan-for-bmw': {
    titleUa: 'BMS Billet DCT Oil Pan для BMW — standard або high-capacity, 3 конфігурації', titleEn: 'BMS Billet DCT Oil Pan for BMW — Standard or High Capacity, 3 Options',
    shortUa: '6061 billet pan із cooling fins; оберіть штатний об’єм або low/high-baffle версію зі збільшеним об’ємом.', shortEn: '6061 billet pan with cooling fins; choose standard volume or low/high-baffle high-capacity version.',
    benefitUa: 'Алюмінієвий DCT pan BMS замінює слабкий пластиковий штатний піддон і розсіює тепло через інтегровані cooling fins. High-capacity версії збільшують об’єм ATF, що допомагає контролювати температуру на потужних або гоночних автомобілях.', benefitEn: 'The BMS aluminum DCT pan replaces the weak factory plastic pan and dissipates heat through integrated cooling fins. High-capacity versions add ATF volume to support temperature management on higher-power or track cars.',
    detailsUa: 'Оберіть Standard Capacity; Low Baffle High Capacity із приблизно +1.5 qt; або High Baffle High Capacity із приблизно +1.4 qt. Усі версії мають нову rubber gasket і suction filter. High-capacity pan може вимагати зняти або підрізати піддон трансмісії; перевірте кліренс.', detailsEn: 'Choose Standard Capacity; Low Baffle High Capacity with about 1.5 extra quarts; or High Baffle High Capacity with about 1.4 extra quarts. All versions include a new rubber gasket and suction filter. A high-capacity pan may require undertray removal or modification; check clearance.',
    fitUa: 'Для BMW DCT коробок із застосувань Burger. Звірте код трансмісії, висоту baffle, дорожній кліренс і сервісну процедуру до встановлення.', fitEn: 'For Burger-listed BMW DCT transmissions. Verify transmission code, baffle clearance, ground clearance, and service procedure before installation.'
  },
  'bms-differential-support-bracket-brace-for-g-chassis-bmw-supra': {
    titleUa: 'BMS Differential Support Brace для BMW G-Chassis / Toyota Supra B58', titleEn: 'BMS Differential Support Brace for BMW G-Chassis / Toyota Supra B58',
    shortUa: 'Сталевий brace фіксує задній диференціал, зменшує wheel hop; монтаж потребує двох отворів.', shortEn: 'Steel brace secures the rear differential and reduces wheel hop; two mounting holes must be drilled.',
    benefitUa: 'BMS Differential Brace з’єднує задній диференціал із підрамником і зменшує його переміщення під час різкого старту та перемикання. Це допомагає зменшити wheel hop, стабілізувати задню частину й обмежити навантаження на підшипники диференціала.', benefitEn: 'The BMS Differential Brace ties the rear differential to the subframe and limits movement under hard launches and shifts. It helps reduce wheel hop, stabilize the rear chassis, and limit differential-bearing shock.',
    detailsUa: 'Однокомпонентний важкогабаритний сталевий brace спроєктований за 3D laser scan і містить збільшене кріплення M12. Важливе попередження Burger: для монтажу верхнього bracket потрібно просвердлити два отвори. Перед встановленням оцініть цю модифікацію та перевірте точку кріплення.', detailsEn: 'The one-piece heavy-gauge steel brace is shaped from 3D laser scans and uses oversized M12 hardware. Burger warns that two holes must be drilled to mount the upper bracket. Review this permanent installation step and confirm mounting points before purchase.',
    fitUa: 'Для BMW G42 M240i, G20/G21 M340i, G22/G23/G26 M440i, G29 Z4 M40i та Toyota GR Supra Mk5 B58 у роках Burger. Не для інших двигунів без підтвердження.', fitEn: 'For Burger-listed BMW G42 M240i, G20/G21 M340i, G22/G23/G26 M440i, G29 Z4 M40i, and Toyota GR Supra Mk5 B58 years. Other engines require confirmation.'
  },
  'dogbone-subframe-mount-stabilizer-insert-for-vw-audi-seat-cupra-skoda': {
    titleUa: 'BMS Dogbone Subframe Insert для VW / Audi / SEAT / CUPRA / Škoda MQB', titleEn: 'BMS Dogbone Subframe Insert for VW / Audi / SEAT / CUPRA / Škoda MQB',
    shortUa: '6061 billet insert заповнює порожнину нижньої опори й зменшує рух трансмісії під час перемикання.', shortEn: '6061 billet insert fills the lower mount void and reduces drivetrain movement during shifts.',
    benefitUa: 'Dogbone insert заповнює порожнину штатної нижньої опори двигуна та обмежує рух силового агрегата під навантаженням. Це може зробити перемикання чіткішими й зменшити wheel hop; алюмінієва вставка може дещо збільшити шум і вібрацію в салоні.', benefitEn: 'The dogbone insert fills the factory lower engine-mount void and limits drivetrain movement under load. It can sharpen shifts and reduce wheel hop; the aluminum insert may add some cabin noise and vibration.',
    detailsUa: 'Вставка виконана з 6061 aluminum alloy. Джерело просить звіряти OEM mount reference 5Q0198037F. Монтаж розташований у нижній опорі: підтримайте двигун, зніміть болт і встановіть вставку за інструкцією; не перетягуйте різьбу.', detailsEn: 'The insert is made from 6061 aluminum alloy. Burger asks buyers to match OE mount reference 5Q0198037F. Installation is at the lower mount: support the engine, remove the bolt, and fit the insert per instructions without over-tightening.',
    fitUa: 'Для відповідних VW/Audi/SEAT/CUPRA/Škoda MQB та MQB Evo з 1.8/2.0 TSI, 2.5 TFSI або 2.0 TDI у переліку Burger. Підтвердіть OE part number перед замовленням.', fitEn: 'For Burger-listed VW/Audi/SEAT/CUPRA/Škoda MQB and MQB Evo with 1.8/2.0 TSI, 2.5 TFSI, or 2.0 TDI. Confirm OE part number before ordering.'
  },
  'bms-differential-brace-for-infiniti-q50-q60': {
    titleUa: 'BMS Differential Stabilizer Brace для Infiniti Q50 / Q60 VR30', titleEn: 'BMS Differential Stabilizer Brace for Infiniti Q50 / Q60 VR30',
    shortUa: 'Однокомпонентний brace зменшує переміщення диференціала та wheel hop на Q50/Q60 RWD або AWD.', shortEn: 'One-piece brace reduces differential movement and wheel hop on Q50/Q60 RWD or AWD.',
    benefitUa: 'BMS stabilizer brace обмежує люфт задніх bushings диференціала, що може покращити зчеплення при старті та зменшити wheel hop. Сталевий однокомпонентний кронштейн не має зварних стиків і не повинен збільшувати шум чи вібрацію за описом виробника.', benefitEn: 'The BMS stabilizer brace limits play in the rear differential bushings, which can improve traction off the line and reduce wheel hop. The one-piece steel bracket avoids welded joints and is described by the supplier as not increasing noise or vibration.',
    detailsUa: 'Bolt-on конструкція без свердління й з усім потрібним кріпленням. Підходить для RWD та AWD. Після встановлення перевірте затягування кріплень і відсутність контакту з вихлопом або сусідніми деталями.', detailsEn: 'Bolt-on installation with no drilling and required hardware included. It supports RWD and AWD. After fitting, check fastener torque and clearance to exhaust or adjacent parts.',
    fitUa: 'Infiniti Q50 2016–2024 VR30 3.0T, включно з Luxe/Sport/Sensory/Red Sport 400, та Q60 2017–2022 VR30 3.0T у версіях Burger. Звірте кузов і двигун.', fitEn: 'For Burger-listed 2016–2024 Infiniti Q50 VR30 3.0T including Luxe/Sport/Sensory/Red Sport 400 and 2017–2022 Q60 VR30 3.0T. Verify chassis and engine.'
  },
  'bms-differential-support-bracket-brace-for-f-chassis-bmw': {
    titleUa: 'BMS Differential Brace для BMW F-Series — вибір RWD / AWD і покоління', titleEn: 'BMS Differential Brace for BMW F-Series — Select RWD / AWD Generation',
    shortUa: 'Оберіть Large RWD, Small pre-LCI RWD або Small AWD; версії відрізняються розміром та розташуванням дифа.', shortEn: 'Choose Large RWD, Small pre-LCI RWD, or Small AWD; versions differ by differential layout.',
    benefitUa: 'Сталевий differential brace з’єднує задній диференціал із підрамником і зменшує його рух під навантаженням. Це може зменшити wheel hop, навантаження на підшипники та нестабільність задньої частини під час старту.', benefitEn: 'The steel differential brace ties the rear differential to the subframe and limits movement under load. It can reduce wheel hop, bearing stress, and rear-end instability during launches.',
    detailsUa: 'Оберіть одну версію: Large для RWD 2016+ F-Series; Small для pre-LCI RWD 2012–2015; Small AWD для повного приводу 2012+. Установлення містить кріплення, але виробник попереджає, що може знадобитися свердління. Неамериканським авто Burger просить надіслати фото корпуса диференціала для перевірки.', detailsEn: 'Select one version: Large for 2016+ F-Series RWD; Small for 2012–2015 pre-LCI RWD; Small AWD for 2012+ all-wheel drive. Hardware is listed, but drilling may be required. Burger asks non-US vehicles to provide differential-carrier photos for verification.',
    fitUa: 'BMW F-Series 1/2/3/4 Series у відповідних роках і приводі з меню. Правильний розмір диференціала критичний; перевірте варіант трансмісії та кузов до замовлення.', fitEn: 'For listed BMW F-Series 1/2/3/4 Series in the matching year and drivetrain. Differential size is critical; verify transmission and chassis before ordering.'
  },
  'differential-brace-for-2018-kia-stinger': {
    titleUa: 'BMS Differential Brace для Kia Stinger / Genesis G70 3.3T', titleEn: 'BMS Differential Brace for Kia Stinger / Genesis G70 3.3T',
    shortUa: 'Двокомпонентний сталевий brace зменшує люфт диференціала і wheel hop; без свердління.', shortEn: 'Two-piece steel brace reduces differential play and wheel hop without drilling.',
    benefitUa: 'BMS brace фіксує задній диференціал Stinger/G70 та зменшує рух гумових bushings під час прискорення. Це допомагає зменшити wheel hop і навантаження на підшипники, зберігаючи комфорт без помітного додаткового шуму за описом Burger.', benefitEn: 'The BMS brace stabilizes the rear differential on Stinger/G70 and limits movement in the rubber bushings under acceleration. It helps reduce wheel hop and bearing load, with no notable added noise per Burger.',
    detailsUa: 'У комплекті нижній diff brace, верхній L-brace, кронштейн і сталеве кріплення. Двокомпонентна конструкція монтується без свердління. Після встановлення перевірте зазори навколо вихлопу й диференціала.', detailsEn: 'The package includes a lower diff brace, upper L-brace, bracket, and steel hardware. The two-piece design installs without drilling. Check clearance around the exhaust and differential after fitting.',
    fitUa: 'Kia Stinger 3.3L RWD/AWD 2018–2023 та Genesis G70 3.3L RWD/AWD 2018+ за переліком Burger. Не для 2.0T без підтвердження.', fitEn: 'For Burger-listed 2018–2023 Kia Stinger 3.3L RWD/AWD and 2018+ Genesis G70 3.3L RWD/AWD. Not for 2.0T without confirmation.'
  },
  'bms-differential-support-bracket-brace-for-e82-135i-and-e9x-335i': {
    titleUa: 'BMS Differential Brace для BMW 135i / 335i E82 / E9x — Small чи Large', titleEn: 'BMS Differential Brace for BMW 135i / 335i E82 / E9x — Small or Large',
    shortUa: 'Оберіть Small або Large differential за моделлю та типом коробки; звірте корпус перед замовленням.', shortEn: 'Choose Small or Large differential by model and gearbox; inspect the carrier before ordering.',
    benefitUa: 'BMS brace кріпить задній диференціал до підрамника й зменшує його переміщення, wheel hop та навантаження на підшипники. Однокомпонентна важкогабаритна сталь прибирає слабкі зварні з’єднання й має стриманий вигляд без зовнішнього логотипа.', benefitEn: 'The BMS brace ties the rear differential to the subframe to limit movement, wheel hop, and bearing stress. One-piece heavy-gauge steel avoids weak welded joints and keeps an understated appearance.',
    detailsUa: 'Оберіть Small Differential або Large Differential. У 135i: механічна та DCT зазвичай Large, автоматична — Small. У 335i/335ix: механічна — Large; автоматична до серпня 2007 — Large, з вересня 2007 — Small; 335d і 335is — Large. Через винятки обов’язково звірте фактичний carrier.', detailsEn: 'Choose Small or Large Differential. For 135i, manual and DCT are generally Large while automatic is Small. For 335i/335ix, manual is Large; automatic through Aug 2007 is Large and from Sep 2007 is Small; 335d and 335is are Large. Verify the actual carrier because exceptions exist.',
    fitUa: 'BMW E82 135i та E9x 335i/335ix/335d/335is у перелічених коробках. Різні комплектації одного року можуть мати різний диференціал — перевірте його фізично до покупки.', fitEn: 'For listed BMW E82 135i and E9x 335i/335ix/335d/335is gearboxes. Different trims from the same year may use different differentials; inspect the carrier before purchase.'
  },
  'bms-angle-cut-billet-exhaust-tips-for-f8x-bmw-m3-m4-m2c-set-of-4': {
    titleUa: 'BMS 3.75″ Angle-Cut Billet Exhaust Tips для BMW F8x M2C / M3 / M4 — 4 шт.', titleEn: 'BMS 3.75-inch Angle-Cut Billet Exhaust Tips for BMW F8x M2C / M3 / M4 — Set of 4',
    shortUa: 'Чотири збільшені billet tips для штатного F8x exhaust; не для M Performance системи.', shortEn: 'Four enlarged billet tips for the factory F8x exhaust; not for M Performance systems.',
    benefitUa: 'BMS angle-cut tips змінюють зовнішній вигляд штатних вихлопних патрубків BMW M без заміни глушника. Діаметр 3.75″ приблизно на 27% більший за штатний, а регульована довжина дає змогу вирівняти виступ наконечника.', benefitEn: 'BMS angle-cut tips change the look of factory BMW M outlets without replacing the muffler. The 3.75-inch diameter is about 27% larger than stock, and adjustable depth helps align tip projection.',
    detailsUa: 'У комплекті 4 billet-алюмінієві tips із set screws; кріпляться поверх труби діаметром 2.75″. Ceramic Black покриття, за Burger, витримує високі температури. Не використовуйте з M Performance exhaust, і не встановлюйте на звичайний M2 з N55.', detailsEn: 'The set contains four billet-aluminum tips with set screws; they fit over a 2.75-inch pipe. Burger rates the Ceramic Black finish for high temperatures. Not for M Performance exhaust or the standard N55 M2.',
    fitUa: 'BMW F87 M2 Competition із S55 2019+, F80 M3 2015–2020, F82/F83 M4 2015–2020 у застосуваннях Burger. Звірте вихідну трубу й відсутність M Performance exhaust.', fitEn: 'For Burger-listed 2019+ BMW F87 M2 Competition with S55, 2015–2020 F80 M3, and 2015–2020 F82/F83 M4. Verify outlet pipe and absence of M Performance exhaust.'
  },
  'burger-motorsports-straight-cut-billet-exhaust-tips-f8x-bmw-m3-m4-m2c': {
    titleUa: 'BMS 3.75″ Straight-Cut Billet Exhaust Tips для BMW F8x M2C / M3 / M4 — 4 шт.', titleEn: 'BMS 3.75-inch Straight-Cut Billet Exhaust Tips for BMW F8x M2C / M3 / M4 — Set of 4',
    shortUa: 'Чотири billet наконечники 3.75″ для штатного F8x M exhaust; оберіть Gloss Black чи Matte Black Ceramic.', shortEn: 'Four 3.75-inch billet tips for the factory F8x M exhaust; choose Gloss Black or Matte Black Ceramic.',
    benefitUa: 'Збільшені BMS straight-cut tips оновлюють вигляд штатного вихлопу BMW M без заміни системи. Наконечники мають діаметр 3.75″, приблизно на 27% більший за штатні, і регулюються за довжиною для акуратного виступу.', benefitEn: 'The larger BMS straight-cut tips update the factory BMW M exhaust appearance without replacing the exhaust system. The 3.75-inch diameter is about 27% larger than stock, and tip depth is adjustable.',
    detailsUa: 'У наборі чотири billet-алюмінієві наконечники з set screws. Оберіть Gloss Black або Matte Black Ceramic; окремі фініші можуть бути недоступні. Не для M Performance exhaust і звичайного N55 M2; перед монтажем перевірте розмір outlet.', detailsEn: 'The set contains four billet-aluminum tips with set screws. Choose Gloss Black or Matte Black Ceramic; some finishes may be unavailable. Not for M Performance exhaust or standard N55 M2; verify outlet size before fitting.',
    fitUa: 'BMW F87 M2 Competition із S55 2019+, F80 M3 2015–2020, F82/F83 M4 2015–2020 за Burger. Перевірте кузов і вихлопну систему до покупки.', fitEn: 'For Burger-listed 2019+ BMW F87 M2 Competition with S55, 2015–2020 F80 M3, and 2015–2020 F82/F83 M4. Check chassis and exhaust system before purchase.'
  },
  'vag-exhaust-flapper-bypass-plugs': {
    titleUa: 'VAG Exhaust Valve Flapper Bypass Plug — 3-pin або 4-pin, ціна за 1 шт.', titleEn: 'VAG Exhaust Valve Flapper Bypass Plug — 3-pin or 4-pin, Each',
    shortUa: 'Plug-and-play адаптер залишає вихлопні клапани відкритими; оберіть 3- або 4-position connector.', shortEn: 'Plug-and-play adapter keeps exhaust flaps open; choose 3- or 4-position connector.',
    benefitUa: 'Bypass plug від’єднує керування заводським exhaust flapper так, щоб клапани залишались у відкритому спортивному режимі в інших drive modes. За описом Burger, адаптер не має викликати fault code; перевірте сумісність роз’єму до встановлення.', benefitEn: 'The bypass plug disconnects factory exhaust-flap control so the valves remain in the open sport position in other drive modes. Burger says the adapter should not trigger a fault code; verify connector fit before installation.',
    detailsUa: 'Опція 3 Position або 4 Position означає кількість контактів; товар оцінений за одну штуку. Для RS3/FL/RS4/RS5/TT/TTRS зазвичай потрібно два 4-position plugs. Для S3/S6/S7/SQ5, Golf R і Mercedes W205 C-Class (C43/C63 тощо) зазвичай потрібно два 3-position plugs.', detailsEn: 'Choose 3-position or 4-position by connector pin count; the item is priced each. RS3/FL/RS4/RS5/TT/TTRS typically require two 4-position plugs. S3/S6/S7/SQ5, Golf R, and Mercedes W205 C-Class (C43/C63 etc.) typically require two 3-position plugs.',
    fitUa: 'Для VAG та Mercedes з електричними exhaust flaps і відповідним конектором. Перевірте число контактів і потребу в 1 чи 2 шт.; клапани не входять.', fitEn: 'For VAG and Mercedes applications with electronic exhaust flaps and matching connector. Verify pin count and whether one or two are needed; valves are not included.'
  },
  'bmw-f90-m5-exhaust-tips': {
    titleUa: 'BMS 3.75″ Angle-Cut Billet Exhaust Tips для BMW F90 M5 — 4 шт.', titleEn: 'BMS 3.75-inch Angle-Cut Billet Exhaust Tips for BMW F90 M5 — Set of 4',
    shortUa: 'Комплект із чотирьох чорних billet tips для штатного F90 M5 exhaust; не для M Performance системи.', shortEn: 'Four black billet tips for the factory F90 M5 exhaust; not for M Performance systems.',
    benefitUa: 'BMS tips надають штатним вихлопним патрубкам F90 M5 ширшого та агресивнішого вигляду без заміни глушника. Діаметр 3.75″ приблизно на 27% більший за заводський, а регульована глибина дає змогу вирівняти наконечники.', benefitEn: 'BMS tips give the factory F90 M5 exhaust outlets a wider, more aggressive appearance without replacing the muffler. Their 3.75-inch diameter is about 27% larger than stock, with adjustable depth for alignment.',
    detailsUa: 'У наборі чотири billet-алюмінієві tips та вісім нержавіючих M8×1.25×12 mm set screws. High-gloss black finish; встановлюються на штатні вихідні труби. Не сумісні з M Performance exhaust.', detailsEn: 'The set includes four billet-aluminum tips and eight stainless M8×1.25×12 mm set screws. High-gloss black finish; mounts to factory outlets. Not compatible with M Performance exhaust.',
    fitUa: 'Для BMW F90 M5 2018+ за сторінкою Burger. Не для інших BMW або aftermarket/M Performance вихлопу без підтвердження.', fitEn: 'For 2018+ BMW F90 M5 as listed by Burger. Not for other BMW models or aftermarket/M Performance exhaust without confirmation.'
  },
  'burger-motorsports-billet-bmw-m5-m6-exhaust-tips': {
    titleUa: 'BMS 3.75″ Straight-Cut Billet Exhaust Tips для BMW F10 M5 / F12 F13 F06 M6 — 4 шт.', titleEn: 'BMS 3.75-inch Straight-Cut Billet Exhaust Tips for BMW F10 M5 / F12 F13 F06 M6 — Set of 4',
    shortUa: 'Чотири polished billet наконечники 3.75″ для штатного BMW M exhaust; не для M Performance систем.', shortEn: 'Four polished 3.75-inch billet tips for factory BMW M exhaust; not for M Performance systems.',
    benefitUa: 'Straight-cut BMS tips змінюють вигляд заводського вихлопу BMW M5/M6, не змінюючи звук чи сам глушник. Billet наконечники приблизно на 27% більші за штатні та регулюються за глибиною встановлення.', benefitEn: 'Straight-cut BMS tips update the factory BMW M5/M6 exhaust appearance without changing the muffler or exhaust system. Billet outlets are about 27% larger than stock and adjustable in installation depth.',
    detailsUa: 'Комплект із чотирьох наконечників, покриття Polished Silver, кріплення set-screw за переліком виробника. Не використовувати з BMW M Performance exhaust; перевірте діаметр штатної труби та зазор бампера.', detailsEn: 'Set of four tips with polished silver finish and set-screw attachment as listed by the supplier. Do not use with BMW M Performance exhaust; check factory pipe diameter and bumper clearance.',
    fitUa: 'BMW F10 M5/M5 Competition 2011–2017 та F12/F13/F06 M6/M6 Competition 2011–2018 за Burger.', fitEn: 'For Burger-listed 2011–2017 BMW F10 M5/M5 Competition and 2011–2018 F12/F13/F06 M6/M6 Competition.'
  },
  'bms-f-chassis-bmw-n55-b58-exhaust-tips': {
    titleUa: 'BMS 3.5″ Billet Exhaust Tips для BMW F-Chassis N55 / B58 — пара', titleEn: 'BMS 3.5-inch Billet Exhaust Tips for BMW F-Chassis N55 / B58 — Pair',
    shortUa: 'Пара angle-cut tips 3.5″ bolt-on на штатний глушник; оберіть High Gloss Black або інший фініш.', shortEn: 'Pair of 3.5-inch angle-cut tips bolt onto the factory muffler; choose a listed finish.',
    benefitUa: 'Пара BMS billet tips змінює вигляд вихлопу BMW F-Chassis без зварювання чи різання труби. Tips насаджуються на штатний muffler і мають два set screws для фіксації, створюючи чистий монтаж без окремих clamps.', benefitEn: 'The pair of BMS billet tips updates the BMW F-Chassis exhaust appearance without welding or cutting. They slip onto the factory muffler and use dual set screws for a clean clamp-free installation.',
    detailsUa: 'Діаметр 3.5″, кутовий зріз, комплект із двох. Оберіть покриття: High Gloss Black Powder Coat, Matte Black Ceramic або Polished Silver; варіанти, позначені Burger out of stock, можуть бути недоступні. Не для M Performance exhaust.', detailsEn: '3.5-inch angle-cut tips, sold as a pair. Choose High Gloss Black Powder Coat, Matte Black Ceramic, or Polished Silver; options marked out of stock by Burger may be unavailable. Not for M Performance exhaust.',
    fitUa: 'Лише BMW F-Chassis із N55/B58 у конфігураціях Burger та штатним muffler із відповідним діаметром виходу. Перевірте модель і трубу перед замовленням.', fitEn: 'For Burger-listed BMW F-Chassis with N55/B58 and factory mufflers with the matching outlet diameter. Verify model and pipe before ordering.'
  },
  'kia-pi-kit': {
    titleUa: 'Fuel-It! Port Injection Kit для Kia Stinger / Genesis 3.3T з Ethanol Sensor', titleEn: 'Fuel-It! Port Injection Kit for Kia Stinger / Genesis 3.3T with Ethanol Sensor',
    shortUa: 'Комплект додає шість 750cc injectors, додатковий насос і ethanol sensor; потребує JB4PRO.', shortEn: 'Kit adds six 750cc injectors, auxiliary pump, and ethanol sensor; requires JB4PRO.',
    benefitUa: 'Fuel-It! CPI/port-injection kit додає шість вторинних форсунок до 3.3T, щоб підтримати більшу подачу пального на E85. Комплект включає насос, регулятор, фільтр, лінії, fittings і новий ethanol sensor для вимірювання суміші; реальна підтримувана потужність залежить від решти паливної системи та налаштування.', benefitEn: 'The Fuel-It! CPI/port-injection kit adds six secondary injectors to the 3.3T for additional fueling on E85. The package includes a pump, regulator, filter, lines, fittings, and a new ethanol sensor; actual power support depends on the complete fuel system and calibration.',
    detailsUa: 'Оберіть HPFP, який установлений на авто: OEM або Fuel-It!. За джерелом, комплект містить шість matched 750cc injectors, secondary low-pressure pump, wiring, gaskets, billet adapters, PI harness, і новий ethanol sensor. Для керування потрібна JB4PRO система, яка продається окремо; наявний Kia flex-fuel sensor не сумісний через інший routing.', detailsEn: 'Select the HPFP currently installed: OEM or Fuel-It!. Burger lists six matched 750cc injectors, secondary low-pressure pump, wiring, gaskets, billet adapters, PI harness, and a new ethanol sensor. A JB4PRO system is required for control and is sold separately; the existing Kia flex-fuel sensor is incompatible because routing differs.',
    fitUa: 'Kia Stinger GT/GT1/GT2 3.3T 2018–2023, Genesis G70/G80 3.3T 2018+ та G90 3.3T 2017+ у списку Burger. Потрібні JB4PRO і новий сенсор із комплекту.', fitEn: 'For Burger-listed 2018–2023 Kia Stinger GT/GT1/GT2 3.3T, 2018+ Genesis G70/G80 3.3T, and 2017+ G90 3.3T. JB4PRO and the included new sensor are required.'
  },
  'used-and-blemished-items-30-final-sale': {
    titleUa: 'Burger Used & Blemished — товар з косметичними дефектами, ручний рахунок', titleEn: 'Burger Used & Blemished — Cosmetic-Condition Item, Manual Invoice',
    shortUa: 'Асортимент і стан змінюються; замовлення оформлюється вручну за конкретним SKU, фінальний продаж.', shortEn: 'Inventory and condition vary; order by exact SKU via manual invoice, final sale.',
    benefitUa: 'Ця сторінка не описує один фіксований продукт. У ній публікують позиції Burger Motorsports із косметичними пошкодженнями, для яких стан і комплектність відрізняються за SKU.', benefitEn: 'This page does not describe one fixed product. It lists Burger Motorsports items with cosmetic damage, and condition and package contents vary by SKU.',
    detailsUa: 'Перед купівлею потрібно вибрати конкретний товар за SKU та отримати ручний рахунок від Burger. Усі продажі фінальні; перевірте фото, дефект, комплектність, ціну та повернення саме цієї позиції до оплати. Не оформлюйте як універсальну картку з фіксованою вагою або доставкою.', detailsEn: 'Before purchase, identify a specific item by SKU and obtain a manual Burger invoice. All sales are final; review photos, blemish, package contents, price, and return terms for that exact item before payment. Do not treat this as a fixed product with standard weight or shipping.',
    fitUa: 'Лише для конкретного підтвердженого SKU. Стан, сумісність, вага та наявність залежать від окремої позиції.', fitEn: 'Only for a specifically confirmed SKU. Condition, fitment, weight, and availability vary by item.', manualQuoteRequired: true
  },
};

export default Object.fromEntries(Object.entries(rows).map(([handle, item]) => [handle, {
  ...item,
  sourceUrl: `https://burgertuning.com/products/${handle}`,
  descUa: `<h3>Призначення та результат</h3>\n<p>${item.benefitUa}</p>\n<h3>Конфігурація та комплектація</h3>\n<p>${item.detailsUa}</p>\n<h3>Сумісність та умови</h3>\n<p>${item.fitUa}</p>`,
  descEn: `<h3>Purpose and result</h3>\n<p>${item.benefitEn}</p>\n<h3>Configuration and package</h3>\n<p>${item.detailsEn}</p>\n<h3>Fitment and conditions</h3>\n<p>${item.fitEn}</p>`,
}]));
