'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Loader2 } from 'lucide-react';

import {
  AdminEmptyState,
  AdminMetricCard,
  AdminMetricGrid,
  AdminPage,
  AdminPageHeader,
  AdminStatusBadge,
  AdminTableShell,
} from '@/components/admin/AdminPrimitives';

type CustomerDetail = {
  id: string;
  airtableId: string;
  name: string;
  businessName: string | null;
  tags: string[];
  totalProfit: number;
  totalSales: number;
  totalPayments: number;
  balance: number;
  whoOwes: string | null;
  markup: { markupPct: number; notes: string | null } | null;
  orders: Array<{
    id: string;
    airtableId: string;
    number: number;
    name: string;
    orderStatus: string;
    paymentStatus: string;
    orderDate: string | null;
    clientTotal: number;
    profit: number;
    marginality: number;
    itemCount: number;
    items: Array<{
      id: string;
      productName: string;
      status: string;
      clientTotal: number;
      profitPerItem: number;
    }>;
  }>;
  topProducts: Array<{ name: string; totalQty: number; totalRevenue: number; totalProfit: number }>;
};

function getOrderTone(status: string) {
  if (status === 'Выполнен') return 'success' as const;
  if (status === 'Отменен') return 'danger' as const;
  if (status === 'В обработке' || status === 'Новый') return 'warning' as const;
  return 'default' as const;
}

export default function CrmCustomerDetailPage() {
  const params = useParams();
  const id = params?.id as string;
  const [customer, setCustomer] = useState<CustomerDetail | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;

    setLoading(true);
    void fetch(`/api/admin/crm/customers/${id}`)
      .then((response) => response.json())
      .then((data) => setCustomer(data))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <AdminPage>
        <div className="flex items-center gap-3 rounded-[28px] border border-white/10 bg-[#101010] px-5 py-6 text-sm text-stone-400">
          <Loader2 className="h-4 w-4 animate-spin" />
          Завантаження клієнта…
        </div>
      </AdminPage>
    );
  }

  if (!customer) {
    return (
      <AdminPage>
        <AdminEmptyState
          title="Клієнта не знайдено"
          description="CRM customer detail is unavailable for this identifier."
          action={
            <Link
              href="/admin/crm"
              className="inline-flex items-center gap-2 rounded-2xl bg-stone-100 px-4 py-2.5 text-sm font-medium text-black transition hover:bg-white"
            >
              Back to CRM
            </Link>
          }
        />
      </AdminPage>
    );
  }

  const balanceTone = customer.balance > 0 ? 'success' : customer.balance < 0 ? 'danger' : 'default';

  return (
    <AdminPage className="space-y-6">
      <div className="space-y-4">
        <Link href="/admin/crm" className="inline-flex items-center gap-2 text-sm text-stone-400 transition hover:text-stone-100">
          CRM Dashboard
        </Link>
        <AdminPageHeader
          eyebrow="CRM Customer"
          title={customer.name}
          description={customer.businessName || 'Customer profitability, orders, balance state, and purchased products.'}
          actions={
            customer.markup ? (
              <Link
                href="/admin/shop/pricing"
                className="rounded-[24px] border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-right"
              >
                <div className="text-[11px] font-medium uppercase tracking-[0.18em] text-emerald-200/70">
                  Персональна націнка
                </div>
                <div className="mt-2 text-2xl font-semibold text-emerald-200">
                  {customer.markup.markupPct}%
                </div>
                {customer.markup.notes ? (
                  <div className="mt-1 text-xs text-emerald-100/70">{customer.markup.notes}</div>
                ) : null}
              </Link>
            ) : undefined
          }
        />
      </div>

      <div className="flex flex-wrap gap-2">
        {customer.tags.map((tag) => (
          <AdminStatusBadge key={tag}>{tag}</AdminStatusBadge>
        ))}
        {customer.whoOwes ? (
          <AdminStatusBadge tone={balanceTone}>{customer.whoOwes}</AdminStatusBadge>
        ) : null}
      </div>

      <AdminMetricGrid className="xl:grid-cols-5">
        <AdminMetricCard label="Revenue" value={`$${customer.totalSales.toLocaleString()}`} meta="Customer sales volume" tone="accent" />
        <AdminMetricCard label="Profit" value={`$${customer.totalProfit.toLocaleString()}`} meta="Profit generated by this customer" />
        <AdminMetricCard label="Payments" value={`$${customer.totalPayments.toLocaleString()}`} meta="Incoming customer payments" />
        <AdminMetricCard label="Balance" value={`$${customer.balance.toLocaleString()}`} meta="Current balance state" />
        <AdminMetricCard label="Orders" value={customer.orders.length} meta="CRM orders linked to this customer" />
      </AdminMetricGrid>

      <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <AdminTableShell>
          <div className="border-b border-white/10 px-5 py-4">
            <h2 className="text-sm font-medium text-stone-100">Orders</h2>
            <p className="mt-1 text-xs text-stone-500">Order history and profitability linked to this customer.</p>
          </div>
          {customer.orders.length ? (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm">
                <thead>
                  <tr className="border-b border-white/[0.06] bg-white/[0.02]">
                    <th className="px-5 py-4 text-[11px] uppercase tracking-[0.18em] text-stone-500">Order</th>
                    <th className="px-5 py-4 text-[11px] uppercase tracking-[0.18em] text-stone-500">Status</th>
                    <th className="px-5 py-4 text-[11px] uppercase tracking-[0.18em] text-stone-500">Payment</th>
                    <th className="px-5 py-4 text-[11px] uppercase tracking-[0.18em] text-stone-500 text-right">Revenue</th>
                    <th className="px-5 py-4 text-[11px] uppercase tracking-[0.18em] text-stone-500 text-right">Profit</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.04]">
                  {customer.orders.map((order) => (
                    <tr key={order.id} className="hover:bg-white/[0.02]">
                      <td className="px-5 py-4">
                        <Link href={`/admin/crm/orders/${order.airtableId}`} className="block">
                          <div className="font-medium text-stone-100">#{order.number}</div>
                          <div className="mt-1 text-xs text-stone-500">{order.name}</div>
                        </Link>
                      </td>
                      <td className="px-5 py-4">
                        <AdminStatusBadge tone={getOrderTone(order.orderStatus)}>
                          {order.orderStatus}
                        </AdminStatusBadge>
                      </td>
                      <td className="px-5 py-4">
                        <AdminStatusBadge tone={order.paymentStatus === 'Оплачено' ? 'success' : 'warning'}>
                          {order.paymentStatus}
                        </AdminStatusBadge>
                      </td>
                      <td className="px-5 py-4 text-right font-medium text-stone-200">
                        ${order.clientTotal.toLocaleString()}
                      </td>
                      <td className={`px-5 py-4 text-right font-medium ${order.profit >= 0 ? 'text-emerald-300' : 'text-red-300'}`}>
                        ${order.profit.toFixed(0)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <AdminEmptyState
              className="rounded-none border-0 bg-transparent"
              title="Немає замовлень"
              description="This customer does not have any CRM orders yet."
            />
          )}
        </AdminTableShell>

        <AdminTableShell>
          <div className="border-b border-white/10 px-5 py-4">
            <h2 className="text-sm font-medium text-stone-100">Top products</h2>
            <p className="mt-1 text-xs text-stone-500">Highest-value purchased products for this customer.</p>
          </div>
          {customer.topProducts.length ? (
            <div className="divide-y divide-white/[0.04]">
              {customer.topProducts.map((product) => (
                <div key={product.name} className="px-5 py-4">
                  <div className="truncate font-medium text-stone-100">{product.name}</div>
                  <div className="mt-2 grid gap-2 text-xs text-stone-400 sm:grid-cols-3">
                    <div>{product.totalQty} pcs</div>
                    <div>${product.totalRevenue.toLocaleString()} revenue</div>
                    <div className={product.totalProfit >= 0 ? 'text-emerald-300' : 'text-red-300'}>
                      ${product.totalProfit.toFixed(0)} profit
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <AdminEmptyState
              className="rounded-none border-0 bg-transparent"
              title="Немає товарів"
              description="Product aggregation will appear here once this customer has order items."
            />
          )}
        </AdminTableShell>
      </div>
    </AdminPage>
  );
}
